// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package xaudio2 implements the Windows.Win32.XAudio2 namespace.
package xaudio2

type XAPO_BUFFER_FLAGS int32

const (
	XAPO_BUFFER_SILENT XAPO_BUFFER_FLAGS = 0
	XAPO_BUFFER_VALID  XAPO_BUFFER_FLAGS = 1
)

type XAUDIO2_FILTER_TYPE int32

const (
	LowPassFilter         XAUDIO2_FILTER_TYPE = 0
	BandPassFilter        XAUDIO2_FILTER_TYPE = 1
	HighPassFilter        XAUDIO2_FILTER_TYPE = 2
	NotchFilter           XAUDIO2_FILTER_TYPE = 3
	LowPassOnePoleFilter  XAUDIO2_FILTER_TYPE = 4
	HighPassOnePoleFilter XAUDIO2_FILTER_TYPE = 5
)

type HrtfDirectivityType int32

const (
	OmniDirectional HrtfDirectivityType = 0
	Cardioid        HrtfDirectivityType = 1
	Cone            HrtfDirectivityType = 2
)

type HrtfEnvironment int32

const (
	Small    HrtfEnvironment = 0
	Medium   HrtfEnvironment = 1
	Large    HrtfEnvironment = 2
	Outdoors HrtfEnvironment = 3
)

type HrtfDistanceDecayType int32

const (
	NaturalDecay HrtfDistanceDecayType = 0
	CustomDecay  HrtfDistanceDecayType = 1
)
