// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package xaudio2 implements the Windows.Win32.XAudio2 namespace.
package xaudio2

type XAPO_REGISTRATION_PROPERTIES struct {
	CLSID                int
	FriendlyName         int
	CopyrightInfo        int
	MajorVersion         int
	MinorVersion         int
	Flags                int
	MinInputBufferCount  int
	MaxInputBufferCount  int
	MinOutputBufferCount int
	MaxOutputBufferCount int
}

type XAPO_LOCKFORPROCESS_PARAMETERS struct {
	PFORMAT       int
	MaxFrameCount int
}

type XAPO_PROCESS_BUFFER_PARAMETERS struct {
	PBUFFER         int
	BufferFlags     int
	ValidFrameCount int
}

type FXEQ struct {
}

type FXMasteringLimiter struct {
}

type FXReverb struct {
}

type FXEcho struct {
}

type FXEQ_PARAMETERS struct {
	FrequencyCenter0 int
	Gain0            int
	Bandwidth0       int
	FrequencyCenter1 int
	Gain1            int
	Bandwidth1       int
	FrequencyCenter2 int
	Gain2            int
	Bandwidth2       int
	FrequencyCenter3 int
	Gain3            int
	Bandwidth3       int
}

type FXMASTERINGLIMITER_PARAMETERS struct {
	Release  int
	Loudness int
}

type FXREVERB_PARAMETERS struct {
	Diffusion int
	RoomSize  int
}

type FXECHO_INITDATA struct {
	MaxDelay int
}

type FXECHO_PARAMETERS struct {
	WetDryMix int
	Feedback  int
	Delay     int
}

type XAUDIO2_VOICE_DETAILS struct {
	CreationFlags   int
	ActiveFlags     int
	InputChannels   int
	InputSampleRate int
}

type XAUDIO2_SEND_DESCRIPTOR struct {
	Flags        int
	POUTPUTVOICE int
}

type XAUDIO2_VOICE_SENDS struct {
	SendCount int
	PSENDS    int
}

type XAUDIO2_EFFECT_DESCRIPTOR struct {
	PEFFECT        int
	InitialState   int
	OutputChannels int
}

type XAUDIO2_EFFECT_CHAIN struct {
	EffectCount        int
	PEFFECTDESCRIPTORS int
}

type XAUDIO2_FILTER_PARAMETERS struct {
	Type      int
	Frequency int
	OneOverQ  int
}

type XAUDIO2_BUFFER struct {
	Flags      int
	AudioBytes int
	PAUDIODATA int
	PlayBegin  int
	PlayLength int
	LoopBegin  int
	LoopLength int
	LoopCount  int
	PCONTEXT   int
}

type XAUDIO2_BUFFER_WMA struct {
	PDECODEDPACKETCUMULATIVEBYTES int
	PacketCount                   int
}

type XAUDIO2_VOICE_STATE struct {
	PCURRENTBUFFERCONTEXT int
	BuffersQueued         int
	SamplesPlayed         int
}

type XAUDIO2_PERFORMANCE_DATA struct {
	AudioCyclesSinceLastQuery  int
	TotalCyclesSinceLastQuery  int
	MinimumCyclesPerQuantum    int
	MaximumCyclesPerQuantum    int
	MemoryUsageInBytes         int
	CurrentLatencyInSamples    int
	GlitchesSinceEngineStarted int
	ActiveSourceVoiceCount     int
	TotalSourceVoiceCount      int
	ActiveSubmixVoiceCount     int
	ActiveResamplerCount       int
	ActiveMatrixMixCount       int
	ActiveXmaSourceVoices      int
	ActiveXmaStreams           int
}

type XAUDIO2_DEBUG_CONFIGURATION struct {
	TraceMask       int
	BreakMask       int
	LogThreadID     int
	LogFileline     int
	LogFunctionName int
	LogTiming       int
}

type AudioVolumeMeter struct {
}

type AudioReverb struct {
}

type XAUDIO2FX_VOLUMEMETER_LEVELS struct {
	PPEAKLEVELS  int
	PRMSLEVELS   int
	ChannelCount int
}

type XAUDIO2FX_REVERB_PARAMETERS struct {
	WetDryMix           int
	ReflectionsDelay    int
	ReverbDelay         int
	RearDelay           int
	SideDelay           int
	PositionLeft        int
	PositionRight       int
	PositionMatrixLeft  int
	PositionMatrixRight int
	EarlyDiffusion      int
	LateDiffusion       int
	LowEQGain           int
	LowEQCutoff         int
	HighEQGain          int
	HighEQCutoff        int
	RoomFilterFreq      int
	RoomFilterMain      int
	RoomFilterHF        int
	ReflectionsGain     int
	ReverbGain          int
	DecayTime           int
	Density             int
	RoomSize            int
	DisableLateField    int
}

type XAUDIO2FX_REVERB_I3DL2_PARAMETERS struct {
	WetDryMix         int
	Room              int
	RoomHF            int
	RoomRolloffFactor int
	DecayTime         int
	DecayHFRatio      int
	Reflections       int
	ReflectionsDelay  int
	Reverb            int
	ReverbDelay       int
	Diffusion         int
	Density           int
	HFReference       int
}

type HrtfPosition struct {
	X int
	Y int
	Z int
}

type HrtfOrientation struct {
	ELEMENT int
}

type HrtfDirectivity struct {
	TYPE    int
	SCALING int
}

type HrtfDirectivityCardioid struct {
	DIRECTIVITY int
	ORDER       int
}

type HrtfDirectivityCone struct {
	DIRECTIVITY int
	INNERANGLE  int
	OUTERANGLE  int
}

type HrtfDistanceDecay struct {
	TYPE              int
	MAXGAIN           int
	MINGAIN           int
	UNITYGAINDISTANCE int
	CUTOFFDISTANCE    int
}

type HrtfApoInit struct {
	DISTANCEDECAY int
	DIRECTIVITY   int
}
