// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package streamingmedia implements the Windows.Win32.StreamingMedia namespace.
package streamingmedia

type FaceRectInfoBlobHeader struct {
	Size  int
	Count int
}

type FaceRectInfo struct {
	Region          int
	CONFIDENCELEVEL int
}

type FaceCharacterizationBlobHeader struct {
	Size  int
	Count int
}

type FaceCharacterization struct {
	BlinkScoreLeft        int
	BlinkScoreRight       int
	FacialExpression      int
	FacialExpressionScore int
}

type CapturedMetadataExposureCompensation struct {
	Flags int
	Value int
}

type CapturedMetadataISOGains struct {
	AnalogGain  int
	DigitalGain int
}

type CapturedMetadataWhiteBalanceGains struct {
	R int
	G int
	B int
}

type MetadataTimeStamps struct {
	Flags        int
	Device       int
	Presentation int
}

type HistogramGrid struct {
	Width  int
	Height int
	Region int
}

type HistogramBlobHeader struct {
	Size       int
	Histograms int
}

type HistogramHeader struct {
	Size         int
	Bins         int
	FourCC       int
	ChannelMasks int
	Grid         int
}

type HistogramDataHeader struct {
	Size        int
	ChannelMask int
	Linear      int
}
