// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package passwordmanagement implements the Windows.Win32.PasswordManagement namespace.
package passwordmanagement

type CYPHER_BLOCK struct {
	DATA int
}

type LM_OWF_PASSWORD struct {
	DATA int
}

type SAMPR_ENCRYPTED_USER_PASSWORD struct {
	Buffer int
}

type ENCRYPTED_LM_OWF_PASSWORD struct {
	DATA int
}
