// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package hardwarecounterprofiling implements the Windows.Win32.HardwareCounterProfiling namespace.
package hardwarecounterprofiling

type HARDWARE_COUNTER_DATA struct {
	Type     int
	Reserved int
	Value    int
}

type PERFORMANCE_DATA struct {
	Size               int
	Version            int
	HwCountersCount    int
	ContextSwitchCount int
	WaitReasonBitMap   int
	CycleTime          int
	RetryCount         int
	Reserved           int
	HwCounters         int
}
