// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package wpfbitmapeffects implements the Windows.Win32.WpfBitmapEffects namespace.
package wpfbitmapeffects

type MilRectD struct {
	LEFT   int
	TOP    int
	RIGHT  int
	BOTTOM int
}

type MilPoint2D struct {
	X int
	Y int
}

type MILMatrixF struct {
	X11 int
	X12 int
	X13 int
	X14 int
	X21 int
	X22 int
	X23 int
	X24 int
	X31 int
	X32 int
	X33 int
	X34 int
	X41 int
	X42 int
	X43 int
	X44 int
}

type MilMatrix3x2D struct {
	S_11 int
	S_12 int
	S_21 int
	S_22 int
	DX   int
	DY   int
}
