// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package iphelper implements the Windows.Win32.IpHelper namespace.
package iphelper

type IcmpHandle struct {
	Value int
}

type IP_OPTION_INFORMATION struct {
	Ttl         int
	Tos         int
	Flags       int
	OptionsSize int
	OptionsData int
}

type ICMP_ECHO_REPLY struct {
	Address       int
	Status        int
	RoundTripTime int
	DataSize      int
	Reserved      int
	Data          int
	Options       int
}

type IPV6_ADDRESS_EX struct {
	SIN6_PORT     int
	SIN6_FLOWINFO int
	SIN6_ADDR     int
	SIN6_SCOPE_ID int
}

type ICMPV6_ECHO_REPLY_LH struct {
	Address       int
	Status        int
	RoundTripTime int
}

type ARP_SEND_REPLY struct {
	DestAddress int
	SrcAddress  int
}

type TCP_RESERVE_PORT_RANGE struct {
	UpperRange int
	LowerRange int
}

type IP_ADAPTER_INDEX_MAP struct {
	Index int
	Name  int
}

type IP_INTERFACE_INFO struct {
	NumAdapters int
	Adapter     int
}

type IP_UNIDIRECTIONAL_ADAPTER_ADDRESS struct {
	NumAdapters int
	Address     int
}

type IP_ADAPTER_ORDER_MAP struct {
	NumAdapters  int
	AdapterOrder int
}

type IP_MCAST_COUNTER_INFO struct {
	InMcastOctets  int
	OutMcastOctets int
	InMcastPkts    int
	OutMcastPkts   int
}

type NET_IF_RCV_ADDRESS_LH struct {
	IFRCVADDRESSTYPE   int
	IFRCVADDRESSLENGTH int
	IFRCVADDRESSOFFSET int
}

type NET_IF_ALIAS_LH struct {
	IFALIASLENGTH int
	IFALIASOFFSET int
}

type NET_LUID_LH struct {
	Value int
	Info  int
}

type IF_PHYSICAL_ADDRESS_LH struct {
	Length  int
	Address int
}

type IP_ADDRESS_PREFIX struct {
	Prefix       int
	PrefixLength int
}

type DNS_SETTINGS struct {
	Version    int
	Flags      int
	Hostname   int
	Domain     int
	SearchList int
}

type DNS_INTERFACE_SETTINGS struct {
	Version             int
	Flags               int
	Domain              int
	NameServer          int
	SearchList          int
	RegistrationEnabled int
	RegisterAdapterName int
	EnableLLMNR         int
	QueryAdapterName    int
	ProfileNameServer   int
}

type DNS_INTERFACE_SETTINGS_EX struct {
	SettingsV1                  int
	DisableUnconstrainedQueries int
	SupplementalSearchList      int
}

type TCPIP_OWNER_MODULE_BASIC_INFO struct {
	PMODULENAME int
	PMODULEPATH int
}

type MIB_IPDESTROW struct {
	ForwardRow          int
	DWFORWARDPREFERENCE int
	DWFORWARDVIEWSET    int
}

type MIB_IPDESTTABLE struct {
	DWNUMENTRIES int
	TABLE        int
}

type MIB_ROUTESTATE struct {
	BROUTESSETTOSTACK int
}

type IP_ADDRESS_STRING struct {
	String int
}

type IP_ADDR_STRING struct {
	Next      int
	IpAddress int
	IpMask    int
	Context   int
}

type IP_ADAPTER_INFO struct {
	Next                int
	ComboIndex          int
	AdapterName         int
	Description         int
	AddressLength       int
	Address             int
	Index               int
	Type                int
	DhcpEnabled         int
	CurrentIpAddress    int
	IpAddressList       int
	GatewayList         int
	DhcpServer          int
	HaveWins            int
	PrimaryWinsServer   int
	SecondaryWinsServer int
	LeaseObtained       int
	LeaseExpires        int
}

type IP_ADAPTER_UNICAST_ADDRESS_LH struct {
	Anonymous          int
	Next               int
	Address            int
	PrefixOrigin       int
	SuffixOrigin       int
	DadState           int
	ValidLifetime      int
	PreferredLifetime  int
	LeaseLifetime      int
	OnLinkPrefixLength int
}

type IP_ADAPTER_UNICAST_ADDRESS_XP struct {
	Anonymous         int
	Next              int
	Address           int
	PrefixOrigin      int
	SuffixOrigin      int
	DadState          int
	ValidLifetime     int
	PreferredLifetime int
	LeaseLifetime     int
}

type IP_ADAPTER_ANYCAST_ADDRESS_XP struct {
	Anonymous int
	Next      int
	Address   int
}

type IP_ADAPTER_MULTICAST_ADDRESS_XP struct {
	Anonymous int
	Next      int
	Address   int
}

type IP_ADAPTER_DNS_SERVER_ADDRESS_XP struct {
	Anonymous int
	Next      int
	Address   int
}

type IP_ADAPTER_WINS_SERVER_ADDRESS_LH struct {
	Anonymous int
	Next      int
	Address   int
}

type IP_ADAPTER_GATEWAY_ADDRESS_LH struct {
	Anonymous int
	Next      int
	Address   int
}

type IP_ADAPTER_PREFIX_XP struct {
	Anonymous    int
	Next         int
	Address      int
	PrefixLength int
}

type IP_ADAPTER_DNS_SUFFIX struct {
	Next   int
	String int
}

type IP_ADAPTER_ADDRESSES_LH struct {
	Anonymous1             int
	Next                   int
	AdapterName            int
	FirstUnicastAddress    int
	FirstAnycastAddress    int
	FirstMulticastAddress  int
	FirstDnsServerAddress  int
	DnsSuffix              int
	Description            int
	FriendlyName           int
	PhysicalAddress        int
	PhysicalAddressLength  int
	Anonymous2             int
	Mtu                    int
	IfType                 int
	OperStatus             int
	Ipv6IfIndex            int
	ZoneIndices            int
	FirstPrefix            int
	TransmitLinkSpeed      int
	ReceiveLinkSpeed       int
	FirstWinsServerAddress int
	FirstGatewayAddress    int
	Ipv4Metric             int
	Ipv6Metric             int
	Luid                   int
	Dhcpv4Server           int
	CompartmentId          int
	NetworkGuid            int
	ConnectionType         int
	TunnelType             int
	Dhcpv6Server           int
	Dhcpv6ClientDuid       int
	Dhcpv6ClientDuidLength int
	Dhcpv6Iaid             int
	FirstDnsSuffix         int
}

type IP_ADAPTER_ADDRESSES_XP struct {
	Anonymous             int
	Next                  int
	AdapterName           int
	FirstUnicastAddress   int
	FirstAnycastAddress   int
	FirstMulticastAddress int
	FirstDnsServerAddress int
	DnsSuffix             int
	Description           int
	FriendlyName          int
	PhysicalAddress       int
	PhysicalAddressLength int
	Flags                 int
	Mtu                   int
	IfType                int
	OperStatus            int
	Ipv6IfIndex           int
	ZoneIndices           int
	FirstPrefix           int
}

type IP_PER_ADAPTER_INFO_W2KSP1 struct {
	AutoconfigEnabled int
	AutoconfigActive  int
	CurrentDnsServer  int
	DnsServerList     int
}

type FIXED_INFO_W2KSP1 struct {
	HostName         int
	DomainName       int
	CurrentDnsServer int
	DnsServerList    int
	NodeType         int
	ScopeId          int
	EnableRouting    int
	EnableProxy      int
	EnableDns        int
}

type IP_INTERFACE_NAME_INFO_W2KSP1 struct {
	Index          int
	MediaType      int
	ConnectionType int
	AccessType     int
	DeviceGuid     int
	InterfaceGuid  int
}

type TCP_ESTATS_SYN_OPTS_ROS_v0 struct {
	ActiveOpen int
	MssRcvd    int
	MssSent    int
}

type TCP_ESTATS_DATA_ROD_v0 struct {
	DataBytesOut      int
	DataSegsOut       int
	DataBytesIn       int
	DataSegsIn        int
	SegsOut           int
	SegsIn            int
	SoftErrors        int
	SoftErrorReason   int
	SndUna            int
	SndNxt            int
	SndMax            int
	ThruBytesAcked    int
	RcvNxt            int
	ThruBytesReceived int
}

type TCP_ESTATS_DATA_RW_v0 struct {
	EnableCollection int
}

type TCP_ESTATS_SND_CONG_ROD_v0 struct {
	SndLimTransRwin int
	SndLimTimeRwin  int
	SndLimBytesRwin int
	SndLimTransCwnd int
	SndLimTimeCwnd  int
	SndLimBytesCwnd int
	SndLimTransSnd  int
	SndLimTimeSnd   int
	SndLimBytesSnd  int
	SlowStart       int
	CongAvoid       int
	OtherReductions int
	CurCwnd         int
	MaxSsCwnd       int
	MaxCaCwnd       int
	CurSsthresh     int
	MaxSsthresh     int
	MinSsthresh     int
}

type TCP_ESTATS_SND_CONG_ROS_v0 struct {
	LimCwnd int
}

type TCP_ESTATS_SND_CONG_RW_v0 struct {
	EnableCollection int
}

type TCP_ESTATS_PATH_ROD_v0 struct {
	FastRetran            int
	Timeouts              int
	SubsequentTimeouts    int
	CurTimeoutCount       int
	AbruptTimeouts        int
	PktsRetrans           int
	BytesRetrans          int
	DupAcksIn             int
	SacksRcvd             int
	SackBlocksRcvd        int
	CongSignals           int
	PreCongSumCwnd        int
	PreCongSumRtt         int
	PostCongSumRtt        int
	PostCongCountRtt      int
	EcnSignals            int
	EceRcvd               int
	SendStall             int
	QuenchRcvd            int
	RetranThresh          int
	SndDupAckEpisodes     int
	SumBytesReordered     int
	NonRecovDa            int
	NonRecovDaEpisodes    int
	AckAfterFr            int
	DsackDups             int
	SampleRtt             int
	SmoothedRtt           int
	RttVar                int
	MaxRtt                int
	MinRtt                int
	SumRtt                int
	CountRtt              int
	CurRto                int
	MaxRto                int
	MinRto                int
	CurMss                int
	MaxMss                int
	MinMss                int
	SpuriousRtoDetections int
}

type TCP_ESTATS_PATH_RW_v0 struct {
	EnableCollection int
}

type TCP_ESTATS_SEND_BUFF_ROD_v0 struct {
	CurRetxQueue int
	MaxRetxQueue int
	CurAppWQueue int
	MaxAppWQueue int
}

type TCP_ESTATS_SEND_BUFF_RW_v0 struct {
	EnableCollection int
}

type TCP_ESTATS_REC_ROD_v0 struct {
	CurRwinSent    int
	MaxRwinSent    int
	MinRwinSent    int
	LimRwin        int
	DupAckEpisodes int
	DupAcksOut     int
	CeRcvd         int
	EcnSent        int
	EcnNoncesRcvd  int
	CurReasmQueue  int
	MaxReasmQueue  int
	CurAppRQueue   int
	MaxAppRQueue   int
	WinScaleSent   int
}

type TCP_ESTATS_REC_RW_v0 struct {
	EnableCollection int
}

type TCP_ESTATS_OBS_REC_ROD_v0 struct {
	CurRwinRcvd  int
	MaxRwinRcvd  int
	MinRwinRcvd  int
	WinScaleRcvd int
}

type TCP_ESTATS_OBS_REC_RW_v0 struct {
	EnableCollection int
}

type TCP_ESTATS_BANDWIDTH_RW_v0 struct {
	EnableCollectionOutbound int
	EnableCollectionInbound  int
}

type TCP_ESTATS_BANDWIDTH_ROD_v0 struct {
	OutboundBandwidth       int
	InboundBandwidth        int
	OutboundInstability     int
	InboundInstability      int
	OutboundBandwidthPeaked int
	InboundBandwidthPeaked  int
}

type TCP_ESTATS_FINE_RTT_RW_v0 struct {
	EnableCollection int
}

type TCP_ESTATS_FINE_RTT_ROD_v0 struct {
	RttVar int
	MaxRtt int
	MinRtt int
	SumRtt int
}

type INTERFACE_TIMESTAMP_CAPABILITY_FLAGS struct {
	PtpV2OverUdpIPv4EventMsgReceiveHw  int
	PtpV2OverUdpIPv4AllMsgReceiveHw    int
	PtpV2OverUdpIPv4EventMsgTransmitHw int
	PtpV2OverUdpIPv4AllMsgTransmitHw   int
	PtpV2OverUdpIPv6EventMsgReceiveHw  int
	PtpV2OverUdpIPv6AllMsgReceiveHw    int
	PtpV2OverUdpIPv6EventMsgTransmitHw int
	PtpV2OverUdpIPv6AllMsgTransmitHw   int
	AllReceiveHw                       int
	AllTransmitHw                      int
	TaggedTransmitHw                   int
	AllReceiveSw                       int
	AllTransmitSw                      int
	TaggedTransmitSw                   int
}

type INTERFACE_TIMESTAMP_CAPABILITIES struct {
	Version                  int
	HardwareClockFrequencyHz int
	CrossTimestamp           int
	Reserved1                int
	Reserved2                int
	TimestampFlags           int
}

type INTERFACE_HARDWARE_CROSSTIMESTAMP struct {
	Version                int
	Flags                  int
	SystemTimestamp1       int
	HardwareClockTimestamp int
	SystemTimestamp2       int
}

type HIFTIMESTAMPCHANGE__ struct {
	UNUSED int
}

type SOCKADDR_INET struct {
	Ipv4      int
	Ipv6      int
	SI_FAMILY int
}

type SOCKADDR_IN6_PAIR struct {
	SourceAddress      int
	DestinationAddress int
}

type NL_NETWORK_CONNECTIVITY_HINT struct {
	ConnectivityLevel    int
	ConnectivityCost     int
	ApproachingDataLimit int
	OverDataLimit        int
	Roaming              int
}

type NL_BANDWIDTH_INFORMATION struct {
	Bandwidth       int
	Instability     int
	BandwidthPeaked int
}

type NET_ADDRESS_INFO struct {
}
