// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package remotedesktopservices implements the Windows.Win32.RemoteDesktopServices namespace.
package remotedesktopservices

type HwtsVirtualChannelHandle struct {
	Value int
}

type WTSSESSION_NOTIFICATION struct {
	CBSIZE      int
	DWSESSIONID int
}

type TSUserExInterfaces struct {
}

type ADsTSUserEx struct {
}

type AAAccountingData struct {
	USERNAME                int
	CLIENTNAME              int
	AUTHTYPE                int
	RESOURCENAME            int
	PORTNUMBER              int
	PROTOCOLNAME            int
	NUMBEROFBYTESRECEIVED   int
	NUMBEROFBYTESTRANSFERED int
	REASONFORDISCONNECT     int
	MAINSESSIONID           int
	SUBSESSIONID            int
}

type WTS_SERVER_INFOW struct {
	PSERVERNAME int
}

type WTS_SERVER_INFOA struct {
	PSERVERNAME int
}

type WTS_SESSION_INFOW struct {
	SessionId       int
	PWINSTATIONNAME int
	State           int
}

type WTS_SESSION_INFOA struct {
	SessionId       int
	PWINSTATIONNAME int
	State           int
}

type WTS_SESSION_INFO_1W struct {
	ExecEnvId    int
	State        int
	SessionId    int
	PSESSIONNAME int
	PHOSTNAME    int
	PUSERNAME    int
	PDOMAINNAME  int
	PFARMNAME    int
}

type WTS_SESSION_INFO_1A struct {
	ExecEnvId    int
	State        int
	SessionId    int
	PSESSIONNAME int
	PHOSTNAME    int
	PUSERNAME    int
	PDOMAINNAME  int
	PFARMNAME    int
}

type WTS_PROCESS_INFOW struct {
	SessionId    int
	ProcessId    int
	PPROCESSNAME int
	PUSERSID     int
}

type WTS_PROCESS_INFOA struct {
	SessionId    int
	ProcessId    int
	PPROCESSNAME int
	PUSERSID     int
}

type WTSCONFIGINFOW struct {
	VERSION                          int
	FCONNECTCLIENTDRIVESATLOGON      int
	FCONNECTPRINTERATLOGON           int
	FDISABLEPRINTERREDIRECTION       int
	FDISABLEDEFAULTMAINCLIENTPRINTER int
	ShadowSettings                   int
	LogonUserName                    int
	LogonDomain                      int
	WorkDirectory                    int
	InitialProgram                   int
	ApplicationName                  int
}

type WTSCONFIGINFOA struct {
	VERSION                          int
	FCONNECTCLIENTDRIVESATLOGON      int
	FCONNECTPRINTERATLOGON           int
	FDISABLEPRINTERREDIRECTION       int
	FDISABLEDEFAULTMAINCLIENTPRINTER int
	ShadowSettings                   int
	LogonUserName                    int
	LogonDomain                      int
	WorkDirectory                    int
	InitialProgram                   int
	ApplicationName                  int
}

type WTSINFOW struct {
	State                   int
	SessionId               int
	IncomingBytes           int
	OutgoingBytes           int
	IncomingFrames          int
	OutgoingFrames          int
	IncomingCompressedBytes int
	OutgoingCompressedBytes int
	WinStationName          int
	Domain                  int
	UserName                int
	ConnectTime             int
	DisconnectTime          int
	LastInputTime           int
	LogonTime               int
	CurrentTime             int
}

type WTSINFOA struct {
	State                   int
	SessionId               int
	IncomingBytes           int
	OutgoingBytes           int
	IncomingFrames          int
	OutgoingFrames          int
	IncomingCompressedBytes int
	OutgoingCompressedBy    int
	WinStationName          int
	Domain                  int
	UserName                int
	ConnectTime             int
	DisconnectTime          int
	LastInputTime           int
	LogonTime               int
	CurrentTime             int
}

type WTSINFOEX_LEVEL1_W struct {
	SessionId               int
	SessionState            int
	SessionFlags            int
	WinStationName          int
	UserName                int
	DomainName              int
	LogonTime               int
	ConnectTime             int
	DisconnectTime          int
	LastInputTime           int
	CurrentTime             int
	IncomingBytes           int
	OutgoingBytes           int
	IncomingFrames          int
	OutgoingFrames          int
	IncomingCompressedBytes int
	OutgoingCompressedBytes int
}

type WTSINFOEX_LEVEL1_A struct {
	SessionId               int
	SessionState            int
	SessionFlags            int
	WinStationName          int
	UserName                int
	DomainName              int
	LogonTime               int
	ConnectTime             int
	DisconnectTime          int
	LastInputTime           int
	CurrentTime             int
	IncomingBytes           int
	OutgoingBytes           int
	IncomingFrames          int
	OutgoingFrames          int
	IncomingCompressedBytes int
	OutgoingCompressedBytes int
}

type WTSINFOEX_LEVEL_W struct {
	WTSInfoExLevel1 int
}

type WTSINFOEX_LEVEL_A struct {
	WTSInfoExLevel1 int
}

type WTSINFOEXW struct {
	Level int
	Data  int
}

type WTSINFOEXA struct {
	Level int
	Data  int
}

type WTSCLIENTW struct {
	ClientName          int
	Domain              int
	UserName            int
	WorkDirectory       int
	InitialProgram      int
	EncryptionLevel     int
	ClientAddressFamily int
	ClientAddress       int
	HRes                int
	VRes                int
	ColorDepth          int
	ClientDirectory     int
	ClientBuildNumber   int
	ClientHardwareId    int
	ClientProductId     int
	OutBufCountHost     int
	OutBufCountClient   int
	OutBufLength        int
	DeviceId            int
}

type WTSCLIENTA struct {
	ClientName          int
	Domain              int
	UserName            int
	WorkDirectory       int
	InitialProgram      int
	EncryptionLevel     int
	ClientAddressFamily int
	ClientAddress       int
	HRes                int
	VRes                int
	ColorDepth          int
	ClientDirectory     int
	ClientBuildNumber   int
	ClientHardwareId    int
	ClientProductId     int
	OutBufCountHost     int
	OutBufCountClient   int
	OutBufLength        int
	DeviceId            int
}

type WTS_PRODUCT_INFOA struct {
	CompanyName int
	ProductID   int
}

type WTS_PRODUCT_INFOW struct {
	CompanyName int
	ProductID   int
}

type WTS_VALIDATION_INFORMATIONA struct {
	ProductInfo      int
	License          int
	LicenseLength    int
	HardwareID       int
	HardwareIDLength int
}

type WTS_VALIDATION_INFORMATIONW struct {
	ProductInfo      int
	License          int
	LicenseLength    int
	HardwareID       int
	HardwareIDLength int
}

type WTS_CLIENT_ADDRESS struct {
	AddressFamily int
	Address       int
}

type WTS_CLIENT_DISPLAY struct {
	HorizontalResolution int
	VerticalResolution   int
	ColorDepth           int
}

type WTSUSERCONFIGA struct {
	Source                        int
	InheritInitialProgram         int
	AllowLogonTerminalServer      int
	TimeoutSettingsConnections    int
	TimeoutSettingsDisconnections int
	TimeoutSettingsIdle           int
	DeviceClientDrives            int
	DeviceClientPrinters          int
	ClientDefaultPrinter          int
	BrokenTimeoutSettings         int
	ReconnectSettings             int
	ShadowingSettings             int
	TerminalServerRemoteHomeDir   int
	InitialProgram                int
	WorkDirectory                 int
	TerminalServerProfilePath     int
	TerminalServerHomeDir         int
	TerminalServerHomeDirDrive    int
}

type WTSUSERCONFIGW struct {
	Source                        int
	InheritInitialProgram         int
	AllowLogonTerminalServer      int
	TimeoutSettingsConnections    int
	TimeoutSettingsDisconnections int
	TimeoutSettingsIdle           int
	DeviceClientDrives            int
	DeviceClientPrinters          int
	ClientDefaultPrinter          int
	BrokenTimeoutSettings         int
	ReconnectSettings             int
	ShadowingSettings             int
	TerminalServerRemoteHomeDir   int
	InitialProgram                int
	WorkDirectory                 int
	TerminalServerProfilePath     int
	TerminalServerHomeDir         int
	TerminalServerHomeDirDrive    int
}

type WTS_SESSION_ADDRESS struct {
	AddressFamily int
	Address       int
}

type WTS_PROCESS_INFO_EXW struct {
	SessionId          int
	ProcessId          int
	PPROCESSNAME       int
	PUSERSID           int
	NumberOfThreads    int
	HandleCount        int
	PagefileUsage      int
	PeakPagefileUsage  int
	WorkingSetSize     int
	PeakWorkingSetSize int
	UserTime           int
	KernelTime         int
}

type WTS_PROCESS_INFO_EXA struct {
	SessionId          int
	ProcessId          int
	PPROCESSNAME       int
	PUSERSID           int
	NumberOfThreads    int
	HandleCount        int
	PagefileUsage      int
	PeakPagefileUsage  int
	WorkingSetSize     int
	PeakWorkingSetSize int
	UserTime           int
	KernelTime         int
}

type WTSLISTENERCONFIGW struct {
	VERSION                          int
	FENABLELISTENER                  int
	MaxConnectionCount               int
	FPROMPTFORPASSWORD               int
	FINHERITCOLORDEPTH               int
	ColorDepth                       int
	FINHERITBROKENTIMEOUTSETTINGS    int
	BrokenTimeoutSettings            int
	FDISABLEPRINTERREDIRECTION       int
	FDISABLEDRIVEREDIRECTION         int
	FDISABLECOMPORTREDIRECTION       int
	FDISABLELPTPORTREDIRECTION       int
	FDISABLECLIPBOARDREDIRECTION     int
	FDISABLEAUDIOREDIRECTION         int
	FDISABLEPNPREDIRECTION           int
	FDISABLEDEFAULTMAINCLIENTPRINTER int
	LanAdapter                       int
	PortNumber                       int
	FINHERITSHADOWSETTINGS           int
	ShadowSettings                   int
	TimeoutSettingsConnection        int
	TimeoutSettingsDisconnection     int
	TimeoutSettingsIdle              int
	SecurityLayer                    int
	MinEncryptionLevel               int
	UserAuthentication               int
	Comment                          int
	LogonUserName                    int
	LogonDomain                      int
	WorkDirectory                    int
	InitialProgram                   int
}

type WTSLISTENERCONFIGA struct {
	VERSION                          int
	FENABLELISTENER                  int
	MaxConnectionCount               int
	FPROMPTFORPASSWORD               int
	FINHERITCOLORDEPTH               int
	ColorDepth                       int
	FINHERITBROKENTIMEOUTSETTINGS    int
	BrokenTimeoutSettings            int
	FDISABLEPRINTERREDIRECTION       int
	FDISABLEDRIVEREDIRECTION         int
	FDISABLECOMPORTREDIRECTION       int
	FDISABLELPTPORTREDIRECTION       int
	FDISABLECLIPBOARDREDIRECTION     int
	FDISABLEAUDIOREDIRECTION         int
	FDISABLEPNPREDIRECTION           int
	FDISABLEDEFAULTMAINCLIENTPRINTER int
	LanAdapter                       int
	PortNumber                       int
	FINHERITSHADOWSETTINGS           int
	ShadowSettings                   int
	TimeoutSettingsConnection        int
	TimeoutSettingsDisconnection     int
	TimeoutSettingsIdle              int
	SecurityLayer                    int
	MinEncryptionLevel               int
	UserAuthentication               int
	Comment                          int
	LogonUserName                    int
	LogonDomain                      int
	WorkDirectory                    int
	InitialProgram                   int
}

type WTSSBX_IP_ADDRESS struct {
	AddressFamily int
	Address       int
	PortNumber    int
	DWSCOPE       int
}

type WTSSBX_MACHINE_CONNECT_INFO struct {
	WCZMACHINEFQDN        int
	WCZMACHINENETBIOSNAME int
	DWNUMOFIPADDR         int
	IPaddr                int
}

type WTSSBX_MACHINE_INFO struct {
	ClientConnectInfo  int
	WCZFARMNAME        int
	InternalIPAddress  int
	DWMAXSESSIONSLIMIT int
	ServerWeight       int
	SingleSessionMode  int
	InDrain            int
	MachineState       int
}

type WTSSBX_SESSION_INFO struct {
	WSZUSERNAME     int
	WSZDOMAINNAME   int
	ApplicationType int
	DWSESSIONID     int
	CreateTime      int
	DisconnectTime  int
	SessionState    int
}

type CHANNEL_DEF struct {
	NAME    int
	OPTIONS int
}

type CHANNEL_PDU_HEADER struct {
	LENGTH int
	FLAGS  int
}

type CHANNEL_ENTRY_POINTS struct {
	CBSIZE               int
	PROTOCOLVERSION      int
	PVIRTUALCHANNELINIT  int
	PVIRTUALCHANNELOPEN  int
	PVIRTUALCHANNELCLOSE int
	PVIRTUALCHANNELWRITE int
}

type Workspace struct {
}

type CLIENT_DISPLAY struct {
	HorizontalResolution int
	VerticalResolution   int
	ColorDepth           int
}

type TSSD_ConnectionPoint struct {
	ServerAddressB int
	AddressType    int
	PortNumber     int
	AddressScope   int
}

type VM_NOTIFY_ENTRY struct {
	VmName int
	VmHost int
}

type VM_PATCH_INFO struct {
	DWNUMENTRIES int
	PVMNAMES     int
}

type VM_NOTIFY_INFO struct {
	DWNUMENTRIES int
	PPVMENTRIES  int
}

type PLUGINRESOURCE struct {
	ALIAS                int
	NAME                 int
	RESOURCEFILECONTENTS int
	FILEEXTENSION        int
	RESOURCEPLUGINTYPE   int
	ISDISCOVERABLE       int
	RESOURCETYPE         int
	PCEICONSIZE          int
	ICONCONTENTS         int
	PCEPLUGINBLOBSIZE    int
	BLOBCONTENTS         int
}

type PLUGINRESOURCE2FILEASSOCIATION struct {
	EXTNAME        int
	PRIMARYHANDLER int
	PCEICONSIZE    int
	ICONCONTENTS   int
}

type PLUGINRESOURCE2 struct {
	RESOURCEV1           int
	PCEFILEASSOCLISTSIZE int
	FILEASSOCLIST        int
	SECURITYDESCRIPTOR   int
	PCEFOLDERLISTSIZE    int
	FOLDERLIST           int
}

type BITMAP_RENDERER_STATISTICS struct {
	DWFRAMESDELIVERED int
	DWFRAMESDROPPED   int
}

type RFX_GFX_RECT struct {
	LEFT   int
	TOP    int
	RIGHT  int
	BOTTOM int
}

type RFX_GFX_MSG_HEADER struct {
	UMSGTYPE int
	CBSIZE   int
}

type RFX_GFX_MONITOR_INFO struct {
	LEFT           int
	TOP            int
	RIGHT          int
	BOTTOM         int
	PHYSICALWIDTH  int
	PHYSICALHEIGHT int
	ORIENTATION    int
	PRIMARY        int
}

type RFX_GFX_MSG_CLIENT_DESKTOP_INFO_REQUEST struct {
	CHANNELHDR int
}

type RFX_GFX_MSG_CLIENT_DESKTOP_INFO_RESPONSE struct {
	CHANNELHDR     int
	RESERVED       int
	MONITORCOUNT   int
	MonitorData    int
	CLIENTUNIQUEID int
}

type RFX_GFX_MSG_DESKTOP_CONFIG_CHANGE_NOTIFY struct {
	CHANNELHDR int
	ULWIDTH    int
	ULHEIGHT   int
	ULBPP      int
	Reserved   int
}

type RFX_GFX_MSG_DESKTOP_CONFIG_CHANGE_CONFIRM struct {
	CHANNELHDR int
}

type RFX_GFX_MSG_DESKTOP_INPUT_RESET struct {
	CHANNELHDR int
	ULWIDTH    int
	ULHEIGHT   int
}

type RFX_GFX_MSG_DISCONNECT_NOTIFY struct {
	CHANNELHDR       int
	DisconnectReason int
}

type RFX_GFX_MSG_DESKTOP_RESEND_REQUEST struct {
	CHANNELHDR int
	RedrawRect int
}

type RFX_GFX_MSG_RDP_DATA struct {
	CHANNELHDR int
	RDPDATA    int
}

type WTS_SOCKADDR struct {
	SIN_FAMILY int
	U          int
}

type WTS_SMALL_RECT struct {
	Left   int
	Top    int
	Right  int
	Bottom int
}

type WTS_SERVICE_STATE struct {
	RcmServiceState int
	RcmDrainState   int
}

type WTS_SESSION_ID struct {
	SessionUniqueGuid int
	SessionId         int
}

type WTS_USER_CREDENTIAL struct {
	UserName int
	Password int
	Domain   int
}

type WTS_SYSTEMTIME struct {
	WYEAR         int
	WMONTH        int
	WDAYOFWEEK    int
	WDAY          int
	WHOUR         int
	WMINUTE       int
	WSECOND       int
	WMILLISECONDS int
}

type WTS_TIME_ZONE_INFORMATION struct {
	Bias         int
	StandardName int
	StandardDate int
	StandardBias int
	DaylightName int
	DaylightDate int
	DaylightBias int
}

type WRDS_DYNAMIC_TIME_ZONE_INFORMATION struct {
	Bias                        int
	StandardName                int
	StandardDate                int
	StandardBias                int
	DaylightName                int
	DaylightDate                int
	DaylightBias                int
	TimeZoneKeyName             int
	DynamicDaylightTimeDisabled int
}

type WTS_CLIENT_DATA struct {
	FDISABLECTRLALTDEL     int
	FDOUBLECLICKDETECT     int
	FENABLEWINDOWSKEY      int
	FHIDETITLEBAR          int
	FINHERITAUTOLOGON      int
	FPROMPTFORPASSWORD     int
	FUSINGSAVEDCREDS       int
	Domain                 int
	UserName               int
	Password               int
	FPASSWORDISSCPIN       int
	FINHERITINITIALPROGRAM int
	WorkDirectory          int
	InitialProgram         int
	FMAXIMIZESHELL         int
	EncryptionLevel        int
	PerformanceFlags       int
	ProtocolName           int
	ProtocolType           int
	FINHERITCOLORDEPTH     int
	HRes                   int
	VRes                   int
	ColorDepth             int
	DisplayDriverName      int
	DisplayDeviceName      int
	FMOUSE                 int
	KeyboardLayout         int
	KeyboardType           int
	KeyboardSubType        int
	KeyboardFunctionKey    int
	IMEFILENAME            int
	ActiveInputLocale      int
	FNOAUDIOPLAYBACK       int
	FREMOTECONSOLEAUDIO    int
	AudioDriverName        int
	ClientTimeZone         int
	ClientName             int
	SerialNumber           int
	ClientAddressFamily    int
	ClientAddress          int
	ClientSockAddress      int
	ClientDirectory        int
	ClientBuildNumber      int
	ClientProductId        int
	OutBufCountHost        int
	OutBufCountClient      int
	OutBufLength           int
	ClientSessionId        int
	ClientDigProductId     int
	FDISABLECPM            int
	FDISABLECDM            int
	FDISABLECCM            int
	FDISABLELPT            int
	FDISABLECLIP           int
	FDISABLEPNP            int
}

type WTS_USER_DATA struct {
	WorkDirectory  int
	InitialProgram int
	UserTimeZone   int
}

type WTS_POLICY_DATA struct {
	FDISABLEENCRYPTION    int
	FDISABLEAUTORECONNECT int
	ColorDepth            int
	MinEncryptionLevel    int
	FDISABLECPM           int
	FDISABLECDM           int
	FDISABLECCM           int
	FDISABLELPT           int
	FDISABLECLIP          int
	FDISABLEPNPREDIR      int
}

type WTS_PROTOCOL_CACHE struct {
	CacheReads int
	CacheHits  int
}

type WTS_CACHE_STATS_UN struct {
	ProtocolCache    int
	TShareCacheStats int
	Reserved         int
}

type WTS_CACHE_STATS struct {
	Specific     int
	Data         int
	ProtocolType int
	Length       int
}

type WTS_PROTOCOL_COUNTERS struct {
	WdBytes            int
	WdFrames           int
	WaitForOutBuf      int
	Frames             int
	Bytes              int
	CompressedBytes    int
	CompressFlushes    int
	Errors             int
	Timeouts           int
	AsyncFramingError  int
	AsyncOverrunError  int
	AsyncOverflowError int
	AsyncParityError   int
	TdErrors           int
	ProtocolType       int
	Length             int
	Specific           int
	Reserved           int
}

type WTS_PROTOCOL_STATUS struct {
	Output          int
	Input           int
	Cache           int
	AsyncSignal     int
	AsyncSignalMask int
	Counters        int
}

type WTS_DISPLAY_IOCTL struct {
	PDISPLAYIOCTLDATA  int
	CBDISPLAYIOCTLDATA int
}

type WTS_PROPERTY_VALUE struct {
	Type int
	U    int
}

type WTS_LICENSE_CAPABILITIES struct {
	KeyExchangeAlg      int
	ProtocolVer         int
	FAUTHENTICATESERVER int
	CertType            int
	CBCLIENTNAME        int
	RGBCLIENTNAME       int
}

type WRDS_LISTENER_SETTINGS_1 struct {
	MaxProtocolListenerConnectionCount int
	SecurityDescriptorSize             int
	PSECURITYDESCRIPTOR                int
}

type WRDS_LISTENER_SETTING struct {
	WRdsListenerSettings1 int
}

type WRDS_LISTENER_SETTINGS struct {
	WRdsListenerSettingLevel int
	WRdsListenerSetting      int
}

type WRDS_CONNECTION_SETTINGS_1 struct {
	FINHERITINITIALPROGRAM int
	FINHERITCOLORDEPTH     int
	FHIDETITLEBAR          int
	FINHERITAUTOLOGON      int
	FMAXIMIZESHELL         int
	FDISABLEPNP            int
	FPASSWORDISSCPIN       int
	FPROMPTFORPASSWORD     int
	FDISABLECPM            int
	FDISABLECDM            int
	FDISABLECCM            int
	FDISABLELPT            int
	FDISABLECLIP           int
	FRESETBROKEN           int
	FDISABLEENCRYPTION     int
	FDISABLEAUTORECONNECT  int
	FDISABLECTRLALTDEL     int
	FDOUBLECLICKDETECT     int
	FENABLEWINDOWSKEY      int
	FUSINGSAVEDCREDS       int
	FMOUSE                 int
	FNOAUDIOPLAYBACK       int
	FREMOTECONSOLEAUDIO    int
	EncryptionLevel        int
	ColorDepth             int
	ProtocolType           int
	HRes                   int
	VRes                   int
	ClientProductId        int
	OutBufCountHost        int
	OutBufCountClient      int
	OutBufLength           int
	KeyboardLayout         int
	MaxConnectionTime      int
	MaxDisconnectionTime   int
	MaxIdleTime            int
	PerformanceFlags       int
	KeyboardType           int
	KeyboardSubType        int
	KeyboardFunctionKey    int
	ActiveInputLocale      int
	SerialNumber           int
	ClientAddressFamily    int
	ClientBuildNumber      int
	ClientSessionId        int
	WorkDirectory          int
	InitialProgram         int
	UserName               int
	Domain                 int
	Password               int
	ProtocolName           int
	DisplayDriverName      int
	DisplayDeviceName      int
	IMEFILENAME            int
	AudioDriverName        int
	ClientName             int
	ClientAddress          int
	ClientDirectory        int
	ClientDigProductId     int
	ClientSockAddress      int
	ClientTimeZone         int
	WRdsListenerSettings   int
	EventLogActivityId     int
	ContextSize            int
	ContextData            int
}

type WRDS_SETTINGS_1 struct {
	WRdsDisableClipStatus           int
	WRdsDisableClipValue            int
	WRdsDisableLPTStatus            int
	WRdsDisableLPTValue             int
	WRdsDisableCcmStatus            int
	WRdsDisableCcmValue             int
	WRdsDisableCdmStatus            int
	WRdsDisableCdmValue             int
	WRdsDisableCpmStatus            int
	WRdsDisableCpmValue             int
	WRdsDisablePnpStatus            int
	WRdsDisablePnpValue             int
	WRdsEncryptionLevelStatus       int
	WRdsEncryptionValue             int
	WRdsColorDepthStatus            int
	WRdsColorDepthValue             int
	WRdsDisableAutoReconnecetStatus int
	WRdsDisableAutoReconnecetValue  int
	WRdsDisableEncryptionStatus     int
	WRdsDisableEncryptionValue      int
	WRdsResetBrokenStatus           int
	WRdsResetBrokenValue            int
	WRdsMaxIdleTimeStatus           int
	WRdsMaxIdleTimeValue            int
	WRdsMaxDisconnectTimeStatus     int
	WRdsMaxDisconnectTimeValue      int
	WRdsMaxConnectTimeStatus        int
	WRdsMaxConnectTimeValue         int
	WRdsKeepAliveStatus             int
	WRdsKeepAliveStartValue         int
	WRdsKeepAliveIntervalValue      int
}

type WRDS_CONNECTION_SETTING struct {
	WRdsConnectionSettings1 int
}

type WRDS_CONNECTION_SETTINGS struct {
	WRdsConnectionSettingLevel int
	WRdsConnectionSetting      int
}

type WRDS_SETTING struct {
	WRdsSettings1 int
}

type WRDS_SETTINGS struct {
	WRdsSettingType  int
	WRdsSettingLevel int
	WRdsSetting      int
}

type APO_CONNECTION_PROPERTY struct {
	PBUFFER            int
	U32VALIDFRAMECOUNT int
	U32BUFFERFLAGS     int
	U32SIGNATURE       int
}

type AE_CURRENT_POSITION struct {
	U64DEVICEPOSITION  int
	U64STREAMPOSITION  int
	U64PADDINGFRAMES   int
	HNSQPCPOSITION     int
	F32FRAMESPERSECOND int
	Flag               int
}
