// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package coreaudio implements the Windows.Win32.CoreAudio namespace.
package coreaudio

type HTASK struct {
	Value int
}

type MCI_GENERIC_PARMS struct {
	DWCALLBACK int
}

type MCI_OPEN_PARMSA struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
}

type MCI_OPEN_PARMSW struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
}

type MCI_PLAY_PARMS struct {
	DWCALLBACK int
	DWFROM     int
	DWTO       int
}

type MCI_SEEK_PARMS struct {
	DWCALLBACK int
	DWTO       int
}

type MCI_STATUS_PARMS struct {
	DWCALLBACK int
	DWRETURN   int
	DWITEM     int
	DWTRACK    int
}

type MCI_INFO_PARMSA struct {
	DWCALLBACK  int
	LPSTRRETURN int
	DWRETSIZE   int
}

type MCI_INFO_PARMSW struct {
	DWCALLBACK  int
	LPSTRRETURN int
	DWRETSIZE   int
}

type MCI_GETDEVCAPS_PARMS struct {
	DWCALLBACK int
	DWRETURN   int
	DWITEM     int
}

type MCI_SYSINFO_PARMSA struct {
	DWCALLBACK  int
	LPSTRRETURN int
	DWRETSIZE   int
	DWNUMBER    int
	WDEVICETYPE int
}

type MCI_SYSINFO_PARMSW struct {
	DWCALLBACK  int
	LPSTRRETURN int
	DWRETSIZE   int
	DWNUMBER    int
	WDEVICETYPE int
}

type MCI_SET_PARMS struct {
	DWCALLBACK   int
	DWTIMEFORMAT int
	DWAUDIO      int
}

type MCI_BREAK_PARMS struct {
	DWCALLBACK int
	NVIRTKEY   int
	HWNDBREAK  int
}

type MCI_SAVE_PARMSA struct {
	DWCALLBACK int
	LPFILENAME int
}

type MCI_SAVE_PARMSW struct {
	DWCALLBACK int
	LPFILENAME int
}

type MCI_LOAD_PARMSA struct {
	DWCALLBACK int
	LPFILENAME int
}

type MCI_LOAD_PARMSW struct {
	DWCALLBACK int
	LPFILENAME int
}

type MCI_RECORD_PARMS struct {
	DWCALLBACK int
	DWFROM     int
	DWTO       int
}

type MCI_VD_PLAY_PARMS struct {
	DWCALLBACK int
	DWFROM     int
	DWTO       int
	DWSPEED    int
}

type MCI_VD_STEP_PARMS struct {
	DWCALLBACK int
	DWFRAMES   int
}

type MCI_VD_ESCAPE_PARMSA struct {
	DWCALLBACK   int
	LPSTRCOMMAND int
}

type MCI_VD_ESCAPE_PARMSW struct {
	DWCALLBACK   int
	LPSTRCOMMAND int
}

type MCI_WAVE_OPEN_PARMSA struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWBUFFERSECONDS  int
}

type MCI_WAVE_OPEN_PARMSW struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWBUFFERSECONDS  int
}

type MCI_WAVE_DELETE_PARMS struct {
	DWCALLBACK int
	DWFROM     int
	DWTO       int
}

type MCI_WAVE_SET_PARMS struct {
	DWCALLBACK      int
	DWTIMEFORMAT    int
	DWAUDIO         int
	WINPUT          int
	WOUTPUT         int
	WFORMATTAG      int
	WRESERVED2      int
	NCHANNELS       int
	WRESERVED3      int
	NSAMPLESPERSEC  int
	NAVGBYTESPERSEC int
	NBLOCKALIGN     int
	WRESERVED4      int
	WBITSPERSAMPLE  int
	WRESERVED5      int
}

type MCI_SEQ_SET_PARMS struct {
	DWCALLBACK   int
	DWTIMEFORMAT int
	DWAUDIO      int
	DWTEMPO      int
	DWPORT       int
	DWSLAVE      int
	DWMASTER     int
	DWOFFSET     int
}

type MCI_ANIM_OPEN_PARMSA struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWSTYLE          int
	HWNDPARENT       int
}

type MCI_ANIM_OPEN_PARMSW struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWSTYLE          int
	HWNDPARENT       int
}

type MCI_ANIM_PLAY_PARMS struct {
	DWCALLBACK int
	DWFROM     int
	DWTO       int
	DWSPEED    int
}

type MCI_ANIM_STEP_PARMS struct {
	DWCALLBACK int
	DWFRAMES   int
}

type MCI_ANIM_WINDOW_PARMSA struct {
	DWCALLBACK int
	HWND       int
	NCMDSHOW   int
	LPSTRTEXT  int
}

type MCI_ANIM_WINDOW_PARMSW struct {
	DWCALLBACK int
	HWND       int
	NCMDSHOW   int
	LPSTRTEXT  int
}

type MCI_ANIM_RECT_PARMS struct {
	DWCALLBACK int
	RC         int
}

type MCI_ANIM_UPDATE_PARMS struct {
	DWCALLBACK int
	RC         int
	HDC        int
}

type MCI_OVLY_OPEN_PARMSA struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWSTYLE          int
	HWNDPARENT       int
}

type MCI_OVLY_OPEN_PARMSW struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWSTYLE          int
	HWNDPARENT       int
}

type MCI_OVLY_WINDOW_PARMSA struct {
	DWCALLBACK int
	HWND       int
	NCMDSHOW   int
	LPSTRTEXT  int
}

type MCI_OVLY_WINDOW_PARMSW struct {
	DWCALLBACK int
	HWND       int
	NCMDSHOW   int
	LPSTRTEXT  int
}

type MCI_OVLY_RECT_PARMS struct {
	DWCALLBACK int
	RC         int
}

type MCI_OVLY_SAVE_PARMSA struct {
	DWCALLBACK int
	LPFILENAME int
	RC         int
}

type MCI_OVLY_SAVE_PARMSW struct {
	DWCALLBACK int
	LPFILENAME int
	RC         int
}

type MCI_OVLY_LOAD_PARMSA struct {
	DWCALLBACK int
	LPFILENAME int
	RC         int
}

type MCI_OVLY_LOAD_PARMSW struct {
	DWCALLBACK int
	LPFILENAME int
	RC         int
}

type GUID_NULL struct {
}

type KSPRIORITY struct {
	PriorityClass    int
	PrioritySubClass int
}

type KSIDENTIFIER struct {
	Anonymous int
}

type KSP_NODE struct {
	Property int
	NodeId   int
	Reserved int
}

type KSM_NODE struct {
	Method   int
	NodeId   int
	Reserved int
}

type KSE_NODE struct {
	Event    int
	NodeId   int
	Reserved int
}

type KSPROPTYPESETID_General struct {
}

type KSMULTIPLE_ITEM struct {
	Size  int
	Count int
}

type KSPROPERTY_DESCRIPTION struct {
	AccessFlags      int
	DescriptionSize  int
	PropTypeSet      int
	MembersListCount int
	Reserved         int
}

type KSPROPERTY_MEMBERSHEADER struct {
	MembersFlags int
	MembersSize  int
	MembersCount int
	Flags        int
}

type KSPROPERTY_BOUNDS_LONG struct {
	Anonymous1 int
	Anonymous2 int
}

type KSPROPERTY_BOUNDS_LONGLONG struct {
	Anonymous1 int
	Anonymous2 int
}

type KSPROPERTY_STEPPING_LONG struct {
	SteppingDelta int
	Reserved      int
	Bounds        int
}

type KSPROPERTY_STEPPING_LONGLONG struct {
	SteppingDelta int
	Bounds        int
}

type KSEVENTDATA struct {
	NotificationType int
	Anonymous        int
}

type KSQUERYBUFFER struct {
	Event     int
	EventData int
	Reserved  int
}

type KSRELATIVEEVENT struct {
	Size      int
	Flags     int
	Anonymous int
	Reserved  int
	Event     int
	EventData int
}

type KSEVENT_TIME_MARK struct {
	EventData int
	MarkTime  int
}

type KSEVENT_TIME_INTERVAL struct {
	EventData int
	TimeBase  int
	Interval  int
}

type KSINTERVAL struct {
	TimeBase int
	Interval int
}

type KSPROPSETID_General struct {
}

type KSCOMPONENTID struct {
	Manufacturer int
	Product      int
	Component    int
	Name         int
	Version      int
	Revision     int
}

type KSMETHODSETID_StreamIo struct {
}

type KSPROPSETID_MediaSeeking struct {
}

type KSPROPERTY_POSITIONS struct {
	Current      int
	Stop         int
	CurrentFlags int
	StopFlags    int
}

type KSPROPERTY_MEDIAAVAILABLE struct {
	Earliest int
	Latest   int
}

type KSP_TIMEFORMAT struct {
	Property     int
	SourceFormat int
	TargetFormat int
	Time         int
}

type KSPROPSETID_Topology struct {
}

type KSCATEGORY_BRIDGE struct {
}

type KSCATEGORY_CAPTURE struct {
}

type KSCATEGORY_VIDEO_CAMERA struct {
}

type KSCATEGORY_SENSOR_CAMERA struct {
}

type KSCATEGORY_NETWORK_CAMERA struct {
}

type KSCATEGORY_SENSOR_GROUP struct {
}

type KSCATEGORY_RENDER struct {
}

type KSCATEGORY_MIXER struct {
}

type KSCATEGORY_SPLITTER struct {
}

type KSCATEGORY_DATACOMPRESSOR struct {
}

type KSCATEGORY_DATADECOMPRESSOR struct {
}

type KSCATEGORY_DATATRANSFORM struct {
}

type KSMFT_CATEGORY_VIDEO_DECODER struct {
}

type KSMFT_CATEGORY_VIDEO_ENCODER struct {
}

type KSMFT_CATEGORY_VIDEO_EFFECT struct {
}

type KSMFT_CATEGORY_MULTIPLEXER struct {
}

type KSMFT_CATEGORY_DEMULTIPLEXER struct {
}

type KSMFT_CATEGORY_AUDIO_DECODER struct {
}

type KSMFT_CATEGORY_AUDIO_ENCODER struct {
}

type KSMFT_CATEGORY_AUDIO_EFFECT struct {
}

type KSMFT_CATEGORY_VIDEO_PROCESSOR struct {
}

type KSMFT_CATEGORY_OTHER struct {
}

type KSCATEGORY_COMMUNICATIONSTRANSFORM struct {
}

type KSCATEGORY_INTERFACETRANSFORM struct {
}

type KSCATEGORY_MEDIUMTRANSFORM struct {
}

type KSCATEGORY_FILESYSTEM struct {
}

type KSCATEGORY_CLOCK struct {
}

type KSCATEGORY_PROXY struct {
}

type KSCATEGORY_QUALITY struct {
}

type KSTOPOLOGY struct {
	CategoriesCount          int
	Categories               int
	TopologyNodesCount       int
	TopologyNodes            int
	TopologyConnectionsCount int
	TopologyConnections      int
	TopologyNodesNames       int
	Reserved                 int
}

type KSNODE_CREATE struct {
	CreateFlags int
	Node        int
}

type KSTIME_FORMAT_FRAME struct {
}

type KSTIME_FORMAT_BYTE struct {
}

type KSTIME_FORMAT_SAMPLE struct {
}

type KSTIME_FORMAT_FIELD struct {
}

type KSTIME_FORMAT_MEDIA_TIME struct {
}

type KSINTERFACESETID_Standard struct {
}

type KSINTERFACESETID_FileIo struct {
}

type KSMEDIUMSETID_Standard struct {
}

type KSPROPSETID_Pin struct {
}

type KSP_PIN struct {
	Property  int
	PinId     int
	Anonymous int
}

type KSE_PIN struct {
	Event    int
	PinId    int
	Reserved int
}

type KSPIN_CINSTANCES struct {
	PossibleCount int
	CurrentCount  int
}

type KSDATAFORMAT struct {
	Anonymous int
	Alignment int
}

type KSATTRIBUTE struct {
	Size      int
	Flags     int
	Attribute int
}

type KSPIN_CONNECT struct {
	Interface   int
	Medium      int
	PinId       int
	PinToHandle int
	Priority    int
}

type KSPIN_PHYSICALCONNECTION struct {
	Size             int
	Pin              int
	SymbolicLinkName int
}

type KSEVENTSETID_PinCapsChange struct {
}

type KSEVENTSETID_VolumeLimit struct {
}

type KSNAME_Filter struct {
}

type KSNAME_Pin struct {
}

type KSNAME_Clock struct {
}

type KSNAME_Allocator struct {
}

type KSNAME_TopologyNode struct {
}

type KSDATAFORMAT_TYPE_STREAM struct {
}

type KSDATAFORMAT_SUBTYPE_NONE struct {
}

type KSDATAFORMAT_SPECIFIER_FILENAME struct {
}

type KSDATAFORMAT_SPECIFIER_FILEHANDLE struct {
}

type KSDATAFORMAT_SPECIFIER_NONE struct {
}

type KSPROPSETID_Quality struct {
}

type KSPROPSETID_Connection struct {
}

type KSPROPSETID_MemoryTransport struct {
}

type KSALLOCATOR_FRAMING struct {
	Anonymous1 int
	PoolType   int
	Frames     int
	FrameSize  int
	Anonymous2 int
	Reserved   int
}

type KS_FRAMING_RANGE struct {
	MinFrameSize int
	MaxFrameSize int
	Stepping     int
}

type KS_FRAMING_RANGE_WEIGHTED struct {
	Range            int
	InPlaceWeight    int
	NotInPlaceWeight int
}

type KS_COMPRESSION struct {
	RatioNumerator      int
	RatioDenominator    int
	RatioConstantMargin int
}

type KS_FRAMING_ITEM struct {
	MemoryType       int
	BusType          int
	MemoryFlags      int
	BusFlags         int
	Flags            int
	Frames           int
	Anonymous        int
	MemoryTypeWeight int
	PhysicalRange    int
	FramingRange     int
}

type KSALLOCATOR_FRAMING_EX struct {
	CountItems        int
	PinFlags          int
	OutputCompression int
	PinWeight         int
	FramingItem       int
}

type KSMEMORY_TYPE_SYSTEM struct {
}

type KSMEMORY_TYPE_USER struct {
}

type KSMEMORY_TYPE_KERNEL_PAGED struct {
}

type KSMEMORY_TYPE_KERNEL_NONPAGED struct {
}

type KSMEMORY_TYPE_DEVICE_UNKNOWN struct {
}

type KSEVENTSETID_StreamAllocator struct {
}

type KSMETHODSETID_StreamAllocator struct {
}

type KSPROPSETID_StreamAllocator struct {
}

type KSSTREAMALLOCATOR_STATUS struct {
	Framing         int
	AllocatedFrames int
	Reserved        int
}

type KSSTREAMALLOCATOR_STATUS_EX struct {
	Framing         int
	AllocatedFrames int
	Reserved        int
}

type KSTIME struct {
	Time        int
	Numerator   int
	Denominator int
}

type KSSTREAM_HEADER struct {
	Size              int
	TypeSpecificFlags int
	PresentationTime  int
	Duration          int
	FrameExtent       int
	DataUsed          int
	Data              int
	OptionsFlags      int
}

type KSSTREAM_METADATA_INFO struct {
	BufferSize int
	UsedSize   int
	Data       int
	SystemVa   int
	Flags      int
	Reserved   int
}

type KSSTREAM_UVC_METADATATYPE_TIMESTAMP struct {
	PresentationTimeStamp int
	SourceClockReference  int
	Anonymous             int
	Reserved0             int
	Reserved1             int
}

type KSSTREAM_UVC_METADATA struct {
	StartOfFrameTimestamp int
	EndOfFrameTimestamp   int
}

type KSPIN_MDL_CACHING_NOTIFICATION struct {
	Event  int
	Buffer int
}

type KSPIN_MDL_CACHING_NOTIFICATION32 struct {
	Event  int
	Buffer int
}

type KSPROPSETID_StreamInterface struct {
}

type KSPROPSETID_Stream struct {
}

type KSPROPSETID_PinMDLCacheClearProp struct {
}

type KSQUALITY_MANAGER struct {
	QualityManager int
	Context        int
}

type KSFRAMETIME struct {
	Duration   int
	FrameFlags int
	Reserved   int
}

type KSRATE struct {
	PresentationStart int
	Duration          int
	Interface         int
	Rate              int
	Flags             int
}

type KSRATE_CAPABILITY struct {
	Property int
	Rate     int
}

type KSPROPSETID_Clock struct {
}

type KSCLOCK_CREATE struct {
	CreateFlags int
}

type KSCORRELATED_TIME struct {
	Time       int
	SystemTime int
}

type KSRESOLUTION struct {
	Granularity int
	Error       int
}

type KSEVENTSETID_Clock struct {
}

type KSEVENTSETID_Connection struct {
}

type KSQUALITY struct {
	Context    int
	Proportion int
	DeltaTime  int
}

type KSERROR struct {
	Context int
	Status  int
}

type KSEVENTSETID_Device struct {
}

type KSDEGRADESETID_Standard struct {
}

type KSPROPERTY_SERIALHDR struct {
	PropertySet int
	Count       int
}

type KSPROPERTY_SERIAL struct {
	PropTypeSet    int
	Id             int
	PropertyLength int
}

type MF_MDL_SHARED_PAYLOAD_KEY struct {
	COMBINED   int
	GMDLHandle int
}

type KSMULTIPLE_DATA_PROP struct {
	Property     int
	MultipleItem int
}

type KSMEDIUMSETID_MidiBus struct {
}

type KSMEDIUMSETID_VPBus struct {
}

type KSINTERFACESETID_Media struct {
}

type KSCOMPONENTID_USBAUDIO struct {
}

type KSNODETYPE_INPUT_UNDEFINED struct {
}

type KSNODETYPE_MICROPHONE struct {
}

type KSNODETYPE_DESKTOP_MICROPHONE struct {
}

type KSNODETYPE_PERSONAL_MICROPHONE struct {
}

type KSNODETYPE_OMNI_DIRECTIONAL_MICROPHONE struct {
}

type KSNODETYPE_MICROPHONE_ARRAY struct {
}

type KSNODETYPE_PROCESSING_MICROPHONE_ARRAY struct {
}

type KSCATEGORY_MICROPHONE_ARRAY_PROCESSOR struct {
}

type KSNODETYPE_OUTPUT_UNDEFINED struct {
}

type KSNODETYPE_SPEAKER struct {
}

type KSNODETYPE_HEADPHONES struct {
}

type KSNODETYPE_HEAD_MOUNTED_DISPLAY_AUDIO struct {
}

type KSNODETYPE_DESKTOP_SPEAKER struct {
}

type KSNODETYPE_ROOM_SPEAKER struct {
}

type KSNODETYPE_COMMUNICATION_SPEAKER struct {
}

type KSNODETYPE_LOW_FREQUENCY_EFFECTS_SPEAKER struct {
}

type KSNODETYPE_BIDIRECTIONAL_UNDEFINED struct {
}

type KSNODETYPE_HANDSET struct {
}

type KSNODETYPE_HEADSET struct {
}

type KSNODETYPE_SPEAKERPHONE_NO_ECHO_REDUCTION struct {
}

type KSNODETYPE_ECHO_SUPPRESSING_SPEAKERPHONE struct {
}

type KSNODETYPE_ECHO_CANCELING_SPEAKERPHONE struct {
}

type KSNODETYPE_TELEPHONY_UNDEFINED struct {
}

type KSNODETYPE_PHONE_LINE struct {
}

type KSNODETYPE_TELEPHONE struct {
}

type KSNODETYPE_DOWN_LINE_PHONE struct {
}

type KSNODETYPE_EXTERNAL_UNDEFINED struct {
}

type KSNODETYPE_ANALOG_CONNECTOR struct {
}

type KSNODETYPE_DIGITAL_AUDIO_INTERFACE struct {
}

type KSNODETYPE_LINE_CONNECTOR struct {
}

type KSNODETYPE_LEGACY_AUDIO_CONNECTOR struct {
}

type KSNODETYPE_SPDIF_INTERFACE struct {
}

type KSNODETYPE_1394_DA_STREAM struct {
}

type KSNODETYPE_1394_DV_STREAM_SOUNDTRACK struct {
}

type KSNODETYPE_EMBEDDED_UNDEFINED struct {
}

type KSNODETYPE_LEVEL_CALIBRATION_NOISE_SOURCE struct {
}

type KSNODETYPE_EQUALIZATION_NOISE struct {
}

type KSNODETYPE_CD_PLAYER struct {
}

type KSNODETYPE_DAT_IO_DIGITAL_AUDIO_TAPE struct {
}

type KSNODETYPE_DCC_IO_DIGITAL_COMPACT_CASSETTE struct {
}

type KSNODETYPE_MINIDISK struct {
}

type KSNODETYPE_ANALOG_TAPE struct {
}

type KSNODETYPE_PHONOGRAPH struct {
}

type KSNODETYPE_VCR_AUDIO struct {
}

type KSNODETYPE_VIDEO_DISC_AUDIO struct {
}

type KSNODETYPE_DVD_AUDIO struct {
}

type KSNODETYPE_TV_TUNER_AUDIO struct {
}

type KSNODETYPE_SATELLITE_RECEIVER_AUDIO struct {
}

type KSNODETYPE_CABLE_TUNER_AUDIO struct {
}

type KSNODETYPE_DSS_AUDIO struct {
}

type KSNODETYPE_RADIO_RECEIVER struct {
}

type KSNODETYPE_RADIO_TRANSMITTER struct {
}

type KSNODETYPE_MULTITRACK_RECORDER struct {
}

type KSNODETYPE_SYNTHESIZER struct {
}

type KSNODETYPE_HDMI_INTERFACE struct {
}

type KSNODETYPE_DISPLAYPORT_INTERFACE struct {
}

type KSNODETYPE_AUDIO_LOOPBACK struct {
}

type KSNODETYPE_AUDIO_KEYWORDDETECTOR struct {
}

type KSNODETYPE_MIDI_JACK struct {
}

type KSNODETYPE_MIDI_ELEMENT struct {
}

type KSNODETYPE_AUDIO_ENGINE struct {
}

type KSNODETYPE_SPEAKERS_STATIC_JACK struct {
}

type PINNAME_SPDIF_OUT struct {
}

type PINNAME_SPDIF_IN struct {
}

type PINNAME_HDMI_OUT struct {
}

type PINNAME_DISPLAYPORT_OUT struct {
}

type KSNODETYPE_DRM_DESCRAMBLE struct {
}

type KSNODETYPE_TELEPHONY_BIDI struct {
}

type KSNODETYPE_FM_RX struct {
}

type KSCATEGORY_AUDIO struct {
}

type KSCATEGORY_VIDEO struct {
}

type KSCATEGORY_REALTIME struct {
}

type KSCATEGORY_TEXT struct {
}

type KSCATEGORY_NETWORK struct {
}

type KSCATEGORY_TOPOLOGY struct {
}

type KSCATEGORY_VIRTUAL struct {
}

type KSCATEGORY_ACOUSTIC_ECHO_CANCEL struct {
}

type KSCATEGORY_WDMAUD_USE_PIN_NAME struct {
}

type KSCATEGORY_ESCALANTE_PLATFORM_DRIVER struct {
}

type KSDATAFORMAT_TYPE_VIDEO struct {
}

type KSDATAFORMAT_TYPE_AUDIO struct {
}

type KSDATAFORMAT_TYPE_TEXT struct {
}

type KSDATAFORMAT_SUBTYPE_ANALOG struct {
}

type KSDATAFORMAT_SUBTYPE_DRM struct {
}

type KSDATAFORMAT_SUBTYPE_ALAW struct {
}

type KSDATAFORMAT_SUBTYPE_MULAW struct {
}

type KSDATAFORMAT_SUBTYPE_ADPCM struct {
}

type KSDATAFORMAT_SUBTYPE_MPEG struct {
}

type KSDATAFORMAT_SPECIFIER_VC_ID struct {
}

type KSDATAFORMAT_SPECIFIER_WAVEFORMATEX struct {
}

type KSDATAFORMAT_SPECIFIER_DSOUND struct {
}

type KSDATAFORMAT_WAVEFORMATEX struct {
	DataFormat   int
	WaveFormatEx int
}

type WAVEFORMATEXTENSIBLE_IEC61937 struct {
	FormatExt              int
	DWENCODEDSAMPLESPERSEC int
	DWENCODEDCHANNELCOUNT  int
	DWAVERAGEBYTESPERSEC   int
}

type KSDATAFORMAT_WAVEFORMATEXTENSIBLE struct {
	DataFormat    int
	WaveFormatExt int
}

type KSDSOUND_BUFFERDESC struct {
	Flags        int
	Control      int
	WaveFormatEx int
}

type KSDATAFORMAT_DSOUND struct {
	DataFormat int
	BufferDesc int
}

type KSAUDIO_POSITION struct {
	PlayOffset  int
	WriteOffset int
}

type KSAUDIO_PRESENTATION_POSITION struct {
	U64POSITIONINBLOCKS int
	U64QPCPOSITION      int
}

type KSAUDIO_PACKETSIZE_SIGNALPROCESSINGMODE_CONSTRAINT struct {
	ProcessingMode                int
	SamplesPerProcessingPacket    int
	ProcessingPacketDurationInHns int
}

type KSAUDIO_PACKETSIZE_CONSTRAINTS struct {
	MinPacketPeriodInHns         int
	PacketSizeFileAlignment      int
	Reserved                     int
	NumProcessingModeConstraints int
	ProcessingModeConstraints    int
}

type KSAUDIO_PACKETSIZE_CONSTRAINTS2 struct {
	MinPacketPeriodInHns         int
	PacketSizeFileAlignment      int
	MaxPacketSizeInBytes         int
	NumProcessingModeConstraints int
	ProcessingModeConstraints    int
}

type KSAUDIO_MICROPHONE_COORDINATES struct {
	USTYPE           int
	WXCOORD          int
	WYCOORD          int
	WZCOORD          int
	WVERTICALANGLE   int
	WHORIZONTALANGLE int
}

type KSAUDIO_MIC_ARRAY_GEOMETRY struct {
	USVERSION             int
	USMICARRAYTYPE        int
	WVERTICALANGLEBEGIN   int
	WVERTICALANGLEEND     int
	WHORIZONTALANGLEBEGIN int
	WHORIZONTALANGLEEND   int
	USFREQUENCYBANDLO     int
	USFREQUENCYBANDHI     int
	USNUMBEROFMICROPHONES int
	KsMicCoord            int
}

type DS3DVECTOR struct {
	Anonymous1 int
	Anonymous2 int
	Anonymous3 int
}

type KSPROPSETID_DirectSound3DListener struct {
}

type KSDS3D_LISTENER_ALL struct {
	Position       int
	Velocity       int
	OrientFront    int
	OrientTop      int
	DistanceFactor int
	RolloffFactor  int
	DopplerFactor  int
}

type KSDS3D_LISTENER_ORIENTATION struct {
	Front int
	Top   int
}

type KSPROPSETID_DirectSound3DBuffer struct {
}

type KSDS3D_BUFFER_ALL struct {
	Position          int
	Velocity          int
	InsideConeAngle   int
	OutsideConeAngle  int
	ConeOrientation   int
	ConeOutsideVolume int
	MinDistance       int
	MaxDistance       int
	Mode              int
}

type KSDS3D_BUFFER_CONE_ANGLES struct {
	InsideConeAngle  int
	OutsideConeAngle int
}

type KSDS3D_HRTF_PARAMS_MSG struct {
	Size            int
	Enabled         int
	SwapChannels    int
	ZeroAzimuth     int
	CrossFadeOutput int
	FilterSize      int
}

type KSDS3D_HRTF_INIT_MSG struct {
	Size                      int
	Quality                   int
	SampleRate                int
	MaxFilterSize             int
	FilterTransientMuteLength int
	FilterOverlapBufferLength int
	OutputOverlapBufferLength int
	Reserved                  int
}

type KSDS3D_HRTF_FILTER_FORMAT_MSG struct {
	FilterMethod int
	CoeffFormat  int
	Version      int
	Reserved     int
}

type KSPROPSETID_Hrtf3d struct {
}

type KSDS3D_ITD_PARAMS struct {
	Channel             int
	VolSmoothScale      int
	TotalDryAttenuation int
	TotalWetAttenuation int
	SmoothFrequency     int
	Delay               int
}

type KSDS3D_ITD_PARAMS_MSG struct {
	Enabled     int
	LeftParams  int
	RightParams int
	Reserved    int
}

type KSPROPSETID_Itd3d struct {
}

type KSDATARANGE_AUDIO struct {
	DataRange              int
	MaximumChannels        int
	MinimumBitsPerSample   int
	MaximumBitsPerSample   int
	MinimumSampleFrequency int
	MaximumSampleFrequency int
}

type KSDATAFORMAT_SUBTYPE_RIFF struct {
}

type KSDATAFORMAT_SUBTYPE_RIFFWAVE struct {
}

type KSPROPSETID_Bibliographic struct {
}

type KSPROPSETID_TopologyNode struct {
}

type KSPROPSETID_RtAudio struct {
}

type KSRTAUDIO_BUFFER_PROPERTY struct {
	Property            int
	BaseAddress         int
	RequestedBufferSize int
}

type KSRTAUDIO_BUFFER_PROPERTY32 struct {
	Property            int
	BaseAddress         int
	RequestedBufferSize int
}

type KSRTAUDIO_BUFFER_PROPERTY_WITH_NOTIFICATION struct {
	Property            int
	BaseAddress         int
	RequestedBufferSize int
	NotificationCount   int
}

type KSRTAUDIO_BUFFER_PROPERTY_WITH_NOTIFICATION32 struct {
	Property            int
	BaseAddress         int
	RequestedBufferSize int
	NotificationCount   int
}

type KSRTAUDIO_BUFFER struct {
	BufferAddress     int
	ActualBufferSize  int
	CallMemoryBarrier int
}

type KSRTAUDIO_BUFFER32 struct {
	BufferAddress     int
	ActualBufferSize  int
	CallMemoryBarrier int
}

type KSRTAUDIO_HWLATENCY struct {
	FifoSize     int
	ChipsetDelay int
	CodecDelay   int
}

type KSRTAUDIO_HWREGISTER_PROPERTY struct {
	Property    int
	BaseAddress int
}

type KSRTAUDIO_HWREGISTER_PROPERTY32 struct {
	Property    int
	BaseAddress int
}

type KSRTAUDIO_HWREGISTER struct {
	Register    int
	Width       int
	Numerator   int
	Denominator int
	Accuracy    int
}

type KSRTAUDIO_HWREGISTER32 struct {
	Register    int
	Width       int
	Numerator   int
	Denominator int
	Accuracy    int
}

type KSRTAUDIO_NOTIFICATION_EVENT_PROPERTY struct {
	Property          int
	NotificationEvent int
}

type KSRTAUDIO_NOTIFICATION_EVENT_PROPERTY32 struct {
	Property          int
	NotificationEvent int
}

type KSRTAUDIO_GETREADPACKET_INFO struct {
	PacketNumber            int
	Flags                   int
	PerformanceCounterValue int
	MoreData                int
}

type KSRTAUDIO_SETWRITEPACKET_INFO struct {
	PacketNumber    int
	Flags           int
	EosPacketLength int
}

type KSRTAUDIO_PACKETVREGISTER_PROPERTY struct {
	Property    int
	BaseAddress int
}

type KSRTAUDIO_PACKETVREGISTER struct {
	CompletedPacketCount int
	CompletedPacketQPC   int
	CompletedPacketHash  int
}

type KSPROPSETID_BtAudio struct {
}

type KSPROPSETID_DrmAudioStream struct {
}

type KSPROPSETID_SoundDetector struct {
}

type KSPROPSETID_SoundDetector2 struct {
}

type KSPROPSETID_InterleavedAudio struct {
}

type INTERLEAVED_AUDIO_FORMAT_INFORMATION struct {
	Size                            int
	PrimaryChannelCount             int
	PrimaryChannelStartPosition     int
	PrimaryChannelMask              int
	InterleavedChannelCount         int
	InterleavedChannelStartPosition int
	InterleavedChannelMask          int
}

type KSSOUNDDETECTORPROPERTY struct {
	Property int
	EventId  int
}

type SOUNDDETECTOR_PATTERNHEADER struct {
	Size        int
	PatternType int
}

type KSEVENTSETID_SoundDetector struct {
}

type KSNOTIFICATIONID_SoundDetector struct {
}

type KSPROPSETID_Audio struct {
}

type KSAUDIO_COPY_PROTECTION struct {
	FCOPYRIGHTED int
	FORIGINAL    int
}

type KSAUDIO_CHANNEL_CONFIG struct {
	ActiveSpeakerPositions int
}

type KSAUDIO_DYNAMIC_RANGE struct {
	QuietCompression int
	LoudCompression  int
}

type KSAUDIO_MIXLEVEL struct {
	Mute  int
	Level int
}

type KSAUDIO_MIX_CAPS struct {
	Mute      int
	Minimum   int
	Maximum   int
	Anonymous int
}

type KSAUDIO_MIXCAP_TABLE struct {
	InputChannels  int
	OutputChannels int
	Capabilities   int
}

type KSAUDIO_POSITIONEX struct {
	TimerFrequency int
	TimeStamp1     int
	Position       int
	TimeStamp2     int
}

type KSPROPSETID_TelephonyControl struct {
}

type KSTELEPHONY_CALLCONTROL struct {
	CallType      int
	CallControlOp int
}

type KSTELEPHONY_PROVIDERCHANGE struct {
	CallType         int
	ProviderChangeOp int
}

type KSTELEPHONY_CALLINFO struct {
	CallType  int
	CallState int
}

type KSPROPSETID_TelephonyTopology struct {
}

type KSTOPOLOGY_ENDPOINTID struct {
	TopologyName int
	PinId        int
}

type KSTOPOLOGY_ENDPOINTIDPAIR struct {
	RenderEndpoint  int
	CaptureEndpoint int
}

type KSPROPSETID_FMRXTopology struct {
}

type KSPROPSETID_FMRXControl struct {
}

type KSEVENTSETID_Telephony struct {
}

type KSNODETYPE_DAC struct {
}

type KSNODETYPE_ADC struct {
}

type KSNODETYPE_SRC struct {
}

type KSNODETYPE_SUPERMIX struct {
}

type KSNODETYPE_MUX struct {
}

type KSNODETYPE_DEMUX struct {
}

type KSNODETYPE_SUM struct {
}

type KSNODETYPE_MUTE struct {
}

type KSNODETYPE_VOLUME struct {
}

type KSNODETYPE_TONE struct {
}

type KSNODETYPE_EQUALIZER struct {
}

type KSNODETYPE_AGC struct {
}

type KSNODETYPE_NOISE_SUPPRESS struct {
}

type KSNODETYPE_DELAY struct {
}

type KSNODETYPE_LOUDNESS struct {
}

type KSNODETYPE_PROLOGIC_DECODER struct {
}

type KSNODETYPE_STEREO_WIDE struct {
}

type KSNODETYPE_REVERB struct {
}

type KSNODETYPE_CHORUS struct {
}

type KSNODETYPE_3D_EFFECTS struct {
}

type KSNODETYPE_PARAMETRIC_EQUALIZER struct {
}

type KSNODETYPE_UPDOWN_MIX struct {
}

type KSNODETYPE_DYN_RANGE_COMPRESSOR struct {
}

type KSALGORITHMINSTANCE_SYSTEM_ACOUSTIC_ECHO_CANCEL struct {
}

type KSALGORITHMINSTANCE_SYSTEM_NOISE_SUPPRESS struct {
}

type KSALGORITHMINSTANCE_SYSTEM_AGC struct {
}

type KSALGORITHMINSTANCE_SYSTEM_MICROPHONE_ARRAY_PROCESSOR struct {
}

type KSNODETYPE_DEV_SPECIFIC struct {
}

type KSNODETYPE_PROLOGIC_ENCODER struct {
}

type KSNODETYPE_PEAKMETER struct {
}

type KSAUDFNAME_BASS struct {
}

type KSAUDFNAME_TREBLE struct {
}

type KSAUDFNAME_MIDRANGE struct {
}

type KSAUDFNAME_3D_STEREO struct {
}

type KSAUDFNAME_MASTER_VOLUME struct {
}

type KSAUDFNAME_MASTER_MUTE struct {
}

type KSAUDFNAME_WAVE_VOLUME struct {
}

type KSAUDFNAME_WAVE_MUTE struct {
}

type KSAUDFNAME_MIDI_VOLUME struct {
}

type KSAUDFNAME_MIDI_MUTE struct {
}

type KSAUDFNAME_CD_VOLUME struct {
}

type KSAUDFNAME_CD_MUTE struct {
}

type KSAUDFNAME_LINE_VOLUME struct {
}

type KSAUDFNAME_LINE_MUTE struct {
}

type KSAUDFNAME_MIC_VOLUME struct {
}

type KSAUDFNAME_MIC_MUTE struct {
}

type KSAUDFNAME_RECORDING_SOURCE struct {
}

type KSAUDFNAME_PC_SPEAKER_VOLUME struct {
}

type KSAUDFNAME_PC_SPEAKER_MUTE struct {
}

type KSAUDFNAME_MIDI_IN_VOLUME struct {
}

type KSAUDFNAME_CD_IN_VOLUME struct {
}

type KSAUDFNAME_LINE_IN_VOLUME struct {
}

type KSAUDFNAME_MIC_IN_VOLUME struct {
}

type KSAUDFNAME_WAVE_IN_VOLUME struct {
}

type KSAUDFNAME_VOLUME_CONTROL struct {
}

type KSAUDFNAME_MIDI struct {
}

type KSAUDFNAME_LINE_IN struct {
}

type KSAUDFNAME_RECORDING_CONTROL struct {
}

type KSAUDFNAME_CD_AUDIO struct {
}

type KSAUDFNAME_AUX_VOLUME struct {
}

type KSAUDFNAME_AUX_MUTE struct {
}

type KSAUDFNAME_AUX struct {
}

type KSAUDFNAME_PC_SPEAKER struct {
}

type KSAUDFNAME_WAVE_OUT_MIX struct {
}

type KSAUDFNAME_MONO_OUT struct {
}

type KSAUDFNAME_STEREO_MIX struct {
}

type KSAUDFNAME_MONO_MIX struct {
}

type KSAUDFNAME_MONO_OUT_VOLUME struct {
}

type KSAUDFNAME_MONO_OUT_MUTE struct {
}

type KSAUDFNAME_STEREO_MIX_VOLUME struct {
}

type KSAUDFNAME_STEREO_MIX_MUTE struct {
}

type KSAUDFNAME_MONO_MIX_VOLUME struct {
}

type KSAUDFNAME_MONO_MIX_MUTE struct {
}

type KSAUDFNAME_MICROPHONE_BOOST struct {
}

type KSAUDFNAME_ALTERNATE_MICROPHONE struct {
}

type KSAUDFNAME_3D_DEPTH struct {
}

type KSAUDFNAME_3D_CENTER struct {
}

type KSAUDFNAME_VIDEO_VOLUME struct {
}

type KSAUDFNAME_VIDEO_MUTE struct {
}

type KSAUDFNAME_VIDEO struct {
}

type KSAUDFNAME_PEAKMETER struct {
}

type KSMETHODSETID_Wavetable struct {
}

type KSWAVETABLE_WAVE_DESC struct {
	Identifier int
	Size       int
	Looped     int
	LoopPoint  int
	InROM      int
	Format     int
}

type KSPROPSETID_Wave struct {
}

type KSWAVE_COMPATCAPS struct {
	ULDEVICETYPE int
}

type KSWAVE_INPUT_CAPABILITIES struct {
	MaximumChannelsPerConnection int
	MinimumBitsPerSample         int
	MaximumBitsPerSample         int
	MinimumSampleFrequency       int
	MaximumSampleFrequency       int
	TotalConnections             int
	ActiveConnections            int
}

type KSWAVE_OUTPUT_CAPABILITIES struct {
	MaximumChannelsPerConnection      int
	MinimumBitsPerSample              int
	MaximumBitsPerSample              int
	MinimumSampleFrequency            int
	MaximumSampleFrequency            int
	TotalConnections                  int
	StaticConnections                 int
	StreamingConnections              int
	ActiveConnections                 int
	ActiveStaticConnections           int
	ActiveStreamingConnections        int
	Total3DConnections                int
	Static3DConnections               int
	Streaming3DConnections            int
	Active3DConnections               int
	ActiveStatic3DConnections         int
	ActiveStreaming3DConnections      int
	TotalSampleMemory                 int
	FreeSampleMemory                  int
	LargestFreeContiguousSampleMemory int
}

type KSWAVE_VOLUME struct {
	LeftAttenuation  int
	RightAttenuation int
}

type KSWAVE_BUFFER struct {
	Attributes    int
	BufferSize    int
	BufferAddress int
}

type KSMUSIC_TECHNOLOGY_PORT struct {
}

type KSMUSIC_TECHNOLOGY_SQSYNTH struct {
}

type KSMUSIC_TECHNOLOGY_FMSYNTH struct {
}

type KSMUSIC_TECHNOLOGY_WAVETABLE struct {
}

type KSMUSIC_TECHNOLOGY_SWSYNTH struct {
}

type KSDATARANGE_MUSIC struct {
	DataRange   int
	Technology  int
	Channels    int
	Notes       int
	ChannelMask int
}

type KSPROPSETID_Cyclic struct {
}

type KSEVENTSETID_AudioControlChange struct {
}

type KSEVENTSETID_LoopedStreaming struct {
}

type LOOPEDSTREAMING_POSITION_EVENT_DATA struct {
	KsEventData int
	Position    int
}

type KSNODEPROPERTY struct {
	Property int
	NodeId   int
	Reserved int
}

type KSNODEPROPERTY_AUDIO_CHANNEL struct {
	NodeProperty int
	Channel      int
	Reserved     int
}

type KSNODEPROPERTY_AUDIO_DEV_SPECIFIC struct {
	NodeProperty  int
	DevSpecificId int
	DeviceInfo    int
	Length        int
}

type KSNODEPROPERTY_AUDIO_3D_LISTENER struct {
	NodeProperty int
	ListenerId   int
	Reserved     int
}

type KSNODEPROPERTY_AUDIO_PROPERTY struct {
	NodeProperty int
	AppContext   int
	Length       int
	Reserved     int
}

type KSDATAFORMAT_TYPE_MUSIC struct {
}

type KSDATAFORMAT_TYPE_MIDI struct {
}

type KSDATAFORMAT_SUBTYPE_MIDI struct {
}

type KSDATAFORMAT_SUBTYPE_MIDI_BUS struct {
}

type KSDATAFORMAT_SUBTYPE_RIFFMIDI struct {
}

type KSMUSICFORMAT struct {
	TimeDeltaMs int
	ByteCount   int
}

type KSDATAFORMAT_TYPE_STANDARD_ELEMENTARY_STREAM struct {
}

type KSDATAFORMAT_TYPE_STANDARD_PES_PACKET struct {
}

type KSDATAFORMAT_TYPE_STANDARD_PACK_HEADER struct {
}

type KSDATAFORMAT_SUBTYPE_STANDARD_MPEG1_VIDEO struct {
}

type KSDATAFORMAT_SUBTYPE_STANDARD_MPEG1_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_STANDARD_MPEG2_VIDEO struct {
}

type KSDATAFORMAT_SUBTYPE_STANDARD_MPEG2_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_STANDARD_AC3_AUDIO struct {
}

type KSDATAFORMAT_SPECIFIER_DIALECT_MPEG1_VIDEO struct {
}

type KSDATAFORMAT_SPECIFIER_DIALECT_MPEG1_AUDIO struct {
}

type KSDATAFORMAT_SPECIFIER_DIALECT_MPEG2_VIDEO struct {
}

type KSDATAFORMAT_SPECIFIER_DIALECT_MPEG2_AUDIO struct {
}

type KSDATAFORMAT_SPECIFIER_DIALECT_AC3_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_DSS_VIDEO struct {
}

type KSDATAFORMAT_SUBTYPE_DSS_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_MPEG1Packet struct {
}

type KSDATAFORMAT_SUBTYPE_MPEG1Payload struct {
}

type KSDATAFORMAT_SUBTYPE_MPEG1Video struct {
}

type KSDATAFORMAT_SPECIFIER_MPEG1_VIDEO struct {
}

type KSDATAFORMAT_TYPE_MPEG2_PES struct {
}

type KSDATAFORMAT_TYPE_MPEG2_PROGRAM struct {
}

type KSDATAFORMAT_TYPE_MPEG2_TRANSPORT struct {
}

type KSDATAFORMAT_SUBTYPE_MPEG2_VIDEO struct {
}

type KSDATAFORMAT_SPECIFIER_MPEG2_VIDEO struct {
}

type KSPROPSETID_Mpeg2Vid struct {
}

type KSMPEGVID_RECT struct {
	StartX int
	StartY int
	EndX   int
	EndY   int
}

type KSDATAFORMAT_SUBTYPE_MPEG2_AUDIO struct {
}

type KSDATAFORMAT_SPECIFIER_MPEG2_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_LPCM_AUDIO struct {
}

type KSDATAFORMAT_SPECIFIER_LPCM_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_AC3_AUDIO struct {
}

type KSDATAFORMAT_SPECIFIER_AC3_AUDIO struct {
}

type KSPROPSETID_AC3 struct {
}

type KSAC3_ERROR_CONCEALMENT struct {
	FREPEATPREVIOUSBLOCK int
	FERRORINCURRENTBLOCK int
}

type KSAC3_ALTERNATE_AUDIO struct {
	FSTEREO  int
	DualMode int
}

type KSAC3_DOWNMIX struct {
	FDOWNMIX       int
	FDOLBYSURROUND int
}

type KSAC3_BIT_STREAM_MODE struct {
	BitStreamMode int
}

type KSAC3_DIALOGUE_LEVEL struct {
	DialogueLevel int
}

type KSAC3_ROOM_TYPE struct {
	FLARGEROOM int
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_WMA_PRO struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DTS struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_MPEG1 struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_MPEG2 struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_MPEG3 struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_AAC struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_ATRAC struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_ONE_BIT_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS_ATMOS struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DTS_HD struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_MLP struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_MAT20 struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_MAT21 struct {
}

type KSDATAFORMAT_SUBTYPE_IEC61937_DST struct {
}

type KSDATAFORMAT_SUBTYPE_MPEGLAYER3 struct {
}

type KSDATAFORMAT_SUBTYPE_MPEG_HEAAC struct {
}

type KSDATAFORMAT_SUBTYPE_WMAUDIO2 struct {
}

type KSDATAFORMAT_SUBTYPE_WMAUDIO3 struct {
}

type KSDATAFORMAT_SUBTYPE_WMAUDIO_LOSSLESS struct {
}

type KSDATAFORMAT_SUBTYPE_DTS_AUDIO struct {
}

type KSDATAFORMAT_SUBTYPE_SDDS_AUDIO struct {
}

type KSPROPSETID_AudioDecoderOut struct {
}

type KSDATAFORMAT_SUBTYPE_SUBPICTURE struct {
}

type KSPROPSETID_DvdSubPic struct {
}

type KS_DVD_YCrCb struct {
	Reserved int
	Y        int
	Cr       int
	Cb       int
}

type KS_DVD_YUV struct {
	Reserved int
	Y        int
	V        int
	U        int
}

type KSPROPERTY_SPPAL struct {
	SPPAL int
}

type KS_COLCON struct {
	BITFIELD1 int
	BITFIELD2 int
	BITFIELD3 int
	BITFIELD4 int
}

type KSPROPERTY_SPHLI struct {
	HLISS    int
	Reserved int
	StartPTM int
	EndPTM   int
	StartX   int
	StartY   int
	StopX    int
	StopY    int
	ColCon   int
}

type KSPROPSETID_CopyProt struct {
}

type KS_DVDCOPY_CHLGKEY struct {
	ChlgKey  int
	Reserved int
}

type KS_DVDCOPY_BUSKEY struct {
	BusKey   int
	Reserved int
}

type KS_DVDCOPY_DISCKEY struct {
	DiscKey int
}

type KS_DVDCOPY_REGION struct {
	Reserved   int
	RegionData int
	Reserved2  int
}

type KS_DVDCOPY_TITLEKEY struct {
	KeyFlags   int
	ReservedNT int
	TitleKey   int
	Reserved   int
}

type KS_COPY_MACROVISION struct {
	MACROVISIONLevel int
}

type KS_DVDCOPY_SET_COPY_STATE struct {
	DVDCopyState int
}

type KSCATEGORY_TVTUNER struct {
}

type KSCATEGORY_CROSSBAR struct {
}

type KSCATEGORY_TVAUDIO struct {
}

type KSCATEGORY_VPMUX struct {
}

type KSCATEGORY_VBICODEC struct {
}

type KSDATAFORMAT_SUBTYPE_VPVideo struct {
}

type KSDATAFORMAT_SUBTYPE_VPVBI struct {
}

type KSDATAFORMAT_SPECIFIER_VIDEOINFO struct {
}

type KSDATAFORMAT_SPECIFIER_VIDEOINFO2 struct {
}

type KSDATAFORMAT_SPECIFIER_H264_VIDEO struct {
}

type KSDATAFORMAT_SPECIFIER_JPEG_IMAGE struct {
}

type KSDATAFORMAT_SPECIFIER_IMAGE struct {
}

type KSDATAFORMAT_TYPE_IMAGE struct {
}

type KSDATAFORMAT_SUBTYPE_JPEG struct {
}

type KSDATAFORMAT_SUBTYPE_IMAGE_RGB32 struct {
}

type KSDATAFORMAT_SUBTYPE_L8 struct {
}

type KSDATAFORMAT_SUBTYPE_L8_IR struct {
}

type KSDATAFORMAT_SUBTYPE_L8_CUSTOM struct {
}

type KSDATAFORMAT_SUBTYPE_L16 struct {
}

type KSDATAFORMAT_SUBTYPE_L16_IR struct {
}

type KSDATAFORMAT_SUBTYPE_D16 struct {
}

type KSDATAFORMAT_SUBTYPE_L16_CUSTOM struct {
}

type KSDATAFORMAT_SUBTYPE_MJPG_IR struct {
}

type KSDATAFORMAT_SUBTYPE_MJPG_DEPTH struct {
}

type KSDATAFORMAT_SUBTYPE_MJPG_CUSTOM struct {
}

type KSDATAFORMAT_TYPE_ANALOGVIDEO struct {
}

type KSDATAFORMAT_SPECIFIER_ANALOGVIDEO struct {
}

type KSDATAFORMAT_TYPE_ANALOGAUDIO struct {
}

type KSDATAFORMAT_SPECIFIER_VBI struct {
}

type KSDATAFORMAT_TYPE_VBI struct {
}

type KSDATAFORMAT_SUBTYPE_RAW8 struct {
}

type KSDATAFORMAT_SUBTYPE_CC struct {
}

type KSDATAFORMAT_SUBTYPE_NABTS struct {
}

type KSDATAFORMAT_SUBTYPE_TELETEXT struct {
}

type KS_RGBQUAD struct {
	RGBBLUE     int
	RGBGREEN    int
	RGBRED      int
	RGBRESERVED int
}

type KS_BITMAPINFOHEADER struct {
	BISIZE          int
	BIWIDTH         int
	BIHEIGHT        int
	BIPLANES        int
	BIBITCOUNT      int
	BICOMPRESSION   int
	BISIZEIMAGE     int
	BIXPELSPERMETER int
	BIYPELSPERMETER int
	BICLRUSED       int
	BICLRIMPORTANT  int
}

type TAG_KS_TRUECOLORINFO struct {
	DWBITMASKS int
	BMICOLORS  int
}

type KS_VIDEOINFOHEADER struct {
	RCSOURCE        int
	RCTARGET        int
	DWBITRATE       int
	DWBITERRORRATE  int
	AvgTimePerFrame int
	BMIHEADER       int
}

type KS_VIDEOINFO struct {
	RCSOURCE        int
	RCTARGET        int
	DWBITRATE       int
	DWBITERRORRATE  int
	AvgTimePerFrame int
	BMIHEADER       int
	Anonymous       int
}

type KS_VBIINFOHEADER struct {
	StartLine           int
	EndLine             int
	SamplingFrequency   int
	MinLineStartTime    int
	MaxLineStartTime    int
	ActualLineStartTime int
	ActualLineEndTime   int
	VideoStandard       int
	SamplesPerLine      int
	StrideInBytes       int
	BufferSize          int
}

type TAGKS_ANALOGVIDEOINFO struct {
	RCSOURCE        int
	RCTARGET        int
	DWACTIVEWIDTH   int
	DWACTIVEHEIGHT  int
	AvgTimePerFrame int
}

type KS_TVTUNER_CHANGE_INFO struct {
	DWFLAGS               int
	DWCOUNTRYCODE         int
	DWANALOGVIDEOSTANDARD int
	DWCHANNEL             int
}

type KS_VIDEOINFOHEADER2 struct {
	RCSOURCE           int
	RCTARGET           int
	DWBITRATE          int
	DWBITERRORRATE     int
	AvgTimePerFrame    int
	DWINTERLACEFLAGS   int
	DWCOPYPROTECTFLAGS int
	DWPICTASPECTRATIOX int
	DWPICTASPECTRATIOY int
	Anonymous          int
	DWRESERVED2        int
	BMIHEADER          int
}

type KS_MPEG1VIDEOINFO struct {
	HDR              int
	DWSTARTTIMECODE  int
	CBSEQUENCEHEADER int
	BSEQUENCEHEADER  int
}

type KS_MPEGVIDEOINFO2 struct {
	HDR              int
	DWSTARTTIMECODE  int
	CBSEQUENCEHEADER int
	DWPROFILE        int
	DWLEVEL          int
	DWFLAGS          int
	BSEQUENCEHEADER  int
}

type KS_H264VIDEOINFO struct {
	WWIDTH                                                int
	WHEIGHT                                               int
	WSARWIDTH                                             int
	WSARHEIGHT                                            int
	WPROFILE                                              int
	BLEVELIDC                                             int
	WCONSTRAINEDTOOLSET                                   int
	BMSUPPORTEDUSAGES                                     int
	BMCAPABILITIES                                        int
	BMSVCCAPABILITIES                                     int
	BMMVCCAPABILITIES                                     int
	DWFRAMEINTERVAL                                       int
	BMAXCODECCONFIGDELAY                                  int
	BMSUPPORTEDSLICEMODES                                 int
	BMSUPPORTEDSYNCFRAMETYPES                             int
	BRESOLUTIONSCALING                                    int
	BSIMULCASTSUPPORT                                     int
	BMSUPPORTEDRATECONTROLMODES                           int
	WMAXMBPERSECONERESOLUTIONNOSCALABILITY                int
	WMAXMBPERSECTWORESOLUTIONSNOSCALABILITY               int
	WMAXMBPERSECTHREERESOLUTIONSNOSCALABILITY             int
	WMAXMBPERSECFOURRESOLUTIONSNOSCALABILITY              int
	WMAXMBPERSECONERESOLUTIONTEMPORALSCALABILITY          int
	WMAXMBPERSECTWORESOLUTIONSTEMPORALSCALABLILITY        int
	WMAXMBPERSECTHREERESOLUTIONSTEMPORALSCALABILITY       int
	WMAXMBPERSECFOURRESOLUTIONSTEMPORALSCALABILITY        int
	WMAXMBPERSECONERESOLUTIONTEMPORALQUALITYSCALABILITY   int
	WMAXMBPERSECTWORESOLUTIONSTEMPORALQUALITYSCALABILITY  int
	WMAXMBPERSECTHREERESOLUTIONSTEMPORALQUALITYSCALABLITY int
	WMAXMBPERSECFOURRESOLUTIONSTEMPORALQUALITYSCALABILITY int
	WMAXMBPERSECONERESOLUTIONTEMPORALSPATIALSCALABILITY   int
	WMAXMBPERSECTWORESOLUTIONSTEMPORALSPATIALSCALABILITY  int
	WMAXMBPERSECTHREERESOLUTIONSTEMPORALSPATIALSCALABLITY int
	WMAXMBPERSECFOURRESOLUTIONSTEMPORALSPATIALSCALABILITY int
	WMAXMBPERSECONERESOLUTIONFULLSCALABILITY              int
	WMAXMBPERSECTWORESOLUTIONSFULLSCALABILITY             int
	WMAXMBPERSECTHREERESOLUTIONSFULLSCALABILITY           int
	WMAXMBPERSECFOURRESOLUTIONSFULLSCALABILITY            int
}

type TAGKS_MPEAUDIOINFO struct {
	DWFLAGS     int
	DWRESERVED1 int
	DWRESERVED2 int
	DWRESERVED3 int
}

type KS_DATAFORMAT_VIDEOINFOHEADER struct {
	DataFormat      int
	VideoInfoHeader int
}

type KS_DATAFORMAT_VIDEOINFOHEADER2 struct {
	DataFormat       int
	VideoInfoHeader2 int
}

type KS_DATAFORMAT_MPEGVIDEOINFO2 struct {
	DataFormat           int
	MpegVideoInfoHeader2 int
}

type KS_DATAFORMAT_H264VIDEOINFO struct {
	DataFormat          int
	H264VideoInfoHeader int
}

type KS_DATAFORMAT_IMAGEINFO struct {
	DataFormat      int
	ImageInfoHeader int
}

type KS_DATAFORMAT_VIDEOINFO_PALETTE struct {
	DataFormat int
	VideoInfo  int
}

type KS_DATAFORMAT_VBIINFOHEADER struct {
	DataFormat    int
	VBIInfoHeader int
}

type KS_VIDEO_STREAM_CONFIG_CAPS struct {
	GUID               int
	VideoStandard      int
	InputSize          int
	MinCroppingSize    int
	MaxCroppingSize    int
	CropGranularityX   int
	CropGranularityY   int
	CropAlignX         int
	CropAlignY         int
	MinOutputSize      int
	MaxOutputSize      int
	OutputGranularityX int
	OutputGranularityY int
	StretchTapsX       int
	StretchTapsY       int
	ShrinkTapsX        int
	ShrinkTapsY        int
	MinFrameInterval   int
	MaxFrameInterval   int
	MinBitsPerSecond   int
	MaxBitsPerSecond   int
}

type KS_DATARANGE_VIDEO struct {
	DataRange              int
	BFIXEDSIZESAMPLES      int
	BTEMPORALCOMPRESSION   int
	StreamDescriptionFlags int
	MemoryAllocationFlags  int
	ConfigCaps             int
	VideoInfoHeader        int
}

type KS_DATARANGE_VIDEO2 struct {
	DataRange              int
	BFIXEDSIZESAMPLES      int
	BTEMPORALCOMPRESSION   int
	StreamDescriptionFlags int
	MemoryAllocationFlags  int
	ConfigCaps             int
	VideoInfoHeader        int
}

type KS_DATARANGE_MPEG1_VIDEO struct {
	DataRange              int
	BFIXEDSIZESAMPLES      int
	BTEMPORALCOMPRESSION   int
	StreamDescriptionFlags int
	MemoryAllocationFlags  int
	ConfigCaps             int
	VideoInfoHeader        int
}

type KS_DATARANGE_MPEG2_VIDEO struct {
	DataRange              int
	BFIXEDSIZESAMPLES      int
	BTEMPORALCOMPRESSION   int
	StreamDescriptionFlags int
	MemoryAllocationFlags  int
	ConfigCaps             int
	VideoInfoHeader        int
}

type KS_DATARANGE_H264_VIDEO struct {
	DataRange              int
	BFIXEDSIZESAMPLES      int
	BTEMPORALCOMPRESSION   int
	StreamDescriptionFlags int
	MemoryAllocationFlags  int
	ConfigCaps             int
	VideoInfoHeader        int
}

type KS_DATARANGE_IMAGE struct {
	DataRange       int
	ConfigCaps      int
	ImageInfoHeader int
}

type KS_DATARANGE_VIDEO_PALETTE struct {
	DataRange              int
	BFIXEDSIZESAMPLES      int
	BTEMPORALCOMPRESSION   int
	StreamDescriptionFlags int
	MemoryAllocationFlags  int
	ConfigCaps             int
	VideoInfo              int
}

type KS_DATARANGE_VIDEO_VBI struct {
	DataRange              int
	BFIXEDSIZESAMPLES      int
	BTEMPORALCOMPRESSION   int
	StreamDescriptionFlags int
	MemoryAllocationFlags  int
	ConfigCaps             int
	VBIInfoHeader          int
}

type KS_DATARANGE_ANALOGVIDEO struct {
	DataRange       int
	AnalogVideoInfo int
}

type KSPROPSETID_VBICAP_PROPERTIES struct {
}

type VBICAP_PROPERTIES_PROTECTION_S struct {
	Property    int
	StreamIndex int
	Status      int
}

type KSDATAFORMAT_TYPE_NABTS struct {
}

type KSDATAFORMAT_SUBTYPE_NABTS_FEC struct {
}

type NABTSFEC_BUFFER struct {
	DATASIZE int
	GROUPID  int
	Reserved int
	DATA     int
}

type KSPROPSETID_VBICodecFiltering struct {
}

type VBICODECFILTERING_SCANLINES struct {
	DwordBitArray int
}

type VBICODECFILTERING_NABTS_SUBSTREAMS struct {
	SubstreamMask int
}

type VBICODECFILTERING_CC_SUBSTREAMS struct {
	SubstreamMask int
}

type CC_BYTE_PAIR struct {
	Decoded  int
	Reserved int
}

type CC_HW_FIELD struct {
	ScanlinesRequested int
	FIELDFLAGS         int
	PictureNumber      int
	Lines              int
}

type NABTS_BUFFER_LINE struct {
	Confidence int
	Bytes      int
}

type NABTS_BUFFER struct {
	ScanlinesRequested int
	PictureNumber      int
	NabtsLines         int
}

type WST_BUFFER_LINE struct {
	Confidence int
	Bytes      int
}

type WST_BUFFER struct {
	ScanlinesRequested int
	WstLines           int
}

type VBICODECFILTERING_STATISTICS_COMMON struct {
	InputSRBsProcessed   int
	OutputSRBsProcessed  int
	SRBsIgnored          int
	InputSRBsMissing     int
	OutputSRBsMissing    int
	OutputFailures       int
	InternalErrors       int
	ExternalErrors       int
	InputDiscontinuities int
	DSPFailures          int
	TvTunerChanges       int
	VBIHeaderChanges     int
	LineConfidenceAvg    int
	BytesOutput          int
}

type VBICODECFILTERING_STATISTICS_COMMON_PIN struct {
	SRBsProcessed     int
	SRBsIgnored       int
	SRBsMissing       int
	InternalErrors    int
	ExternalErrors    int
	Discontinuities   int
	LineConfidenceAvg int
	BytesOutput       int
}

type VBICODECFILTERING_STATISTICS_NABTS struct {
	Common                int
	FECBundleBadLines     int
	FECQueueOverflows     int
	FECCorrectedLines     int
	FECUncorrectableLines int
	BundlesProcessed      int
	BundlesSent2IP        int
	FilteredLines         int
}

type VBICODECFILTERING_STATISTICS_NABTS_PIN struct {
	Common int
}

type VBICODECFILTERING_STATISTICS_CC struct {
	Common int
}

type VBICODECFILTERING_STATISTICS_CC_PIN struct {
	Common int
}

type VBICODECFILTERING_STATISTICS_TELETEXT struct {
	Common int
}

type VBICODECFILTERING_STATISTICS_TELETEXT_PIN struct {
	Common int
}

type KSPROPERTY_VBICODECFILTERING_SCANLINES_S struct {
	Property  int
	Scanlines int
}

type KSPROPERTY_VBICODECFILTERING_NABTS_SUBSTREAMS_S struct {
	Property   int
	Substreams int
}

type KSPROPERTY_VBICODECFILTERING_CC_SUBSTREAMS_S struct {
	Property   int
	Substreams int
}

type KSPROPERTY_VBICODECFILTERING_STATISTICS_COMMON_S struct {
	Property   int
	Statistics int
}

type KSPROPERTY_VBICODECFILTERING_STATISTICS_COMMON_PIN_S struct {
	Property   int
	Statistics int
}

type KSPROPERTY_VBICODECFILTERING_STATISTICS_NABTS_S struct {
	Property   int
	Statistics int
}

type KSPROPERTY_VBICODECFILTERING_STATISTICS_NABTS_PIN_S struct {
	Property   int
	Statistics int
}

type KSPROPERTY_VBICODECFILTERING_STATISTICS_CC_S struct {
	Property   int
	Statistics int
}

type KSPROPERTY_VBICODECFILTERING_STATISTICS_CC_PIN_S struct {
	Property   int
	Statistics int
}

type PINNAME_VIDEO_CAPTURE struct {
}

type PINNAME_VIDEO_CC_CAPTURE struct {
}

type PINNAME_VIDEO_NABTS_CAPTURE struct {
}

type PINNAME_VIDEO_PREVIEW struct {
}

type PINNAME_VIDEO_ANALOGVIDEOIN struct {
}

type PINNAME_VIDEO_VBI struct {
}

type PINNAME_VIDEO_VIDEOPORT struct {
}

type PINNAME_VIDEO_NABTS struct {
}

type PINNAME_VIDEO_EDS struct {
}

type PINNAME_VIDEO_TELETEXT struct {
}

type PINNAME_VIDEO_CC struct {
}

type PINNAME_VIDEO_STILL struct {
}

type PINNAME_IMAGE struct {
}

type PINNAME_VIDEO_TIMECODE struct {
}

type PINNAME_VIDEO_VIDEOPORT_VBI struct {
}

type KSPROPSETID_VramCapture struct {
}

type VRAM_SURFACE_INFO struct {
	HSURFACE            int
	VramPhysicalAddress int
	CBCAPTURED          int
	DWWIDTH             int
	DWHEIGHT            int
	DWLINEARSIZE        int
	LPITCH              int
	ULLRESERVED         int
}

type VRAM_SURFACE_INFO_PROPERTY_S struct {
	Property         int
	PVRAMSURFACEINFO int
}

type SECURE_BUFFER_INFO struct {
	GUIDBUFFERIDENTIFIER int
	CBBUFFERSIZE         int
	CBCAPTURED           int
	ULLRESERVED          int
}

type KS_SECURE_CAMERA_SCENARIO_ID struct {
}

type KSPROPSETID_MPEG4_MediaType_Attributes struct {
}

type KSEVENTSETID_DynamicFormatChange struct {
}

type KS_FRAME_INFO struct {
	ExtendedHeaderSize int
	DWFRAMEFLAGS       int
	PictureNumber      int
	DropCount          int
	HDIRECTDRAW        int
	HSURFACEHANDLE     int
	DirectDrawRect     int
	Anonymous1         int
	Reserved2          int
	Anonymous2         int
}

type KS_VBI_FRAME_INFO struct {
	ExtendedHeaderSize  int
	DWFRAMEFLAGS        int
	PictureNumber       int
	DropCount           int
	DWSAMPLINGFREQUENCY int
	TvTunerChangeInfo   int
	VBIInfoHeader       int
}

type PROPSETID_ALLOCATOR_CONTROL struct {
}

type KSPROPERTY_ALLOCATOR_CONTROL_SURFACE_SIZE_S struct {
	CX int
	CY int
}

type KSPROPERTY_ALLOCATOR_CONTROL_CAPTURE_CAPS_S struct {
	InterleavedCapSupported int
}

type KSPROPERTY_ALLOCATOR_CONTROL_CAPTURE_INTERLEAVE_S struct {
	InterleavedCapPossible int
}

type PROPSETID_VIDCAP_VIDEOPROCAMP struct {
}

type KSPROPERTY_VIDEOPROCAMP_S struct {
	Property     int
	Value        int
	Flags        int
	Capabilities int
}

type KSPROPERTY_VIDEOPROCAMP_NODE_S struct {
	NodeProperty int
	Value        int
	Flags        int
	Capabilities int
}

type KSPROPERTY_VIDEOPROCAMP_S2 struct {
	Property     int
	Value1       int
	Flags        int
	Capabilities int
	Value2       int
}

type KSPROPERTY_VIDEOPROCAMP_NODE_S2 struct {
	NodeProperty int
	Value1       int
	Flags        int
	Capabilities int
	Value2       int
}

type PROPSETID_VIDCAP_SELECTOR struct {
}

type KSPROPERTY_SELECTOR_S struct {
	Property     int
	Value        int
	Flags        int
	Capabilities int
}

type KSPROPERTY_SELECTOR_NODE_S struct {
	NodeProperty int
	Value        int
	Flags        int
	Capabilities int
}

type PROPSETID_TUNER struct {
}

type KSPROPERTY_TUNER_CAPS_S struct {
	Property         int
	ModesSupported   int
	VideoMedium      int
	TVAudioMedium    int
	RadioAudioMedium int
}

type KSPROPERTY_TUNER_IF_MEDIUM_S struct {
	Property int
	IFMedium int
}

type KSPROPERTY_TUNER_MODE_CAPS_S struct {
	Property           int
	Mode               int
	StandardsSupported int
	MinFrequency       int
	MaxFrequency       int
	TuningGranularity  int
	NumberOfInputs     int
	SettlingTime       int
	Strategy           int
}

type KSPROPERTY_TUNER_MODE_S struct {
	Property int
	Mode     int
}

type KSPROPERTY_TUNER_FREQUENCY_S struct {
	Property        int
	Frequency       int
	LastFrequency   int
	TuningFlags     int
	VideoSubChannel int
	AudioSubChannel int
	Channel         int
	Country         int
}

type KSPROPERTY_TUNER_STANDARD_S struct {
	Property int
	Standard int
}

type KSPROPERTY_TUNER_STANDARD_MODE_S struct {
	Property   int
	AutoDetect int
}

type KSPROPERTY_TUNER_INPUT_S struct {
	Property   int
	InputIndex int
}

type KSPROPERTY_TUNER_STATUS_S struct {
	Property         int
	CurrentFrequency int
	PLLOffset        int
	SignalStrength   int
	Busy             int
}

type TUNER_ANALOG_CAPS_S struct {
	Mode                 int
	StandardsSupported   int
	MinFrequency         int
	MaxFrequency         int
	TuningGranularity    int
	SettlingTime         int
	ScanSensingRange     int
	FineTuneSensingRange int
}

type EVENTSETID_TUNER struct {
}

type KSPROPERTY_TUNER_SCAN_CAPS_S struct {
	Property                          int
	FSUPPORTSHARDWAREASSISTEDSCANNING int
	SupportedBroadcastStandards       int
	GUIDBucket                        int
	LENGTHOFBUCKET                    int
}

type KSPROPERTY_TUNER_NETWORKTYPE_SCAN_CAPS_S struct {
	Property                 int
	NetworkType              int
	BufferSize               int
	NetworkTunerCapabilities int
}

type KSPROPERTY_TUNER_SCAN_STATUS_S struct {
	Property         int
	LockStatus       int
	CurrentFrequency int
}

type KSEVENT_TUNER_INITIATE_SCAN_S struct {
	EventData      int
	StartFrequency int
	EndFrequency   int
}

type KSNODETYPE_VIDEO_STREAMING struct {
}

type KSNODETYPE_VIDEO_INPUT_TERMINAL struct {
}

type KSNODETYPE_VIDEO_OUTPUT_TERMINAL struct {
}

type KSNODETYPE_VIDEO_SELECTOR struct {
}

type KSNODETYPE_VIDEO_PROCESSING struct {
}

type KSNODETYPE_VIDEO_CAMERA_TERMINAL struct {
}

type KSNODETYPE_VIDEO_INPUT_MTT struct {
}

type KSNODETYPE_VIDEO_OUTPUT_MTT struct {
}

type PROPSETID_VIDCAP_VIDEOENCODER struct {
}

type KSPROPERTY_VIDEOENCODER_S struct {
	Property     int
	Value        int
	Flags        int
	Capabilities int
}

type PROPSETID_VIDCAP_VIDEODECODER struct {
}

type KSPROPERTY_VIDEODECODER_CAPS_S struct {
	Property           int
	StandardsSupported int
	Capabilities       int
	SettlingTime       int
	HSyncPerVSync      int
}

type KSPROPERTY_VIDEODECODER_STATUS_S struct {
	Property      int
	NumberOfLines int
	SignalLocked  int
}

type KSPROPERTY_VIDEODECODER_STATUS2_S struct {
	Property      int
	NumberOfLines int
	SignalLocked  int
	ChromaLock    int
}

type KSPROPERTY_VIDEODECODER_S struct {
	Property int
	Value    int
}

type EVENTSETID_VIDEODECODER struct {
}

type KSEVENTSETID_CameraAsyncControl struct {
}

type PROPSETID_VIDCAP_CAMERACONTROL struct {
}

type KSPROPERTY_CAMERACONTROL_S_EX struct {
	Property     int
	Value        int
	Flags        int
	Capabilities int
	FocusRect    int
}

type KSPROPERTY_CAMERACONTROL_S struct {
	Property     int
	Value        int
	Flags        int
	Capabilities int
}

type KSPROPERTY_CAMERACONTROL_NODE_S struct {
	NodeProperty int
	Value        int
	Flags        int
	Capabilities int
}

type KSPROPERTY_CAMERACONTROL_S2 struct {
	Property     int
	Value1       int
	Flags        int
	Capabilities int
	Value2       int
}

type KSPROPERTY_CAMERACONTROL_NODE_S2 struct {
	NodeProperty int
	Value1       int
	Flags        int
	Capabilities int
	Value2       int
}

type KSPROPERTY_CAMERACONTROL_FOCAL_LENGTH_S struct {
	Property                 int
	LOCULARFOCALLENGTH       int
	LOBJECTIVEFOCALLENGTHMIN int
	LOBJECTIVEFOCALLENGTHMAX int
}

type KSPROPERTY_CAMERACONTROL_NODE_FOCAL_LENGTH_S struct {
	NodeProperty             int
	LOCULARFOCALLENGTH       int
	LOBJECTIVEFOCALLENGTHMIN int
	LOBJECTIVEFOCALLENGTHMAX int
}

type PROPSETID_VIDCAP_CAMERACONTROL_FLASH struct {
}

type KSPROPERTY_CAMERACONTROL_FLASH_S struct {
	Flash        int
	Capabilities int
}

type PROPSETID_VIDCAP_CAMERACONTROL_VIDEO_STABILIZATION struct {
}

type KSPROPERTY_CAMERACONTROL_VIDEOSTABILIZATION_MODE_S struct {
	VideoStabilizationMode int
	Capabilities           int
}

type PROPSETID_VIDCAP_CAMERACONTROL_REGION_OF_INTEREST struct {
}

type EVENTSETID_VIDCAP_CAMERACONTROL_REGION_OF_INTEREST struct {
}

type KSPROPERTY_CAMERACONTROL_REGION_OF_INTEREST_S struct {
	FocusRect            int
	AutoFocusLock        int
	AutoExposureLock     int
	AutoWhitebalanceLock int
	Anonymous            int
}

type PROPSETID_VIDCAP_CAMERACONTROL_IMAGE_PIN_CAPABILITY struct {
}

type KSPROPERTY_CAMERACONTROL_IMAGE_PIN_CAPABILITY_S struct {
	Capabilities int
	Reserved0    int
}

type KSPROPERTYSETID_ExtendedCameraControl struct {
}

type KSEVENTSETID_ExtendedCameraControl struct {
}

type KSEVENTSETID_CameraEvent struct {
}

type KSCAMERA_EXTENDEDPROP_HEADER struct {
	Version    int
	PinId      int
	Size       int
	Result     int
	Flags      int
	Capability int
}

type KSCAMERA_EXTENDEDPROP_VALUE struct {
	Value int
}

type KSCAMERA_MAXVIDEOFPS_FORPHOTORES struct {
	PhotoResWidth   int
	PhotoResHeight  int
	PreviewFPSNum   int
	PreviewFPSDenom int
	CaptureFPSNum   int
	CaptureFPSDenom int
}

type KSCAMERA_EXTENDEDPROP_PHOTOMODE struct {
	RequestedHistoryFrames int
	MaxHistoryFrames       int
	SubMode                int
	Reserved               int
}

type KSCAMERA_EXTENDEDPROP_VIDEOPROCSETTING struct {
	Mode      int
	Min       int
	Max       int
	Step      int
	VideoProc int
	Reserved  int
}

type KSCAMERA_EXTENDEDPROP_EVCOMPENSATION struct {
	Mode     int
	Min      int
	Max      int
	Value    int
	Reserved int
}

type KSCAMERA_EXTENDEDPROP_FIELDOFVIEW struct {
	NormalizedFocalLengthX int
	NormalizedFocalLengthY int
	Flag                   int
	Reserved               int
}

type KSCAMERA_EXTENDEDPROP_CAMERAOFFSET struct {
	PitchAngle int
	YawAngle   int
	Flag       int
	Reserved   int
}

type KSCAMERA_EXTENDEDPROP_METADATAINFO struct {
	BufferAlignment       int
	MaxMetadataBufferSize int
}

type KSCAMERA_METADATA_ITEMHEADER struct {
	MetadataId int
	Size       int
}

type KSCAMERA_METADATA_PHOTOCONFIRMATION struct {
	Header                 int
	PhotoConfirmationIndex int
	Reserved               int
}

type KSCAMERA_METADATA_FRAMEILLUMINATION struct {
	Header   int
	Flags    int
	Reserved int
}

type KSCAMERA_METADATA_CAPTURESTATS struct {
	Header                    int
	Flags                     int
	Reserved                  int
	ExposureTime              int
	ExposureCompensationFlags int
	ExposureCompensationValue int
	IsoSpeed                  int
	FocusState                int
	LensPosition              int
	WhiteBalance              int
	Flash                     int
	FlashPower                int
	ZoomFactor                int
	SceneMode                 int
	SensorFramerate           int
}

type KSCAMERA_EXTENDEDPROP_ROI_CONFIGCAPSHEADER struct {
	Size           int
	ConfigCapCount int
	Reserved       int
}

type KSCAMERA_EXTENDEDPROP_ROI_CONFIGCAPS struct {
	ControlId       int
	MaxNumberOfROIs int
	Capability      int
}

type KSCAMERA_EXTENDEDPROP_ROI_ISPCONTROLHEADER struct {
	Size         int
	ControlCount int
	Reserved     int
}

type KSCAMERA_EXTENDEDPROP_ROI_ISPCONTROL struct {
	ControlId int
	ROICount  int
	Result    int
	Reserved  int
}

type KSCAMERA_EXTENDEDPROP_ROI_INFO struct {
	Region               int
	Flags                int
	Weight               int
	RegionOfInterestType int
}

type KSCAMERA_EXTENDEDPROP_ROI_WHITEBALANCE struct {
	ROIInfo  int
	Reserved int
}

type KSCAMERA_EXTENDEDPROP_ROI_EXPOSURE struct {
	ROIInfo  int
	Reserved int
}

type KSCAMERA_EXTENDEDPROP_ROI_FOCUS struct {
	ROIInfo  int
	Reserved int
}

type KSPROPERTYSETID_PerFrameSettingControl struct {
}

type KSCAMERA_PERFRAMESETTING_CAP_ITEM_HEADER struct {
	Size  int
	Type  int
	Flags int
}

type KSCAMERA_PERFRAMESETTING_CAP_HEADER struct {
	Size      int
	ItemCount int
	Flags     int
}

type KSCAMERA_PERFRAMESETTING_CUSTOM_ITEM struct {
	Size     int
	Reserved int
	Id       int
}

type KSCAMERA_PERFRAMESETTING_ITEM_HEADER struct {
	Size  int
	Type  int
	Flags int
}

type KSCAMERA_PERFRAMESETTING_FRAME_HEADER struct {
	Size      int
	Id        int
	ItemCount int
	Reserved  int
}

type KSCAMERA_PERFRAMESETTING_HEADER struct {
	Size       int
	FrameCount int
	Id         int
	Flags      int
	LoopCount  int
	Reserved   int
}

type KSCAMERA_EXTENDEDPROP_PROFILE struct {
	ProfileId int
	Index     int
	Reserved  int
}

type KSCAMERAPROFILE_Legacy struct {
}

type KSCAMERAPROFILE_VideoRecording struct {
}

type KSCAMERAPROFILE_HighQualityPhoto struct {
}

type KSCAMERAPROFILE_BalancedVideoAndPhoto struct {
}

type KSCAMERAPROFILE_VideoConferencing struct {
}

type KSCAMERAPROFILE_PhotoSequence struct {
}

type KSCAMERAPROFILE_FaceAuth_Mode struct {
}

type KSCAMERAPROFILE_HighFrameRate struct {
}

type KSCAMERAPROFILE_HDRWithWCGVideo struct {
}

type KSCAMERAPROFILE_HDRWithWCGPhoto struct {
}

type KSCAMERAPROFILE_VariablePhotoSequence struct {
}

type KSCAMERAPROFILE_VideoHDR8 struct {
}

type KSCAMERA_PROFILE_MEDIAINFO struct {
	Resolution   int
	MaxFrameRate int
	Flags        int
	Data0        int
	Data1        int
	Data2        int
	Data3        int
}

type KSCAMERA_PROFILE_PININFO struct {
	PinCategory    int
	Anonymous      int
	MediaInfoCount int
	MediaInfos     int
}

type KSCAMERA_PROFILE_INFO struct {
	ProfileId int
	Index     int
	PinCount  int
	Pins      int
}

type KSCAMERA_PROFILE_CONCURRENCYINFO struct {
	ReferenceGuid int
	Reserved      int
	ProfileCount  int
	Profiles      int
}

type KSDEVICE_PROFILE_INFO struct {
	Type      int
	Size      int
	Anonymous int
}

type WNF_KSCAMERA_STREAMSTATE_INFO struct {
	ProcessId   int
	SessionId   int
	StreamState int
	Reserved    int
}

type KSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_HEADER struct {
	Size int
	Type int
}

type KSPROPERTYSETID_NetworkCameraControl struct {
}

type PROPSETID_EXT_DEVICE struct {
}

type DEVCAPS struct {
	CanRecord         int
	CanRecordStrobe   int
	HasAudio          int
	HasVideo          int
	UsesFiles         int
	CanSave           int
	DeviceType        int
	TCRead            int
	TCWrite           int
	CTLRead           int
	IndexRead         int
	Preroll           int
	Postroll          int
	SyncAcc           int
	NormRate          int
	CanPreview        int
	CanMonitorSrc     int
	CanTest           int
	VideoIn           int
	AudioIn           int
	Calibrate         int
	SeekType          int
	SimulatedHardware int
}

type KSPROPERTY_EXTDEVICE_S struct {
	Property int
	U        int
}

type PROPSETID_EXT_TRANSPORT struct {
}

type TRANSPORTSTATUS struct {
	Mode             int
	LastError        int
	RecordInhibit    int
	ServoLock        int
	MediaPresent     int
	MediaLength      int
	MediaSize        int
	MediaTrackCount  int
	MediaTrackLength int
	MediaTrackSide   int
	MediaType        int
	LinkMode         int
	NotifyOn         int
}

type TRANSPORTBASICPARMS struct {
	TimeFormat      int
	TimeReference   int
	Superimpose     int
	EndStopAction   int
	RecordFormat    int
	StepFrames      int
	SetpField       int
	Preroll         int
	RecPreroll      int
	Postroll        int
	EditDelay       int
	PlayTCDelay     int
	RecTCDelay      int
	EditField       int
	FrameServo      int
	ColorFrameServo int
	ServoRef        int
	WarnGenlock     int
	SetTracking     int
	VolumeName      int
	Ballistic       int
	Speed           int
	CounterFormat   int
	TunerChannel    int
	TunerNumber     int
	TimerEvent      int
	TimerStartDay   int
	TimerStartTime  int
	TimerStopDay    int
	TimerStopTime   int
}

type TRANSPORTVIDEOPARMS struct {
	OutputMode int
	Input      int
}

type TRANSPORTAUDIOPARMS struct {
	EnableOutput  int
	EnableRecord  int
	EnableSelsync int
	Input         int
	MonitorSource int
}

type MEDIUM_INFO struct {
	MediaPresent  int
	MediaType     int
	RecordInhibit int
}

type TRANSPORT_STATE struct {
	Mode  int
	State int
}

type KSPROPERTY_EXTXPORT_S struct {
	Property int
	U        int
}

type KSPROPERTY_EXTXPORT_NODE_S struct {
	NodeProperty int
	U            int
}

type PROPSETID_TIMECODE_READER struct {
}

type KSPROPERTY_TIMECODE_S struct {
	Property     int
	TimecodeSamp int
}

type KSPROPERTY_TIMECODE_NODE_S struct {
	NodeProperty int
	TimecodeSamp int
}

type KSEVENTSETID_EXTDEV_Command struct {
}

type PROPSETID_VIDCAP_CROSSBAR struct {
}

type KSPROPERTY_CROSSBAR_CAPS_S struct {
	Property        int
	NumberOfInputs  int
	NumberOfOutputs int
}

type KSPROPERTY_CROSSBAR_PININFO_S struct {
	Property        int
	Direction       int
	Index           int
	PinType         int
	RelatedPinIndex int
	Medium          int
}

type KSPROPERTY_CROSSBAR_ROUTE_S struct {
	Property       int
	IndexInputPin  int
	IndexOutputPin int
	CanRoute       int
}

type KSPROPERTY_CROSSBAR_ACTIVE_S struct {
	Property      int
	IndexInputPin int
	Active        int
}

type EVENTSETID_CROSSBAR struct {
}

type PROPSETID_VIDCAP_TVAUDIO struct {
}

type KSPROPERTY_TVAUDIO_CAPS_S struct {
	Property     int
	Capabilities int
	InputMedium  int
	OutputMedium int
}

type KSPROPERTY_TVAUDIO_S struct {
	Property int
	Mode     int
}

type KSEVENTSETID_VIDCAP_TVAUDIO struct {
}

type PROPSETID_VIDCAP_VIDEOCOMPRESSION struct {
}

type KSPROPERTY_VIDEOCOMPRESSION_GETINFO_S struct {
	Property                int
	StreamIndex             int
	DefaultKeyFrameRate     int
	DefaultPFrameRate       int
	DefaultQuality          int
	NumberOfQualitySettings int
	Capabilities            int
}

type KSPROPERTY_VIDEOCOMPRESSION_S struct {
	Property    int
	StreamIndex int
	Value       int
}

type KSPROPERTY_VIDEOCOMPRESSION_S1 struct {
	Property    int
	StreamIndex int
	Value       int
	Flags       int
}

type KSDATAFORMAT_SUBTYPE_OVERLAY struct {
}

type KSPROPSETID_OverlayUpdate struct {
}

type KSDISPLAYCHANGE struct {
	PelsWidth  int
	PelsHeight int
	BitsPerPel int
	DeviceID   int
}

type PROPSETID_VIDCAP_VIDEOCONTROL struct {
}

type KSPROPERTY_VIDEOCONTROL_CAPS_S struct {
	Property         int
	StreamIndex      int
	VideoControlCaps int
}

type KSPROPERTY_VIDEOCONTROL_MODE_S struct {
	Property    int
	StreamIndex int
	Mode        int
}

type KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S struct {
	Property                     int
	StreamIndex                  int
	RangeIndex                   int
	Dimensions                   int
	CurrentActualFrameRate       int
	CurrentMaxAvailableFrameRate int
}

type KSPROPERTY_VIDEOCONTROL_FRAME_RATES_S struct {
	Property    int
	StreamIndex int
	RangeIndex  int
	Dimensions  int
}

type PROPSETID_VIDCAP_DROPPEDFRAMES struct {
}

type KSPROPERTY_DROPPEDFRAMES_CURRENT_S struct {
	Property         int
	PictureNumber    int
	DropCount        int
	AverageFrameSize int
}

type KSPROPSETID_VPConfig struct {
}

type KSPROPSETID_VPVBIConfig struct {
}

type CLSID_KsIBasicAudioInterfaceHandler struct {
}

type DDVIDEOPORTCONNECT struct {
	DWSIZE      int
	DWPORTWIDTH int
	GUIDTYPEID  int
	DWFLAGS     int
	DWRESERVED1 int
}

type KS_AMVPDIMINFO struct {
	DWFIELDWIDTH  int
	DWFIELDHEIGHT int
	DWVBIWIDTH    int
	DWVBIHEIGHT   int
	RCVALIDREGION int
}

type KS_AMVPDATAINFO struct {
	DWSIZE                 int
	DWMICROSECONDSPERFIELD int
	AMVPDIMINFO            int
	DWPICTASPECTRATIOX     int
	DWPICTASPECTRATIOY     int
	BENABLEDOUBLECLOCK     int
	BENABLEVACT            int
	BDATAISINTERLACED      int
	LHALFLINESODD          int
	BFIELDPOLARITYINVERTED int
	DWNUMLINESINVREF       int
	LHALFLINESEVEN         int
	DWRESERVED1            int
}

type KS_AMVPSIZE struct {
	DWWIDTH  int
	DWHEIGHT int
}

type KSVPMAXPIXELRATE struct {
	Size               int
	MaxPixelsPerSecond int
	Reserved           int
}

type KSVPSIZE_PROP struct {
	Property int
	Size     int
}

type KSVPSURFACEPARAMS struct {
	DWPITCH   int
	DWXORIGIN int
	DWYORIGIN int
}

type KSEVENTSETID_VPNotify struct {
}

type KSEVENTSETID_VIDCAPTOSTI struct {
}

type KSEVENTSETID_VPVBINotify struct {
}

type KSDATAFORMAT_TYPE_AUXLine21Data struct {
}

type KSDATAFORMAT_SUBTYPE_Line21_BytePair struct {
}

type KSDATAFORMAT_SUBTYPE_Line21_GOPPacket struct {
}

type KSGOP_USERDATA struct {
	SC        int
	RESERVED1 int
	CFIELDS   int
	L21DATA   int
}

type KSDATAFORMAT_TYPE_DVD_ENCRYPTED_PACK struct {
}

type KSPROPSETID_TSRateChange struct {
}

type KS_AM_SimpleRateChange struct {
	StartTime int
	Rate      int
}

type KS_AM_ExactRateChange struct {
	OutputZeroTime int
	Rate           int
}

type KSCATEGORY_ENCODER struct {
}

type KSCATEGORY_MULTIPLEXER struct {
}

type ENCAPIPARAM_BITRATE struct {
}

type ENCAPIPARAM_PEAK_BITRATE struct {
}

type ENCAPIPARAM_BITRATE_MODE struct {
}

type CODECAPI_CHANGELISTS struct {
}

type CODECAPI_VIDEO_ENCODER struct {
}

type CODECAPI_AUDIO_ENCODER struct {
}

type CODECAPI_SETALLDEFAULTS struct {
}

type CODECAPI_ALLSETTINGS struct {
}

type CODECAPI_SUPPORTSEVENTS struct {
}

type CODECAPI_CURRENTCHANGELIST struct {
}

type KSPROPSETID_Jack struct {
}

type KSJACK_DESCRIPTION struct {
	ChannelMapping int
	Color          int
	ConnectionType int
	GeoLocation    int
	GenLocation    int
	PortConnection int
	IsConnected    int
}

type KSJACK_SINK_INFORMATION struct {
	ConnType              int
	ManufacturerId        int
	ProductId             int
	AudioLatency          int
	HDCPCapable           int
	AICapable             int
	SinkDescriptionLength int
	SinkDescription       int
	PortId                int
}

type KSJACK_DESCRIPTION2 struct {
	DeviceStateInfo  int
	JackCapabilities int
}

type KSPROPSETID_AudioPosture struct {
}

type KSAUDIOPOSTURE_PANEL_STATE struct {
	Power       int
	Orientation int
}

type KSAUDIOPOSTURE_DESCRIPTION struct {
	CbSize           int
	MembersListCount int
}

type KSPROPSETID_AudioBufferDuration struct {
}

type KSPROPSETID_AudioEngine struct {
}

type KSAUDIOENGINE_DESCRIPTOR struct {
	NHOSTPINID     int
	NOFFLOADPINID  int
	NLOOPBACKPINID int
}

type KSAUDIOENGINE_BUFFER_SIZE_RANGE struct {
	MinBufferBytes int
	MaxBufferBytes int
}

type KSAUDIOENGINE_VOLUMELEVEL struct {
	TargetVolume  int
	CurveType     int
	CurveDuration int
}

type KSPROPSETID_AudioSignalProcessing struct {
}

type KSATTRIBUTEID_AUDIOSIGNALPROCESSING_MODE struct {
}

type KSATTRIBUTE_AUDIOSIGNALPROCESSING_MODE struct {
	AttributeHeader      int
	SignalProcessingMode int
}

type AUDIO_SIGNALPROCESSINGMODE_DEFAULT struct {
}

type AUDIO_SIGNALPROCESSINGMODE_RAW struct {
}

type BLUETOOTHLE_MIDI_SERVICE_UUID struct {
}

type BLUETOOTH_MIDI_DATAIO_CHARACTERISTIC struct {
}

type APO_CLASS_UUID struct {
}

type AUDIOENDPOINT_CLASS_UUID struct {
}

type AUDIO_SIGNALPROCESSINGMODE_COMMUNICATIONS struct {
}

type AUDIO_SIGNALPROCESSINGMODE_SPEECH struct {
}

type AUDIO_SIGNALPROCESSINGMODE_NOTIFICATION struct {
}

type AUDIO_SIGNALPROCESSINGMODE_MEDIA struct {
}

type AUDIO_SIGNALPROCESSINGMODE_MOVIE struct {
}

type AUDIO_EFFECT_TYPE_ACOUSTIC_ECHO_CANCELLATION struct {
}

type AUDIO_EFFECT_TYPE_NOISE_SUPPRESSION struct {
}

type AUDIO_EFFECT_TYPE_AUTOMATIC_GAIN_CONTROL struct {
}

type AUDIO_EFFECT_TYPE_BEAMFORMING struct {
}

type AUDIO_EFFECT_TYPE_CONSTANT_TONE_REMOVAL struct {
}

type AUDIO_EFFECT_TYPE_EQUALIZER struct {
}

type AUDIO_EFFECT_TYPE_LOUDNESS_EQUALIZER struct {
}

type AUDIO_EFFECT_TYPE_BASS_BOOST struct {
}

type AUDIO_EFFECT_TYPE_VIRTUAL_SURROUND struct {
}

type AUDIO_EFFECT_TYPE_VIRTUAL_HEADPHONES struct {
}

type AUDIO_EFFECT_TYPE_SPEAKER_FILL struct {
}

type AUDIO_EFFECT_TYPE_ROOM_CORRECTION struct {
}

type AUDIO_EFFECT_TYPE_BASS_MANAGEMENT struct {
}

type AUDIO_EFFECT_TYPE_ENVIRONMENTAL_EFFECTS struct {
}

type AUDIO_EFFECT_TYPE_SPEAKER_PROTECTION struct {
}

type AUDIO_EFFECT_TYPE_SPEAKER_COMPENSATION struct {
}

type AUDIO_EFFECT_TYPE_DYNAMIC_RANGE_COMPRESSION struct {
}

type KSPROPSETID_AudioModule struct {
}

type KSAUDIOMODULE_DESCRIPTOR struct {
	ClassId      int
	InstanceId   int
	VersionMajor int
	VersionMinor int
	Name         int
}

type KSAUDIOMODULE_PROPERTY struct {
	Property   int
	ClassId    int
	InstanceId int
}

type KSNOTIFICATIONID_AudioModule struct {
}

type KSAUDIOMODULE_NOTIFICATION struct {
	Anonymous int
}

type AudioClientProperties struct {
	CBSIZE     int
	BISOFFLOAD int
	ECATEGORY  int
	Options    int
}

type AudioClient3ActivationParams struct {
	TRACINGCONTEXTID int
}

type AMBISONICS_PARAMS struct {
	U32SIZE            int
	U32VERSION         int
	U32TYPE            int
	U32CHANNELORDERING int
	U32NORMALIZATION   int
	U32ORDER           int
	U32NUMCHANNELS     int
	PU32CHANNELMAP     int
}

type SpatialAudioObjectRenderStreamActivationParams struct {
	ObjectFormat          int
	StaticObjectTypeMask  int
	MinDynamicObjectCount int
	MaxDynamicObjectCount int
	Category              int
	EventHandle           int
	NotifyObject          int
}

type SpatialAudioClientActivationParams struct {
	TRACINGCONTEXTID int
	APPID            int
	MAJORVERSION     int
	MINORVERSION1    int
	MINORVERSION2    int
	MINORVERSION3    int
}

type SpatialAudioHrtfDirectivity struct {
	Type    int
	Scaling int
}

type SpatialAudioHrtfDirectivityCardioid struct {
	DIRECTIVITY int
	Order       int
}

type SpatialAudioHrtfDirectivityCone struct {
	DIRECTIVITY int
	InnerAngle  int
	OuterAngle  int
}

type SpatialAudioHrtfDirectivityUnion struct {
	Cone    int
	Cardiod int
	Omni    int
}

type SpatialAudioHrtfDistanceDecay struct {
	Type              int
	MaxGain           int
	MinGain           int
	UnityGainDistance int
	CutoffDistance    int
}

type SpatialAudioHrtfActivationParams struct {
	ObjectFormat          int
	StaticObjectTypeMask  int
	MinDynamicObjectCount int
	MaxDynamicObjectCount int
	Category              int
	EventHandle           int
	NotifyObject          int
	DistanceDecay         int
	Directivity           int
	Environment           int
	Orientation           int
}

type MMDeviceEnumerator struct {
}

type DIRECTX_AUDIO_ACTIVATION_PARAMS struct {
	CBDIRECTXAUDIOACTIVATIONPARAMS int
	GUIDAUDIOSESSION               int
	DWAUDIOSTREAMFLAGS             int
}

type AudioExtensionParams struct {
	AddPageParam  int
	PENDPOINT     int
	PPNPINTERFACE int
	PPNPDEVNODE   int
}

type AUDIO_ENDPOINT_SHARED_CREATE_PARAMS struct {
	U32SIZE                     int
	U32TSSESSIONID              int
	TARGETENDPOINTCONNECTORTYPE int
	WFXDEVICEFORMAT             int
}

type DEVINTERFACE_AUDIOENDPOINTPLUGIN struct {
}

type DeviceTopology struct {
}

type AUDIO_VOLUME_NOTIFICATION_DATA struct {
	GUIDEVENTCONTEXT int
	BMUTED           int
	FMASTERVOLUME    int
	NCHANNELS        int
	AFCHANNELVOLUMES int
}

type SpatialAudioMetadataItemsInfo struct {
	FrameCount           int
	ItemCount            int
	MaxItemCount         int
	MaxValueBufferLength int
}

type SpatialAudioObjectRenderStreamForMetadataActivationParams struct {
	ObjectFormat             int
	StaticObjectTypeMask     int
	MinDynamicObjectCount    int
	MaxDynamicObjectCount    int
	Category                 int
	EventHandle              int
	MetadataFormatId         int
	MaxMetadataItemCount     int
	MetadataActivationParams int
	NotifyObject             int
}
