// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package directmanipulation implements the Windows.Win32.DirectManipulation namespace.
package directmanipulation

type IDirectManipulationSnapPointsInertiaBehavior struct {
}

type IDirectManipulationContent2 struct {
}

type IDirectManipulationViewport3 struct {
}

type IDirectManipulationPrimaryContent2 struct {
}

type IDirectManipulationParametricMotionBehavior struct {
}

type IDirectManipulationParametricMotionCurve struct {
}

type IDirectManipulationParametricRestPointList struct {
}

type IDirectManipulationParametricRestPointBehavior struct {
}

type IDirectManipulationCompositorPartner struct {
}

type IDirectManipulationManagerPartner struct {
}

type IDirectManipulationViewportPartner struct {
}

type DirectManipulationViewport struct {
}

type DirectManipulationUpdateManager struct {
}

type DirectManipulationPrimaryContent struct {
}

type DirectManipulationManager struct {
}

type DirectManipulationSharedManager struct {
}

type DCompManipulationCompositor struct {
}
