// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package location implements the Windows.Win32.Location namespace.
package location

type LOCATION_REPORT_STATUS int32

const (
	REPORT_NOT_SUPPORTED = 0
	REPORT_ERROR = 1
	REPORT_ACCESS_DENIED = 2
	REPORT_INITIALIZING = 3
	REPORT_RUNNING = 4
)

