// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package softwaredevice implements the Windows.Win32.SoftwareDevice namespace.
package softwaredevice

type SW_DEVICE_CAPABILITIES int32

const (
	SWDeviceCapabilitiesNone           SW_DEVICE_CAPABILITIES = 0
	SWDeviceCapabilitiesRemovable      SW_DEVICE_CAPABILITIES = 1
	SWDeviceCapabilitiesSilentInstall  SW_DEVICE_CAPABILITIES = 2
	SWDeviceCapabilitiesNoDisplayInUI  SW_DEVICE_CAPABILITIES = 4
	SWDeviceCapabilitiesDriverRequired SW_DEVICE_CAPABILITIES = 8
)

type SW_DEVICE_LIFETIME int32

const (
	SWDeviceLifetimeHandle        SW_DEVICE_LIFETIME = 0
	SWDeviceLifetimeParentPresent SW_DEVICE_LIFETIME = 1
	SWDeviceLifetimeMax           SW_DEVICE_LIFETIME = 2
)
