// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package softwaredevice implements the Windows.Win32.SoftwareDevice namespace.
package softwaredevice

type SW_DEVICE_CAPABILITIES int32

const (
	SWDeviceCapabilitiesNone = 0
	SWDeviceCapabilitiesRemovable = 1
	SWDeviceCapabilitiesSilentInstall = 2
	SWDeviceCapabilitiesNoDisplayInUI = 4
	SWDeviceCapabilitiesDriverRequired = 8
)

type SW_DEVICE_LIFETIME int32

const (
	SWDeviceLifetimeHandle = 0
	SWDeviceLifetimeParentPresent = 1
	SWDeviceLifetimeMax = 2
)

