// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package useraccesslogging implements the Windows.Win32.UserAccessLogging namespace.
package useraccesslogging

type UAL_DATA_BLOB struct {
	Size     int
	RoleGuid int
	TenantId int
	Address  int
	UserName int
}
