// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package legacywindowsenvironmentfeatures implements the Windows.Win32.LegacyWindowsEnvironmentFeatures namespace.
package legacywindowsenvironmentfeatures

type _ColumnSortOrder int32

const (
	SortOrder_Ascending = 0
	SortOrder_Descending = 1
)

type _reconcilef int32

const (
	RECONCILEF_MAYBOTHERUSER = 1
	RECONCILEF_FEEDBACKWINDOWVALID = 2
	RECONCILEF_NORESIDUESOK = 4
	RECONCILEF_OMITSELFRESIDUE = 8
	RECONCILEF_RESUMERECONCILIATION = 16
	RECONCILEF_YOUMAYDOTHEUPDATES = 32
	RECONCILEF_ONLYYOUWERECHANGED = 64
	ALL_RECONCILE_FLAGS = 127
)

