// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package qualityofservice implements the Windows.Win32.QualityOfService namespace.
package qualityofservice

type FLOWSPEC struct {
	TokenRate          int
	TokenBucketSize    int
	PeakBandwidth      int
	Latency            int
	DelayVariation     int
	ServiceType        int
	MaxSduSize         int
	MinimumPolicedSize int
}

type QOS_OBJECT_HDR struct {
	ObjectType   int
	ObjectLength int
}

type QOS_SD_MODE struct {
	ObjectHdr        int
	ShapeDiscardMode int
}

type QOS_SHAPING_RATE struct {
	ObjectHdr   int
	ShapingRate int
}

type RsvpObjHdr struct {
	OBJ_LENGTH int
	OBJ_CLASS  int
	OBJ_CTYPE  int
}

type Session_IPv4 struct {
	SESS_DESTADDR int
	SESS_PROTID   int
	SESS_FLAGS    int
	SESS_DESTPORT int
}

type RSVP_SESSION struct {
	SESS_HEADER int
	SESS_U      int
}

type Rsvp_Hop_IPv4 struct {
	HOP_IPADDR int
	HOP_LIH    int
}

type RSVP_HOP struct {
	HOP_HEADER int
	HOP_U      int
}

type RESV_STYLE struct {
	STYLE_HEADER int
	STYLE_WORD   int
}

type Filter_Spec_IPv4 struct {
	FILT_IPADDR int
	FILT_UNUSED int
	FILT_PORT   int
}

type Filter_Spec_IPv4GPI struct {
	FILT_IPADDR int
	FILT_GPI    int
}

type FILTER_SPEC struct {
	FILT_HEADER int
	FILT_U      int
}

type Scope_list_ipv4 struct {
	SCOPL_IPADDR int
}

type RSVP_SCOPE struct {
	SCOPL_HEADER int
	SCOPE_U      int
}

type Error_Spec_IPv4 struct {
	ERRS_ERRNODE int
	ERRS_FLAGS   int
	ERRS_CODE    int
	ERRS_VALUE   int
}

type ERROR_SPEC struct {
	ERRS_HEADER int
	ERRS_U      int
}

type POLICY_DATA struct {
	PolicyObjHdr int
	USPEOFFSET   int
	USRESERVED   int
}

type POLICY_ELEMENT struct {
	USPELENGTH int
	USPETYPE   int
	UCPEDATA   int
}

type IntServMainHdr struct {
	ISMH_VERSION int
	ISMH_UNUSED  int
	ISMH_LEN32B  int
}

type IntServServiceHdr struct {
	ISSH_SERVICE int
	ISSH_FLAGS   int
	ISSH_LEN32B  int
}

type IntServParmHdr struct {
	ISPH_PARM_NUM int
	ISPH_FLAGS    int
	ISPH_LEN32B   int
}

type GenTspecParms struct {
	TB_Tspec_r int
	TB_Tspec_b int
	TB_Tspec_p int
	TB_Tspec_m int
	TB_Tspec_M int
}

type GenTspec struct {
	GEN_TSPEC_SERV_HDR int
	GEN_TSPEC_PARM_HDR int
	GEN_TSPEC_PARMS    int
}

type QualTspecParms struct {
	TB_Tspec_M int
}

type QualTspec struct {
	QUAL_TSPEC_SERV_HDR int
	QUAL_TSPEC_PARM_HDR int
	QUAL_TSPEC_PARMS    int
}

type QualAppFlowSpec struct {
	Q_spec_serv_hdr int
	Q_spec_parm_hdr int
	Q_spec_parms    int
}

type IntServTspecBody struct {
	ST_MH   int
	TSPEC_U int
}

type SENDER_TSPEC struct {
	STSPEC_HEADER int
	STSPEC_BODY   int
}

type CtrlLoadFlowspec struct {
	CL_spec_serv_hdr int
	CL_spec_parm_hdr int
	CL_spec_parms    int
}

type GuarRspec struct {
	Guar_R int
	Guar_S int
}

type GuarFlowSpec struct {
	Guar_serv_hdr    int
	Guar_Tspec_hdr   int
	Guar_Tspec_parms int
	Guar_Rspec_hdr   int
	Guar_Rspec       int
}

type IntServFlowSpec struct {
	SPEC_MH int
	SPEC_U  int
}

type IS_FLOWSPEC struct {
	FLOW_HEADER int
	FLOW_BODY   int
}

type FLOW_DESC struct {
	U1 int
	U2 int
}

type Gads_parms_t struct {
	Gads_serv_hdr int
	Gads_Ctot_hdr int
	Gads_Ctot     int
	Gads_Dtot_hdr int
	Gads_Dtot     int
	Gads_Csum_hdr int
	Gads_Csum     int
	Gads_Dsum_hdr int
	Gads_Dsum     int
}

type GenAdspecParams struct {
	GEN_PARM_HDR          int
	GEN_PARM_HOPCNT_HDR   int
	GEN_PARM_HOPCNT       int
	GEN_PARM_PATHBW_HDR   int
	GEN_PARM_PATH_BW      int
	GEN_PARM_MINLAT_HDR   int
	GEN_PARM_MIN_LATENCY  int
	GEN_PARM_COMPMTU_HDR  int
	GEN_PARM_COMPOSED_MTU int
}

type IS_ADSPEC_BODY struct {
	ADSPEC_MH       int
	ADSPEC_GENPARMS int
}

type ADSPEC struct {
	ADSPEC_HEADER int
	ADSPEC_BODY   int
}

type ID_ERROR_OBJECT struct {
	USIDERRLENGTH  int
	UCATYPE        int
	UCSUBTYPE      int
	USRESERVED     int
	USIDERRORVALUE int
	UCIDERRDATA    int
}

type LPM_HANDLE__ struct {
	UNUSED int
}

type RHANDLE__ struct {
	UNUSED int
}

type RSVP_MSG_OBJS struct {
	RsvpMsgType   int
	PRSVPSESSION  int
	PRSVPFROMHOP  int
	PRSVPTOHOP    int
	PRESVSTYLE    int
	PRSVPSCOPE    int
	FlowDescCount int
	PFLOWDESCS    int
	PdObjectCount int
	PPPDOBJECTS   int
	PERRORSPEC    int
	PADSPEC       int
}

type POLICY_DECISION struct {
	LPVRESULT       int
	WPOLICYERRCODE  int
	WPOLICYERRVALUE int
}

type LPM_INIT_INFO struct {
	PcmVersionNumber       int
	ResultTimeLimit        int
	ConfiguredLpmCount     int
	AllocMemory            int
	FreeMemory             int
	PcmAdmitResultCallback int
	GetRsvpObjectsCallback int
}

type LPMIPTABLE struct {
	ULIFINDEX int
	MediaType int
	IfIpAddr  int
	IfNetMask int
}

type QOS_PACKET_PRIORITY struct {
	ConformantDSCPValue    int
	NonConformantDSCPValue int
	ConformantL2Value      int
	NonConformantL2Value   int
}

type QOS_FLOW_FUNDAMENTALS struct {
	BottleneckBandwidthSet int
	BottleneckBandwidth    int
	AvailableBandwidthSet  int
	AvailableBandwidth     int
	RTTSet                 int
	RTT                    int
}

type QOS_FLOWRATE_OUTGOING struct {
	Bandwidth       int
	ShapingBehavior int
	Reason          int
}

type QOS_VERSION struct {
	MajorVersion int
	MinorVersion int
}

type QOS_FRIENDLY_NAME struct {
	ObjectHdr    int
	FriendlyName int
}

type QOS_TRAFFIC_CLASS struct {
	ObjectHdr    int
	TrafficClass int
}

type QOS_DS_CLASS struct {
	ObjectHdr int
	DSField   int
}

type QOS_DIFFSERV struct {
	ObjectHdr    int
	DSFieldCount int
	DiffservRule int
}

type QOS_DIFFSERV_RULE struct {
	InboundDSField               int
	ConformingOutboundDSField    int
	NonConformingOutboundDSField int
	ConformingUserPriority       int
	NonConformingUserPriority    int
}

type QOS_TCP_TRAFFIC struct {
	ObjectHdr int
}

type TCI_CLIENT_FUNC_LIST struct {
	ClNotifyHandler             int
	ClAddFlowCompleteHandler    int
	ClModifyFlowCompleteHandler int
	ClDeleteFlowCompleteHandler int
}

type ADDRESS_LIST_DESCRIPTOR struct {
	MediaType   int
	AddressList int
}

type TC_IFC_DESCRIPTOR struct {
	Length          int
	PINTERFACENAME  int
	PINTERFACEID    int
	AddressListDesc int
}

type TC_SUPPORTED_INFO_BUFFER struct {
	InstanceIDLength int
	InstanceID       int
	InterfaceLuid    int
	AddrListDesc     int
}

type TC_GEN_FILTER struct {
	AddressType int
	PatternSize int
	Pattern     int
	Mask        int
}

type TC_GEN_FLOW struct {
	SendingFlowspec   int
	ReceivingFlowspec int
	TcObjectsLength   int
	TcObjects         int
}

type IP_PATTERN struct {
	Reserved1  int
	Reserved2  int
	SrcAddr    int
	DstAddr    int
	S_un       int
	ProtocolId int
	Reserved3  int
}

type IPX_PATTERN struct {
	Src  int
	Dest int
}

type ENUMERATION_BUFFER struct {
	Length          int
	OwnerProcessId  int
	FlowNameLength  int
	FlowName        int
	PFLOW           int
	NumberOfFilters int
	GenericFilter   int
}

type QOS struct {
	SendingFlowspec   int
	ReceivingFlowspec int
	ProviderSpecific  int
}
