// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowsconnectionmanager implements the Windows.Win32.WindowsConnectionManager namespace.
package windowsconnectionmanager

type WCM_POLICY_VALUE struct {
	FVALUE         int
	FISGROUPPOLICY int
}

type WCM_PROFILE_INFO struct {
	STRPROFILENAME int
	AdapterGUID    int
	Media          int
}

type WCM_PROFILE_INFO_LIST struct {
	DWNUMBEROFITEMS int
	ProfileInfo     int
}

type WCM_CONNECTION_COST_DATA struct {
	ConnectionCost int
	CostSource     int
}

type WCM_TIME_INTERVAL struct {
	WYEAR         int
	WMONTH        int
	WDAY          int
	WHOUR         int
	WMINUTE       int
	WSECOND       int
	WMILLISECONDS int
}

type WCM_USAGE_DATA struct {
	UsageInMegabytes int
	LastSyncTime     int
}

type WCM_BILLING_CYCLE_INFO struct {
	StartDate int
	Duration  int
	Reset     int
}

type WCM_DATAPLAN_STATUS struct {
	UsageData                  int
	DataLimitInMegabytes       int
	InboundBandwidthInKbps     int
	OutboundBandwidthInKbps    int
	BillingCycle               int
	MaxTransferSizeInMegabytes int
	Reserved                   int
}
