// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package gdi implements the Windows.Win32.Gdi namespace.
package gdi

type XFORM struct {
	EM11 int
	EM12 int
	EM21 int
	EM22 int
	EDX  int
	EDY  int
}

type BITMAP struct {
	BMTYPE       int
	BMWIDTH      int
	BMHEIGHT     int
	BMWIDTHBYTES int
	BMPLANES     int
	BMBITSPIXEL  int
	BMBITS       int
}

type RGBTRIPLE struct {
	RGBTBLUE  int
	RGBTGREEN int
	RGBTRED   int
}

type RGBQUAD struct {
	RGBBLUE     int
	RGBGREEN    int
	RGBRED      int
	RGBRESERVED int
}

type BITMAPCOREHEADER struct {
	BCSIZE     int
	BCWIDTH    int
	BCHEIGHT   int
	BCPLANES   int
	BCBITCOUNT int
}

type BITMAPV4HEADER struct {
	BV4SIZE          int
	BV4WIDTH         int
	BV4HEIGHT        int
	BV4PLANES        int
	BV4BITCOUNT      int
	BV4V4COMPRESSION int
	BV4SIZEIMAGE     int
	BV4XPELSPERMETER int
	BV4YPELSPERMETER int
	BV4CLRUSED       int
	BV4CLRIMPORTANT  int
	BV4REDMASK       int
	BV4GREENMASK     int
	BV4BLUEMASK      int
	BV4ALPHAMASK     int
	BV4CSTYPE        int
	BV4ENDPOINTS     int
	BV4GAMMARED      int
	BV4GAMMAGREEN    int
	BV4GAMMABLUE     int
}

type BITMAPV5HEADER struct {
	BV5SIZE          int
	BV5WIDTH         int
	BV5HEIGHT        int
	BV5PLANES        int
	BV5BITCOUNT      int
	BV5COMPRESSION   int
	BV5SIZEIMAGE     int
	BV5XPELSPERMETER int
	BV5YPELSPERMETER int
	BV5CLRUSED       int
	BV5CLRIMPORTANT  int
	BV5REDMASK       int
	BV5GREENMASK     int
	BV5BLUEMASK      int
	BV5ALPHAMASK     int
	BV5CSTYPE        int
	BV5ENDPOINTS     int
	BV5GAMMARED      int
	BV5GAMMAGREEN    int
	BV5GAMMABLUE     int
	BV5INTENT        int
	BV5PROFILEDATA   int
	BV5PROFILESIZE   int
	BV5RESERVED      int
}

type BITMAPINFO struct {
	BMIHEADER int
	BMICOLORS int
}

type BITMAPCOREINFO struct {
	BMCIHEADER int
	BMCICOLORS int
}

type BITMAPFILEHEADER struct {
	BFTYPE      int
	BFSIZE      int
	BFRESERVED1 int
	BFRESERVED2 int
	BFOFFBITS   int
}

type HANDLETABLE struct {
	OBJECTHANDLE int
}

type METARECORD struct {
	RDSIZE     int
	RDFUNCTION int
	RDPARM     int
}

type METAHEADER struct {
	MTTYPE         int
	MTHEADERSIZE   int
	MTVERSION      int
	MTSIZE         int
	MTNOOBJECTS    int
	MTMAXRECORD    int
	MTNOPARAMETERS int
}

type ENHMETARECORD struct {
	ITYPE int
	NSIZE int
	DPARM int
}

type ENHMETAHEADER struct {
	ITYPE          int
	NSIZE          int
	RCLBOUNDS      int
	RCLFRAME       int
	DSIGNATURE     int
	NVERSION       int
	NBYTES         int
	NRECORDS       int
	NHANDLES       int
	SRESERVED      int
	NDESCRIPTION   int
	OFFDESCRIPTION int
	NPALENTRIES    int
	SZLDEVICE      int
	SZLMILLIMETERS int
	CBPIXELFORMAT  int
	OFFPIXELFORMAT int
	BOPENGL        int
	SZLMICROMETERS int
}

type TEXTMETRICA struct {
	TMHEIGHT           int
	TMASCENT           int
	TMDESCENT          int
	TMINTERNALLEADING  int
	TMEXTERNALLEADING  int
	TMAVECHARWIDTH     int
	TMMAXCHARWIDTH     int
	TMWEIGHT           int
	TMOVERHANG         int
	TMDIGITIZEDASPECTX int
	TMDIGITIZEDASPECTY int
	TMFIRSTCHAR        int
	TMLASTCHAR         int
	TMDEFAULTCHAR      int
	TMBREAKCHAR        int
	TMITALIC           int
	TMUNDERLINED       int
	TMSTRUCKOUT        int
	TMPITCHANDFAMILY   int
	TMCHARSET          int
}

type TEXTMETRICW struct {
	TMHEIGHT           int
	TMASCENT           int
	TMDESCENT          int
	TMINTERNALLEADING  int
	TMEXTERNALLEADING  int
	TMAVECHARWIDTH     int
	TMMAXCHARWIDTH     int
	TMWEIGHT           int
	TMOVERHANG         int
	TMDIGITIZEDASPECTX int
	TMDIGITIZEDASPECTY int
	TMFIRSTCHAR        int
	TMLASTCHAR         int
	TMDEFAULTCHAR      int
	TMBREAKCHAR        int
	TMITALIC           int
	TMUNDERLINED       int
	TMSTRUCKOUT        int
	TMPITCHANDFAMILY   int
	TMCHARSET          int
}

type NEWTEXTMETRICA struct {
	TMHEIGHT           int
	TMASCENT           int
	TMDESCENT          int
	TMINTERNALLEADING  int
	TMEXTERNALLEADING  int
	TMAVECHARWIDTH     int
	TMMAXCHARWIDTH     int
	TMWEIGHT           int
	TMOVERHANG         int
	TMDIGITIZEDASPECTX int
	TMDIGITIZEDASPECTY int
	TMFIRSTCHAR        int
	TMLASTCHAR         int
	TMDEFAULTCHAR      int
	TMBREAKCHAR        int
	TMITALIC           int
	TMUNDERLINED       int
	TMSTRUCKOUT        int
	TMPITCHANDFAMILY   int
	TMCHARSET          int
	NTMFLAGS           int
	NTMSIZEEM          int
	NTMCELLHEIGHT      int
	NTMAVGWIDTH        int
}

type NEWTEXTMETRICW struct {
	TMHEIGHT           int
	TMASCENT           int
	TMDESCENT          int
	TMINTERNALLEADING  int
	TMEXTERNALLEADING  int
	TMAVECHARWIDTH     int
	TMMAXCHARWIDTH     int
	TMWEIGHT           int
	TMOVERHANG         int
	TMDIGITIZEDASPECTX int
	TMDIGITIZEDASPECTY int
	TMFIRSTCHAR        int
	TMLASTCHAR         int
	TMDEFAULTCHAR      int
	TMBREAKCHAR        int
	TMITALIC           int
	TMUNDERLINED       int
	TMSTRUCKOUT        int
	TMPITCHANDFAMILY   int
	TMCHARSET          int
	NTMFLAGS           int
	NTMSIZEEM          int
	NTMCELLHEIGHT      int
	NTMAVGWIDTH        int
}

type NEWTEXTMETRICEXA struct {
	NTMTM      int
	NTMFONTSIG int
}

type NEWTEXTMETRICEXW struct {
	NTMTM      int
	NTMFONTSIG int
}

type PELARRAY struct {
	PAXCOUNT int
	PAYCOUNT int
	PAXEXT   int
	PAYEXT   int
	PARGBS   int
}

type LOGBRUSH struct {
	LBSTYLE int
	LBCOLOR int
	LBHATCH int
}

type LOGBRUSH32 struct {
	LBSTYLE int
	LBCOLOR int
	LBHATCH int
}

type LOGPEN struct {
	LOPNSTYLE int
	LOPNWIDTH int
	LOPNCOLOR int
}

type EXTLOGPEN struct {
	ELPPENSTYLE   int
	ELPWIDTH      int
	ELPBRUSHSTYLE int
	ELPCOLOR      int
	ELPHATCH      int
	ELPNUMENTRIES int
	ELPSTYLEENTRY int
}

type EXTLOGPEN32 struct {
	ELPPENSTYLE   int
	ELPWIDTH      int
	ELPBRUSHSTYLE int
	ELPCOLOR      int
	ELPHATCH      int
	ELPNUMENTRIES int
	ELPSTYLEENTRY int
}

type PALETTEENTRY struct {
	PERED   int
	PEGREEN int
	PEBLUE  int
	PEFLAGS int
}

type LOGPALETTE struct {
	PALVERSION    int
	PALNUMENTRIES int
	PALPALENTRY   int
}

type ENUMLOGFONTA struct {
	ELFLOGFONT  int
	ELFFULLNAME int
	ELFSTYLE    int
}

type ENUMLOGFONTW struct {
	ELFLOGFONT  int
	ELFFULLNAME int
	ELFSTYLE    int
}

type ENUMLOGFONTEXA struct {
	ELFLOGFONT  int
	ELFFULLNAME int
	ELFSTYLE    int
	ELFSCRIPT   int
}

type ENUMLOGFONTEXW struct {
	ELFLOGFONT  int
	ELFFULLNAME int
	ELFSTYLE    int
	ELFSCRIPT   int
}

type PANOSE struct {
	BFAMILYTYPE      int
	BSERIFSTYLE      int
	BWEIGHT          int
	BPROPORTION      int
	BCONTRAST        int
	BSTROKEVARIATION int
	BARMSTYLE        int
	BLETTERFORM      int
	BMIDLINE         int
	BXHEIGHT         int
}

type EXTLOGFONTA struct {
	ELFLOGFONT   int
	ELFFULLNAME  int
	ELFSTYLE     int
	ELFVERSION   int
	ELFSTYLESIZE int
	ELFMATCH     int
	ELFRESERVED  int
	ELFVENDORID  int
	ELFCULTURE   int
	ELFPANOSE    int
}

type EXTLOGFONTW struct {
	ELFLOGFONT   int
	ELFFULLNAME  int
	ELFSTYLE     int
	ELFVERSION   int
	ELFSTYLESIZE int
	ELFMATCH     int
	ELFRESERVED  int
	ELFVENDORID  int
	ELFCULTURE   int
	ELFPANOSE    int
}

type DISPLAY_DEVICEA struct {
	CB           int
	DeviceName   int
	DeviceString int
	StateFlags   int
	DeviceID     int
	DeviceKey    int
}

type DISPLAY_DEVICEW struct {
	CB           int
	DeviceName   int
	DeviceString int
	StateFlags   int
	DeviceID     int
	DeviceKey    int
}

type DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO struct {
	HEADER              int
	Anonymous           int
	COLORENCODING       int
	BITSPERCOLORCHANNEL int
}

type DISPLAYCONFIG_SET_ADVANCED_COLOR_STATE struct {
	HEADER    int
	Anonymous int
}

type DISPLAYCONFIG_SDR_WHITE_LEVEL struct {
	HEADER        int
	SDRWhiteLevel int
}

type RGNDATAHEADER struct {
	DWSIZE   int
	ITYPE    int
	NCOUNT   int
	NRGNSIZE int
	RCBOUND  int
}

type RGNDATA struct {
	RDH    int
	Buffer int
}

type ABC struct {
	ABCA int
	ABCB int
	ABCC int
}

type ABCFLOAT struct {
	ABCFA int
	ABCFB int
	ABCFC int
}

type OUTLINETEXTMETRICA struct {
	OTMSIZE                int
	OTMTEXTMETRICS         int
	OTMFILLER              int
	OTMPANOSENUMBER        int
	OTMFSSELECTION         int
	OTMFSTYPE              int
	OTMSCHARSLOPERISE      int
	OTMSCHARSLOPERUN       int
	OTMITALICANGLE         int
	OTMEMSQUARE            int
	OTMASCENT              int
	OTMDESCENT             int
	OTMLINEGAP             int
	OTMSCAPEMHEIGHT        int
	OTMSXHEIGHT            int
	OTMRCFONTBOX           int
	OTMMACASCENT           int
	OTMMACDESCENT          int
	OTMMACLINEGAP          int
	OTMUSMINIMUMPPEM       int
	OTMPTSUBSCRIPTSIZE     int
	OTMPTSUBSCRIPTOFFSET   int
	OTMPTSUPERSCRIPTSIZE   int
	OTMPTSUPERSCRIPTOFFSET int
	OTMSSTRIKEOUTSIZE      int
	OTMSSTRIKEOUTPOSITION  int
	OTMSUNDERSCORESIZE     int
	OTMSUNDERSCOREPOSITION int
	OTMPFAMILYNAME         int
	OTMPFACENAME           int
	OTMPSTYLENAME          int
	OTMPFULLNAME           int
}

type OUTLINETEXTMETRICW struct {
	OTMSIZE                int
	OTMTEXTMETRICS         int
	OTMFILLER              int
	OTMPANOSENUMBER        int
	OTMFSSELECTION         int
	OTMFSTYPE              int
	OTMSCHARSLOPERISE      int
	OTMSCHARSLOPERUN       int
	OTMITALICANGLE         int
	OTMEMSQUARE            int
	OTMASCENT              int
	OTMDESCENT             int
	OTMLINEGAP             int
	OTMSCAPEMHEIGHT        int
	OTMSXHEIGHT            int
	OTMRCFONTBOX           int
	OTMMACASCENT           int
	OTMMACDESCENT          int
	OTMMACLINEGAP          int
	OTMUSMINIMUMPPEM       int
	OTMPTSUBSCRIPTSIZE     int
	OTMPTSUBSCRIPTOFFSET   int
	OTMPTSUPERSCRIPTSIZE   int
	OTMPTSUPERSCRIPTOFFSET int
	OTMSSTRIKEOUTSIZE      int
	OTMSSTRIKEOUTPOSITION  int
	OTMSUNDERSCORESIZE     int
	OTMSUNDERSCOREPOSITION int
	OTMPFAMILYNAME         int
	OTMPFACENAME           int
	OTMPSTYLENAME          int
	OTMPFULLNAME           int
}

type POLYTEXTA struct {
	X       int
	Y       int
	N       int
	LPSTR   int
	UIFLAGS int
	RCL     int
	PDX     int
}

type POLYTEXTW struct {
	X       int
	Y       int
	N       int
	LPSTR   int
	UIFLAGS int
	RCL     int
	PDX     int
}

type FIXED struct {
	FRACT int
	VALUE int
}

type MAT2 struct {
	EM11 int
	EM12 int
	EM21 int
	EM22 int
}

type GLYPHMETRICS struct {
	GMBLACKBOXX     int
	GMBLACKBOXY     int
	GMPTGLYPHORIGIN int
	GMCELLINCX      int
	GMCELLINCY      int
}

type POINTFX struct {
	X int
	Y int
}

type TTPOLYCURVE struct {
	WTYPE int
	CPFX  int
	APFX  int
}

type TTPOLYGONHEADER struct {
	CB       int
	DWTYPE   int
	PFXSTART int
}

type GCP_RESULTSA struct {
	LSTRUCTSIZE int
	LPOUTSTRING int
	LPORDER     int
	LPDX        int
	LPCARETPOS  int
	LPCLASS     int
	LPGLYPHS    int
	NGLYPHS     int
	NMAXFIT     int
}

type GCP_RESULTSW struct {
	LSTRUCTSIZE int
	LPOUTSTRING int
	LPORDER     int
	LPDX        int
	LPCARETPOS  int
	LPCLASS     int
	LPGLYPHS    int
	NGLYPHS     int
	NMAXFIT     int
}

type RASTERIZER_STATUS struct {
	NSIZE       int
	WFLAGS      int
	NLANGUAGEID int
}

type WCRANGE struct {
	WCLOW   int
	CGLYPHS int
}

type GLYPHSET struct {
	CBTHIS           int
	FLACCEL          int
	CGLYPHSSUPPORTED int
	CRANGES          int
	RANGES           int
}

type DESIGNVECTOR struct {
	DVRESERVED int
	DVNUMAXES  int
	DVVALUES   int
}

type AXISINFOA struct {
	AXMINVALUE int
	AXMAXVALUE int
	AXAXISNAME int
}

type AXISINFOW struct {
	AXMINVALUE int
	AXMAXVALUE int
	AXAXISNAME int
}

type AXESLISTA struct {
	AXLRESERVED int
	AXLNUMAXES  int
	AXLAXISINFO int
}

type AXESLISTW struct {
	AXLRESERVED int
	AXLNUMAXES  int
	AXLAXISINFO int
}

type ENUMLOGFONTEXDVA struct {
	ELFENUMLOGFONTEX int
	ELFDESIGNVECTOR  int
}

type ENUMLOGFONTEXDVW struct {
	ELFENUMLOGFONTEX int
	ELFDESIGNVECTOR  int
}

type ENUMTEXTMETRICA struct {
	ETMNEWTEXTMETRICEX int
	ETMAXESLIST        int
}

type ENUMTEXTMETRICW struct {
	ETMNEWTEXTMETRICEX int
	ETMAXESLIST        int
}

type TRIVERTEX struct {
	X     int
	Y     int
	Red   int
	Green int
	Blue  int
	Alpha int
}

type GRADIENT_TRIANGLE struct {
	Vertex1 int
	Vertex2 int
	Vertex3 int
}

type GRADIENT_RECT struct {
	UpperLeft  int
	LowerRight int
}

type BLENDFUNCTION struct {
	BlendOp             int
	BlendFlags          int
	SourceConstantAlpha int
	AlphaFormat         int
}

type DIBSECTION struct {
	DSBM        int
	DSBMIH      int
	DSBITFIELDS int
	DSHSECTION  int
	DSOFFSET    int
}

type COLORADJUSTMENT struct {
	CASIZE            int
	CAFLAGS           int
	CAILLUMINANTINDEX int
	CAREDGAMMA        int
	CAGREENGAMMA      int
	CABLUEGAMMA       int
	CAREFERENCEBLACK  int
	CAREFERENCEWHITE  int
	CACONTRAST        int
	CABRIGHTNESS      int
	CACOLORFULNESS    int
	CAREDGREENTINT    int
}

type KERNINGPAIR struct {
	WFIRST      int
	WSECOND     int
	IKERNAMOUNT int
}

type EMR struct {
	ITYPE int
	NSIZE int
}

type EMRTEXT struct {
	PTLREFERENCE int
	NCHARS       int
	OFFSTRING    int
	FOPTIONS     int
	RCL          int
	OFFDX        int
}

type ABORTPATH struct {
	EMR int
}

type EMRSELECTCLIPPATH struct {
	EMR   int
	IMODE int
}

type EMRSETMITERLIMIT struct {
	EMR         int
	EMITERLIMIT int
}

type EMRRESTOREDC struct {
	EMR       int
	IRELATIVE int
}

type EMRSETARCDIRECTION struct {
	EMR           int
	IARCDIRECTION int
}

type EMRSETMAPPERFLAGS struct {
	EMR     int
	DWFLAGS int
}

type EMRSETTEXTCOLOR struct {
	EMR     int
	CRCOLOR int
}

type EMRSELECTOBJECT struct {
	EMR      int
	IHOBJECT int
}

type EMRSELECTPALETTE struct {
	EMR   int
	IHPAL int
}

type EMRRESIZEPALETTE struct {
	EMR      int
	IHPAL    int
	CENTRIES int
}

type EMRSETPALETTEENTRIES struct {
	EMR         int
	IHPAL       int
	ISTART      int
	CENTRIES    int
	APALENTRIES int
}

type EMRSETCOLORADJUSTMENT struct {
	EMR             int
	ColorAdjustment int
}

type EMRGDICOMMENT struct {
	EMR    int
	CBDATA int
	Data   int
}

type EMREOF struct {
	EMR           int
	NPALENTRIES   int
	OFFPALENTRIES int
	NSIZELAST     int
}

type EMRLINETO struct {
	EMR int
	PTL int
}

type EMROFFSETCLIPRGN struct {
	EMR       int
	PTLOFFSET int
}

type EMRFILLPATH struct {
	EMR       int
	RCLBOUNDS int
}

type EMREXCLUDECLIPRECT struct {
	EMR     int
	RCLCLIP int
}

type EMRSETVIEWPORTORGEX struct {
	EMR       int
	PTLORIGIN int
}

type EMRSETVIEWPORTEXTEX struct {
	EMR       int
	SZLEXTENT int
}

type EMRSCALEVIEWPORTEXTEX struct {
	EMR    int
	XNUM   int
	XDENOM int
	YNUM   int
	YDENOM int
}

type EMRSETWORLDTRANSFORM struct {
	EMR   int
	XFORM int
}

type EMRMODIFYWORLDTRANSFORM struct {
	EMR   int
	XFORM int
	IMODE int
}

type EMRSETPIXELV struct {
	EMR      int
	PTLPIXEL int
	CRCOLOR  int
}

type EMREXTFLOODFILL struct {
	EMR      int
	PTLSTART int
	CRCOLOR  int
	IMODE    int
}

type EMRELLIPSE struct {
	EMR    int
	RCLBOX int
}

type EMRROUNDRECT struct {
	EMR       int
	RCLBOX    int
	SZLCORNER int
}

type EMRARC struct {
	EMR      int
	RCLBOX   int
	PTLSTART int
	PTLEND   int
}

type EMRANGLEARC struct {
	EMR         int
	PTLCENTER   int
	NRADIUS     int
	ESTARTANGLE int
	ESWEEPANGLE int
}

type EMRPOLYLINE struct {
	EMR       int
	RCLBOUNDS int
	CPTL      int
	APTL      int
}

type EMRPOLYLINE16 struct {
	EMR       int
	RCLBOUNDS int
	CPTS      int
	APTS      int
}

type EMRPOLYDRAW struct {
	EMR       int
	RCLBOUNDS int
	CPTL      int
	APTL      int
	ABTYPES   int
}

type EMRPOLYDRAW16 struct {
	EMR       int
	RCLBOUNDS int
	CPTS      int
	APTS      int
	ABTYPES   int
}

type EMRPOLYPOLYLINE struct {
	EMR         int
	RCLBOUNDS   int
	NPOLYS      int
	CPTL        int
	APOLYCOUNTS int
	APTL        int
}

type EMRPOLYPOLYLINE16 struct {
	EMR         int
	RCLBOUNDS   int
	NPOLYS      int
	CPTS        int
	APOLYCOUNTS int
	APTS        int
}

type EMRINVERTRGN struct {
	EMR       int
	RCLBOUNDS int
	CBRGNDATA int
	RgnData   int
}

type EMRFILLRGN struct {
	EMR       int
	RCLBOUNDS int
	CBRGNDATA int
	IHBRUSH   int
	RgnData   int
}

type EMRFRAMERGN struct {
	EMR       int
	RCLBOUNDS int
	CBRGNDATA int
	IHBRUSH   int
	SZLSTROKE int
	RgnData   int
}

type EMREXTSELECTCLIPRGN struct {
	EMR       int
	CBRGNDATA int
	IMODE     int
	RgnData   int
}

type EMREXTTEXTOUTA struct {
	EMR           int
	RCLBOUNDS     int
	IGRAPHICSMODE int
	EXSCALE       int
	EYSCALE       int
	EMRTEXT       int
}

type EMRPOLYTEXTOUTA struct {
	EMR           int
	RCLBOUNDS     int
	IGRAPHICSMODE int
	EXSCALE       int
	EYSCALE       int
	CSTRINGS      int
	AEMRTEXT      int
}

type EMRBITBLT struct {
	EMR          int
	RCLBOUNDS    int
	XDEST        int
	YDEST        int
	CXDEST       int
	CYDEST       int
	DWROP        int
	XSRC         int
	YSRC         int
	XFORMSRC     int
	CRBKCOLORSRC int
	IUSAGESRC    int
	OFFBMISRC    int
	CBBMISRC     int
	OFFBITSSRC   int
	CBBITSSRC    int
}

type EMRSTRETCHBLT struct {
	EMR          int
	RCLBOUNDS    int
	XDEST        int
	YDEST        int
	CXDEST       int
	CYDEST       int
	DWROP        int
	XSRC         int
	YSRC         int
	XFORMSRC     int
	CRBKCOLORSRC int
	IUSAGESRC    int
	OFFBMISRC    int
	CBBMISRC     int
	OFFBITSSRC   int
	CBBITSSRC    int
	CXSRC        int
	CYSRC        int
}

type EMRMASKBLT struct {
	EMR          int
	RCLBOUNDS    int
	XDEST        int
	YDEST        int
	CXDEST       int
	CYDEST       int
	DWROP        int
	XSRC         int
	YSRC         int
	XFORMSRC     int
	CRBKCOLORSRC int
	IUSAGESRC    int
	OFFBMISRC    int
	CBBMISRC     int
	OFFBITSSRC   int
	CBBITSSRC    int
	XMASK        int
	YMASK        int
	IUSAGEMASK   int
	OFFBMIMASK   int
	CBBMIMASK    int
	OFFBITSMASK  int
	CBBITSMASK   int
}

type EMRPLGBLT struct {
	EMR          int
	RCLBOUNDS    int
	APTLDEST     int
	XSRC         int
	YSRC         int
	CXSRC        int
	CYSRC        int
	XFORMSRC     int
	CRBKCOLORSRC int
	IUSAGESRC    int
	OFFBMISRC    int
	CBBMISRC     int
	OFFBITSSRC   int
	CBBITSSRC    int
	XMASK        int
	YMASK        int
	IUSAGEMASK   int
	OFFBMIMASK   int
	CBBMIMASK    int
	OFFBITSMASK  int
	CBBITSMASK   int
}

type EMRSETDIBITSTODEVICE struct {
	EMR        int
	RCLBOUNDS  int
	XDEST      int
	YDEST      int
	XSRC       int
	YSRC       int
	CXSRC      int
	CYSRC      int
	OFFBMISRC  int
	CBBMISRC   int
	OFFBITSSRC int
	CBBITSSRC  int
	IUSAGESRC  int
	ISTARTSCAN int
	CSCANS     int
}

type EMRSTRETCHDIBITS struct {
	EMR        int
	RCLBOUNDS  int
	XDEST      int
	YDEST      int
	XSRC       int
	YSRC       int
	CXSRC      int
	CYSRC      int
	OFFBMISRC  int
	CBBMISRC   int
	OFFBITSSRC int
	CBBITSSRC  int
	IUSAGESRC  int
	DWROP      int
	CXDEST     int
	CYDEST     int
}

type EMREXTCREATEFONTINDIRECTW struct {
	EMR    int
	IHFONT int
	ELFW   int
}

type EMRCREATEPALETTE struct {
	EMR   int
	IHPAL int
	LGPL  int
}

type EMRCREATEPEN struct {
	EMR   int
	IHPEN int
	LOPN  int
}

type EMREXTCREATEPEN struct {
	EMR     int
	IHPEN   int
	OFFBMI  int
	CBBMI   int
	OFFBITS int
	CBBITS  int
	ELP     int
}

type EMRCREATEBRUSHINDIRECT struct {
	EMR     int
	IHBRUSH int
	LB      int
}

type EMRCREATEMONOBRUSH struct {
	EMR     int
	IHBRUSH int
	IUSAGE  int
	OFFBMI  int
	CBBMI   int
	OFFBITS int
	CBBITS  int
}

type EMRCREATEDIBPATTERNBRUSHPT struct {
	EMR     int
	IHBRUSH int
	IUSAGE  int
	OFFBMI  int
	CBBMI   int
	OFFBITS int
	CBBITS  int
}

type EMRFORMAT struct {
	DSIGNATURE int
	NVERSION   int
	CBDATA     int
	OFFDATA    int
}

type EMRGLSRECORD struct {
	EMR    int
	CBDATA int
	Data   int
}

type EMRGLSBOUNDEDRECORD struct {
	EMR       int
	RCLBOUNDS int
	CBDATA    int
	Data      int
}

type EMRPIXELFORMAT struct {
	EMR int
	PFD int
}

type EMRCREATECOLORSPACE struct {
	EMR  int
	IHCS int
	LCS  int
}

type EMRSETCOLORSPACE struct {
	EMR  int
	IHCS int
}

type EMREXTESCAPE struct {
	EMR       int
	IESCAPE   int
	CBESCDATA int
	EscData   int
}

type EMRNAMEDESCAPE struct {
	EMR       int
	IESCAPE   int
	CBDRIVER  int
	CBESCDATA int
	EscData   int
}

type EMRSETICMPROFILE struct {
	EMR     int
	DWFLAGS int
	CBNAME  int
	CBDATA  int
	Data    int
}

type EMRCREATECOLORSPACEW struct {
	EMR     int
	IHCS    int
	LCS     int
	DWFLAGS int
	CBDATA  int
	Data    int
}

type COLORMATCHTOTARGET struct {
	EMR      int
	DWACTION int
	DWFLAGS  int
	CBNAME   int
	CBDATA   int
	Data     int
}

type COLORCORRECTPALETTE struct {
	EMR         int
	IHPALETTE   int
	NFIRSTENTRY int
	NPALENTRIES int
	NRESERVED   int
}

type EMRALPHABLEND struct {
	EMR          int
	RCLBOUNDS    int
	XDEST        int
	YDEST        int
	CXDEST       int
	CYDEST       int
	DWROP        int
	XSRC         int
	YSRC         int
	XFORMSRC     int
	CRBKCOLORSRC int
	IUSAGESRC    int
	OFFBMISRC    int
	CBBMISRC     int
	OFFBITSSRC   int
	CBBITSSRC    int
	CXSRC        int
	CYSRC        int
}

type EMRGRADIENTFILL struct {
	EMR       int
	RCLBOUNDS int
	NVER      int
	NTRI      int
	ULMODE    int
	Ver       int
}

type EMRTRANSPARENTBLT struct {
	EMR          int
	RCLBOUNDS    int
	XDEST        int
	YDEST        int
	CXDEST       int
	CYDEST       int
	DWROP        int
	XSRC         int
	YSRC         int
	XFORMSRC     int
	CRBKCOLORSRC int
	IUSAGESRC    int
	OFFBMISRC    int
	CBBMISRC     int
	OFFBITSSRC   int
	CBBITSSRC    int
	CXSRC        int
	CYSRC        int
}

type WGLSWAP struct {
	HDC     int
	UIFLAGS int
}

type TTLOADINFO struct {
	USSTRUCTSIZE int
	USREFSTRSIZE int
	PUSREFSTR    int
}

type TTEMBEDINFO struct {
	USSTRUCTSIZE  int
	USROOTSTRSIZE int
	PUSROOTSTR    int
}

type TTVALIDATIONTESTSPARAMS struct {
	ULSTRUCTSIZE    int
	LTESTFROMSIZE   int
	LTESTTOSIZE     int
	ULCHARSET       int
	USRESERVED1     int
	USCHARCODECOUNT int
	PUSCHARCODESET  int
}

type TTVALIDATIONTESTSPARAMSEX struct {
	ULSTRUCTSIZE    int
	LTESTFROMSIZE   int
	LTESTTOSIZE     int
	ULCHARSET       int
	USRESERVED1     int
	USCHARCODECOUNT int
	PULCHARCODESET  int
}

type TAGMXDCESCAPEHEADER struct {
	CBINPUT  int
	CBOUTPUT int
	OPCODE   int
}

type TAGMXDCGETFILENAMEDATA struct {
	CBOUTPUT int
	WSZDATA  int
}

type TAGMXDCS0PAGEDATA struct {
	DWSIZE int
	BDATA  int
}

type TAGMXDCXPSS0PAGERESOURCE struct {
	DWSIZE         int
	DWRESOURCETYPE int
	SZURI          int
	DWDATASIZE     int
	BDATA          int
}

type TAGMXDCPRINTTICKETPASSTHROUGH struct {
	DWDATASIZE int
	BDATA      int
}

type TAGMXDCPRINTTICKETESCAPE struct {
	MXDCESCAPE      int
	PRINTTICKETDATA int
}

type TAGMXDCS0PAGEPASSTHROUGHESCAPE struct {
	MXDCESCAPE    int
	XPSS0PAGEDATA int
}

type TAGMXDCS0PAGERESOURCEESCAPE struct {
	MXDCESCAPE                   int
	XPSS0PAGERESOURCEPASSTHROUGH int
}

type HBITMAP struct {
	Value int
}

type HBRUSH struct {
	Value int
}

type HCOLORSPACE struct {
	Value int
}

type HCURSOR struct {
	Value int
}

type HDC struct {
	Value int
}

type HdcMetdataEnhFileHandle struct {
	Value int
}

type HdcMetdataFileHandle struct {
	Value int
}

type HENHMETAFILE struct {
	Value int
}

type HFONT struct {
	Value int
}

type HICON struct {
	Value int
}

type HMETAFILE struct {
	Value int
}

type HMONITOR struct {
	Value int
}

type HPALETTE struct {
	Value int
}

type HPEN struct {
	Value int
}

type HRGN struct {
	Value int
}

type PAINTSTRUCT struct {
	HDC         int
	FERASE      int
	RCPAINT     int
	FRESTORE    int
	FINCUPDATE  int
	RGBRESERVED int
}

type DRAWTEXTPARAMS struct {
	CBSIZE        int
	ITABLENGTH    int
	ILEFTMARGIN   int
	IRIGHTMARGIN  int
	UILENGTHDRAWN int
}

type MONITORINFO struct {
	CBSIZE    int
	RCMONITOR int
	RCWORK    int
	DWFLAGS   int
}

type MONITORINFOEXA struct {
	AnonymousBase_winuser_L13554_C43 int
	SZDEVICE                         int
}

type MONITORINFOEXW struct {
	AnonymousBase_winuser_L13558_C43 int
	SZDEVICE                         int
}
