// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package touchinput implements the Windows.Win32.TouchInput namespace.
package touchinput

type MANIPULATION_PROCESSOR_MANIPULATIONS int32

const (
	MANIPULATION_NONE = 0
	MANIPULATION_TRANSLATE_X = 1
	MANIPULATION_TRANSLATE_Y = 2
	MANIPULATION_SCALE = 4
	MANIPULATION_ROTATE = 8
	MANIPULATION_ALL = 15
)

