// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package mbn implements the Windows.Win32.Mbn namespace.
package mbn

type MBN_DEVICE_SERVICE_SESSIONS_STATE int32

const (
	MBN_DEVICE_SERVICE_SESSIONS_RESTORED MBN_DEVICE_SERVICE_SESSIONS_STATE = 0
)
