// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package dns implements the Windows.Win32.Dns namespace.
package dns

type DnsContextHandle struct {
	Value int
}

type IP4_ARRAY struct {
	AddrCount int
	AddrArray int
}

type IP6_ADDRESS struct {
	IP6Dword int
	IP6Word  int
	IP6Byte  int
}

type DNS_ADDR struct {
	MaxSa int
	Data  int
}

type DNS_ADDR_ARRAY struct {
	MaxCount     int
	AddrCount    int
	Tag          int
	Family       int
	WordReserved int
	Flags        int
	MatchFlag    int
	Reserved1    int
	Reserved2    int
	AddrArray    int
}

type DNS_HEADER struct {
	Xid             int
	BITFIELD1       int
	BITFIELD2       int
	QuestionCount   int
	AnswerCount     int
	NameServerCount int
	AdditionalCount int
}

type DNS_HEADER_EXT struct {
	BITFIELD  int
	CHRCODE   int
	CHVERSION int
}

type DNS_WIRE_QUESTION struct {
	QuestionType  int
	QuestionClass int
}

type DNS_WIRE_RECORD struct {
	RecordType  int
	RecordClass int
	TimeToLive  int
	DataLength  int
}

type DNS_A_DATA struct {
	IpAddress int
}

type DNS_PTR_DATAW struct {
	PNAMEHOST int
}

type DNS_PTR_DATAA struct {
	PNAMEHOST int
}

type DNS_SOA_DATAW struct {
	PNAMEPRIMARYSERVER int
	PNAMEADMINISTRATOR int
	DWSERIALNO         int
	DWREFRESH          int
	DWRETRY            int
	DWEXPIRE           int
	DWDEFAULTTTL       int
}

type DNS_SOA_DATAA struct {
	PNAMEPRIMARYSERVER int
	PNAMEADMINISTRATOR int
	DWSERIALNO         int
	DWREFRESH          int
	DWRETRY            int
	DWEXPIRE           int
	DWDEFAULTTTL       int
}

type DNS_MINFO_DATAW struct {
	PNAMEMAILBOX       int
	PNAMEERRORSMAILBOX int
}

type DNS_MINFO_DATAA struct {
	PNAMEMAILBOX       int
	PNAMEERRORSMAILBOX int
}

type DNS_MX_DATAW struct {
	PNAMEEXCHANGE int
	WPREFERENCE   int
	Pad           int
}

type DNS_MX_DATAA struct {
	PNAMEEXCHANGE int
	WPREFERENCE   int
	Pad           int
}

type DNS_TXT_DATAW struct {
	DWSTRINGCOUNT int
	PSTRINGARRAY  int
}

type DNS_TXT_DATAA struct {
	DWSTRINGCOUNT int
	PSTRINGARRAY  int
}

type DNS_NULL_DATA struct {
	DWBYTECOUNT int
	Data        int
}

type DNS_WKS_DATA struct {
	IpAddress  int
	CHPROTOCOL int
	BitMask    int
}

type DNS_AAAA_DATA struct {
	Ip6Address int
}

type DNS_SIG_DATAW struct {
	WTYPECOVERED     int
	CHALGORITHM      int
	CHLABELCOUNT     int
	DWORIGINALTTL    int
	DWEXPIRATION     int
	DWTIMESIGNED     int
	WKEYTAG          int
	WSIGNATURELENGTH int
	PNAMESIGNER      int
	Signature        int
}

type DNS_SIG_DATAA struct {
	WTYPECOVERED     int
	CHALGORITHM      int
	CHLABELCOUNT     int
	DWORIGINALTTL    int
	DWEXPIRATION     int
	DWTIMESIGNED     int
	WKEYTAG          int
	WSIGNATURELENGTH int
	PNAMESIGNER      int
	Signature        int
}

type DNS_KEY_DATA struct {
	WFLAGS      int
	CHPROTOCOL  int
	CHALGORITHM int
	WKEYLENGTH  int
	WPAD        int
	Key         int
}

type DNS_DHCID_DATA struct {
	DWBYTECOUNT int
	DHCID       int
}

type DNS_NSEC_DATAW struct {
	PNEXTDOMAINNAME    int
	WTYPEBITMAPSLENGTH int
	WPAD               int
	TypeBitMaps        int
}

type DNS_NSEC_DATAA struct {
	PNEXTDOMAINNAME    int
	WTYPEBITMAPSLENGTH int
	WPAD               int
	TypeBitMaps        int
}

type DNS_NSEC3_DATA struct {
	CHALGORITHM        int
	BFLAGS             int
	WITERATIONS        int
	BSALTLENGTH        int
	BHASHLENGTH        int
	WTYPEBITMAPSLENGTH int
	CHDATA             int
}

type DNS_NSEC3PARAM_DATA struct {
	CHALGORITHM int
	BFLAGS      int
	WITERATIONS int
	BSALTLENGTH int
	BPAD        int
	PBSALT      int
}

type DNS_TLSA_DATA struct {
	BCERTUSAGE                        int
	BSELECTOR                         int
	BMATCHINGTYPE                     int
	BCERTIFICATEASSOCIATIONDATALENGTH int
	BPAD                              int
	BCERTIFICATEASSOCIATIONDATA       int
}

type DNS_DS_DATA struct {
	WKEYTAG       int
	CHALGORITHM   int
	CHDIGESTTYPE  int
	WDIGESTLENGTH int
	WPAD          int
	Digest        int
}

type DNS_OPT_DATA struct {
	WDATALENGTH int
	WPAD        int
	Data        int
}

type DNS_LOC_DATA struct {
	WVERSION    int
	WSIZE       int
	WHORPREC    int
	WVERPREC    int
	DWLATITUDE  int
	DWLONGITUDE int
	DWALTITUDE  int
}

type DNS_NXT_DATAW struct {
	PNAMENEXT int
	WNUMTYPES int
	WTYPES    int
}

type DNS_NXT_DATAA struct {
	PNAMENEXT int
	WNUMTYPES int
	WTYPES    int
}

type DNS_SRV_DATAW struct {
	PNAMETARGET int
	WPRIORITY   int
	WWEIGHT     int
	WPORT       int
	Pad         int
}

type DNS_SRV_DATAA struct {
	PNAMETARGET int
	WPRIORITY   int
	WWEIGHT     int
	WPORT       int
	Pad         int
}

type DNS_NAPTR_DATAW struct {
	WORDER             int
	WPREFERENCE        int
	PFLAGS             int
	PSERVICE           int
	PREGULAREXPRESSION int
	PREPLACEMENT       int
}

type DNS_NAPTR_DATAA struct {
	WORDER             int
	WPREFERENCE        int
	PFLAGS             int
	PSERVICE           int
	PREGULAREXPRESSION int
	PREPLACEMENT       int
}

type DNS_ATMA_DATA struct {
	AddressType int
	Address     int
}

type DNS_TKEY_DATAW struct {
	PNAMEALGORITHM   int
	PALGORITHMPACKET int
	PKEY             int
	POTHERDATA       int
	DWCREATETIME     int
	DWEXPIRETIME     int
	WMODE            int
	WERROR           int
	WKEYLENGTH       int
	WOTHERLENGTH     int
	CALGNAMELENGTH   int
	BPACKETPOINTERS  int
}

type DNS_TKEY_DATAA struct {
	PNAMEALGORITHM   int
	PALGORITHMPACKET int
	PKEY             int
	POTHERDATA       int
	DWCREATETIME     int
	DWEXPIRETIME     int
	WMODE            int
	WERROR           int
	WKEYLENGTH       int
	WOTHERLENGTH     int
	CALGNAMELENGTH   int
	BPACKETPOINTERS  int
}

type DNS_TSIG_DATAW struct {
	PNAMEALGORITHM   int
	PALGORITHMPACKET int
	PSIGNATURE       int
	POTHERDATA       int
	I64CREATETIME    int
	WFUDGETIME       int
	WORIGINALXID     int
	WERROR           int
	WSIGLENGTH       int
	WOTHERLENGTH     int
	CALGNAMELENGTH   int
	BPACKETPOINTERS  int
}

type DNS_TSIG_DATAA struct {
	PNAMEALGORITHM   int
	PALGORITHMPACKET int
	PSIGNATURE       int
	POTHERDATA       int
	I64CREATETIME    int
	WFUDGETIME       int
	WORIGINALXID     int
	WERROR           int
	WSIGLENGTH       int
	WOTHERLENGTH     int
	CALGNAMELENGTH   int
	BPACKETPOINTERS  int
}

type DNS_UNKNOWN_DATA struct {
	DWBYTECOUNT int
	BDATA       int
}

type DNS_WINS_DATA struct {
	DWMAPPINGFLAG    int
	DWLOOKUPTIMEOUT  int
	DWCACHETIMEOUT   int
	CWINSSERVERCOUNT int
	WinsServers      int
}

type DNS_WINSR_DATAW struct {
	DWMAPPINGFLAG     int
	DWLOOKUPTIMEOUT   int
	DWCACHETIMEOUT    int
	PNAMERESULTDOMAIN int
}

type DNS_WINSR_DATAA struct {
	DWMAPPINGFLAG     int
	DWLOOKUPTIMEOUT   int
	DWCACHETIMEOUT    int
	PNAMERESULTDOMAIN int
}

type DNS_RECORD_FLAGS struct {
	BITFIELD int
}

type DNS_RECORDW struct {
	PNEXT       int
	PNAME       int
	WTYPE       int
	WDATALENGTH int
	Flags       int
	DWTTL       int
	DWRESERVED  int
	Data        int
}

type DnsRecordOptW struct {
	PNEXT        int
	PNAME        int
	WTYPE        int
	WDATALENGTH  int
	Flags        int
	ExtHeader    int
	WPAYLOADSIZE int
	WRESERVED    int
	Data         int
}

type DNS_RECORDA struct {
	PNEXT       int
	PNAME       int
	WTYPE       int
	WDATALENGTH int
	Flags       int
	DWTTL       int
	DWRESERVED  int
	Data        int
}

type DnsRecordOptA struct {
	PNEXT        int
	PNAME        int
	WTYPE        int
	WDATALENGTH  int
	Flags        int
	ExtHeader    int
	WPAYLOADSIZE int
	WRESERVED    int
	Data         int
}

type DNS_RRSET struct {
	PFIRSTRR int
	PLASTRR  int
}

type DNS_PROXY_INFORMATION struct {
	VERSION              int
	PROXYINFORMATIONTYPE int
	PROXYNAME            int
}

type DNS_QUERY_RESULT struct {
	Version       int
	QueryStatus   int
	QueryOptions  int
	PQUERYRECORDS int
	Reserved      int
}

type DNS_QUERY_REQUEST struct {
	Version                  int
	QueryName                int
	QueryType                int
	QueryOptions             int
	PDNSSERVERLIST           int
	InterfaceIndex           int
	PQUERYCOMPLETIONCALLBACK int
	PQUERYCONTEXT            int
}

type DNS_QUERY_CANCEL struct {
	Reserved int
}

type DNS_MESSAGE_BUFFER struct {
	MessageHead int
	MessageBody int
}

type DNS_CONNECTION_PROXY_INFO struct {
	Version          int
	PWSZFRIENDLYNAME int
	Flags            int
	Switch           int
	Anonymous        int
}

type DNS_CONNECTION_PROXY_INFO_EX struct {
	ProxyInfo            int
	DWINTERFACEINDEX     int
	PWSZCONNECTIONNAME   int
	FDIRECTCONFIGURATION int
	HCONNECTION          int
}

type DNS_CONNECTION_PROXY_ELEMENT struct {
	Type int
	Info int
}

type DNS_CONNECTION_PROXY_LIST struct {
	CPROXIES int
	PPROXIES int
}

type DNS_CONNECTION_NAME struct {
	WSZNAME int
}

type DNS_CONNECTION_NAME_LIST struct {
	CNAMES int
	PNAMES int
}

type DNS_CONNECTION_IFINDEX_ENTRY struct {
	PWSZCONNECTIONNAME int
	DWIFINDEX          int
}

type DNS_CONNECTION_IFINDEX_LIST struct {
	PCONNECTIONIFINDEXENTRIES int
	NENTRIES                  int
}

type DNS_CONNECTION_POLICY_ENTRY struct {
	PWSZHOST           int
	PWSZAPPID          int
	CBAPPSID           int
	PBAPPSID           int
	NCONNECTIONS       int
	PPWSZCONNECTIONS   int
	DWPOLICYENTRYFLAGS int
}

type DNS_CONNECTION_POLICY_ENTRY_LIST struct {
	PPOLICYENTRIES int
	NENTRIES       int
}

type DNS_SERVICE_INSTANCE struct {
	PSZINSTANCENAME  int
	PSZHOSTNAME      int
	IP4ADDRESS       int
	IP6ADDRESS       int
	WPORT            int
	WPRIORITY        int
	WWEIGHT          int
	DWPROPERTYCOUNT  int
	KEYS             int
	VALUES           int
	DWINTERFACEINDEX int
}

type DNS_SERVICE_CANCEL struct {
	RESERVED int
}

type DNS_SERVICE_BROWSE_REQUEST struct {
	Version        int
	InterfaceIndex int
	QueryName      int
	Anonymous      int
	PQUERYCONTEXT  int
}

type DNS_SERVICE_RESOLVE_REQUEST struct {
	Version                    int
	InterfaceIndex             int
	QueryName                  int
	PRESOLVECOMPLETIONCALLBACK int
	PQUERYCONTEXT              int
}

type DNS_SERVICE_REGISTER_REQUEST struct {
	Version                     int
	InterfaceIndex              int
	PSERVICEINSTANCE            int
	PREGISTERCOMPLETIONCALLBACK int
	PQUERYCONTEXT               int
	HCREDENTIALS                int
	UNICASTENABLED              int
}

type MDNS_QUERY_HANDLE struct {
	NAMEBUF            int
	WTYPE              int
	PSUBSCRIPTION      int
	PWNFCALLBACKPARAMS int
	STATENAMEDATA      int
}

type MDNS_QUERY_REQUEST struct {
	Version         int
	ULREFCOUNT      int
	Query           int
	QueryType       int
	QueryOptions    int
	InterfaceIndex  int
	PQUERYCALLBACK  int
	PQUERYCONTEXT   int
	FANSWERRECEIVED int
	ULRESENDCOUNT   int
}
