// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package inkinput implements the Windows.Win32.InkInput namespace.
package inkinput

type InkDesktopHost struct {
}

type InkD2DRenderer struct {
}
