// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package performancelogandalerts implements the Windows.Win32.PerformanceLogAndAlerts namespace.
package performancelogandalerts

type DataCollectorSet struct {
}

type TraceSession struct {
}

type TraceSessionCollection struct {
}

type TraceDataProvider struct {
}

type TraceDataProviderCollection struct {
}

type DataCollectorSetCollection struct {
}

type LegacyDataCollectorSet struct {
}

type LegacyDataCollectorSetCollection struct {
}

type LegacyTraceSession struct {
}

type LegacyTraceSessionCollection struct {
}

type ServerDataCollectorSet struct {
}

type ServerDataCollectorSetCollection struct {
}

type SystemDataCollectorSet struct {
}

type SystemDataCollectorSetCollection struct {
}

type BootTraceSession struct {
}

type BootTraceSessionCollection struct {
}
