// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package componentservices implements the Windows.Win32.ComponentServices namespace.
package componentservices

type SecurityIdentity struct {
}

type SecurityCallers struct {
}

type SecurityCallContext struct {
}

type GetSecurityCallContextAppObject struct {
}

type Dummy30040732 struct {
}

type TransactionContext struct {
}

type TransactionContextEx struct {
}

type ByotServerEx struct {
}

type CServiceConfig struct {
}

type ServicePool struct {
}

type ServicePoolConfig struct {
}

type SharedProperty struct {
}

type SharedPropertyGroup struct {
}

type SharedPropertyGroupManager struct {
}

type COMEvents struct {
}

type CoMTSLocator struct {
}

type MtsGrp struct {
}

type ComServiceEvents struct {
}

type ComSystemAppEventData struct {
}

type CRMClerk struct {
}

type CRMRecoveryClerk struct {
}

type LBEvents struct {
}

type MessageMover struct {
}

type DispenserManager struct {
}

type PoolMgr struct {
}

type EventServer struct {
}

type TrackerServer struct {
}

type AppDomainHelper struct {
}

type ClrAssemblyLocator struct {
}

type COMAdminCatalog struct {
}

type COMAdminCatalogObject struct {
}

type COMAdminCatalogCollection struct {
}

type BOID struct {
	RGB int
}

type XACTTRANSINFO struct {
	UOW                     int
	ISOLEVEL                int
	ISOFLAGS                int
	GRFTCSUPPORTED          int
	GRFRMSUPPORTED          int
	GRFTCSUPPORTEDRETAINING int
	GRFRMSUPPORTEDRETAINING int
}

type XACTSTATS struct {
	COPEN              int
	CCOMMITTING        int
	CCOMMITTED         int
	CABORTING          int
	CABORTED           int
	CINDOUBT           int
	CHEURISTICDECISION int
	TIMETRANSACTIONSUP int
}

type XACTOPT struct {
	ULTIMEOUT     int
	SZDESCRIPTION int
}

type XID_T struct {
	FORMATID     int
	GTRID_LENGTH int
	BQUAL_LENGTH int
	DATA         int
}

type XA_SWITCH_T struct {
	NAME              int
	FLAGS             int
	VERSION           int
	XA_OPEN_ENTRY     int
	XA_CLOSE_ENTRY    int
	XA_START_ENTRY    int
	XA_END_ENTRY      int
	XA_ROLLBACK_ENTRY int
	XA_PREPARE_ENTRY  int
	XA_COMMIT_ENTRY   int
	XA_RECOVER_ENTRY  int
	XA_FORGET_ENTRY   int
	XA_COMPLETE_ENTRY int
}

type ProxyConfigParams struct {
	WCTHREADSMAX int
}

type COMSVCSEVENTINFO struct {
	CBSIZE       int
	DWPID        int
	LTIME        int
	LMICROTIME   int
	PERFCOUNT    int
	GUIDAPP      int
	SMACHINENAME int
}

type RECYCLE_INFO struct {
	GUIDCOMBASEPROCESSIDENTIFIER int
	ProcessStartTime             int
	DWRECYCLELIFETIMELIMIT       int
	DWRECYCLEMEMORYLIMIT         int
	DWRECYCLEEXPIRATIONTIMEOUT   int
}

type HANG_INFO struct {
	FAPPHANGMONITORENABLED int
	FTERMINATEONHANG       int
	DumpType               int
	DWHANGTIMEOUT          int
	DWDUMPCOUNT            int
	DWINFOMSGCOUNT         int
}

type CAppStatistics struct {
	M_CTOTALCALLS     int
	M_CTOTALINSTANCES int
	M_CTOTALCLASSES   int
	M_CCALLSPERSECOND int
}

type CAppData struct {
	M_IDAPP          int
	M_SZAPPGUID      int
	M_DWAPPPROCESSID int
	M_APPSTATISTICS  int
}

type CCLSIDData struct {
	M_CLSID           int
	M_CREFERENCES     int
	M_CBOUND          int
	M_CPOOLED         int
	M_CINCALL         int
	M_DWRESPTIME      int
	M_CCALLSCOMPLETED int
	M_CCALLSFAILED    int
}

type CCLSIDData2 struct {
	M_CLSID           int
	M_APPID           int
	M_PARTID          int
	M_PWSZAPPNAME     int
	M_PWSZCTXNAME     int
	M_EAPPTYPE        int
	M_CREFERENCES     int
	M_CBOUND          int
	M_CPOOLED         int
	M_CINCALL         int
	M_DWRESPTIME      int
	M_CCALLSCOMPLETED int
	M_CCALLSFAILED    int
}

type ApplicationProcessSummary struct {
	PartitionIdPrimaryApplication   int
	ApplicationIdPrimaryApplication int
	ApplicationInstanceId           int
	ProcessId                       int
	Type                            int
	ProcessExeName                  int
	IsService                       int
	IsPaused                        int
	IsRecycled                      int
}

type ApplicationProcessStatistics struct {
	NumCallsOutstanding   int
	NumTrackedComponents  int
	NumComponentInstances int
	AvgCallsPerSecond     int
	Reserved1             int
	Reserved2             int
	Reserved3             int
	Reserved4             int
}

type ApplicationProcessRecycleInfo struct {
	IsRecyclable                  int
	IsRecycled                    int
	TimeRecycled                  int
	TimeToTerminate               int
	RecycleReasonCode             int
	IsPendingRecycle              int
	HasAutomaticLifetimeRecycling int
	TimeForAutomaticRecycling     int
	MemoryLimitInKB               int
	MemoryUsageInKBLastCheck      int
	ActivationLimit               int
	NumActivationsLastReported    int
	CallLimit                     int
	NumCallsLastReported          int
}

type ApplicationSummary struct {
	ApplicationInstanceId int
	PartitionId           int
	ApplicationId         int
	Type                  int
	ApplicationName       int
	NumTrackedComponents  int
	NumComponentInstances int
}

type ComponentSummary struct {
	ApplicationInstanceId int
	PartitionId           int
	ApplicationId         int
	Clsid                 int
	ClassName             int
	ApplicationName       int
}

type ComponentStatistics struct {
	NumInstances            int
	NumBoundReferences      int
	NumPooledObjects        int
	NumObjectsInCall        int
	AvgResponseTimeInMs     int
	NumCallsCompletedRecent int
	NumCallsFailedRecent    int
	NumCallsCompletedTotal  int
	NumCallsFailedTotal     int
	Reserved1               int
	Reserved2               int
	Reserved3               int
	Reserved4               int
}

type ComponentHangMonitorInfo struct {
	IsMonitored          int
	TerminateOnHang      int
	AvgCallThresholdInMs int
}

type CrmLogRecordRead struct {
	DWCRMFLAGS       int
	DWSEQUENCENUMBER int
	BLOBUSERDATA     int
}

type CEventSystem struct {
}

type CEventPublisher struct {
}

type CEventClass struct {
}

type CEventSubscription struct {
}

type EventObjectChange struct {
}

type EventObjectChange2 struct {
}

type COMEVENTSYSCHANGEINFO struct {
	CBSIZE        int
	CHANGETYPE    int
	OBJECTID      int
	PARTITIONID   int
	APPLICATIONID int
	RESERVED      int
}
