// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package tilesbadgesnotifications implements the Windows.Win32.TilesBadgesNotifications namespace.
package tilesbadgesnotifications

type NOTIFICATION_USER_INPUT_DATA struct {
	Key   int
	Value int
}
