// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package activedirectory implements the Windows.Win32.ActiveDirectory namespace.
package activedirectory

type GetDcContextHandle struct {
	Value int
}

type CQFORM struct {
	CBSTRUCT int
	DWFLAGS  int
	CLSID    int
	HICON    int
	PSZTITLE int
}

type CQPAGE struct {
	CBSTRUCT       int
	DWFLAGS        int
	PPAGEPROC      int
	HINSTANCE      int
	IDPAGENAME     int
	IDPAGETEMPLATE int
	PDLGPROC       int
	LPARAM         int
}

type OPENQUERYWINDOW struct {
	CBSTRUCT           int
	DWFLAGS            int
	CLSIDHANDLER       int
	PHANDLERPARAMETERS int
	CLSIDDEFAULTFORM   int
	PPERSISTQUERY      int
	Anonymous          int
}

type PropertyEntry struct {
}

type PropertyValue struct {
}

type AccessControlEntry struct {
}

type AccessControlList struct {
}

type SecurityDescriptor struct {
}

type LargeInteger struct {
}

type NameTranslate struct {
}

type CaseIgnoreList struct {
}

type FaxNumber struct {
}

type NetAddress struct {
}

type OctetList struct {
}

type Email struct {
}

type Path struct {
}

type ReplicaPointer struct {
}

type Timestamp struct {
}

type PostalAddress struct {
}

type BackLink struct {
}

type TypedName struct {
}

type Hold struct {
}

type Pathname struct {
}

type ADSystemInfo struct {
}

type WinNTSystemInfo struct {
}

type DNWithBinary struct {
}

type DNWithString struct {
}

type ADsSecurityUtility struct {
}

type ADS_OCTET_STRING struct {
	DWLENGTH int
	LPVALUE  int
}

type ADS_NT_SECURITY_DESCRIPTOR struct {
	DWLENGTH int
	LPVALUE  int
}

type ADS_PROV_SPECIFIC struct {
	DWLENGTH int
	LPVALUE  int
}

type ADS_CASEIGNORE_LIST struct {
	Next   int
	String int
}

type ADS_OCTET_LIST struct {
	Next   int
	Length int
	Data   int
}

type ADS_PATH struct {
	Type       int
	VolumeName int
	Path       int
}

type ADS_POSTALADDRESS struct {
	PostalAddress int
}

type ADS_TIMESTAMP struct {
	WholeSeconds int
	EventID      int
}

type ADS_BACKLINK struct {
	RemoteID   int
	ObjectName int
}

type ADS_TYPEDNAME struct {
	ObjectName int
	Level      int
	Interval   int
}

type ADS_HOLD struct {
	ObjectName int
	Amount     int
}

type ADS_NETADDRESS struct {
	AddressType   int
	AddressLength int
	Address       int
}

type ADS_REPLICAPOINTER struct {
	ServerName          int
	ReplicaType         int
	ReplicaNumber       int
	Count               int
	ReplicaAddressHints int
}

type ADS_FAXNUMBER struct {
	TelephoneNumber int
	NumberOfBits    int
	Parameters      int
}

type ADS_EMAIL struct {
	Address int
	Type    int
}

type ADS_DN_WITH_BINARY struct {
	DWLENGTH      int
	LPBINARYVALUE int
	PSZDNSTRING   int
}

type ADS_DN_WITH_STRING struct {
	PSZSTRINGVALUE int
	PSZDNSTRING    int
}

type ADSVALUE struct {
	DWTYPE    int
	Anonymous int
}

type ADS_ATTR_INFO struct {
	PSZATTRNAME   int
	DWCONTROLCODE int
	DWADSTYPE     int
	PADSVALUES    int
	DWNUMVALUES   int
}

type ADS_OBJECT_INFO struct {
	PSZRDN       int
	PSZOBJECTDN  int
	PSZPARENTDN  int
	PSZSCHEMADN  int
	PSZCLASSNAME int
}

type ADS_SEARCHPREF_INFO struct {
	DWSEARCHPREF int
	VVALUE       int
	DWSTATUS     int
}

type ADS_SEARCH_COLUMN struct {
	PSZATTRNAME int
	DWADSTYPE   int
	PADSVALUES  int
	DWNUMVALUES int
	HRESERVED   int
}

type ADS_ATTR_DEF struct {
	PSZATTRNAME  int
	DWADSTYPE    int
	DWMINRANGE   int
	DWMAXRANGE   int
	FMULTIVALUED int
}

type ADS_CLASS_DEF struct {
	PSZCLASSNAME       int
	DWMANDATORYATTRS   int
	PPSZMANDATORYATTRS int
	OPTIONALATTRS      int
	PPSZOPTIONALATTRS  int
	DWNAMINGATTRS      int
	PPSZNAMINGATTRS    int
	DWSUPERCLASSES     int
	PPSZSUPERCLASSES   int
	FISCONTAINER       int
}

type ADS_SORTKEY struct {
	PSZATTRTYPE   int
	PSZRESERVED   int
	FREVERSEORDER int
}

type ADS_VLV struct {
	DWBEFORECOUNT     int
	DWAFTERCOUNT      int
	DWOFFSET          int
	DWCONTENTCOUNT    int
	PSZTARGET         int
	DWCONTEXTIDLENGTH int
	LPCONTEXTID       int
}

type DSOBJECT struct {
	DWFLAGS         int
	DWPROVIDERFLAGS int
	OFFSETNAME      int
	OFFSETCLASS     int
}

type DSOBJECTNAMES struct {
	CLSIDNAMESPACE int
	CITEMS         int
	AOBJECTS       int
}

type DSDISPLAYSPECOPTIONS struct {
	DWSIZE                 int
	DWFLAGS                int
	OFFSETATTRIBPREFIX     int
	OFFSETUSERNAME         int
	OFFSETPASSWORD         int
	OFFSETSERVER           int
	OFFSETSERVERCONFIGPATH int
}

type DSPROPERTYPAGEINFO struct {
	OFFSETSTRING int
}

type DOMAINDESC struct {
	PSZNAME        int
	PSZPATH        int
	PSZNCNAME      int
	PSZTRUSTPARENT int
	PSZOBJECTCLASS int
	ULFLAGS        int
	FDOWNLEVEL     int
	PDCHILDLIST    int
	PDNEXTSIBLING  int
}

type DOMAIN_TREE struct {
	DSSIZE   int
	DWCOUNT  int
	ADOMAINS int
}

type DSCLASSCREATIONINFO struct {
	DWFLAGS                int
	CLSIDWIZARDDIALOG      int
	CLSIDWIZARDPRIMARYPAGE int
	CWIZARDEXTENSIONS      int
	AWIZARDEXTENSIONS      int
}

type DSBROWSEINFOW struct {
	CBSTRUCT       int
	HWNDOWNER      int
	PSZCAPTION     int
	PSZTITLE       int
	PSZROOT        int
	PSZPATH        int
	CCHPATH        int
	DWFLAGS        int
	PFNCALLBACK    int
	LPARAM         int
	DWRETURNFORMAT int
	PUSERNAME      int
	PPASSWORD      int
	PSZOBJECTCLASS int
	CCHOBJECTCLASS int
}

type DSBROWSEINFOA struct {
	CBSTRUCT       int
	HWNDOWNER      int
	PSZCAPTION     int
	PSZTITLE       int
	PSZROOT        int
	PSZPATH        int
	CCHPATH        int
	DWFLAGS        int
	PFNCALLBACK    int
	LPARAM         int
	DWRETURNFORMAT int
	PUSERNAME      int
	PPASSWORD      int
	PSZOBJECTCLASS int
	CCHOBJECTCLASS int
}

type DSBITEMW struct {
	CBSTRUCT       int
	PSZADSPATH     int
	PSZCLASS       int
	DWMASK         int
	DWSTATE        int
	DWSTATEMASK    int
	SZDISPLAYNAME  int
	SZICONLOCATION int
	IICONRESID     int
}

type DSBITEMA struct {
	CBSTRUCT       int
	PSZADSPATH     int
	PSZCLASS       int
	DWMASK         int
	DWSTATE        int
	DWSTATEMASK    int
	SZDISPLAYNAME  int
	SZICONLOCATION int
	IICONRESID     int
}

type DSOP_UPLEVEL_FILTER_FLAGS struct {
	FLBOTHMODES      int
	FLMIXEDMODEONLY  int
	FLNATIVEMODEONLY int
}

type DSOP_FILTER_FLAGS struct {
	Uplevel     int
	FLDOWNLEVEL int
}

type DSOP_SCOPE_INIT_INFO struct {
	CBSIZE      int
	FLTYPE      int
	FLSCOPE     int
	FilterFlags int
	PWZDCNAME   int
	PWZADSPATH  int
	HR          int
}

type DSOP_INIT_INFO struct {
	CBSIZE             int
	PWZTARGETCOMPUTER  int
	CDSSCOPEINFOS      int
	ADSSCOPEINFOS      int
	FLOPTIONS          int
	CATTRIBUTESTOFETCH int
	APWZATTRIBUTENAMES int
}

type DS_SELECTION struct {
	PWZNAME               int
	PWZADSPATH            int
	PWZCLASS              int
	PWZUPN                int
	PVARFETCHEDATTRIBUTES int
	FLSCOPETYPE           int
}

type DS_SELECTION_LIST struct {
	CITEMS             int
	CFETCHEDATTRIBUTES int
	ADSSELECTION       int
}

type DSQUERYINITPARAMS struct {
	CBSTRUCT             int
	DWFLAGS              int
	PDEFAULTSCOPE        int
	PDEFAULTSAVELOCATION int
	PUSERNAME            int
	PPASSWORD            int
	PSERVER              int
}

type DSCOLUMN struct {
	DWFLAGS        int
	FMT            int
	CX             int
	IDSNAME        int
	OFFSETPROPERTY int
	DWRESERVED     int
}

type DSQUERYPARAMS struct {
	CBSTRUCT    int
	DWFLAGS     int
	HINSTANCE   int
	OFFSETQUERY int
	ICOLUMNS    int
	DWRESERVED  int
	ACOLUMNS    int
}

type DSQUERYCLASSLIST struct {
	CBSTRUCT    int
	CCLASSES    int
	OFFSETCLASS int
}

type DSA_NEWOBJ_DISPINFO struct {
	DWSIZE              int
	HOBJCLASSICON       int
	LPSZWIZTITLE        int
	LPSZCONTDISPLAYNAME int
}

type ADSPROPINITPARAMS struct {
	DWSIZE         int
	DWFLAGS        int
	HR             int
	PDSOBJ         int
	PWZCN          int
	PWRITABLEATTRS int
}

type ADSPROPERROR struct {
	HWNDPAGE     int
	PSZPAGETITLE int
	PSZOBJPATH   int
	PSZOBJCLASS  int
	HR           int
	PSZERROR     int
}

type SCHEDULE_HEADER struct {
	Type   int
	Offset int
}

type SCHEDULE struct {
	Size              int
	Bandwidth         int
	NumberOfSchedules int
	Schedules         int
}

type DS_NAME_RESULT_ITEMA struct {
	STATUS  int
	PDOMAIN int
	PNAME   int
}

type DS_NAME_RESULTA struct {
	CITEMS int
	RITEMS int
}

type DS_NAME_RESULT_ITEMW struct {
	STATUS  int
	PDOMAIN int
	PNAME   int
}

type DS_NAME_RESULTW struct {
	CITEMS int
	RITEMS int
}

type DS_REPSYNCALL_SYNCA struct {
	PSZSRCID int
	PSZDSTID int
	PSZNC    int
	PGUIDSRC int
	PGUIDDST int
}

type DS_REPSYNCALL_SYNCW struct {
	PSZSRCID int
	PSZDSTID int
	PSZNC    int
	PGUIDSRC int
	PGUIDDST int
}

type DS_REPSYNCALL_ERRINFOA struct {
	PSZSVRID   int
	ERROR      int
	DWWIN32ERR int
	PSZSRCID   int
}

type DS_REPSYNCALL_ERRINFOW struct {
	PSZSVRID   int
	ERROR      int
	DWWIN32ERR int
	PSZSRCID   int
}

type DS_REPSYNCALL_UPDATEA struct {
	EVENT    int
	PERRINFO int
	PSYNC    int
}

type DS_REPSYNCALL_UPDATEW struct {
	EVENT    int
	PERRINFO int
	PSYNC    int
}

type DS_SITE_COST_INFO struct {
	ERRORCODE int
	COST      int
}

type DS_SCHEMA_GUID_MAPA struct {
	GUID     int
	GUIDTYPE int
	PNAME    int
}

type DS_SCHEMA_GUID_MAPW struct {
	GUID     int
	GUIDTYPE int
	PNAME    int
}

type DS_DOMAIN_CONTROLLER_INFO_1A struct {
	NetbiosName        int
	DnsHostName        int
	SiteName           int
	ComputerObjectName int
	ServerObjectName   int
	FISPDC             int
	FDSENABLED         int
}

type DS_DOMAIN_CONTROLLER_INFO_1W struct {
	NetbiosName        int
	DnsHostName        int
	SiteName           int
	ComputerObjectName int
	ServerObjectName   int
	FISPDC             int
	FDSENABLED         int
}

type DS_DOMAIN_CONTROLLER_INFO_2A struct {
	NetbiosName        int
	DnsHostName        int
	SiteName           int
	SiteObjectName     int
	ComputerObjectName int
	ServerObjectName   int
	NtdsDsaObjectName  int
	FISPDC             int
	FDSENABLED         int
	FISGC              int
	SiteObjectGuid     int
	ComputerObjectGuid int
	ServerObjectGuid   int
	NtdsDsaObjectGuid  int
}

type DS_DOMAIN_CONTROLLER_INFO_2W struct {
	NetbiosName        int
	DnsHostName        int
	SiteName           int
	SiteObjectName     int
	ComputerObjectName int
	ServerObjectName   int
	NtdsDsaObjectName  int
	FISPDC             int
	FDSENABLED         int
	FISGC              int
	SiteObjectGuid     int
	ComputerObjectGuid int
	ServerObjectGuid   int
	NtdsDsaObjectGuid  int
}

type DS_DOMAIN_CONTROLLER_INFO_3A struct {
	NetbiosName        int
	DnsHostName        int
	SiteName           int
	SiteObjectName     int
	ComputerObjectName int
	ServerObjectName   int
	NtdsDsaObjectName  int
	FISPDC             int
	FDSENABLED         int
	FISGC              int
	FISRODC            int
	SiteObjectGuid     int
	ComputerObjectGuid int
	ServerObjectGuid   int
	NtdsDsaObjectGuid  int
}

type DS_DOMAIN_CONTROLLER_INFO_3W struct {
	NetbiosName        int
	DnsHostName        int
	SiteName           int
	SiteObjectName     int
	ComputerObjectName int
	ServerObjectName   int
	NtdsDsaObjectName  int
	FISPDC             int
	FDSENABLED         int
	FISGC              int
	FISRODC            int
	SiteObjectGuid     int
	ComputerObjectGuid int
	ServerObjectGuid   int
	NtdsDsaObjectGuid  int
}

type DS_REPL_NEIGHBORW struct {
	PSZNAMINGCONTEXT                   int
	PSZSOURCEDSADN                     int
	PSZSOURCEDSAADDRESS                int
	PSZASYNCINTERSITETRANSPORTDN       int
	DWREPLICAFLAGS                     int
	DWRESERVED                         int
	UUIDNAMINGCONTEXTOBJGUID           int
	UUIDSOURCEDSAOBJGUID               int
	UUIDSOURCEDSAINVOCATIONID          int
	UUIDASYNCINTERSITETRANSPORTOBJGUID int
	USNLASTOBJCHANGESYNCED             int
	USNATTRIBUTEFILTER                 int
	FTIMELASTSYNCSUCCESS               int
	FTIMELASTSYNCATTEMPT               int
	DWLASTSYNCRESULT                   int
	CNUMCONSECUTIVESYNCFAILURES        int
}

type DS_REPL_NEIGHBORW_BLOB struct {
	OSZNAMINGCONTEXT                   int
	OSZSOURCEDSADN                     int
	OSZSOURCEDSAADDRESS                int
	OSZASYNCINTERSITETRANSPORTDN       int
	DWREPLICAFLAGS                     int
	DWRESERVED                         int
	UUIDNAMINGCONTEXTOBJGUID           int
	UUIDSOURCEDSAOBJGUID               int
	UUIDSOURCEDSAINVOCATIONID          int
	UUIDASYNCINTERSITETRANSPORTOBJGUID int
	USNLASTOBJCHANGESYNCED             int
	USNATTRIBUTEFILTER                 int
	FTIMELASTSYNCSUCCESS               int
	FTIMELASTSYNCATTEMPT               int
	DWLASTSYNCRESULT                   int
	CNUMCONSECUTIVESYNCFAILURES        int
}

type DS_REPL_NEIGHBORSW struct {
	CNUMNEIGHBORS int
	DWRESERVED    int
	RGNEIGHBOR    int
}

type DS_REPL_CURSOR struct {
	UUIDSOURCEDSAINVOCATIONID int
	USNATTRIBUTEFILTER        int
}

type DS_REPL_CURSOR_2 struct {
	UUIDSOURCEDSAINVOCATIONID int
	USNATTRIBUTEFILTER        int
	FTIMELASTSYNCSUCCESS      int
}

type DS_REPL_CURSOR_3W struct {
	UUIDSOURCEDSAINVOCATIONID int
	USNATTRIBUTEFILTER        int
	FTIMELASTSYNCSUCCESS      int
	PSZSOURCEDSADN            int
}

type DS_REPL_CURSOR_BLOB struct {
	UUIDSOURCEDSAINVOCATIONID int
	USNATTRIBUTEFILTER        int
	FTIMELASTSYNCSUCCESS      int
	OSZSOURCEDSADN            int
}

type DS_REPL_CURSORS struct {
	CNUMCURSORS int
	DWRESERVED  int
	RGCURSOR    int
}

type DS_REPL_CURSORS_2 struct {
	CNUMCURSORS          int
	DWENUMERATIONCONTEXT int
	RGCURSOR             int
}

type DS_REPL_CURSORS_3W struct {
	CNUMCURSORS          int
	DWENUMERATIONCONTEXT int
	RGCURSOR             int
}

type DS_REPL_ATTR_META_DATA struct {
	PSZATTRIBUTENAME                   int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
}

type DS_REPL_ATTR_META_DATA_2 struct {
	PSZATTRIBUTENAME                   int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
	PSZLASTORIGINATINGDSADN            int
}

type DS_REPL_ATTR_META_DATA_BLOB struct {
	OSZATTRIBUTENAME                   int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
	OSZLASTORIGINATINGDSADN            int
}

type DS_REPL_OBJ_META_DATA struct {
	CNUMENTRIES int
	DWRESERVED  int
	RGMETADATA  int
}

type DS_REPL_OBJ_META_DATA_2 struct {
	CNUMENTRIES int
	DWRESERVED  int
	RGMETADATA  int
}

type DS_REPL_KCC_DSA_FAILUREW struct {
	PSZDSADN          int
	UUIDDSAOBJGUID    int
	FTIMEFIRSTFAILURE int
	CNUMFAILURES      int
	DWLASTRESULT      int
}

type DS_REPL_KCC_DSA_FAILUREW_BLOB struct {
	OSZDSADN          int
	UUIDDSAOBJGUID    int
	FTIMEFIRSTFAILURE int
	CNUMFAILURES      int
	DWLASTRESULT      int
}

type DS_REPL_KCC_DSA_FAILURESW struct {
	CNUMENTRIES  int
	DWRESERVED   int
	RGDSAFAILURE int
}

type DS_REPL_OPW struct {
	FTIMEENQUEUED            int
	ULSERIALNUMBER           int
	ULPRIORITY               int
	OpType                   int
	ULOPTIONS                int
	PSZNAMINGCONTEXT         int
	PSZDSADN                 int
	PSZDSAADDRESS            int
	UUIDNAMINGCONTEXTOBJGUID int
	UUIDDSAOBJGUID           int
}

type DS_REPL_OPW_BLOB struct {
	FTIMEENQUEUED            int
	ULSERIALNUMBER           int
	ULPRIORITY               int
	OpType                   int
	ULOPTIONS                int
	OSZNAMINGCONTEXT         int
	OSZDSADN                 int
	OSZDSAADDRESS            int
	UUIDNAMINGCONTEXTOBJGUID int
	UUIDDSAOBJGUID           int
}

type DS_REPL_PENDING_OPSW struct {
	FTIMECURRENTOPSTARTED int
	CNUMPENDINGOPS        int
	RGPENDINGOP           int
}

type DS_REPL_VALUE_META_DATA struct {
	PSZATTRIBUTENAME                   int
	PSZOBJECTDN                        int
	CBDATA                             int
	PBDATA                             int
	FTIMEDELETED                       int
	FTIMECREATED                       int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
}

type DS_REPL_VALUE_META_DATA_2 struct {
	PSZATTRIBUTENAME                   int
	PSZOBJECTDN                        int
	CBDATA                             int
	PBDATA                             int
	FTIMEDELETED                       int
	FTIMECREATED                       int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
	PSZLASTORIGINATINGDSADN            int
}

type DS_REPL_VALUE_META_DATA_EXT struct {
	PSZATTRIBUTENAME                   int
	PSZOBJECTDN                        int
	CBDATA                             int
	PBDATA                             int
	FTIMEDELETED                       int
	FTIMECREATED                       int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
	PSZLASTORIGINATINGDSADN            int
	DWUSERIDENTIFIER                   int
	DWPRIORLINKSTATE                   int
	DWCURRENTLINKSTATE                 int
}

type DS_REPL_VALUE_META_DATA_BLOB struct {
	OSZATTRIBUTENAME                   int
	OSZOBJECTDN                        int
	CBDATA                             int
	OBDATA                             int
	FTIMEDELETED                       int
	FTIMECREATED                       int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
	OSZLASTORIGINATINGDSADN            int
}

type DS_REPL_VALUE_META_DATA_BLOB_EXT struct {
	OSZATTRIBUTENAME                   int
	OSZOBJECTDN                        int
	CBDATA                             int
	OBDATA                             int
	FTIMEDELETED                       int
	FTIMECREATED                       int
	DWVERSION                          int
	FTIMELASTORIGINATINGCHANGE         int
	UUIDLASTORIGINATINGDSAINVOCATIONID int
	USNORIGINATINGCHANGE               int
	USNLOCALCHANGE                     int
	OSZLASTORIGINATINGDSADN            int
	DWUSERIDENTIFIER                   int
	DWPRIORLINKSTATE                   int
	DWCURRENTLINKSTATE                 int
}

type DS_REPL_ATTR_VALUE_META_DATA struct {
	CNUMENTRIES          int
	DWENUMERATIONCONTEXT int
	RGMETADATA           int
}

type DS_REPL_ATTR_VALUE_META_DATA_2 struct {
	CNUMENTRIES          int
	DWENUMERATIONCONTEXT int
	RGMETADATA           int
}

type DS_REPL_ATTR_VALUE_META_DATA_EXT struct {
	CNUMENTRIES          int
	DWENUMERATIONCONTEXT int
	RGMETADATA           int
}

type DS_REPL_QUEUE_STATISTICSW struct {
	FTIMECURRENTOPSTARTED int
	CNUMPENDINGOPS        int
	FTIMEOLDESTSYNC       int
	FTIMEOLDESTADD        int
	FTIMEOLDESTMOD        int
	FTIMEOLDESTDEL        int
	FTIMEOLDESTUPDREFS    int
}

type DSROLE_PRIMARY_DOMAIN_INFO_BASIC struct {
	MachineRole      int
	Flags            int
	DomainNameFlat   int
	DomainNameDns    int
	DomainForestName int
	DomainGuid       int
}

type DSROLE_UPGRADE_STATUS_INFO struct {
	OperationState      int
	PreviousServerState int
}

type DSROLE_OPERATION_STATE_INFO struct {
	OperationState int
}

type DOMAIN_CONTROLLER_INFOA struct {
	DomainControllerName        int
	DomainControllerAddress     int
	DomainControllerAddressType int
	DomainGuid                  int
	DomainName                  int
	DnsForestName               int
	Flags                       int
	DcSiteName                  int
	ClientSiteName              int
}

type DOMAIN_CONTROLLER_INFOW struct {
	DomainControllerName        int
	DomainControllerAddress     int
	DomainControllerAddressType int
	DomainGuid                  int
	DomainName                  int
	DnsForestName               int
	Flags                       int
	DcSiteName                  int
	ClientSiteName              int
}

type DS_DOMAIN_TRUSTSW struct {
	NetbiosDomainName int
	DnsDomainName     int
	Flags             int
	ParentIndex       int
	TrustType         int
	TrustAttributes   int
	DomainSid         int
	DomainGuid        int
}

type DS_DOMAIN_TRUSTSA struct {
	NetbiosDomainName int
	DnsDomainName     int
	Flags             int
	ParentIndex       int
	TrustType         int
	TrustAttributes   int
	DomainSid         int
	DomainGuid        int
}
