// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package nativewifi implements the Windows.Win32.NativeWiFi namespace.
package nativewifi

type DOT11_SSID struct {
	USSIDLENGTH int
	UCSSID      int
}

type DOT11_AUTH_CIPHER_PAIR struct {
	AuthAlgoId   int
	CipherAlgoId int
}

type DOT11_OI struct {
	OILength int
	OI       int
}

type DOT11_ACCESSNETWORKOPTIONS struct {
	AccessNetworkType int
	Internet          int
	ASRA              int
	ESR               int
	UESA              int
}

type DOT11_VENUEINFO struct {
	VenueGroup int
	VenueType  int
}

type NDIS_STATISTICS_VALUE struct {
	Oid        int
	DataLength int
	Data       int
}

type NDIS_STATISTICS_VALUE_EX struct {
	Oid        int
	DataLength int
	Length     int
	Data       int
}

type NDIS_VAR_DATA_DESC struct {
	Length        int
	MaximumLength int
	Offset        int
}

type NDIS_OBJECT_HEADER struct {
	Type     int
	Revision int
	Size     int
}

type NDIS_STATISTICS_INFO struct {
	Header                 int
	SupportedStatistics    int
	IFINDISCARDS           int
	IFINERRORS             int
	IFHCINOCTETS           int
	IFHCINUCASTPKTS        int
	IFHCINMULTICASTPKTS    int
	IFHCINBROADCASTPKTS    int
	IFHCOUTOCTETS          int
	IFHCOUTUCASTPKTS       int
	IFHCOUTMULTICASTPKTS   int
	IFHCOUTBROADCASTPKTS   int
	IFOUTERRORS            int
	IFOUTDISCARDS          int
	IFHCINUCASTOCTETS      int
	IFHCINMULTICASTOCTETS  int
	IFHCINBROADCASTOCTETS  int
	IFHCOUTUCASTOCTETS     int
	IFHCOUTMULTICASTOCTETS int
	IFHCOUTBROADCASTOCTETS int
}

type NDIS_INTERRUPT_MODERATION_PARAMETERS struct {
	Header              int
	Flags               int
	InterruptModeration int
}

type NDIS_TIMEOUT_DPC_REQUEST_CAPABILITIES struct {
	Header             int
	Flags              int
	TimeoutArrayLength int
	TimeoutArray       int
}

type NDIS_PCI_DEVICE_CUSTOM_PROPERTIES struct {
	Header               int
	DeviceType           int
	CurrentSpeedAndMode  int
	CurrentPayloadSize   int
	MaxPayloadSize       int
	MaxReadRequestSize   int
	CurrentLinkSpeed     int
	CurrentLinkWidth     int
	MaxLinkSpeed         int
	MaxLinkWidth         int
	PciExpressVersion    int
	InterruptType        int
	MaxInterruptMessages int
}

type NDIS_802_11_STATUS_INDICATION struct {
	StatusType int
}

type NDIS_802_11_AUTHENTICATION_REQUEST struct {
	Length int
	Bssid  int
	Flags  int
}

type PMKID_CANDIDATE struct {
	BSSID int
	Flags int
}

type NDIS_802_11_PMKID_CANDIDATE_LIST struct {
	Version       int
	NumCandidates int
	CandidateList int
}

type NDIS_802_11_NETWORK_TYPE_LIST struct {
	NumberOfItems int
	NetworkType   int
}

type NDIS_802_11_CONFIGURATION_FH struct {
	Length     int
	HopPattern int
	HopSet     int
	DwellTime  int
}

type NDIS_802_11_CONFIGURATION struct {
	Length       int
	BeaconPeriod int
	ATIMWindow   int
	DSConfig     int
	FHConfig     int
}

type NDIS_802_11_STATISTICS struct {
	Length                         int
	TransmittedFragmentCount       int
	MulticastTransmittedFrameCount int
	FailedCount                    int
	RetryCount                     int
	MultipleRetryCount             int
	RTSSuccessCount                int
	RTSFailureCount                int
	ACKFailureCount                int
	FrameDuplicateCount            int
	ReceivedFragmentCount          int
	MulticastReceivedFrameCount    int
	FCSErrorCount                  int
	TKIPLocalMICFailures           int
	TKIPICVErrorCount              int
	TKIPCounterMeasuresInvoked     int
	TKIPReplays                    int
	CCMPFormatErrors               int
	CCMPReplays                    int
	CCMPDecryptErrors              int
	FourWayHandshakeFailures       int
	WEPUndecryptableCount          int
	WEPICVErrorCount               int
	DecryptSuccessCount            int
	DecryptFailureCount            int
}

type NDIS_802_11_KEY struct {
	Length      int
	KeyIndex    int
	KeyLength   int
	BSSID       int
	KeyRSC      int
	KeyMaterial int
}

type NDIS_802_11_REMOVE_KEY struct {
	Length   int
	KeyIndex int
	BSSID    int
}

type NDIS_802_11_WEP struct {
	Length      int
	KeyIndex    int
	KeyLength   int
	KeyMaterial int
}

type NDIS_802_11_SSID struct {
	SsidLength int
	Ssid       int
}

type NDIS_WLAN_BSSID struct {
	Length             int
	MacAddress         int
	Reserved           int
	Ssid               int
	Privacy            int
	Rssi               int
	NetworkTypeInUse   int
	Configuration      int
	InfrastructureMode int
	SupportedRates     int
}

type NDIS_802_11_BSSID_LIST struct {
	NumberOfItems int
	Bssid         int
}

type NDIS_WLAN_BSSID_EX struct {
	Length             int
	MacAddress         int
	Reserved           int
	Ssid               int
	Privacy            int
	Rssi               int
	NetworkTypeInUse   int
	Configuration      int
	InfrastructureMode int
	SupportedRates     int
	IELength           int
	IEs                int
}

type NDIS_802_11_BSSID_LIST_EX struct {
	NumberOfItems int
	Bssid         int
}

type NDIS_802_11_FIXED_IEs struct {
	Timestamp      int
	BeaconInterval int
	Capabilities   int
}

type NDIS_802_11_VARIABLE_IEs struct {
	ElementID int
	Length    int
	DATA      int
}

type NDIS_802_11_AI_REQFI struct {
	Capabilities     int
	ListenInterval   int
	CurrentAPAddress int
}

type NDIS_802_11_AI_RESFI struct {
	Capabilities  int
	StatusCode    int
	AssociationId int
}

type NDIS_802_11_ASSOCIATION_INFORMATION struct {
	Length                    int
	AvailableRequestFixedIEs  int
	RequestFixedIEs           int
	RequestIELength           int
	OffsetRequestIEs          int
	AvailableResponseFixedIEs int
	ResponseFixedIEs          int
	ResponseIELength          int
	OffsetResponseIEs         int
}

type NDIS_802_11_AUTHENTICATION_EVENT struct {
	Status  int
	Request int
}

type NDIS_802_11_TEST struct {
	Length    int
	Type      int
	Anonymous int
}

type BSSID_INFO struct {
	BSSID int
	PMKID int
}

type NDIS_802_11_PMKID struct {
	Length         int
	BSSIDInfoCount int
	BSSIDInfo      int
}

type NDIS_802_11_AUTHENTICATION_ENCRYPTION struct {
	AuthModeSupported      int
	EncryptStatusSupported int
}

type NDIS_802_11_CAPABILITY struct {
	Length                            int
	Version                           int
	NoOfPMKIDs                        int
	NoOfAuthEncryptPairsSupported     int
	AuthenticationEncryptionSupported int
}

type NDIS_802_11_NON_BCAST_SSID_LIST struct {
	NumberOfItems  int
	Non_Bcast_Ssid int
}

type NDIS_CO_DEVICE_PROFILE struct {
	DeviceDescription           int
	DevSpecificInfo             int
	ULTAPISUPPLEMENTARYPASSTHRU int
	ULADDRESSMODES              int
	ULNUMADDRESSES              int
	ULBEARERMODES               int
	ULMAXTXRATE                 int
	ULMINTXRATE                 int
	ULMAXRXRATE                 int
	ULMINRXRATE                 int
	ULMEDIAMODES                int
	ULGENERATETONEMODES         int
	ULGENERATETONEMAXNUMFREQ    int
	ULGENERATEDIGITMODES        int
	ULMONITORTONEMAXNUMFREQ     int
	ULMONITORTONEMAXNUMENTRIES  int
	ULMONITORDIGITMODES         int
	ULGATHERDIGITSMINTIMEOUT    int
	ULGATHERDIGITSMAXTIMEOUT    int
	ULDEVCAPFLAGS               int
	ULMAXNUMACTIVECALLS         int
	ULANSWERMODE                int
	ULUUIACCEPTSIZE             int
	ULUUIANSWERSIZE             int
	ULUUIMAKECALLSIZE           int
	ULUUIDROPSIZE               int
	ULUUISENDUSERUSERINFOSIZE   int
	ULUUICALLINFOSIZE           int
}

type OFFLOAD_ALGO_INFO struct {
	ALGOIDENTIFIER int
	ALGOKEYLEN     int
	ALGOROUNDS     int
}

type OFFLOAD_SECURITY_ASSOCIATION struct {
	Operation     int
	SPI           int
	IntegrityAlgo int
	ConfAlgo      int
	Reserved      int
}

type OFFLOAD_IPSEC_ADD_SA struct {
	SrcAddr        int
	SrcMask        int
	DestAddr       int
	DestMask       int
	Protocol       int
	SrcPort        int
	DestPort       int
	SrcTunnelAddr  int
	DestTunnelAddr int
	Flags          int
	NumSAs         int
	SecAssoc       int
	OffloadHandle  int
	KeyLen         int
	KeyMat         int
}

type OFFLOAD_IPSEC_DELETE_SA struct {
	OffloadHandle int
}

type OFFLOAD_IPSEC_UDPESP_ENCAPTYPE_ENTRY struct {
	UdpEncapType int
	DstEncapPort int
}

type OFFLOAD_IPSEC_ADD_UDPESP_SA struct {
	SrcAddr                   int
	SrcMask                   int
	DstAddr                   int
	DstMask                   int
	Protocol                  int
	SrcPort                   int
	DstPort                   int
	SrcTunnelAddr             int
	DstTunnelAddr             int
	Flags                     int
	NumSAs                    int
	SecAssoc                  int
	OffloadHandle             int
	EncapTypeEntry            int
	EncapTypeEntryOffldHandle int
	KeyLen                    int
	KeyMat                    int
}

type OFFLOAD_IPSEC_DELETE_UDPESP_SA struct {
	OffloadHandle             int
	EncapTypeEntryOffldHandle int
}

type TRANSPORT_HEADER_OFFSET struct {
	ProtocolType int
	HeaderOffset int
}

type NETWORK_ADDRESS struct {
	AddressLength int
	AddressType   int
	Address       int
}

type NETWORK_ADDRESS_LIST struct {
	AddressCount int
	AddressType  int
	Address      int
}

type NETWORK_ADDRESS_IP struct {
	SIN_PORT int
	IN_ADDR  int
	SIN_ZERO int
}

type NETWORK_ADDRESS_IP6 struct {
	SIN6_PORT     int
	SIN6_FLOWINFO int
	SIN6_ADDR     int
	SIN6_SCOPE_ID int
}

type NETWORK_ADDRESS_IPX struct {
	NetworkAddress int
	NodeAddress    int
	Socket         int
}

type GEN_GET_TIME_CAPS struct {
	Flags          int
	ClockPrecision int
}

type GEN_GET_NETCARD_TIME struct {
	ReadTime int
}

type NDIS_PM_PACKET_PATTERN struct {
	Priority      int
	Reserved      int
	MaskSize      int
	PatternOffset int
	PatternSize   int
	PatternFlags  int
}

type NDIS_PM_WAKE_UP_CAPABILITIES struct {
	MinMagicPacketWakeUp int
	MinPatternWakeUp     int
	MinLinkChangeWakeUp  int
}

type NDIS_PNP_CAPABILITIES struct {
	Flags              int
	WakeUpCapabilities int
}

type NDIS_WAN_PROTOCOL_CAPS struct {
	Flags    int
	Reserved int
}

type NDIS_CO_LINK_SPEED struct {
	Outbound int
	Inbound  int
}

type NDIS_LINK_SPEED struct {
	XmitLinkSpeed int
	RcvLinkSpeed  int
}

type NDIS_GUID struct {
	Guid      int
	Anonymous int
	Size      int
	Flags     int
}

type NDIS_IRDA_PACKET_INFO struct {
	ExtraBOFs         int
	MinTurnAroundTime int
}

type NDIS_LINK_STATE struct {
	Header               int
	MediaConnectState    int
	MediaDuplexState     int
	XmitLinkSpeed        int
	RcvLinkSpeed         int
	PauseFunctions       int
	AutoNegotiationFlags int
}

type NDIS_LINK_PARAMETERS struct {
	Header               int
	MediaDuplexState     int
	XmitLinkSpeed        int
	RcvLinkSpeed         int
	PauseFunctions       int
	AutoNegotiationFlags int
}

type NDIS_OPER_STATE struct {
	Header                 int
	OperationalStatus      int
	OperationalStatusFlags int
}

type NDIS_IP_OPER_STATUS struct {
	AddressFamily          int
	OperationalStatus      int
	OperationalStatusFlags int
}

type NDIS_IP_OPER_STATUS_INFO struct {
	Header                          int
	Flags                           int
	NumberofAddressFamiliesReturned int
	IpOperationalStatus             int
}

type NDIS_IP_OPER_STATE struct {
	Header              int
	Flags               int
	IpOperationalStatus int
}

type NDIS_OFFLOAD_PARAMETERS struct {
	Header            int
	IPv4Checksum      int
	TCPIPv4Checksum   int
	UDPIPv4Checksum   int
	TCPIPv6Checksum   int
	UDPIPv6Checksum   int
	LsoV1             int
	IPsecV1           int
	LsoV2IPv4         int
	LsoV2IPv6         int
	TcpConnectionIPv4 int
	TcpConnectionIPv6 int
	Flags             int
}

type NDIS_TCP_LARGE_SEND_OFFLOAD_V1 struct {
	IPv4 int
}

type NDIS_TCP_IP_CHECKSUM_OFFLOAD struct {
	IPv4Transmit int
	IPv4Receive  int
	IPv6Transmit int
	IPv6Receive  int
}

type NDIS_IPSEC_OFFLOAD_V1 struct {
	Supported int
	IPv4AH    int
	IPv4ESP   int
}

type NDIS_TCP_LARGE_SEND_OFFLOAD_V2 struct {
	IPv4 int
	IPv6 int
}

type NDIS_OFFLOAD struct {
	Header   int
	Checksum int
	LsoV1    int
	IPsecV1  int
	LsoV2    int
	Flags    int
}

type NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V1 struct {
	IPv4 int
}

type NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD struct {
	IPv4Transmit int
	IPv4Receive  int
	IPv6Transmit int
	IPv6Receive  int
}

type NDIS_WMI_IPSEC_OFFLOAD_V1 struct {
	Supported int
	IPv4AH    int
	IPv4ESP   int
}

type NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V2 struct {
	IPv4 int
	IPv6 int
}

type NDIS_WMI_OFFLOAD struct {
	Header   int
	Checksum int
	LsoV1    int
	IPsecV1  int
	LsoV2    int
	Flags    int
}

type NDIS_TCP_CONNECTION_OFFLOAD struct {
	Header                       int
	Encapsulation                int
	BITFIELD                     int
	TcpConnectionOffloadCapacity int
	Flags                        int
}

type NDIS_WMI_TCP_CONNECTION_OFFLOAD struct {
	Header                       int
	Encapsulation                int
	SupportIPv4                  int
	SupportIPv6                  int
	SupportIPv6ExtensionHeaders  int
	SupportSack                  int
	TcpConnectionOffloadCapacity int
	Flags                        int
}

type NDIS_PORT_AUTHENTICATION_PARAMETERS struct {
	Header                 int
	SendControlState       int
	RcvControlState        int
	SendAuthorizationState int
	RcvAuthorizationState  int
}

type NDIS_WMI_METHOD_HEADER struct {
	Header     int
	PortNumber int
	NetLuid    int
	RequestId  int
	Timeout    int
	Padding    int
}

type NDIS_WMI_SET_HEADER struct {
	Header     int
	PortNumber int
	NetLuid    int
	RequestId  int
	Timeout    int
	Padding    int
}

type NDIS_WMI_EVENT_HEADER struct {
	Header           int
	IfIndex          int
	NetLuid          int
	RequestId        int
	PortNumber       int
	DeviceNameLength int
	DeviceNameOffset int
	Padding          int
}

type NDIS_WMI_ENUM_ADAPTER struct {
	Header           int
	IfIndex          int
	NetLuid          int
	DeviceNameLength int
	DeviceName       int
}

type NDIS_WMI_OUTPUT_INFO struct {
	Header            int
	Flags             int
	SupportedRevision int
	DataOffset        int
}

type NDIS_RECEIVE_SCALE_CAPABILITIES struct {
	Header                    int
	CapabilitiesFlags         int
	NumberOfInterruptMessages int
	NumberOfReceiveQueues     int
}

type NDIS_RECEIVE_SCALE_PARAMETERS struct {
	Header                 int
	Flags                  int
	BaseCpuNumber          int
	HashInformation        int
	IndirectionTableSize   int
	IndirectionTableOffset int
	HashSecretKeySize      int
	HashSecretKeyOffset    int
}

type NDIS_RECEIVE_HASH_PARAMETERS struct {
	Header              int
	Flags               int
	HashInformation     int
	HashSecretKeySize   int
	HashSecretKeyOffset int
}

type NDIS_PORT_STATE struct {
	Header                 int
	MediaConnectState      int
	XmitLinkSpeed          int
	RcvLinkSpeed           int
	Direction              int
	SendControlState       int
	RcvControlState        int
	SendAuthorizationState int
	RcvAuthorizationState  int
	Flags                  int
}

type NDIS_PORT_CHARACTERISTICS struct {
	Header                 int
	PortNumber             int
	Flags                  int
	Type                   int
	MediaConnectState      int
	XmitLinkSpeed          int
	RcvLinkSpeed           int
	Direction              int
	SendControlState       int
	RcvControlState        int
	SendAuthorizationState int
	RcvAuthorizationState  int
}

type NDIS_PORT struct {
	Next                int
	NdisReserved        int
	MiniportReserved    int
	ProtocolReserved    int
	PortCharacteristics int
}

type NDIS_PORT_ARRAY struct {
	Header          int
	NumberOfPorts   int
	OffsetFirstPort int
	ElementSize     int
	Ports           int
}

type NDIS_TIMESTAMP_CAPABILITY_FLAGS struct {
	PtpV2OverUdpIPv4EventMsgReceiveHw  int
	PtpV2OverUdpIPv4AllMsgReceiveHw    int
	PtpV2OverUdpIPv4EventMsgTransmitHw int
	PtpV2OverUdpIPv4AllMsgTransmitHw   int
	PtpV2OverUdpIPv6EventMsgReceiveHw  int
	PtpV2OverUdpIPv6AllMsgReceiveHw    int
	PtpV2OverUdpIPv6EventMsgTransmitHw int
	PtpV2OverUdpIPv6AllMsgTransmitHw   int
	AllReceiveHw                       int
	AllTransmitHw                      int
	TaggedTransmitHw                   int
	AllReceiveSw                       int
	AllTransmitSw                      int
	TaggedTransmitSw                   int
}

type NDIS_TIMESTAMP_CAPABILITIES struct {
	Header                   int
	HardwareClockFrequencyHz int
	CrossTimestamp           int
	Reserved1                int
	Reserved2                int
	TimestampFlags           int
}

type NDIS_HARDWARE_CROSSTIMESTAMP struct {
	Header                 int
	Flags                  int
	SystemTimestamp1       int
	HardwareClockTimestamp int
	SystemTimestamp2       int
}

type DOT11_BSSID_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	BSSIDs             int
}

type DOT11_RATE_SET struct {
	URATESETLENGTH int
	UCRATESET      int
}

type DOT11_WFD_SESSION_INFO struct {
	USESSIONINFOLENGTH int
	UCSESSIONINFO      int
}

type DOT11_OFFLOAD_CAPABILITY struct {
	URESERVED                int
	UFLAGS                   int
	USUPPORTEDWEPALGORITHMS  int
	UNUMOFREPLAYWINDOWS      int
	UMAXWEPKEYMAPPINGLENGTH  int
	USUPPORTEDAUTHALGORITHMS int
	UMAXAUTHKEYMAPPINGLENGTH int
}

type DOT11_CURRENT_OFFLOAD_CAPABILITY struct {
	URESERVED int
	UFLAGS    int
}

type DOT11_IV48_COUNTER struct {
	UIV32COUNTER  int
	USIV16COUNTER int
}

type DOT11_WEP_OFFLOAD struct {
	URESERVED         int
	HOFFLOADCONTEXT   int
	HOFFLOAD          int
	DOT11OFFLOADTYPE  int
	DWALGORITHM       int
	BROWISOUTBOUND    int
	BUSEDEFAULT       int
	UFLAGS            int
	UCMACADDRESS      int
	UNUMOFRWSONPEER   int
	UNUMOFRWSONME     int
	DOT11IV48COUNTERS int
	USDOT11RWBITMAPS  int
	USKEYLENGTH       int
	UCKEY             int
}

type DOT11_WEP_UPLOAD struct {
	URESERVED         int
	DOT11OFFLOADTYPE  int
	HOFFLOAD          int
	UNUMOFRWSUSED     int
	DOT11IV48COUNTERS int
	USDOT11RWBITMAPS  int
}

type DOT11_DEFAULT_WEP_OFFLOAD struct {
	URESERVED         int
	HOFFLOADCONTEXT   int
	HOFFLOAD          int
	DWINDEX           int
	DOT11OFFLOADTYPE  int
	DWALGORITHM       int
	UFLAGS            int
	DOT11KEYDIRECTION int
	UCMACADDRESS      int
	UNUMOFRWSONME     int
	DOT11IV48COUNTERS int
	USDOT11RWBITMAPS  int
	USKEYLENGTH       int
	UCKEY             int
}

type DOT11_DEFAULT_WEP_UPLOAD struct {
	URESERVED         int
	DOT11OFFLOADTYPE  int
	HOFFLOAD          int
	UNUMOFRWSUSED     int
	DOT11IV48COUNTERS int
	USDOT11RWBITMAPS  int
}

type DOT11_OPERATION_MODE_CAPABILITY struct {
	URESERVED         int
	UMAJORVERSION     int
	UMINORVERSION     int
	UNUMOFTXBUFFERS   int
	UNUMOFRXBUFFERS   int
	UOPMODECAPABILITY int
}

type DOT11_CURRENT_OPERATION_MODE struct {
	URESERVED      int
	UCURRENTOPMODE int
}

type DOT11_SCAN_REQUEST struct {
	DOT11BSSTYPE      int
	DOT11BSSID        int
	DOT11SSID         int
	DOT11SCANTYPE     int
	BRESTRICTEDSCAN   int
	BUSEREQUESTIE     int
	UREQUESTIDSOFFSET int
	UNUMOFREQUESTIDS  int
	UPHYTYPESOFFSET   int
	UNUMOFPHYTYPES    int
	UIESOFFSET        int
	UIESLENGTH        int
	UCBUFFER          int
}

type DOT11_PHY_TYPE_INFO struct {
	DOT11PHYTYPE        int
	BUSEPARAMETERS      int
	UPROBEDELAY         int
	UMINCHANNELTIME     int
	UMAXCHANNELTIME     int
	ChDescriptionType   int
	UCHANNELLISTSIZE    int
	UCCHANNELLISTBUFFER int
}

type DOT11_SCAN_REQUEST_V2 struct {
	DOT11BSSTYPE        int
	DOT11BSSID          int
	DOT11SCANTYPE       int
	BRESTRICTEDSCAN     int
	UDOT11SSIDSOFFSET   int
	UNUMOFDOT11SSIDS    int
	BUSEREQUESTIE       int
	UREQUESTIDSOFFSET   int
	UNUMOFREQUESTIDS    int
	UPHYTYPEINFOSOFFSET int
	UNUMOFPHYTYPEINFOS  int
	UIESOFFSET          int
	UIESLENGTH          int
	UCBUFFER            int
}

type DOT11_PHY_TYPE_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	DOT11PHYTYPE       int
}

type DOT11_BSS_DESCRIPTION struct {
	URESERVED               int
	DOT11BSSID              int
	DOT11BSSTYPE            int
	USBEACONPERIOD          int
	ULLTIMESTAMP            int
	USCAPABILITYINFORMATION int
	UBUFFERLENGTH           int
	UCBUFFER                int
}

type DOT11_JOIN_REQUEST struct {
	UJOINFAILURETIMEOUT int
	OperationalRateSet  int
	UCHCENTERFREQUENCY  int
	DOT11BSSDESCRIPTION int
}

type DOT11_START_REQUEST struct {
	USTARTFAILURETIMEOUT int
	OperationalRateSet   int
	UCHCENTERFREQUENCY   int
	DOT11BSSDESCRIPTION  int
}

type DOT11_UPDATE_IE struct {
	DOT11UPDATEIEOP int
	UBUFFERLENGTH   int
	UCBUFFER        int
}

type DOT11_RESET_REQUEST struct {
	DOT11RESETTYPE  int
	DOT11MACADDRESS int
	BSETDEFAULTMIB  int
}

type DOT11_OPTIONAL_CAPABILITY struct {
	URESERVED                    int
	BDOT11PCF                    int
	BDOT11PCFMPDUTRANSFERTOPC    int
	BSTRICTLYORDEREDSERVICECLASS int
}

type DOT11_CURRENT_OPTIONAL_CAPABILITY struct {
	URESERVED                    int
	BDOT11CFPOLLABLE             int
	BDOT11PCF                    int
	BDOT11PCFMPDUTRANSFERTOPC    int
	BSTRICTLYORDEREDSERVICECLASS int
}

type DOT11_POWER_MGMT_MODE struct {
	DOT11POWERMODE   int
	UPOWERSAVELEVEL  int
	USLISTENINTERVAL int
	USAID            int
	BRECEIVEDTIMS    int
}

type DOT11_COUNTERS_ENTRY struct {
	UTRANSMITTEDFRAGMENTCOUNT       int
	UMULTICASTTRANSMITTEDFRAMECOUNT int
	UFAILEDCOUNT                    int
	URETRYCOUNT                     int
	UMULTIPLERETRYCOUNT             int
	UFRAMEDUPLICATECOUNT            int
	URTSSUCCESSCOUNT                int
	URTSFAILURECOUNT                int
	UACKFAILURECOUNT                int
	URECEIVEDFRAGMENTCOUNT          int
	UMULTICASTRECEIVEDFRAMECOUNT    int
	UFCSERRORCOUNT                  int
	UTRANSMITTEDFRAMECOUNT          int
}

type DOT11_SUPPORTED_PHY_TYPES struct {
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	DOT11PHYTYPE       int
}

type DOT11_SUPPORTED_POWER_LEVELS struct {
	UNUMOFSUPPORTEDPOWERLEVELS int
	UTXPOWERLEVELVALUES        int
}

type DOT11_REG_DOMAIN_VALUE struct {
	UREGDOMAINSSUPPORTINDEX int
	UREGDOMAINSSUPPORTVALUE int
}

type DOT11_REG_DOMAINS_SUPPORT_VALUE struct {
	UNUMOFENTRIES       int
	UTOTALNUMOFENTRIES  int
	DOT11REGDOMAINVALUE int
}

type DOT11_SUPPORTED_ANTENNA struct {
	UANTENNALISTINDEX int
	BSUPPORTEDANTENNA int
}

type DOT11_SUPPORTED_ANTENNA_LIST struct {
	UNUMOFENTRIES         int
	UTOTALNUMOFENTRIES    int
	DOT11SUPPORTEDANTENNA int
}

type DOT11_DIVERSITY_SELECTION_RX struct {
	UANTENNALISTINDEX     int
	BDIVERSITYSELECTIONRX int
}

type DOT11_DIVERSITY_SELECTION_RX_LIST struct {
	UNUMOFENTRIES             int
	UTOTALNUMOFENTRIES        int
	DOT11DIVERSITYSELECTIONRX int
}

type DOT11_SUPPORTED_DATA_RATES_VALUE struct {
	UCSUPPORTEDTXDATARATESVALUE int
	UCSUPPORTEDRXDATARATESVALUE int
}

type DOT11_SUPPORTED_DATA_RATES_VALUE_V2 struct {
	UCSUPPORTEDTXDATARATESVALUE int
	UCSUPPORTEDRXDATARATESVALUE int
}

type DOT11_MULTI_DOMAIN_CAPABILITY_ENTRY struct {
	UMULTIDOMAINCAPABILITYINDEX int
	UFIRSTCHANNELNUMBER         int
	UNUMBEROFCHANNELS           int
	LMAXIMUMTRANSMITPOWERLEVEL  int
}

type DOT11_MD_CAPABILITY_ENTRY_LIST struct {
	UNUMOFENTRIES          int
	UTOTALNUMOFENTRIES     int
	DOT11MDCAPABILITYENTRY int
}

type DOT11_HOPPING_PATTERN_ENTRY struct {
	UHOPPINGPATTERNINDEX    int
	URANDOMTABLEFIELDNUMBER int
}

type DOT11_HOPPING_PATTERN_ENTRY_LIST struct {
	UNUMOFENTRIES            int
	UTOTALNUMOFENTRIES       int
	DOT11HOPPINGPATTERNENTRY int
}

type DOT11_WPA_TSC struct {
	URESERVED        int
	DOT11OFFLOADTYPE int
	HOFFLOAD         int
	DOT11IV48COUNTER int
}

type DOT11_RSSI_RANGE struct {
	DOT11PHYTYPE int
	URSSIMIN     int
	URSSIMAX     int
}

type DOT11_NIC_SPECIFIC_EXTENSION struct {
	UBUFFERLENGTH      int
	UTOTALBUFFERLENGTH int
	UCBUFFER           int
}

type DOT11_AP_JOIN_REQUEST struct {
	UJOINFAILURETIMEOUT int
	OperationalRateSet  int
	UCHCENTERFREQUENCY  int
	DOT11BSSDESCRIPTION int
}

type DOT11_RECV_SENSITIVITY struct {
	UCDATARATE int
	LRSSIMIN   int
	LRSSIMAX   int
}

type DOT11_RECV_SENSITIVITY_LIST struct {
	Anonymous            int
	UNUMOFENTRIES        int
	UTOTALNUMOFENTRIES   int
	DOT11RECVSENSITIVITY int
}

type DOT11_WME_AC_PARAMETERS struct {
	UCACCESSCATEGORYINDEX int
	UCAIFSN               int
	UCECWMIN              int
	UCECWMAX              int
	USTXOPLIMIT           int
}

type DOT11_WME_AC_PARAMTERS_LIST struct {
	UNUMOFENTRIES        int
	UTOTALNUMOFENTRIES   int
	DOT11WMEACPARAMETERS int
}

type DOT11_WME_UPDATE_IE struct {
	UPARAMELEMMINBEACONINTERVALS int
	UWMEINFOELEMOFFSET           int
	UWMEINFOELEMLENGTH           int
	UWMEPARAMELEMOFFSET          int
	UWMEPARAMELEMLENGTH          int
	UCBUFFER                     int
}

type DOT11_QOS_TX_DURATION struct {
	UNOMINALMSDUSIZE int
	UMINPHYRATE      int
	UDURATION        int
}

type DOT11_QOS_TX_MEDIUM_TIME struct {
	DOT11PEERADDRESS   int
	UCQOSPRIORITY      int
	UMEDIUMTIMEADMITED int
}

type DOT11_SUPPORTED_OFDM_FREQUENCY struct {
	UCENTERFREQUENCY int
}

type DOT11_SUPPORTED_OFDM_FREQUENCY_LIST struct {
	UNUMOFENTRIES               int
	UTOTALNUMOFENTRIES          int
	DOT11SUPPORTEDOFDMFREQUENCY int
}

type DOT11_SUPPORTED_DSSS_CHANNEL struct {
	UCHANNEL int
}

type DOT11_SUPPORTED_DSSS_CHANNEL_LIST struct {
	UNUMOFENTRIES             int
	UTOTALNUMOFENTRIES        int
	DOT11SUPPORTEDDSSSCHANNEL int
}

type DOT11_BYTE_ARRAY struct {
	Header           int
	UNUMOFBYTES      int
	UTOTALNUMOFBYTES int
	UCBUFFER         int
}

type DOT11_BSS_ENTRY_PHY_SPECIFIC_INFO struct {
	UCHCENTERFREQUENCY int
	FHSS               int
}

type DOT11_BSS_ENTRY struct {
	UPHYID                  int
	PhySpecificInfo         int
	DOT11BSSID              int
	DOT11BSSTYPE            int
	LRSSI                   int
	ULINKQUALITY            int
	BINREGDOMAIN            int
	USBEACONPERIOD          int
	ULLTIMESTAMP            int
	ULLHOSTTIMESTAMP        int
	USCAPABILITYINFORMATION int
	UBUFFERLENGTH           int
	UCBUFFER                int
}

type DOT11_SSID_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	SSIDs              int
}

type DOT11_MAC_ADDRESS_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	MacAddrs           int
}

type DOT11_PMKID_ENTRY struct {
	BSSID  int
	PMKID  int
	UFLAGS int
}

type DOT11_PMKID_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	PMKIDs             int
}

type DOT11_PHY_FRAME_STATISTICS struct {
	ULLTRANSMITTEDFRAMECOUNT            int
	ULLMULTICASTTRANSMITTEDFRAMECOUNT   int
	ULLFAILEDCOUNT                      int
	ULLRETRYCOUNT                       int
	ULLMULTIPLERETRYCOUNT               int
	ULLMAXTXLIFETIMEEXCEEDEDCOUNT       int
	ULLTRANSMITTEDFRAGMENTCOUNT         int
	ULLRTSSUCCESSCOUNT                  int
	ULLRTSFAILURECOUNT                  int
	ULLACKFAILURECOUNT                  int
	ULLRECEIVEDFRAMECOUNT               int
	ULLMULTICASTRECEIVEDFRAMECOUNT      int
	ULLPROMISCUOUSRECEIVEDFRAMECOUNT    int
	ULLMAXRXLIFETIMEEXCEEDEDCOUNT       int
	ULLFRAMEDUPLICATECOUNT              int
	ULLRECEIVEDFRAGMENTCOUNT            int
	ULLPROMISCUOUSRECEIVEDFRAGMENTCOUNT int
	ULLFCSERRORCOUNT                    int
}

type DOT11_MAC_FRAME_STATISTICS struct {
	ULLTRANSMITTEDFRAMECOUNT        int
	ULLRECEIVEDFRAMECOUNT           int
	ULLTRANSMITTEDFAILUREFRAMECOUNT int
	ULLRECEIVEDFAILUREFRAMECOUNT    int
	ULLWEPEXCLUDEDCOUNT             int
	ULLTKIPLOCALMICFAILURES         int
	ULLTKIPREPLAYS                  int
	ULLTKIPICVERRORCOUNT            int
	ULLCCMPREPLAYS                  int
	ULLCCMPDECRYPTERRORS            int
	ULLWEPUNDECRYPTABLECOUNT        int
	ULLWEPICVERRORCOUNT             int
	ULLDECRYPTSUCCESSCOUNT          int
	ULLDECRYPTFAILURECOUNT          int
}

type DOT11_STATISTICS struct {
	Header                        int
	ULLFOURWAYHANDSHAKEFAILURES   int
	ULLTKIPCOUNTERMEASURESINVOKED int
	ULLRESERVED                   int
	MacUcastCounters              int
	MacMcastCounters              int
	PhyCounters                   int
}

type DOT11_PRIVACY_EXEMPTION struct {
	USETHERTYPE           int
	USEXEMPTIONACTIONTYPE int
	USEXEMPTIONPACKETTYPE int
}

type DOT11_PRIVACY_EXEMPTION_LIST struct {
	Header                  int
	UNUMOFENTRIES           int
	UTOTALNUMOFENTRIES      int
	PrivacyExemptionEntries int
}

type DOT11_AUTH_ALGORITHM_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	AlgorithmIds       int
}

type DOT11_AUTH_CIPHER_PAIR_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	AuthCipherPairs    int
}

type DOT11_CIPHER_ALGORITHM_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	AlgorithmIds       int
}

type DOT11_CIPHER_DEFAULT_KEY_VALUE struct {
	Header      int
	UKEYINDEX   int
	AlgorithmId int
	MacAddr     int
	BDELETE     int
	BSTATIC     int
	USKEYLENGTH int
	UCKEY       int
}

type DOT11_KEY_ALGO_TKIP_MIC struct {
	UCIV48COUNTER   int
	ULTKIPKEYLENGTH int
	ULMICKEYLENGTH  int
	UCTKIPMICKEYS   int
}

type DOT11_KEY_ALGO_CCMP struct {
	UCIV48COUNTER   int
	ULCCMPKEYLENGTH int
	UCCCMPKEY       int
}

type DOT11_KEY_ALGO_GCMP struct {
	UCIV48COUNTER   int
	ULGCMPKEYLENGTH int
	UCGCMPKEY       int
}

type DOT11_KEY_ALGO_GCMP_256 struct {
	UCIV48COUNTER      int
	ULGCMP256KEYLENGTH int
	UCGCMP256KEY       int
}

type DOT11_KEY_ALGO_BIP struct {
	UCIPN          int
	ULBIPKEYLENGTH int
	UCBIPKEY       int
}

type DOT11_KEY_ALGO_BIP_GMAC_256 struct {
	UCIPN                 int
	ULBIPGMAC256KEYLENGTH int
	UCBIPGMAC256KEY       int
}

type DOT11_CIPHER_KEY_MAPPING_KEY_VALUE struct {
	PeerMacAddr int
	AlgorithmId int
	Direction   int
	BDELETE     int
	BSTATIC     int
	USKEYLENGTH int
	UCKEY       int
}

type DOT11_ASSOCIATION_INFO_EX struct {
	PeerMacAddress            int
	BSSID                     int
	USCAPABILITYINFORMATION   int
	USLISTENINTERVAL          int
	UCPEERSUPPORTEDRATES      int
	USASSOCIATIONID           int
	DOT11ASSOCIATIONSTATE     int
	DOT11POWERMODE            int
	LIASSOCIATIONUPTIME       int
	ULLNUMOFTXPACKETSUCCESSES int
	ULLNUMOFTXPACKETFAILURES  int
	ULLNUMOFRXPACKETSUCCESSES int
	ULLNUMOFRXPACKETFAILURES  int
}

type DOT11_ASSOCIATION_INFO_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	DOT11ASSOCINFO     int
}

type DOT11_PHY_ID_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	DOT11PHYID         int
}

type DOT11_EXTSTA_CAPABILITY struct {
	Header                        int
	USCANSSIDLISTSIZE             int
	UDESIREDBSSIDLISTSIZE         int
	UDESIREDSSIDLISTSIZE          int
	UEXCLUDEDMACADDRESSLISTSIZE   int
	UPRIVACYEXEMPTIONLISTSIZE     int
	UKEYMAPPINGTABLESIZE          int
	UDEFAULTKEYTABLESIZE          int
	UWEPKEYVALUEMAXLENGTH         int
	UPMKIDCACHESIZE               int
	UMAXNUMPERSTADEFAULTKEYTABLES int
}

type DOT11_DATA_RATE_MAPPING_ENTRY struct {
	UCDATARATEINDEX int
	UCDATARATEFLAG  int
	USDATARATEVALUE int
}

type DOT11_DATA_RATE_MAPPING_TABLE struct {
	Header                 int
	UDATARATEMAPPINGLENGTH int
	DataRateMappingEntries int
}

type DOT11_COUNTRY_OR_REGION_STRING_LIST struct {
	Header                 int
	UNUMOFENTRIES          int
	UTOTALNUMOFENTRIES     int
	CountryOrRegionStrings int
}

type DOT11_PORT_STATE_NOTIFICATION struct {
	Header  int
	PeerMac int
	BOPEN   int
}

type DOT11_IBSS_PARAMS struct {
	Header     int
	BJOINONLY  int
	UIESOFFSET int
	UIESLENGTH int
}

type DOT11_QOS_PARAMS struct {
	Header                    int
	UCENABLEDQOSPROTOCOLFLAGS int
}

type DOT11_ASSOCIATION_PARAMS struct {
	Header                 int
	BSSID                  int
	UASSOCREQUESTIESOFFSET int
	UASSOCREQUESTIESLENGTH int
}

type DOT11_FRAGMENT_DESCRIPTOR struct {
	UOFFSET int
	ULENGTH int
}

type DOT11_PER_MSDU_COUNTERS struct {
	UTRANSMITTEDFRAGMENTCOUNT int
	URETRYCOUNT               int
	URTSSUCCESSCOUNT          int
	URTSFAILURECOUNT          int
	UACKFAILURECOUNT          int
}

type DOT11_HRDSSS_PHY_ATTRIBUTES struct {
	BSHORTPREAMBLEOPTIONIMPLEMENTED int
	BPBCCOPTIONIMPLEMENTED          int
	BCHANNELAGILITYPRESENT          int
	UHRCCAMODESUPPORTED             int
}

type DOT11_OFDM_PHY_ATTRIBUTES struct {
	UFREQUENCYBANDSSUPPORTED int
}

type DOT11_ERP_PHY_ATTRIBUTES struct {
	HRDSSSAttributes                int
	BERPPBCCOPTIONIMPLEMENTED       int
	BDSSSOFDMOPTIONIMPLEMENTED      int
	BSHORTSLOTTIMEOPTIONIMPLEMENTED int
}

type DOT11_PHY_ATTRIBUTES struct {
	Header                      int
	PhyType                     int
	BHARDWAREPHYSTATE           int
	BSOFTWAREPHYSTATE           int
	BCFPOLLABLE                 int
	UMPDUMAXLENGTH              int
	TempType                    int
	DiversitySupport            int
	PhySpecificAttributes       int
	UNUMBERSUPPORTEDPOWERLEVELS int
	TxPowerLevels               int
	UNUMDATARATEMAPPINGENTRIES  int
	DataRateMappingEntries      int
	SupportedDataRatesValue     int
}

type DOT11_EXTSTA_ATTRIBUTES struct {
	Header                                  int
	USCANSSIDLISTSIZE                       int
	UDESIREDBSSIDLISTSIZE                   int
	UDESIREDSSIDLISTSIZE                    int
	UEXCLUDEDMACADDRESSLISTSIZE             int
	UPRIVACYEXEMPTIONLISTSIZE               int
	UKEYMAPPINGTABLESIZE                    int
	UDEFAULTKEYTABLESIZE                    int
	UWEPKEYVALUEMAXLENGTH                   int
	UPMKIDCACHESIZE                         int
	UMAXNUMPERSTADEFAULTKEYTABLES           int
	BSTRICTLYORDEREDSERVICECLASSIMPLEMENTED int
	UCSUPPORTEDQOSPROTOCOLFLAGS             int
	BSAFEMODEIMPLEMENTED                    int
	UNUMSUPPORTEDCOUNTRYORREGIONSTRINGS     int
	PSUPPORTEDCOUNTRYORREGIONSTRINGS        int
	UINFRANUMSUPPORTEDUCASTALGOPAIRS        int
	PINFRASUPPORTEDUCASTALGOPAIRS           int
	UINFRANUMSUPPORTEDMCASTALGOPAIRS        int
	PINFRASUPPORTEDMCASTALGOPAIRS           int
	UADHOCNUMSUPPORTEDUCASTALGOPAIRS        int
	PADHOCSUPPORTEDUCASTALGOPAIRS           int
	UADHOCNUMSUPPORTEDMCASTALGOPAIRS        int
	PADHOCSUPPORTEDMCASTALGOPAIRS           int
	BAUTOPOWERSAVEMODE                      int
	UMAXNETWORKOFFLOADLISTSIZE              int
	BMFPCAPABLE                             int
	UINFRANUMSUPPORTEDMCASTMGMTALGOPAIRS    int
	PINFRASUPPORTEDMCASTMGMTALGOPAIRS       int
	BNEIGHBORREPORTSUPPORTED                int
	BAPCHANNELREPORTSUPPORTED               int
	BACTIONFRAMESSUPPORTED                  int
	BANQPQUERYOFFLOADSUPPORTED              int
	BHESSIDCONNECTIONSUPPORTED              int
}

type DOT11_RECV_EXTENSION_INFO struct {
	UVERSION                int
	PVRESERVED              int
	DOT11PHYTYPE            int
	UCHCENTERFREQUENCY      int
	LRSSI                   int
	LRSSIMIN                int
	LRSSIMAX                int
	URSSI                   int
	UCPRIORITY              int
	UCDATARATE              int
	UCPEERMACADDRESS        int
	DWEXTENDEDSTATUS        int
	HWEPOFFLOADCONTEXT      int
	HAUTHOFFLOADCONTEXT     int
	USWEPAPPLIEDMASK        int
	USWPAMSDUPRIORITY       int
	DOT11LOWESTIV48COUNTER  int
	USDOT11LEFTRWBITMAP     int
	DOT11HIGHESTIV48COUNTER int
	USDOT11RIGHTRWBITMAP    int
	USNUMBEROFMPDUSRECEIVED int
	USNUMBEROFFRAGMENTS     int
	PNDISPACKETS            int
}

type DOT11_RECV_EXTENSION_INFO_V2 struct {
	UVERSION                int
	PVRESERVED              int
	DOT11PHYTYPE            int
	UCHCENTERFREQUENCY      int
	LRSSI                   int
	URSSI                   int
	UCPRIORITY              int
	UCDATARATE              int
	UCPEERMACADDRESS        int
	DWEXTENDEDSTATUS        int
	HWEPOFFLOADCONTEXT      int
	HAUTHOFFLOADCONTEXT     int
	USWEPAPPLIEDMASK        int
	USWPAMSDUPRIORITY       int
	DOT11LOWESTIV48COUNTER  int
	USDOT11LEFTRWBITMAP     int
	DOT11HIGHESTIV48COUNTER int
	USDOT11RIGHTRWBITMAP    int
	USNUMBEROFMPDUSRECEIVED int
	USNUMBEROFFRAGMENTS     int
	PNDISPACKETS            int
}

type DOT11_STATUS_INDICATION struct {
	USTATUSTYPE int
	NDISSTATUS  int
}

type DOT11_MPDU_MAX_LENGTH_INDICATION struct {
	Header         int
	UPHYID         int
	UMPDUMAXLENGTH int
}

type DOT11_ASSOCIATION_START_PARAMETERS struct {
	Header         int
	MacAddr        int
	SSID           int
	UIHVDATAOFFSET int
	UIHVDATASIZE   int
}

type DOT11_ENCAP_ENTRY struct {
	USETHERTYPE int
	USENCAPTYPE int
}

type DOT11_ASSOCIATION_COMPLETION_PARAMETERS struct {
	Header                int
	MacAddr               int
	USTATUS               int
	BREASSOCREQ           int
	BREASSOCRESP          int
	UASSOCREQOFFSET       int
	UASSOCREQSIZE         int
	UASSOCRESPOFFSET      int
	UASSOCRESPSIZE        int
	UBEACONOFFSET         int
	UBEACONSIZE           int
	UIHVDATAOFFSET        int
	UIHVDATASIZE          int
	AuthAlgo              int
	UnicastCipher         int
	MulticastCipher       int
	UACTIVEPHYLISTOFFSET  int
	UACTIVEPHYLISTSIZE    int
	BFOURADDRESSSUPPORTED int
	BPORTAUTHORIZED       int
	UCACTIVEQOSPROTOCOL   int
	DSInfo                int
	UENCAPTABLEOFFSET     int
	UENCAPTABLESIZE       int
	MulticastMgmtCipher   int
	UASSOCCOMEBACKTIME    int
}

type DOT11_CONNECTION_START_PARAMETERS struct {
	Header     int
	BSSType    int
	AdhocBSSID int
	AdhocSSID  int
}

type DOT11_CONNECTION_COMPLETION_PARAMETERS struct {
	Header  int
	USTATUS int
}

type DOT11_ROAMING_START_PARAMETERS struct {
	Header         int
	AdhocBSSID     int
	AdhocSSID      int
	UROAMINGREASON int
}

type DOT11_ROAMING_COMPLETION_PARAMETERS struct {
	Header  int
	USTATUS int
}

type DOT11_DISASSOCIATION_PARAMETERS struct {
	Header         int
	MacAddr        int
	UREASON        int
	UIHVDATAOFFSET int
	UIHVDATASIZE   int
}

type DOT11_TKIPMIC_FAILURE_PARAMETERS struct {
	Header             int
	BDEFAULTKEYFAILURE int
	UKEYINDEX          int
	PeerMac            int
}

type DOT11_PMKID_CANDIDATE_LIST_PARAMETERS struct {
	Header               int
	UCANDIDATELISTSIZE   int
	UCANDIDATELISTOFFSET int
}

type DOT11_BSSID_CANDIDATE struct {
	BSSID  int
	UFLAGS int
}

type DOT11_PHY_STATE_PARAMETERS struct {
	Header            int
	UPHYID            int
	BHARDWAREPHYSTATE int
	BSOFTWAREPHYSTATE int
}

type DOT11_LINK_QUALITY_ENTRY struct {
	PeerMacAddr   int
	UCLINKQUALITY int
}

type DOT11_LINK_QUALITY_PARAMETERS struct {
	Header                 int
	ULINKQUALITYLISTSIZE   int
	ULINKQUALITYLISTOFFSET int
}

type DOT11_EXTSTA_SEND_CONTEXT struct {
	Header                int
	USEXEMPTIONACTIONTYPE int
	UPHYID                int
	UDELAYEDSLEEPVALUE    int
	PVMEDIASPECIFICINFO   int
	USENDFLAGS            int
}

type DOT11_EXTSTA_RECV_CONTEXT struct {
	Header                  int
	URECEIVEFLAGS           int
	UPHYID                  int
	UCHCENTERFREQUENCY      int
	USNUMBEROFMPDUSRECEIVED int
	LRSSI                   int
	UCDATARATE              int
	USIZEMEDIASPECIFICINFO  int
	PVMEDIASPECIFICINFO     int
	ULLTIMESTAMP            int
}

type DOT11_EXTAP_ATTRIBUTES struct {
	Header                                  int
	USCANSSIDLISTSIZE                       int
	UDESIREDSSIDLISTSIZE                    int
	UPRIVACYEXEMPTIONLISTSIZE               int
	UASSOCIATIONTABLESIZE                   int
	UDEFAULTKEYTABLESIZE                    int
	UWEPKEYVALUEMAXLENGTH                   int
	BSTRICTLYORDEREDSERVICECLASSIMPLEMENTED int
	UNUMSUPPORTEDCOUNTRYORREGIONSTRINGS     int
	PSUPPORTEDCOUNTRYORREGIONSTRINGS        int
	UINFRANUMSUPPORTEDUCASTALGOPAIRS        int
	PINFRASUPPORTEDUCASTALGOPAIRS           int
	UINFRANUMSUPPORTEDMCASTALGOPAIRS        int
	PINFRASUPPORTEDMCASTALGOPAIRS           int
}

type DOT11_INCOMING_ASSOC_STARTED_PARAMETERS struct {
	Header      int
	PeerMacAddr int
}

type DOT11_INCOMING_ASSOC_REQUEST_RECEIVED_PARAMETERS struct {
	Header          int
	PeerMacAddr     int
	BREASSOCREQ     int
	UASSOCREQOFFSET int
	UASSOCREQSIZE   int
}

type DOT11_INCOMING_ASSOC_COMPLETION_PARAMETERS struct {
	Header               int
	PeerMacAddr          int
	USTATUS              int
	UCERRORSOURCE        int
	BREASSOCREQ          int
	BREASSOCRESP         int
	UASSOCREQOFFSET      int
	UASSOCREQSIZE        int
	UASSOCRESPOFFSET     int
	UASSOCRESPSIZE       int
	AuthAlgo             int
	UnicastCipher        int
	MulticastCipher      int
	UACTIVEPHYLISTOFFSET int
	UACTIVEPHYLISTSIZE   int
	UBEACONOFFSET        int
	UBEACONSIZE          int
}

type DOT11_STOP_AP_PARAMETERS struct {
	Header   int
	ULREASON int
}

type DOT11_PHY_FREQUENCY_ADOPTED_PARAMETERS struct {
	Header    int
	ULPHYID   int
	Anonymous int
}

type DOT11_CAN_SUSTAIN_AP_PARAMETERS struct {
	Header   int
	ULREASON int
}

type DOT11_AVAILABLE_CHANNEL_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	UCHANNELNUMBER     int
}

type DOT11_AVAILABLE_FREQUENCY_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	UFREQUENCYVALUE    int
}

type DOT11_DISASSOCIATE_PEER_REQUEST struct {
	Header      int
	PeerMacAddr int
	USREASON    int
}

type DOT11_INCOMING_ASSOC_DECISION struct {
	Header                  int
	PeerMacAddr             int
	BACCEPT                 int
	USREASONCODE            int
	UASSOCRESPONSEIESOFFSET int
	UASSOCRESPONSEIESLENGTH int
}

type DOT11_INCOMING_ASSOC_DECISION_V2 struct {
	Header                  int
	PeerMacAddr             int
	BACCEPT                 int
	USREASONCODE            int
	UASSOCRESPONSEIESOFFSET int
	UASSOCRESPONSEIESLENGTH int
	WFDStatus               int
}

type DOT11_ADDITIONAL_IE struct {
	Header             int
	UBEACONIESOFFSET   int
	UBEACONIESLENGTH   int
	URESPONSEIESOFFSET int
	URESPONSEIESLENGTH int
}

type DOT11_PEER_STATISTICS struct {
	ULLDECRYPTSUCCESSCOUNT  int
	ULLDECRYPTFAILURECOUNT  int
	ULLTXPACKETSUCCESSCOUNT int
	ULLTXPACKETFAILURECOUNT int
	ULLRXPACKETSUCCESSCOUNT int
	ULLRXPACKETFAILURECOUNT int
}

type DOT11_PEER_INFO struct {
	MacAddress              int
	USCAPABILITYINFORMATION int
	AuthAlgo                int
	UnicastCipherAlgo       int
	MulticastCipherAlgo     int
	BWPSENABLED             int
	USLISTENINTERVAL        int
	UCSUPPORTEDRATES        int
	USASSOCIATIONID         int
	AssociationState        int
	PowerMode               int
	LIASSOCIATIONUPTIME     int
	Statistics              int
}

type DOT11_PEER_INFO_LIST struct {
	Header             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	PeerInfo           int
}

type DOT11_VWIFI_COMBINATION struct {
	Header             int
	UNUMINFRASTRUCTURE int
	UNUMADHOC          int
	UNUMSOFTAP         int
}

type DOT11_VWIFI_COMBINATION_V2 struct {
	Header             int
	UNUMINFRASTRUCTURE int
	UNUMADHOC          int
	UNUMSOFTAP         int
	UNUMVIRTUALSTATION int
}

type DOT11_VWIFI_COMBINATION_V3 struct {
	Header             int
	UNUMINFRASTRUCTURE int
	UNUMADHOC          int
	UNUMSOFTAP         int
	UNUMVIRTUALSTATION int
	UNUMWFDGROUP       int
}

type DOT11_VWIFI_ATTRIBUTES struct {
	Header             int
	UTOTALNUMOFENTRIES int
	Combinations       int
}

type DOT11_MAC_PARAMETERS struct {
	Header      int
	UOPMODEMASK int
}

type DOT11_MAC_INFO struct {
	URESERVED       int
	UNDISPORTNUMBER int
	MacAddr         int
}

type DOT11_WFD_ATTRIBUTES struct {
	Header                              int
	UNUMCONCURRENTGOROLE                int
	UNUMCONCURRENTCLIENTROLE            int
	WPSVersionsSupported                int
	BSERVICEDISCOVERYSUPPORTED          int
	BCLIENTDISCOVERABILITYSUPPORTED     int
	BINFRASTRUCTUREMANAGEMENTSUPPORTED  int
	UMAXSECONDARYDEVICETYPELISTSIZE     int
	DeviceAddress                       int
	UINTERFACEADDRESSLISTCOUNT          int
	PINTERFACEADDRESSLIST               int
	UNUMSUPPORTEDCOUNTRYORREGIONSTRINGS int
	PSUPPORTEDCOUNTRYORREGIONSTRINGS    int
	UDISCOVERYFILTERLISTSIZE            int
	UGOROLECLIENTTABLESIZE              int
}

type DOT11_WFD_DEVICE_TYPE struct {
	CategoryID    int
	SubCategoryID int
	OUI           int
}

type DOT11_WPS_DEVICE_NAME struct {
	UDEVICENAMELENGTH int
	UCDEVICENAME      int
}

type DOT11_WFD_CONFIGURATION_TIMEOUT struct {
	GOTimeout     int
	ClientTimeout int
}

type DOT11_WFD_GROUP_ID struct {
	DeviceAddress int
	SSID          int
}

type DOT11_WFD_GO_INTENT struct {
	BITFIELD int
}

type DOT11_WFD_CHANNEL struct {
	CountryRegionString int
	OperatingClass      int
	ChannelNumber       int
}

type WFDSVC_CONNECTION_CAPABILITY struct {
	BNEW    int
	BCLIENT int
	BGO     int
}

type DOT11_WFD_SERVICE_HASH_LIST struct {
	ServiceHashCount int
	ServiceHash      int
}

type DOT11_WFD_ADVERTISEMENT_ID struct {
	AdvertisementID int
	ServiceAddress  int
}

type DOT11_WFD_SESSION_ID struct {
	SessionID      int
	SessionAddress int
}

type DOT11_WFD_ADVERTISED_SERVICE_DESCRIPTOR struct {
	AdvertisementID   int
	ConfigMethods     int
	ServiceNameLength int
	ServiceName       int
}

type DOT11_WFD_ADVERTISED_SERVICE_LIST struct {
	ServiceCount      int
	AdvertisedService int
}

type DOT11_WFD_DISCOVER_COMPLETE_PARAMETERS struct {
	Header             int
	Status             int
	UNUMOFENTRIES      int
	UTOTALNUMOFENTRIES int
	ULISTOFFSET        int
	ULISTLENGTH        int
}

type DOT11_GO_NEGOTIATION_REQUEST_SEND_COMPLETE_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	DialogToken       int
	Status            int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_RECEIVED_GO_NEGOTIATION_REQUEST_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	DialogToken       int
	RequestContext    int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_GO_NEGOTIATION_RESPONSE_SEND_COMPLETE_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	DialogToken       int
	Status            int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_RECEIVED_GO_NEGOTIATION_RESPONSE_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	DialogToken       int
	ResponseContext   int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_GO_NEGOTIATION_CONFIRMATION_SEND_COMPLETE_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	DialogToken       int
	Status            int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_RECEIVED_GO_NEGOTIATION_CONFIRMATION_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	DialogToken       int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_INVITATION_REQUEST_SEND_COMPLETE_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	ReceiverAddress   int
	DialogToken       int
	Status            int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_RECEIVED_INVITATION_REQUEST_PARAMETERS struct {
	Header                   int
	TransmitterDeviceAddress int
	BSSID                    int
	DialogToken              int
	RequestContext           int
	UIESOFFSET               int
	UIESLENGTH               int
}

type DOT11_INVITATION_RESPONSE_SEND_COMPLETE_PARAMETERS struct {
	Header                int
	ReceiverDeviceAddress int
	DialogToken           int
	Status                int
	UIESOFFSET            int
	UIESLENGTH            int
}

type DOT11_RECEIVED_INVITATION_RESPONSE_PARAMETERS struct {
	Header                   int
	TransmitterDeviceAddress int
	BSSID                    int
	DialogToken              int
	UIESOFFSET               int
	UIESLENGTH               int
}

type DOT11_PROVISION_DISCOVERY_REQUEST_SEND_COMPLETE_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	ReceiverAddress   int
	DialogToken       int
	Status            int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_RECEIVED_PROVISION_DISCOVERY_REQUEST_PARAMETERS struct {
	Header                   int
	TransmitterDeviceAddress int
	BSSID                    int
	DialogToken              int
	RequestContext           int
	UIESOFFSET               int
	UIESLENGTH               int
}

type DOT11_PROVISION_DISCOVERY_RESPONSE_SEND_COMPLETE_PARAMETERS struct {
	Header                int
	ReceiverDeviceAddress int
	DialogToken           int
	Status                int
	UIESOFFSET            int
	UIESLENGTH            int
}

type DOT11_RECEIVED_PROVISION_DISCOVERY_RESPONSE_PARAMETERS struct {
	Header                   int
	TransmitterDeviceAddress int
	BSSID                    int
	DialogToken              int
	UIESOFFSET               int
	UIESLENGTH               int
}

type DOT11_ANQP_QUERY_COMPLETE_PARAMETERS struct {
	Header          int
	Status          int
	HCONTEXT        int
	URESPONSELENGTH int
}

type DOT11_WFD_DEVICE_CAPABILITY_CONFIG struct {
	Header                           int
	BSERVICEDISCOVERYENABLED         int
	BCLIENTDISCOVERABILITYENABLED    int
	BCONCURRENTOPERATIONSUPPORTED    int
	BINFRASTRUCTUREMANAGEMENTENABLED int
	BDEVICELIMITREACHED              int
	BINVITATIONPROCEDUREENABLED      int
	WPSVersionsEnabled               int
}

type DOT11_WFD_GROUP_OWNER_CAPABILITY_CONFIG struct {
	Header                         int
	BPERSISTENTGROUPENABLED        int
	BINTRABSSDISTRIBUTIONSUPPORTED int
	BCROSSCONNECTIONSUPPORTED      int
	BPERSISTENTRECONNECTSUPPORTED  int
	BGROUPFORMATIONENABLED         int
	UMAXIMUMGROUPLIMIT             int
}

type DOT11_WFD_GROUP_OWNER_CAPABILITY_CONFIG_V2 struct {
	Header                                int
	BPERSISTENTGROUPENABLED               int
	BINTRABSSDISTRIBUTIONSUPPORTED        int
	BCROSSCONNECTIONSUPPORTED             int
	BPERSISTENTRECONNECTSUPPORTED         int
	BGROUPFORMATIONENABLED                int
	UMAXIMUMGROUPLIMIT                    int
	BEAPOLKEYIPADDRESSALLOCATIONSUPPORTED int
}

type DOT11_WFD_DEVICE_INFO struct {
	Header            int
	DeviceAddress     int
	ConfigMethods     int
	PrimaryDeviceType int
	DeviceName        int
}

type DOT11_WFD_SECONDARY_DEVICE_TYPE_LIST struct {
	Header               int
	UNUMOFENTRIES        int
	UTOTALNUMOFENTRIES   int
	SecondaryDeviceTypes int
}

type DOT11_WFD_DISCOVER_DEVICE_FILTER struct {
	DeviceID  int
	UCBITMASK int
	GroupSSID int
}

type DOT11_WFD_DISCOVER_REQUEST struct {
	Header                   int
	DiscoverType             int
	ScanType                 int
	UDISCOVERTIMEOUT         int
	UDEVICEFILTERLISTOFFSET  int
	UNUMDEVICEFILTERS        int
	UIESOFFSET               int
	UIESLENGTH               int
	BFORCESCANLEGACYNETWORKS int
}

type DOT11_WFD_DEVICE_ENTRY struct {
	UPHYID                        int
	PhySpecificInfo               int
	DOT11BSSID                    int
	DOT11BSSTYPE                  int
	TransmitterAddress            int
	LRSSI                         int
	ULINKQUALITY                  int
	USBEACONPERIOD                int
	ULLTIMESTAMP                  int
	ULLBEACONHOSTTIMESTAMP        int
	ULLPROBERESPONSEHOSTTIMESTAMP int
	USCAPABILITYINFORMATION       int
	UBEACONIESOFFSET              int
	UBEACONIESLENGTH              int
	UPROBERESPONSEIESOFFSET       int
	UPROBERESPONSEIESLENGTH       int
}

type DOT11_WFD_ADDITIONAL_IE struct {
	Header                   int
	UBEACONIESOFFSET         int
	UBEACONIESLENGTH         int
	UPROBERESPONSEIESOFFSET  int
	UPROBERESPONSEIESLENGTH  int
	UDEFAULTREQUESTIESOFFSET int
	UDEFAULTREQUESTIESLENGTH int
}

type DOT11_SEND_GO_NEGOTIATION_REQUEST_PARAMETERS struct {
	Header                   int
	PeerDeviceAddress        int
	DialogToken              int
	USENDTIMEOUT             int
	GroupOwnerIntent         int
	MinimumConfigTimeout     int
	IntendedInterfaceAddress int
	GroupCapability          int
	UIESOFFSET               int
	UIESLENGTH               int
}

type DOT11_SEND_GO_NEGOTIATION_RESPONSE_PARAMETERS struct {
	Header                   int
	PeerDeviceAddress        int
	DialogToken              int
	RequestContext           int
	USENDTIMEOUT             int
	Status                   int
	GroupOwnerIntent         int
	MinimumConfigTimeout     int
	IntendedInterfaceAddress int
	GroupCapability          int
	GroupID                  int
	BUSEGROUPID              int
	UIESOFFSET               int
	UIESLENGTH               int
}

type DOT11_SEND_GO_NEGOTIATION_CONFIRMATION_PARAMETERS struct {
	Header            int
	PeerDeviceAddress int
	DialogToken       int
	ResponseContext   int
	USENDTIMEOUT      int
	Status            int
	GroupCapability   int
	GroupID           int
	BUSEGROUPID       int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_WFD_INVITATION_FLAGS struct {
	BITFIELD int
}

type DOT11_SEND_INVITATION_REQUEST_PARAMETERS struct {
	Header                        int
	DialogToken                   int
	PeerDeviceAddress             int
	USENDTIMEOUT                  int
	MinimumConfigTimeout          int
	InvitationFlags               int
	GroupBSSID                    int
	BUSEGROUPBSSID                int
	OperatingChannel              int
	BUSESPECIFIEDOPERATINGCHANNEL int
	GroupID                       int
	BLOCALGO                      int
	UIESOFFSET                    int
	UIESLENGTH                    int
}

type DOT11_SEND_INVITATION_RESPONSE_PARAMETERS struct {
	Header                        int
	ReceiverDeviceAddress         int
	DialogToken                   int
	RequestContext                int
	USENDTIMEOUT                  int
	Status                        int
	MinimumConfigTimeout          int
	GroupBSSID                    int
	BUSEGROUPBSSID                int
	OperatingChannel              int
	BUSESPECIFIEDOPERATINGCHANNEL int
	UIESOFFSET                    int
	UIESLENGTH                    int
}

type DOT11_SEND_PROVISION_DISCOVERY_REQUEST_PARAMETERS struct {
	Header            int
	DialogToken       int
	PeerDeviceAddress int
	USENDTIMEOUT      int
	GroupCapability   int
	GroupID           int
	BUSEGROUPID       int
	UIESOFFSET        int
	UIESLENGTH        int
}

type DOT11_SEND_PROVISION_DISCOVERY_RESPONSE_PARAMETERS struct {
	Header                int
	ReceiverDeviceAddress int
	DialogToken           int
	RequestContext        int
	USENDTIMEOUT          int
	UIESOFFSET            int
	UIESLENGTH            int
}

type DOT11_WFD_DEVICE_LISTEN_CHANNEL struct {
	Header        int
	ChannelNumber int
}

type DOT11_WFD_GROUP_START_PARAMETERS struct {
	Header                     int
	AdvertisedOperatingChannel int
}

type DOT11_WFD_GROUP_JOIN_PARAMETERS struct {
	Header             int
	GOOperatingChannel int
	GOConfigTime       int
	BINGROUPFORMATION  int
	BWAITFORWPSREADY   int
}

type DOT11_POWER_MGMT_AUTO_MODE_ENABLED_INFO struct {
	Header   int
	BENABLED int
}

type DOT11_POWER_MGMT_MODE_STATUS_INFO struct {
	Header          int
	PowerSaveMode   int
	UPOWERSAVELEVEL int
	Reason          int
}

type DOT11_CHANNEL_HINT struct {
	Dot11PhyType   int
	UCHANNELNUMBER int
}

type DOT11_OFFLOAD_NETWORK struct {
	Ssid              int
	UnicastCipher     int
	AuthAlgo          int
	Dot11ChannelHints int
}

type DOT11_OFFLOAD_NETWORK_LIST_INFO struct {
	Header             int
	ULFLAGS            int
	FastScanPeriod     int
	FastScanIterations int
	SlowScanPeriod     int
	UNUMOFENTRIES      int
	OFFLOADNETWORKLIST int
}

type DOT11_OFFLOAD_NETWORK_STATUS_PARAMETERS struct {
	Header int
	Status int
}

type DOT11_MANUFACTURING_TEST struct {
	DOT11MANUFACTURINGTESTTYPE int
	UBUFFERLENGTH              int
	UCBUFFER                   int
}

type DOT11_MANUFACTURING_SELF_TEST_SET_PARAMS struct {
	SelfTestType  int
	UTESTID       int
	UPINBITMASK   int
	PVCONTEXT     int
	UBUFFERLENGTH int
	UCBUFFERIN    int
}

type DOT11_MANUFACTURING_SELF_TEST_QUERY_RESULTS struct {
	SelfTestType      int
	UTESTID           int
	BRESULT           int
	UPINFAILEDBITMASK int
	PVCONTEXT         int
	UBYTESWRITTENOUT  int
	UCBUFFEROUT       int
}

type DOT11_MANUFACTURING_FUNCTIONAL_TEST_RX struct {
	BENABLED   int
	Dot11Band  int
	UCHANNEL   int
	PowerLevel int
}

type DOT11_MANUFACTURING_FUNCTIONAL_TEST_TX struct {
	BENABLE        int
	BOPENLOOP      int
	Dot11Band      int
	UCHANNEL       int
	USETPOWERLEVEL int
	ADCPowerLevel  int
}

type DOT11_MANUFACTURING_FUNCTIONAL_TEST_QUERY_ADC struct {
	Dot11Band     int
	UCHANNEL      int
	ADCPowerLevel int
}

type DOT11_MANUFACTURING_TEST_SET_DATA_ struct {
	UKEY          int
	UOFFSET       int
	UBUFFERLENGTH int
	UCBUFFERIN    int
}

type DOT11_MANUFACTURING_TEST_QUERY_DATA_ struct {
	UKEY          int
	UOFFSET       int
	UBUFFERLENGTH int
	UBYTESREAD    int
	UCBUFFEROUT   int
}

type DOT11_MANUFACTURING_TEST_SLEEP_ struct {
	USLEEPTIME int
	PVCONTEXT  int
}

type DOT11_MANUFACTURING_CALLBACK_PARAMETERS struct {
	Header                         int
	DOT11MANUFACTURINGCALLBACKTYPE int
	USTATUS                        int
	PVCONTEXT                      int
}

type WLAN_PROFILE_INFO struct {
	STRPROFILENAME int
	DWFLAGS        int
}

type DOT11_NETWORK struct {
	DOT11SSID    int
	DOT11BSSTYPE int
}

type WLAN_RAW_DATA struct {
	DWDATASIZE int
	DataBlob   int
}

type WLAN_RAW_DATA_LIST struct {
	DWTOTALSIZE     int
	DWNUMBEROFITEMS int
	DataList        int
}

type WLAN_RATE_SET struct {
	URATESETLENGTH int
	USRATESET      int
}

type WLAN_AVAILABLE_NETWORK struct {
	STRPROFILENAME              int
	DOT11SSID                   int
	DOT11BSSTYPE                int
	UNUMBEROFBSSIDS             int
	BNETWORKCONNECTABLE         int
	WLANNOTCONNECTABLEREASON    int
	UNUMBEROFPHYTYPES           int
	DOT11PHYTYPES               int
	BMOREPHYTYPES               int
	WLANSIGNALQUALITY           int
	BSECURITYENABLED            int
	DOT11DEFAULTAUTHALGORITHM   int
	DOT11DEFAULTCIPHERALGORITHM int
	DWFLAGS                     int
	DWRESERVED                  int
}

type WLAN_AVAILABLE_NETWORK_V2 struct {
	STRPROFILENAME              int
	DOT11SSID                   int
	DOT11BSSTYPE                int
	UNUMBEROFBSSIDS             int
	BNETWORKCONNECTABLE         int
	WLANNOTCONNECTABLEREASON    int
	UNUMBEROFPHYTYPES           int
	DOT11PHYTYPES               int
	BMOREPHYTYPES               int
	WLANSIGNALQUALITY           int
	BSECURITYENABLED            int
	DOT11DEFAULTAUTHALGORITHM   int
	DOT11DEFAULTCIPHERALGORITHM int
	DWFLAGS                     int
	AccessNetworkOptions        int
	DOT11HESSID                 int
	VenueInfo                   int
	DWRESERVED                  int
}

type WLAN_BSS_ENTRY struct {
	DOT11SSID               int
	UPHYID                  int
	DOT11BSSID              int
	DOT11BSSTYPE            int
	DOT11BSSPHYTYPE         int
	LRSSI                   int
	ULINKQUALITY            int
	BINREGDOMAIN            int
	USBEACONPERIOD          int
	ULLTIMESTAMP            int
	ULLHOSTTIMESTAMP        int
	USCAPABILITYINFORMATION int
	ULCHCENTERFREQUENCY     int
	WLANRATESET             int
	ULIEOFFSET              int
	ULIESIZE                int
}

type WLAN_BSS_LIST struct {
	DWTOTALSIZE     int
	DWNUMBEROFITEMS int
	WLANBSSENTRIES  int
}

type WLAN_INTERFACE_INFO struct {
	InterfaceGuid           int
	STRINTERFACEDESCRIPTION int
	ISSTATE                 int
}

type WLAN_ASSOCIATION_ATTRIBUTES struct {
	DOT11SSID         int
	DOT11BSSTYPE      int
	DOT11BSSID        int
	DOT11PHYTYPE      int
	UDOT11PHYINDEX    int
	WLANSIGNALQUALITY int
	ULRXRATE          int
	ULTXRATE          int
}

type WLAN_SECURITY_ATTRIBUTES struct {
	BSECURITYENABLED     int
	BONEXENABLED         int
	DOT11AUTHALGORITHM   int
	DOT11CIPHERALGORITHM int
}

type WLAN_CONNECTION_ATTRIBUTES struct {
	ISSTATE                   int
	WLANCONNECTIONMODE        int
	STRPROFILENAME            int
	WLANASSOCIATIONATTRIBUTES int
	WLANSECURITYATTRIBUTES    int
}

type WLAN_PHY_RADIO_STATE struct {
	DWPHYINDEX              int
	DOT11SOFTWARERADIOSTATE int
	DOT11HARDWARERADIOSTATE int
}

type WLAN_RADIO_STATE struct {
	DWNUMBEROFPHYS int
	PhyRadioState  int
}

type WLAN_INTERFACE_CAPABILITY struct {
	INTERFACETYPE             int
	BDOT11DSUPPORTED          int
	DWMAXDESIREDSSIDLISTSIZE  int
	DWMAXDESIREDBSSIDLISTSIZE int
	DWNUMBEROFSUPPORTEDPHYS   int
	DOT11PHYTYPES             int
}

type WLAN_AUTH_CIPHER_PAIR_LIST struct {
	DWNUMBEROFITEMS     int
	PAUTHCIPHERPAIRLIST int
}

type WLAN_COUNTRY_OR_REGION_STRING_LIST struct {
	DWNUMBEROFITEMS            int
	PCOUNTRYORREGIONSTRINGLIST int
}

type WLAN_PROFILE_INFO_LIST struct {
	DWNUMBEROFITEMS int
	DWINDEX         int
	ProfileInfo     int
}

type WLAN_AVAILABLE_NETWORK_LIST struct {
	DWNUMBEROFITEMS int
	DWINDEX         int
	Network         int
}

type WLAN_AVAILABLE_NETWORK_LIST_V2 struct {
	DWNUMBEROFITEMS int
	DWINDEX         int
	Network         int
}

type WLAN_INTERFACE_INFO_LIST struct {
	DWNUMBEROFITEMS int
	DWINDEX         int
	InterfaceInfo   int
}

type DOT11_NETWORK_LIST struct {
	DWNUMBEROFITEMS int
	DWINDEX         int
	Network         int
}

type WLAN_CONNECTION_PARAMETERS struct {
	WLANCONNECTIONMODE int
	STRPROFILE         int
	PDOT11SSID         int
	PDESIREDBSSIDLIST  int
	DOT11BSSTYPE       int
	DWFLAGS            int
}

type WLAN_CONNECTION_PARAMETERS_V2 struct {
	WLANCONNECTIONMODE         int
	STRPROFILE                 int
	PDOT11SSID                 int
	PDOT11HESSID               int
	PDESIREDBSSIDLIST          int
	DOT11BSSTYPE               int
	DWFLAGS                    int
	PDOT11ACCESSNETWORKOPTIONS int
}

type WLAN_MSM_NOTIFICATION_DATA struct {
	WLANCONNECTIONMODE int
	STRPROFILENAME     int
	DOT11SSID          int
	DOT11BSSTYPE       int
	DOT11MACADDR       int
	BSECURITYENABLED   int
	BFIRSTPEER         int
	BLASTPEER          int
	WLANREASONCODE     int
}

type WLAN_CONNECTION_NOTIFICATION_DATA struct {
	WLANCONNECTIONMODE int
	STRPROFILENAME     int
	DOT11SSID          int
	DOT11BSSTYPE       int
	BSECURITYENABLED   int
	WLANREASONCODE     int
	DWFLAGS            int
	STRPROFILEXML      int
}

type WLAN_DEVICE_SERVICE_NOTIFICATION_DATA struct {
	DeviceService int
	DWOPCODE      int
	DWDATASIZE    int
	DataBlob      int
}

type WLAN_PHY_FRAME_STATISTICS struct {
	ULLTRANSMITTEDFRAMECOUNT            int
	ULLMULTICASTTRANSMITTEDFRAMECOUNT   int
	ULLFAILEDCOUNT                      int
	ULLRETRYCOUNT                       int
	ULLMULTIPLERETRYCOUNT               int
	ULLMAXTXLIFETIMEEXCEEDEDCOUNT       int
	ULLTRANSMITTEDFRAGMENTCOUNT         int
	ULLRTSSUCCESSCOUNT                  int
	ULLRTSFAILURECOUNT                  int
	ULLACKFAILURECOUNT                  int
	ULLRECEIVEDFRAMECOUNT               int
	ULLMULTICASTRECEIVEDFRAMECOUNT      int
	ULLPROMISCUOUSRECEIVEDFRAMECOUNT    int
	ULLMAXRXLIFETIMEEXCEEDEDCOUNT       int
	ULLFRAMEDUPLICATECOUNT              int
	ULLRECEIVEDFRAGMENTCOUNT            int
	ULLPROMISCUOUSRECEIVEDFRAGMENTCOUNT int
	ULLFCSERRORCOUNT                    int
}

type WLAN_MAC_FRAME_STATISTICS struct {
	ULLTRANSMITTEDFRAMECOUNT int
	ULLRECEIVEDFRAMECOUNT    int
	ULLWEPEXCLUDEDCOUNT      int
	ULLTKIPLOCALMICFAILURES  int
	ULLTKIPREPLAYS           int
	ULLTKIPICVERRORCOUNT     int
	ULLCCMPREPLAYS           int
	ULLCCMPDECRYPTERRORS     int
	ULLWEPUNDECRYPTABLECOUNT int
	ULLWEPICVERRORCOUNT      int
	ULLDECRYPTSUCCESSCOUNT   int
	ULLDECRYPTFAILURECOUNT   int
}

type WLAN_STATISTICS struct {
	ULLFOURWAYHANDSHAKEFAILURES   int
	ULLTKIPCOUNTERMEASURESINVOKED int
	ULLRESERVED                   int
	MacUcastCounters              int
	MacMcastCounters              int
	DWNUMBEROFPHYS                int
	PhyCounters                   int
}

type WLAN_DEVICE_SERVICE_GUID_LIST struct {
	DWNUMBEROFITEMS int
	DWINDEX         int
	DeviceService   int
}

type WFD_GROUP_ID struct {
	DeviceAddress int
	GroupSSID     int
}

type WLAN_HOSTED_NETWORK_PEER_STATE struct {
	PeerMacAddress int
	PeerAuthState  int
}

type WLAN_HOSTED_NETWORK_RADIO_STATE struct {
	DOT11SOFTWARERADIOSTATE int
	DOT11HARDWARERADIOSTATE int
}

type WLAN_HOSTED_NETWORK_STATE_CHANGE_ struct {
	OldState          int
	NewState          int
	StateChangeReason int
}

type WLAN_HOSTED_NETWORK_DATA_PEER_STATE_CHANGE struct {
	OldState              int
	NewState              int
	PeerStateChangeReason int
}

type WLAN_HOSTED_NETWORK_CONNECTION_SETTINGS struct {
	HOSTEDNETWORKSSID  int
	DWMAXNUMBEROFPEERS int
}

type WLAN_HOSTED_NETWORK_SECURITY_SETTINGS struct {
	DOT11AUTHALGO   int
	DOT11CIPHERALGO int
}

type WLAN_HOSTED_NETWORK_STATUS struct {
	HostedNetworkState     int
	IPDeviceID             int
	WLANHOSTEDNETWORKBSSID int
	DOT11PHYTYPE           int
	ULCHANNELFREQUENCY     int
	DWNUMBEROFPEERS        int
	PeerList               int
}

type ONEX_VARIABLE_BLOB struct {
	DWSIZE   int
	DWOFFSET int
}

type ONEX_AUTH_PARAMS struct {
	FUPDATEPENDING    int
	ONEXCONNPROFILE   int
	AUTHIDENTITY      int
	DWQUARANTINESTATE int
	BITFIELD          int
	DWSESSIONID       int
	HUSERTOKEN        int
	OneXUserProfile   int
	Identity          int
	UserName          int
	Domain            int
}

type ONEX_EAP_ERROR struct {
	DWWINERROR      int
	TYPE            int
	DWREASONCODE    int
	ROOTCAUSEGUID   int
	REPAIRGUID      int
	HELPLINKGUID    int
	BITFIELD        int
	RootCauseString int
	RepairString    int
}

type ONEX_STATUS struct {
	AUTHSTATUS int
	DWREASON   int
	DWERROR    int
}

type ONEX_RESULT_UPDATE_DATA struct {
	ONEXSTATUS      int
	BackendSupport  int
	FBACKENDENGAGED int
	BITFIELD        int
	AUTHPARAMS      int
	EAPERROR        int
}

type ONEX_USER_INFO struct {
	AUTHIDENTITY int
	BITFIELD     int
	UserName     int
	DomainName   int
}

type Dot11AdHocManager struct {
}
