// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowsribbon implements the Windows.Win32.WindowsRibbon namespace.
package windowsribbon

type UIRibbonFramework struct {
}

type UIRibbonImageFromBitmapFactory struct {
}

type UI_EVENTPARAMS_COMMAND struct {
	CommandID         int
	CommandName       int
	ParentCommandID   int
	ParentCommandName int
	SelectionIndex    int
	Location          int
}

type UI_EVENTPARAMS struct {
	EventType int
	Anonymous int
}
