// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package hid implements the Windows.Win32.Hid namespace.
package hid

type HIDP_REPORT_TYPE int32

const (
	HidP_Input = 0
	HidP_Output = 1
	HidP_Feature = 2
)

type HIDP_KEYBOARD_DIRECTION int32

const (
	HidP_Keyboard_Break = 0
	HidP_Keyboard_Make = 1
)

