// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package monitor implements the Windows.Win32.Monitor namespace.
package monitor

type PHYSICAL_MONITOR struct {
	HPHYSICALMONITOR             int
	SZPHYSICALMONITORDESCRIPTION int
}

type MC_TIMING_REPORT struct {
	DWHORIZONTALFREQUENCYINHZ int
	DWVERTICALFREQUENCYINHZ   int
	BTIMINGSTATUSBYTE         int
}
