// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowsnetworking implements the Windows.Win32.WindowsNetworking namespace.
package windowsnetworking

type NetEnumHandle struct {
	Value int
}

type CONNECTDLGSTRUCTA struct {
	CBSTRUCTURE int
	HWNDOWNER   int
	LPCONNRES   int
	DWFLAGS     int
	DWDEVNUM    int
}

type CONNECTDLGSTRUCTW struct {
	CBSTRUCTURE int
	HWNDOWNER   int
	LPCONNRES   int
	DWFLAGS     int
	DWDEVNUM    int
}

type DISCDLGSTRUCTA struct {
	CBSTRUCTURE  int
	HWNDOWNER    int
	LPLOCALNAME  int
	LPREMOTENAME int
	DWFLAGS      int
}

type DISCDLGSTRUCTW struct {
	CBSTRUCTURE  int
	HWNDOWNER    int
	LPLOCALNAME  int
	LPREMOTENAME int
	DWFLAGS      int
}

type NETINFOSTRUCT struct {
	CBSTRUCTURE       int
	DWPROVIDERVERSION int
	DWSTATUS          int
	DWCHARACTERISTICS int
	DWHANDLE          int
	WNETTYPE          int
	DWPRINTERS        int
	DWDRIVES          int
}
