// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package policy implements the Windows.Win32.Policy namespace.
package policy

type CriticalPolicySectionHandle struct {
	Value int
}

type GROUP_POLICY_OBJECTA struct {
	DWOPTIONS     int
	DWVERSION     int
	LPDSPATH      int
	LPFILESYSPATH int
	LPDISPLAYNAME int
	SZGPONAME     int
	GPOLink       int
	LPARAM        int
	PNEXT         int
	PPREV         int
	LPEXTENSIONS  int
	LPARAM2       int
	LPLINK        int
}

type GROUP_POLICY_OBJECTW struct {
	DWOPTIONS     int
	DWVERSION     int
	LPDSPATH      int
	LPFILESYSPATH int
	LPDISPLAYNAME int
	SZGPONAME     int
	GPOLink       int
	LPARAM        int
	PNEXT         int
	PPREV         int
	LPEXTENSIONS  int
	LPARAM2       int
	LPLINK        int
}

type RSOP_TARGET struct {
	PWSZACCOUNTNAME   int
	PWSZNEWSOM        int
	PSASECURITYGROUPS int
	PRSOPTOKEN        int
	PGPOLIST          int
	PWBEMSERVICES     int
}

type POLICYSETTINGSTATUSINFO struct {
	SZKEY          int
	SZEVENTSOURCE  int
	SZEVENTLOGNAME int
	DWEVENTID      int
	DWERRORCODE    int
	STATUS         int
	TIMELOGGED     int
}

type INSTALLSPEC struct {
	AppName  int
	FileExt  int
	ProgId   int
	COMClass int
}

type INSTALLDATA struct {
	Type int
	Spec int
}

type LOCALMANAGEDAPPLICATION struct {
	PSZDEPLOYMENTNAME int
	PSZPOLICYNAME     int
	PSZPRODUCTID      int
	DWSTATE           int
}

type MANAGEDAPPLICATION struct {
	PSZPACKAGENAME int
	PSZPUBLISHER   int
	DWVERSIONHI    int
	DWVERSIONLO    int
	DWREVISION     int
	GpoId          int
	PSZPOLICYNAME  int
	ProductId      int
	Language       int
	PSZOWNER       int
	PSZCOMPANY     int
	PSZCOMMENTS    int
	PSZCONTACT     int
	PSZSUPPORTURL  int
	DWPATHTYPE     int
	BINSTALLED     int
}

type GPOBROWSEINFO struct {
	DWSIZE       int
	DWFLAGS      int
	HWNDOWNER    int
	LPTITLE      int
	LPINITIALOU  int
	LPDSPATH     int
	DWDSPATHSIZE int
	LPNAME       int
	DWNAMESIZE   int
	GPOTYPE      int
	GPOHINT      int
}
