// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowsdeploymentservices implements the Windows.Win32.WindowsDeploymentServices namespace.
package windowsdeploymentservices

type WDS_CLI_IMAGE_TYPE int32

const (
	WDS_CLI_IMAGE_TYPE_UNKNOWN = 0
	WDS_CLI_IMAGE_TYPE_WIM = 1
	WDS_CLI_IMAGE_TYPE_VHD = 2
	WDS_CLI_IMAGE_TYPE_VHDX = 3
)

type WDS_CLI_FIRMWARE_TYPE int32

const (
	WDS_CLI_FIRMWARE_UNKNOWN = 0
	WDS_CLI_FIRMWARE_BIOS = 1
	WDS_CLI_FIRMWARE_EFI = 2
)

type WDS_CLI_IMAGE_PARAM_TYPE int32

const (
	WDS_CLI_IMAGE_PARAM_UNKNOWN = 0
	WDS_CLI_IMAGE_PARAM_SPARSE_FILE = 1
	WDS_CLI_IMAGE_PARAM_SUPPORTED_FIRMWARES = 2
)

type TRANSPORTPROVIDER_CALLBACK_ID int32

const (
	WDS_TRANSPORTPROVIDER_CREATE_INSTANCE = 0
	WDS_TRANSPORTPROVIDER_COMPARE_CONTENT = 1
	WDS_TRANSPORTPROVIDER_OPEN_CONTENT = 2
	WDS_TRANSPORTPROVIDER_USER_ACCESS_CHECK = 3
	WDS_TRANSPORTPROVIDER_GET_CONTENT_SIZE = 4
	WDS_TRANSPORTPROVIDER_READ_CONTENT = 5
	WDS_TRANSPORTPROVIDER_CLOSE_CONTENT = 6
	WDS_TRANSPORTPROVIDER_CLOSE_INSTANCE = 7
	WDS_TRANSPORTPROVIDER_SHUTDOWN = 8
	WDS_TRANSPORTPROVIDER_DUMP_STATE = 9
	WDS_TRANSPORTPROVIDER_REFRESH_SETTINGS = 10
	WDS_TRANSPORTPROVIDER_GET_CONTENT_METADATA = 11
	WDS_TRANSPORTPROVIDER_MAX_CALLBACKS = 12
)

type TRANSPORTCLIENT_CALLBACK_ID int32

const (
	WDS_TRANSPORTCLIENT_SESSION_START = 0
	WDS_TRANSPORTCLIENT_RECEIVE_CONTENTS = 1
	WDS_TRANSPORTCLIENT_SESSION_COMPLETE = 2
	WDS_TRANSPORTCLIENT_RECEIVE_METADATA = 3
	WDS_TRANSPORTCLIENT_SESSION_STARTEX = 4
	WDS_TRANSPORTCLIENT_SESSION_NEGOTIATE = 5
	WDS_TRANSPORTCLIENT_MAX_CALLBACKS = 6
)

type WDSTRANSPORT_FEATURE_FLAGS int32

const (
	WdsTptFeatureAdminPack = 1
	WdsTptFeatureTransportServer = 2
	WdsTptFeatureDeploymentServer = 4
)

type WDSTRANSPORT_PROTOCOL_FLAGS int32

const (
	WdsTptProtocolUnicast = 1
	WdsTptProtocolMulticast = 2
)

type WDSTRANSPORT_NAMESPACE_TYPE int32

const (
	WdsTptNamespaceTypeUnknown = 0
	WdsTptNamespaceTypeAutoCast = 1
	WdsTptNamespaceTypeScheduledCastManualStart = 2
	WdsTptNamespaceTypeScheduledCastAutoStart = 3
)

type WDSTRANSPORT_DISCONNECT_TYPE int32

const (
	WdsTptDisconnectUnknown = 0
	WdsTptDisconnectFallback = 1
	WdsTptDisconnectAbort = 2
)

type WDSTRANSPORT_SERVICE_NOTIFICATION int32

const (
	WdsTptServiceNotifyUnknown = 0
	WdsTptServiceNotifyReadSettings = 1
)

type WDSTRANSPORT_IP_ADDRESS_TYPE int32

const (
	WdsTptIpAddressUnknown = 0
	WdsTptIpAddressIpv4 = 1
	WdsTptIpAddressIpv6 = 2
)

type WDSTRANSPORT_IP_ADDRESS_SOURCE_TYPE int32

const (
	WdsTptIpAddressSourceUnknown = 0
	WdsTptIpAddressSourceDhcp = 1
	WdsTptIpAddressSourceRange = 2
)

type WDSTRANSPORT_NETWORK_PROFILE_TYPE int32

const (
	WdsTptNetworkProfileUnknown = 0
	WdsTptNetworkProfileCustom = 1
	WdsTptNetworkProfile10Mbps = 2
	WdsTptNetworkProfile100Mbps = 3
	WdsTptNetworkProfile1Gbps = 4
)

type WDSTRANSPORT_DIAGNOSTICS_COMPONENT_FLAGS int32

const (
	WdsTptDiagnosticsComponentPxe = 1
	WdsTptDiagnosticsComponentTftp = 2
	WdsTptDiagnosticsComponentImageServer = 4
	WdsTptDiagnosticsComponentMulticast = 8
)

type WDSTRANSPORT_SLOW_CLIENT_HANDLING_TYPE int32

const (
	WdsTptSlowClientHandlingUnknown = 0
	WdsTptSlowClientHandlingNone = 1
	WdsTptSlowClientHandlingAutoDisconnect = 2
	WdsTptSlowClientHandlingMultistream = 3
)

type WDSTRANSPORT_UDP_PORT_POLICY int32

const (
	WdsTptUdpPortPolicyDynamic = 0
	WdsTptUdpPortPolicyFixed = 1
)

type WDSTRANSPORT_TFTP_CAPABILITY int32

const (
	WdsTptTftpCapMaximumBlockSize = 1
	WdsTptTftpCapVariableWindow = 2
)

