// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package multimedia implements the Windows.Win32.Multimedia namespace.
package multimedia

type HMIDI struct {
	Value int
}

type HMIDIIN struct {
	Value int
}

type HMIDIOUT struct {
	Value int
}

type HMIDISTRM struct {
	Value int
}

type HMIXER struct {
	Value int
}

type HMIXEROBJ struct {
	Value int
}

type HWAVEIN struct {
	Value int
}

type HWAVEOUT struct {
	Value int
}

type MMTIME struct {
	WTYPE int
	U     int
}

type HDRVR__ struct {
	UNUSED int
}

type DRVCONFIGINFOEX struct {
	DWDCISIZE          int
	LPSZDCISECTIONNAME int
	LPSZDCIALIASNAME   int
	DNDEVNODE          int
}

type DRVCONFIGINFO struct {
	DWDCISIZE          int
	LPSZDCISECTIONNAME int
	LPSZDCIALIASNAME   int
}

type HMMIO__ struct {
	UNUSED int
}

type MMIOINFO struct {
	DWFLAGS     int
	FCCIOPROC   int
	PIOPROC     int
	WERRORRET   int
	HTASK       int
	CCHBUFFER   int
	PCHBUFFER   int
	PCHNEXT     int
	PCHENDREAD  int
	PCHENDWRITE int
	LBUFOFFSET  int
	LDISKOFFSET int
	ADWINFO     int
	DWRESERVED1 int
	DWRESERVED2 int
	HMMIO       int
}

type MMCKINFO struct {
	CKID         int
	CKSIZE       int
	FCCTYPE      int
	DWDATAOFFSET int
	DWFLAGS      int
}

type WAVEHDR struct {
	LPDATA          int
	DWBUFFERLENGTH  int
	DWBYTESRECORDED int
	DWUSER          int
	DWFLAGS         int
	DWLOOPS         int
	LPNEXT          int
	RESERVED        int
}

type WAVEOUTCAPSA struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	DWFORMATS      int
	WCHANNELS      int
	WRESERVED1     int
	DWSUPPORT      int
}

type WAVEOUTCAPSW struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	DWFORMATS      int
	WCHANNELS      int
	WRESERVED1     int
	DWSUPPORT      int
}

type WAVEOUTCAPS2A struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	DWFORMATS        int
	WCHANNELS        int
	WRESERVED1       int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type WAVEOUTCAPS2W struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	DWFORMATS        int
	WCHANNELS        int
	WRESERVED1       int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type WAVEINCAPSA struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	DWFORMATS      int
	WCHANNELS      int
	WRESERVED1     int
}

type WAVEINCAPSW struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	DWFORMATS      int
	WCHANNELS      int
	WRESERVED1     int
}

type WAVEINCAPS2A struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	DWFORMATS        int
	WCHANNELS        int
	WRESERVED1       int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type WAVEINCAPS2W struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	DWFORMATS        int
	WCHANNELS        int
	WRESERVED1       int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type WAVEFORMAT struct {
	WFORMATTAG      int
	NCHANNELS       int
	NSAMPLESPERSEC  int
	NAVGBYTESPERSEC int
	NBLOCKALIGN     int
}

type PCMWAVEFORMAT struct {
	WF             int
	WBITSPERSAMPLE int
}

type WAVEFORMATEX struct {
	WFORMATTAG      int
	NCHANNELS       int
	NSAMPLESPERSEC  int
	NAVGBYTESPERSEC int
	NBLOCKALIGN     int
	WBITSPERSAMPLE  int
	CBSIZE          int
}

type MIDIOUTCAPSA struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	WTECHNOLOGY    int
	WVOICES        int
	WNOTES         int
	WCHANNELMASK   int
	DWSUPPORT      int
}

type MIDIOUTCAPSW struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	WTECHNOLOGY    int
	WVOICES        int
	WNOTES         int
	WCHANNELMASK   int
	DWSUPPORT      int
}

type MIDIOUTCAPS2A struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	WTECHNOLOGY      int
	WVOICES          int
	WNOTES           int
	WCHANNELMASK     int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type MIDIOUTCAPS2W struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	WTECHNOLOGY      int
	WVOICES          int
	WNOTES           int
	WCHANNELMASK     int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type MIDIINCAPSA struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	DWSUPPORT      int
}

type MIDIINCAPSW struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	DWSUPPORT      int
}

type MIDIINCAPS2A struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type MIDIINCAPS2W struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type MIDIHDR struct {
	LPDATA          int
	DWBUFFERLENGTH  int
	DWBYTESRECORDED int
	DWUSER          int
	DWFLAGS         int
	LPNEXT          int
	RESERVED        int
	DWOFFSET        int
	DWRESERVED      int
}

type MIDIEVENT struct {
	DWDELTATIME int
	DWSTREAMID  int
	DWEVENT     int
	DWPARMS     int
}

type MIDISTRMBUFFVER struct {
	DWVERSION    int
	DWMID        int
	DWOEMVERSION int
}

type MIDIPROPTIMEDIV struct {
	CBSTRUCT  int
	DWTIMEDIV int
}

type MIDIPROPTEMPO struct {
	CBSTRUCT int
	DWTEMPO  int
}

type AUXCAPSA struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	WTECHNOLOGY    int
	WRESERVED1     int
	DWSUPPORT      int
}

type AUXCAPSW struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	WTECHNOLOGY    int
	WRESERVED1     int
	DWSUPPORT      int
}

type AUXCAPS2A struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	WTECHNOLOGY      int
	WRESERVED1       int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type AUXCAPS2W struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	WTECHNOLOGY      int
	WRESERVED1       int
	DWSUPPORT        int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type MIXERCAPSA struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	FDWSUPPORT     int
	CDESTINATIONS  int
}

type MIXERCAPSW struct {
	WMID           int
	WPID           int
	VDRIVERVERSION int
	SZPNAME        int
	FDWSUPPORT     int
	CDESTINATIONS  int
}

type MIXERCAPS2A struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	FDWSUPPORT       int
	CDESTINATIONS    int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type MIXERCAPS2W struct {
	WMID             int
	WPID             int
	VDRIVERVERSION   int
	SZPNAME          int
	FDWSUPPORT       int
	CDESTINATIONS    int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type MIXERLINEA struct {
	CBSTRUCT        int
	DWDESTINATION   int
	DWSOURCE        int
	DWLINEID        int
	FDWLINE         int
	DWUSER          int
	DWCOMPONENTTYPE int
	CCHANNELS       int
	CCONNECTIONS    int
	CCONTROLS       int
	SZSHORTNAME     int
	SZNAME          int
	Target          int
}

type MIXERLINEW struct {
	CBSTRUCT        int
	DWDESTINATION   int
	DWSOURCE        int
	DWLINEID        int
	FDWLINE         int
	DWUSER          int
	DWCOMPONENTTYPE int
	CCHANNELS       int
	CCONNECTIONS    int
	CCONTROLS       int
	SZSHORTNAME     int
	SZNAME          int
	Target          int
}

type MIXERCONTROLA struct {
	CBSTRUCT       int
	DWCONTROLID    int
	DWCONTROLTYPE  int
	FDWCONTROL     int
	CMULTIPLEITEMS int
	SZSHORTNAME    int
	SZNAME         int
	Bounds         int
	Metrics        int
}

type MIXERCONTROLW struct {
	CBSTRUCT       int
	DWCONTROLID    int
	DWCONTROLTYPE  int
	FDWCONTROL     int
	CMULTIPLEITEMS int
	SZSHORTNAME    int
	SZNAME         int
	Bounds         int
	Metrics        int
}

type MIXERLINECONTROLSA struct {
	CBSTRUCT  int
	DWLINEID  int
	Anonymous int
	CCONTROLS int
	CBMXCTRL  int
	PAMXCTRL  int
}

type MIXERLINECONTROLSW struct {
	CBSTRUCT  int
	DWLINEID  int
	Anonymous int
	CCONTROLS int
	CBMXCTRL  int
	PAMXCTRL  int
}

type MIXERCONTROLDETAILS struct {
	CBSTRUCT    int
	DWCONTROLID int
	CCHANNELS   int
	Anonymous   int
	CBDETAILS   int
	PADETAILS   int
}

type MIXERCONTROLDETAILS_LISTTEXTA struct {
	DWPARAM1 int
	DWPARAM2 int
	SZNAME   int
}

type MIXERCONTROLDETAILS_LISTTEXTW struct {
	DWPARAM1 int
	DWPARAM2 int
	SZNAME   int
}

type MIXERCONTROLDETAILS_BOOLEAN struct {
	FVALUE int
}

type MIXERCONTROLDETAILS_SIGNED struct {
	LVALUE int
}

type MIXERCONTROLDETAILS_UNSIGNED struct {
	DWVALUE int
}

type TIMECAPS struct {
	WPERIODMIN int
	WPERIODMAX int
}

type JOYCAPSA struct {
	WMID        int
	WPID        int
	SZPNAME     int
	WXMIN       int
	WXMAX       int
	WYMIN       int
	WYMAX       int
	WZMIN       int
	WZMAX       int
	WNUMBUTTONS int
	WPERIODMIN  int
	WPERIODMAX  int
	WRMIN       int
	WRMAX       int
	WUMIN       int
	WUMAX       int
	WVMIN       int
	WVMAX       int
	WCAPS       int
	WMAXAXES    int
	WNUMAXES    int
	WMAXBUTTONS int
	SZREGKEY    int
	SZOEMVXD    int
}

type JOYCAPSW struct {
	WMID        int
	WPID        int
	SZPNAME     int
	WXMIN       int
	WXMAX       int
	WYMIN       int
	WYMAX       int
	WZMIN       int
	WZMAX       int
	WNUMBUTTONS int
	WPERIODMIN  int
	WPERIODMAX  int
	WRMIN       int
	WRMAX       int
	WUMIN       int
	WUMAX       int
	WVMIN       int
	WVMAX       int
	WCAPS       int
	WMAXAXES    int
	WNUMAXES    int
	WMAXBUTTONS int
	SZREGKEY    int
	SZOEMVXD    int
}

type JOYCAPS2A struct {
	WMID             int
	WPID             int
	SZPNAME          int
	WXMIN            int
	WXMAX            int
	WYMIN            int
	WYMAX            int
	WZMIN            int
	WZMAX            int
	WNUMBUTTONS      int
	WPERIODMIN       int
	WPERIODMAX       int
	WRMIN            int
	WRMAX            int
	WUMIN            int
	WUMAX            int
	WVMIN            int
	WVMAX            int
	WCAPS            int
	WMAXAXES         int
	WNUMAXES         int
	WMAXBUTTONS      int
	SZREGKEY         int
	SZOEMVXD         int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type JOYCAPS2W struct {
	WMID             int
	WPID             int
	SZPNAME          int
	WXMIN            int
	WXMAX            int
	WYMIN            int
	WYMAX            int
	WZMIN            int
	WZMAX            int
	WNUMBUTTONS      int
	WPERIODMIN       int
	WPERIODMAX       int
	WRMIN            int
	WRMAX            int
	WUMIN            int
	WUMAX            int
	WVMIN            int
	WVMAX            int
	WCAPS            int
	WMAXAXES         int
	WNUMAXES         int
	WMAXBUTTONS      int
	SZREGKEY         int
	SZOEMVXD         int
	ManufacturerGuid int
	ProductGuid      int
	NameGuid         int
}

type JOYINFO struct {
	WXPOS    int
	WYPOS    int
	WZPOS    int
	WBUTTONS int
}

type JOYINFOEX struct {
	DWSIZE         int
	DWFLAGS        int
	DWXPOS         int
	DWYPOS         int
	DWZPOS         int
	DWRPOS         int
	DWUPOS         int
	DWVPOS         int
	DWBUTTONS      int
	DWBUTTONNUMBER int
	DWPOV          int
	DWRESERVED1    int
	DWRESERVED2    int
}

type KSDATAFORMAT_SUBTYPE_PCM struct {
}

type KSDATAFORMAT_SUBTYPE_IEEE_FLOAT struct {
}

type KSDATAFORMAT_SUBTYPE_WAVEFORMATEX struct {
}

type WAVEFORMATEXTENSIBLE struct {
	Format        int
	Samples       int
	DWCHANNELMASK int
	SubFormat     int
}

type ADPCMCOEFSET struct {
	ICOEF1 int
	ICOEF2 int
}

type ADPCMWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
	WNUMCOEF         int
	ACOEF            int
}

type DRMWAVEFORMAT struct {
	WFX         int
	WRESERVED   int
	ULCONTENTID int
	WFXSECURE   int
}

type DVIADPCMWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type IMAADPCMWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type MEDIASPACEADPCMWAVEFORMAT struct {
	WFX       int
	WREVISION int
}

type SIERRAADPCMWAVEFORMAT struct {
	WFX       int
	WREVISION int
}

type G723_ADPCMWAVEFORMAT struct {
	WFX           int
	CBEXTRASIZE   int
	NAUXBLOCKSIZE int
}

type DIGISTDWAVEFORMAT struct {
	WFX int
}

type DIGIFIXWAVEFORMAT struct {
	WFX int
}

type DIALOGICOKIADPCMWAVEFORMAT struct {
	EWF int
}

type YAMAHA_ADPCMWAVEFORMAT struct {
	WFX int
}

type SONARCWAVEFORMAT struct {
	WFX       int
	WCOMPTYPE int
}

type TRUESPEECHWAVEFORMAT struct {
	WFX              int
	WREVISION        int
	NSAMPLESPERBLOCK int
	ABRESERVED       int
}

type ECHOSC1WAVEFORMAT struct {
	WFX int
}

type AUDIOFILE_AF36WAVEFORMAT struct {
	WFX int
}

type APTXWAVEFORMAT struct {
	WFX int
}

type AUDIOFILE_AF10WAVEFORMAT struct {
	WFX int
}

type DOLBYAC2WAVEFORMAT struct {
	WFX          int
	NAUXBITSCODE int
}

type GSM610WAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type ADPCMEWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type CONTRESVQLPCWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type DIGIREALWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type DIGIADPCMWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type CONTRESCR10WAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type NMS_VBXADPCMWAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
}

type G721_ADPCMWAVEFORMAT struct {
	WFX           int
	NAUXBLOCKSIZE int
}

type MSAUDIO1WAVEFORMAT struct {
	WFX              int
	WSAMPLESPERBLOCK int
	WENCODEOPTIONS   int
}

type WMAUDIO2WAVEFORMAT struct {
	WFX               int
	DWSAMPLESPERBLOCK int
	WENCODEOPTIONS    int
	DWSUPERBLOCKALIGN int
}

type WMAUDIO3WAVEFORMAT struct {
	WFX                 int
	WVALIDBITSPERSAMPLE int
	DWCHANNELMASK       int
	DWRESERVED1         int
	DWRESERVED2         int
	WENCODEOPTIONS      int
	WRESERVED3          int
}

type CREATIVEADPCMWAVEFORMAT struct {
	WFX       int
	WREVISION int
}

type CREATIVEFASTSPEECH8WAVEFORMAT struct {
	WFX       int
	WREVISION int
}

type CREATIVEFASTSPEECH10WAVEFORMAT struct {
	WFX       int
	WREVISION int
}

type FMTOWNS_SND_WAVEFORMAT struct {
	WFX       int
	WREVISION int
}

type OLIGSMWAVEFORMAT struct {
	WFX int
}

type OLIADPCMWAVEFORMAT struct {
	WFX int
}

type OLICELPWAVEFORMAT struct {
	WFX int
}

type OLISBCWAVEFORMAT struct {
	WFX int
}

type OLIOPRWAVEFORMAT struct {
	WFX int
}

type CSIMAADPCMWAVEFORMAT struct {
	WFX int
}

type WAVEFILTER struct {
	CBSTRUCT    int
	DWFILTERTAG int
	FDWFILTER   int
	DWRESERVED  int
}

type VOLUMEWAVEFILTER struct {
	WFLTR    int
	DWVOLUME int
}

type ECHOWAVEFILTER struct {
	WFLTR    int
	DWVOLUME int
	DWDELAY  int
}

type S_RIFFWAVE_INST struct {
	BUNSHIFTEDNOTE int
	CHFINETUNE     int
	CHGAIN         int
	BLOWNOTE       int
	BHIGHNOTE      int
	BLOWVELOCITY   int
	BHIGHVELOCITY  int
}

type TAG_S_RIFFWAVE_INST struct {
}

type EXBMINFOHEADER struct {
	BMI             int
	BIEXTDATAOFFSET int
}

type JPEGINFOHEADER struct {
	JPEGSize          int
	JPEGProcess       int
	JPEGColorSpaceID  int
	JPEGBitsPerSample int
	JPEGHSubSampling  int
	JPEGVSubSampling  int
}

type MCI_DGV_RECT_PARMS struct {
	DWCALLBACK int
	RC         int
}

type MCI_DGV_CAPTURE_PARMSA struct {
	DWCALLBACK    int
	LPSTRFILENAME int
	RC            int
}

type MCI_DGV_CAPTURE_PARMSW struct {
	DWCALLBACK    int
	LPSTRFILENAME int
	RC            int
}

type MCI_DGV_COPY_PARMS struct {
	DWCALLBACK    int
	DWFROM        int
	DWTO          int
	RC            int
	DWAUDIOSTREAM int
	DWVIDEOSTREAM int
}

type MCI_DGV_CUE_PARMS struct {
	DWCALLBACK int
	DWTO       int
}

type MCI_DGV_CUT_PARMS struct {
	DWCALLBACK    int
	DWFROM        int
	DWTO          int
	RC            int
	DWAUDIOSTREAM int
	DWVIDEOSTREAM int
}

type MCI_DGV_DELETE_PARMS struct {
	DWCALLBACK    int
	DWFROM        int
	DWTO          int
	RC            int
	DWAUDIOSTREAM int
	DWVIDEOSTREAM int
}

type MCI_DGV_INFO_PARMSA struct {
	DWCALLBACK  int
	LPSTRRETURN int
	DWRETSIZE   int
	DWITEM      int
}

type MCI_DGV_INFO_PARMSW struct {
	DWCALLBACK  int
	LPSTRRETURN int
	DWRETSIZE   int
	DWITEM      int
}

type MCI_DGV_LIST_PARMSA struct {
	DWCALLBACK     int
	LPSTRRETURN    int
	DWLENGTH       int
	DWNUMBER       int
	DWITEM         int
	LPSTRALGORITHM int
}

type MCI_DGV_LIST_PARMSW struct {
	DWCALLBACK     int
	LPSTRRETURN    int
	DWLENGTH       int
	DWNUMBER       int
	DWITEM         int
	LPSTRALGORITHM int
}

type MCI_DGV_MONITOR_PARMS struct {
	DWCALLBACK int
	DWSOURCE   int
	DWMETHOD   int
}

type MCI_DGV_OPEN_PARMSA struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWSTYLE          int
	HWNDPARENT       int
}

type MCI_DGV_OPEN_PARMSW struct {
	DWCALLBACK       int
	WDEVICEID        int
	LPSTRDEVICETYPE  int
	LPSTRELEMENTNAME int
	LPSTRALIAS       int
	DWSTYLE          int
	HWNDPARENT       int
}

type MCI_DGV_PASTE_PARMS struct {
	DWCALLBACK    int
	DWTO          int
	RC            int
	DWAUDIOSTREAM int
	DWVIDEOSTREAM int
}

type MCI_DGV_QUALITY_PARMSA struct {
	DWCALLBACK     int
	DWITEM         int
	LPSTRNAME      int
	LPSTRALGORITHM int
	DWHANDLE       int
}

type MCI_DGV_QUALITY_PARMSW struct {
	DWCALLBACK     int
	DWITEM         int
	LPSTRNAME      int
	LPSTRALGORITHM int
	DWHANDLE       int
}

type MCI_DGV_RECORD_PARMS struct {
	DWCALLBACK    int
	DWFROM        int
	DWTO          int
	RC            int
	DWAUDIOSTREAM int
	DWVIDEOSTREAM int
}

type MCI_DGV_RESERVE_PARMSA struct {
	DWCALLBACK int
	LPSTRPATH  int
	DWSIZE     int
}

type MCI_DGV_RESERVE_PARMSW struct {
	DWCALLBACK int
	LPSTRPATH  int
	DWSIZE     int
}

type MCI_DGV_RESTORE_PARMSA struct {
	DWCALLBACK    int
	LPSTRFILENAME int
	RC            int
}

type MCI_DGV_RESTORE_PARMSW struct {
	DWCALLBACK    int
	LPSTRFILENAME int
	RC            int
}

type MCI_DGV_SAVE_PARMSA struct {
	DWCALLBACK    int
	LPSTRFILENAME int
	RC            int
}

type MCI_DGV_SAVE_PARMSW struct {
	DWCALLBACK    int
	LPSTRFILENAME int
	RC            int
}

type MCI_DGV_SET_PARMS struct {
	DWCALLBACK   int
	DWTIMEFORMAT int
	DWAUDIO      int
	DWFILEFORMAT int
	DWSPEED      int
}

type MCI_DGV_SETAUDIO_PARMSA struct {
	DWCALLBACK     int
	DWITEM         int
	DWVALUE        int
	DWOVER         int
	LPSTRALGORITHM int
	LPSTRQUALITY   int
}

type MCI_DGV_SETAUDIO_PARMSW struct {
	DWCALLBACK     int
	DWITEM         int
	DWVALUE        int
	DWOVER         int
	LPSTRALGORITHM int
	LPSTRQUALITY   int
}

type MCI_DGV_SIGNAL_PARMS struct {
	DWCALLBACK int
	DWPOSITION int
	DWPERIOD   int
	DWUSERPARM int
}

type MCI_DGV_SETVIDEO_PARMSA struct {
	DWCALLBACK     int
	DWITEM         int
	DWVALUE        int
	DWOVER         int
	LPSTRALGORITHM int
	LPSTRQUALITY   int
	DWSOURCENUMBER int
}

type MCI_DGV_SETVIDEO_PARMSW struct {
	DWCALLBACK     int
	DWITEM         int
	DWVALUE        int
	DWOVER         int
	LPSTRALGORITHM int
	LPSTRQUALITY   int
	DWSOURCENUMBER int
}

type MCI_DGV_STATUS_PARMSA struct {
	DWCALLBACK  int
	DWRETURN    int
	DWITEM      int
	DWTRACK     int
	LPSTRDRIVE  int
	DWREFERENCE int
}

type MCI_DGV_STATUS_PARMSW struct {
	DWCALLBACK  int
	DWRETURN    int
	DWITEM      int
	DWTRACK     int
	LPSTRDRIVE  int
	DWREFERENCE int
}

type MCI_DGV_STEP_PARMS struct {
	DWCALLBACK int
	DWFRAMES   int
}

type MCI_DGV_UPDATE_PARMS struct {
	DWCALLBACK int
	RC         int
	HDC        int
}

type MCI_DGV_WINDOW_PARMSA struct {
	DWCALLBACK int
	HWND       int
	NCMDSHOW   int
	LPSTRTEXT  int
}

type MCI_DGV_WINDOW_PARMSW struct {
	DWCALLBACK int
	HWND       int
	NCMDSHOW   int
	LPSTRTEXT  int
}

type HACMDRIVERID__ struct {
	UNUSED int
}

type HACMDRIVER__ struct {
	UNUSED int
}

type HACMSTREAM__ struct {
	UNUSED int
}

type HACMOBJ__ struct {
	UNUSED int
}

type TACMDRIVERDETAILSA struct {
	CBSTRUCT    int
	FCCTYPE     int
	FCCCOMP     int
	WMID        int
	WPID        int
	VDWACM      int
	VDWDRIVER   int
	FDWSUPPORT  int
	CFORMATTAGS int
	CFILTERTAGS int
	HICON       int
	SZSHORTNAME int
	SZLONGNAME  int
	SZCOPYRIGHT int
	SZLICENSING int
	SZFEATURES  int
}

type TACMDRIVERDETAILSW struct {
	CBSTRUCT    int
	FCCTYPE     int
	FCCCOMP     int
	WMID        int
	WPID        int
	VDWACM      int
	VDWDRIVER   int
	FDWSUPPORT  int
	CFORMATTAGS int
	CFILTERTAGS int
	HICON       int
	SZSHORTNAME int
	SZLONGNAME  int
	SZCOPYRIGHT int
	SZLICENSING int
	SZFEATURES  int
}

type TACMFORMATTAGDETAILSA struct {
	CBSTRUCT         int
	DWFORMATTAGINDEX int
	DWFORMATTAG      int
	CBFORMATSIZE     int
	FDWSUPPORT       int
	CSTANDARDFORMATS int
	SZFORMATTAG      int
}

type TACMFORMATTAGDETAILSW struct {
	CBSTRUCT         int
	DWFORMATTAGINDEX int
	DWFORMATTAG      int
	CBFORMATSIZE     int
	FDWSUPPORT       int
	CSTANDARDFORMATS int
	SZFORMATTAG      int
}

type TACMFORMATDETAILSA struct {
	CBSTRUCT      int
	DWFORMATINDEX int
	DWFORMATTAG   int
	FDWSUPPORT    int
	PWFX          int
	CBWFX         int
	SZFORMAT      int
}

type TACMFORMATDETAILSW struct {
	CBSTRUCT      int
	DWFORMATINDEX int
	DWFORMATTAG   int
	FDWSUPPORT    int
	PWFX          int
	CBWFX         int
	SZFORMAT      int
}

type TACMFORMATCHOOSEA struct {
	CBSTRUCT        int
	FDWSTYLE        int
	HWNDOWNER       int
	PWFX            int
	CBWFX           int
	PSZTITLE        int
	SZFORMATTAG     int
	SZFORMAT        int
	PSZNAME         int
	CCHNAME         int
	FDWENUM         int
	PWFXENUM        int
	HINSTANCE       int
	PSZTEMPLATENAME int
	LCUSTDATA       int
	PFNHOOK         int
}

type TACMFORMATCHOOSEW struct {
	CBSTRUCT        int
	FDWSTYLE        int
	HWNDOWNER       int
	PWFX            int
	CBWFX           int
	PSZTITLE        int
	SZFORMATTAG     int
	SZFORMAT        int
	PSZNAME         int
	CCHNAME         int
	FDWENUM         int
	PWFXENUM        int
	HINSTANCE       int
	PSZTEMPLATENAME int
	LCUSTDATA       int
	PFNHOOK         int
}

type TACMFILTERTAGDETAILSA struct {
	CBSTRUCT         int
	DWFILTERTAGINDEX int
	DWFILTERTAG      int
	CBFILTERSIZE     int
	FDWSUPPORT       int
	CSTANDARDFILTERS int
	SZFILTERTAG      int
}

type TACMFILTERTAGDETAILSW struct {
	CBSTRUCT         int
	DWFILTERTAGINDEX int
	DWFILTERTAG      int
	CBFILTERSIZE     int
	FDWSUPPORT       int
	CSTANDARDFILTERS int
	SZFILTERTAG      int
}

type TACMFILTERDETAILSA struct {
	CBSTRUCT      int
	DWFILTERINDEX int
	DWFILTERTAG   int
	FDWSUPPORT    int
	PWFLTR        int
	CBWFLTR       int
	SZFILTER      int
}

type TACMFILTERDETAILSW struct {
	CBSTRUCT      int
	DWFILTERINDEX int
	DWFILTERTAG   int
	FDWSUPPORT    int
	PWFLTR        int
	CBWFLTR       int
	SZFILTER      int
}

type TACMFILTERCHOOSEA struct {
	CBSTRUCT        int
	FDWSTYLE        int
	HWNDOWNER       int
	PWFLTR          int
	CBWFLTR         int
	PSZTITLE        int
	SZFILTERTAG     int
	SZFILTER        int
	PSZNAME         int
	CCHNAME         int
	FDWENUM         int
	PWFLTRENUM      int
	HINSTANCE       int
	PSZTEMPLATENAME int
	LCUSTDATA       int
	PFNHOOK         int
}

type TACMFILTERCHOOSEW struct {
	CBSTRUCT        int
	FDWSTYLE        int
	HWNDOWNER       int
	PWFLTR          int
	CBWFLTR         int
	PSZTITLE        int
	SZFILTERTAG     int
	SZFILTER        int
	PSZNAME         int
	CCHNAME         int
	FDWENUM         int
	PWFLTRENUM      int
	HINSTANCE       int
	PSZTEMPLATENAME int
	LCUSTDATA       int
	PFNHOOK         int
}

type ACMSTREAMHEADER struct {
	CBSTRUCT         int
	FDWSTATUS        int
	DWUSER           int
	PBSRC            int
	CBSRCLENGTH      int
	CBSRCLENGTHUSED  int
	DWSRCUSER        int
	PBDST            int
	CBDSTLENGTH      int
	CBDSTLENGTHUSED  int
	DWDSTUSER        int
	DWRESERVEDDRIVER int
}

type HIC__ struct {
	UNUSED int
}

type ICOPEN struct {
	DWSIZE      int
	FCCTYPE     int
	FCCHANDLER  int
	DWVERSION   int
	DWFLAGS     int
	DWERROR     int
	PV1RESERVED int
	PV2RESERVED int
	DNDEVNODE   int
}

type ICINFO struct {
	DWSIZE        int
	FCCTYPE       int
	FCCHANDLER    int
	DWFLAGS       int
	DWVERSION     int
	DWVERSIONICM  int
	SZNAME        int
	SZDESCRIPTION int
	SZDRIVER      int
}

type ICCOMPRESS struct {
	DWFLAGS     int
	LPBIOUTPUT  int
	LPOUTPUT    int
	LPBIINPUT   int
	LPINPUT     int
	LPCKID      int
	LPDWFLAGS   int
	LFRAMENUM   int
	DWFRAMESIZE int
	DWQUALITY   int
	LPBIPREV    int
	LPPREV      int
}

type ICCOMPRESSFRAMES struct {
	DWFLAGS            int
	LPBIOUTPUT         int
	LOUTPUT            int
	LPBIINPUT          int
	LINPUT             int
	LSTARTFRAME        int
	LFRAMECOUNT        int
	LQUALITY           int
	LDATARATE          int
	LKEYRATE           int
	DWRATE             int
	DWSCALE            int
	DWOVERHEADPERFRAME int
	DWRESERVED2        int
	GetData            int
	PutData            int
}

type ICSETSTATUSPROC struct {
	DWFLAGS int
	LPARAM  int
	Status  int
}

type ICDECOMPRESS struct {
	DWFLAGS    int
	LPBIINPUT  int
	LPINPUT    int
	LPBIOUTPUT int
	LPOUTPUT   int
	CKID       int
}

type ICDECOMPRESSEX struct {
	DWFLAGS int
	LPBISRC int
	LPSRC   int
	LPBIDST int
	LPDST   int
	XDST    int
	YDST    int
	DXDST   int
	DYDST   int
	XSRC    int
	YSRC    int
	DXSRC   int
	DYSRC   int
}

type ICDRAWBEGIN struct {
	DWFLAGS int
	HPAL    int
	HWND    int
	HDC     int
	XDST    int
	YDST    int
	DXDST   int
	DYDST   int
	LPBI    int
	XSRC    int
	YSRC    int
	DXSRC   int
	DYSRC   int
	DWRATE  int
	DWSCALE int
}

type ICDRAW struct {
	DWFLAGS  int
	LPFORMAT int
	LPDATA   int
	CBDATA   int
	LTIME    int
}

type ICDRAWSUGGEST struct {
	LPBIIN          int
	LPBISUGGEST     int
	DXSRC           int
	DYSRC           int
	DXDST           int
	DYDST           int
	HICDECOMPRESSOR int
}

type ICPALETTE struct {
	DWFLAGS int
	ISTART  int
	ILEN    int
	LPPE    int
}

type COMPVARS struct {
	CBSIZE     int
	DWFLAGS    int
	HIC        int
	FCCTYPE    int
	FCCHANDLER int
	LPBIIN     int
	LPBIOUT    int
	LPBITSOUT  int
	LPBITSPREV int
	LFRAME     int
	LKEY       int
	LDATARATE  int
	LQ         int
	LKEYCOUNT  int
	LPSTATE    int
	CBSTATE    int
}

type DRAWDIBTIME struct {
	TIMECOUNT      int
	TIMEDRAW       int
	TIMEDECOMPRESS int
	TIMEDITHER     int
	TIMESTRETCH    int
	TIMEBLT        int
	TIMESETDIBITS  int
}

type AVISTREAMINFOW struct {
	FCCTYPE               int
	FCCHANDLER            int
	DWFLAGS               int
	DWCAPS                int
	WPRIORITY             int
	WLANGUAGE             int
	DWSCALE               int
	DWRATE                int
	DWSTART               int
	DWLENGTH              int
	DWINITIALFRAMES       int
	DWSUGGESTEDBUFFERSIZE int
	DWQUALITY             int
	DWSAMPLESIZE          int
	RCFRAME               int
	DWEDITCOUNT           int
	DWFORMATCHANGECOUNT   int
	SZNAME                int
}

type AVISTREAMINFOA struct {
	FCCTYPE               int
	FCCHANDLER            int
	DWFLAGS               int
	DWCAPS                int
	WPRIORITY             int
	WLANGUAGE             int
	DWSCALE               int
	DWRATE                int
	DWSTART               int
	DWLENGTH              int
	DWINITIALFRAMES       int
	DWSUGGESTEDBUFFERSIZE int
	DWQUALITY             int
	DWSAMPLESIZE          int
	RCFRAME               int
	DWEDITCOUNT           int
	DWFORMATCHANGECOUNT   int
	SZNAME                int
}

type AVIFILEINFOW struct {
	DWMAXBYTESPERSEC      int
	DWFLAGS               int
	DWCAPS                int
	DWSTREAMS             int
	DWSUGGESTEDBUFFERSIZE int
	DWWIDTH               int
	DWHEIGHT              int
	DWSCALE               int
	DWRATE                int
	DWLENGTH              int
	DWEDITCOUNT           int
	SZFILETYPE            int
}

type AVIFILEINFOA struct {
	DWMAXBYTESPERSEC      int
	DWFLAGS               int
	DWCAPS                int
	DWSTREAMS             int
	DWSUGGESTEDBUFFERSIZE int
	DWWIDTH               int
	DWHEIGHT              int
	DWSCALE               int
	DWRATE                int
	DWLENGTH              int
	DWEDITCOUNT           int
	SZFILETYPE            int
}

type AVICOMPRESSOPTIONS struct {
	FCCTYPE           int
	FCCHANDLER        int
	DWKEYFRAMEEVERY   int
	DWQUALITY         int
	DWBYTESPERSECOND  int
	DWFLAGS           int
	LPFORMAT          int
	CBFORMAT          int
	LPPARMS           int
	CBPARMS           int
	DWINTERLEAVEEVERY int
}

type HVIDEO__ struct {
	UNUSED int
}

type VIDEOHDR struct {
	LPDATA         int
	DWBUFFERLENGTH int
	DWBYTESUSED    int
	DWTIMECAPTURED int
	DWUSER         int
	DWFLAGS        int
	DWRESERVED     int
}

type CHANNEL_CAPS_TAG struct {
	DWFLAGS            int
	DWSRCRECTXMOD      int
	DWSRCRECTYMOD      int
	DWSRCRECTWIDTHMOD  int
	DWSRCRECTHEIGHTMOD int
	DWDSTRECTXMOD      int
	DWDSTRECTYMOD      int
	DWDSTRECTWIDTHMOD  int
	DWDSTRECTHEIGHTMOD int
}

type CAPDRIVERCAPS struct {
	WDEVICEINDEX            int
	FHASOVERLAY             int
	FHASDLGVIDEOSOURCE      int
	FHASDLGVIDEOFORMAT      int
	FHASDLGVIDEODISPLAY     int
	FCAPTUREINITIALIZED     int
	FDRIVERSUPPLIESPALETTES int
	HVIDEOIN                int
	HVIDEOOUT               int
	HVIDEOEXTIN             int
	HVIDEOEXTOUT            int
}

type CAPSTATUS struct {
	UIIMAGEWIDTH                int
	UIIMAGEHEIGHT               int
	FLIVEWINDOW                 int
	FOVERLAYWINDOW              int
	FSCALE                      int
	PTSCROLL                    int
	FUSINGDEFAULTPALETTE        int
	FAUDIOHARDWARE              int
	FCAPFILEEXISTS              int
	DWCURRENTVIDEOFRAME         int
	DWCURRENTVIDEOFRAMESDROPPED int
	DWCURRENTWAVESAMPLES        int
	DWCURRENTTIMEELAPSEDMS      int
	HPALCURRENT                 int
	FCAPTURINGNOW               int
	DWRETURN                    int
	WNUMVIDEOALLOCATED          int
	WNUMAUDIOALLOCATED          int
}

type CAPTUREPARMS struct {
	DWREQUESTMICROSECPERFRAME int
	FMAKEUSERHITOKTOCAPTURE   int
	WPERCENTDROPFORERROR      int
	FYIELD                    int
	DWINDEXSIZE               int
	WCHUNKGRANULARITY         int
	FUSINGDOSMEMORY           int
	WNUMVIDEOREQUESTED        int
	FCAPTUREAUDIO             int
	WNUMAUDIOREQUESTED        int
	VKEYABORT                 int
	FABORTLEFTMOUSE           int
	FABORTRIGHTMOUSE          int
	FLIMITENABLED             int
	WTIMELIMIT                int
	FMCICONTROL               int
	FSTEPMCIDEVICE            int
	DWMCISTARTTIME            int
	DWMCISTOPTIME             int
	FSTEPCAPTUREAT2X          int
	WSTEPCAPTUREAVERAGEFRAMES int
	DWAUDIOBUFFERSIZE         int
	FDISABLEWRITECACHE        int
	AVStreamMaster            int
}

type CAPINFOCHUNK struct {
	FCCINFOID int
	LPDATA    int
	CBDATA    int
}

type DRVM_IOCTL_DATA struct {
	DWSIZE int
	DWCMD  int
}

type WAVEOPENDESC struct {
	HWAVE           int
	LPFORMAT        int
	DWCALLBACK      int
	DWINSTANCE      int
	UMAPPEDDEVICEID int
	DNDEVNODE       int
}

type MIDIOPENSTRMID_TAG struct {
	DWSTREAMID int
	UDEVICEID  int
}

type TMIXEROPENDESC struct {
	HMX        int
	PRESERVED0 int
	DWCALLBACK int
	DWINSTANCE int
	DNDEVNODE  int
}

type TIMEREVENT_TAG struct {
	WDELAY      int
	WRESOLUTION int
	LPFUNCTION  int
	DWUSER      int
	WFLAGS      int
	WRESERVED1  int
}

type JOYPOS_TAG struct {
	DWX int
	DWY int
	DWZ int
	DWR int
	DWU int
	DWV int
}

type JOYRANGE_TAG struct {
	JPMIN    int
	JPMAX    int
	JPCENTER int
}

type JOYREGUSERVALUES_TAG struct {
	DWTIMEOUT  int
	JRVRANGES  int
	JPDEADZONE int
}

type JOYREGHWSETTINGS_TAG struct {
	DWFLAGS      int
	DWNUMBUTTONS int
}

type JOYREGHWCONFIG_TAG struct {
	HWS             int
	DWUSAGESETTINGS int
	HWV             int
	DWTYPE          int
	DWRESERVED      int
}

type JOYCALIBRATE_TAG struct {
	WXBASE  int
	WXDELTA int
	WYBASE  int
	WYDELTA int
	WZBASE  int
	WZDELTA int
}

type MCI_OPEN_DRIVER_PARMS struct {
	WDEVICEID           int
	LPSTRPARAMS         int
	WCUSTOMCOMMANDTABLE int
	WTYPE               int
}
