// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package settingsmanagementinfrastructure implements the Windows.Win32.SettingsManagementInfrastructure namespace.
package settingsmanagementinfrastructure

type WcmTargetMode int32

const (
	OfflineMode WcmTargetMode = 1
	OnlineMode  WcmTargetMode = 2
)

type WcmNamespaceEnumerationFlags int32

const (
	SharedEnumeration WcmNamespaceEnumerationFlags = 1
	UserEnumeration   WcmNamespaceEnumerationFlags = 2
	AllEnumeration    WcmNamespaceEnumerationFlags = 3
)

type WcmDataType int32

const (
	DATATYPEBYTE      WcmDataType = 1
	DATATYPESBYTE     WcmDataType = 2
	DATATYPEUINT16    WcmDataType = 3
	DATATYPEINT16     WcmDataType = 4
	DATATYPEUINT32    WcmDataType = 5
	DATATYPEINT32     WcmDataType = 6
	DATATYPEUINT64    WcmDataType = 7
	DATATYPEINT64     WcmDataType = 8
	DATATYPEBOOLEAN   WcmDataType = 11
	DATATYPESTRING    WcmDataType = 12
	DATATYPEFLAGARRAY WcmDataType = 32768
)

type WcmSettingType int32

const (
	SETTINGTYPESCALAR  WcmSettingType = 1
	SETTINGTYPECOMPLEX WcmSettingType = 2
	SETTINGTYPELIST    WcmSettingType = 3
)

type WcmRestrictionFacets int32

const (
	RESTRICTIONFACETMAXLENGTH    WcmRestrictionFacets = 1
	RESTRICTIONFACETENUMERATION  WcmRestrictionFacets = 2
	RESTRICTIONFACETMAXINCLUSIVE WcmRestrictionFacets = 4
	RESTRICTIONFACETMININCLUSIVE WcmRestrictionFacets = 8
)

type WcmUserStatus int32

const (
	UnknownStatus    WcmUserStatus = 0
	UserRegistered   WcmUserStatus = 1
	UserUnregistered WcmUserStatus = 2
	UserLoaded       WcmUserStatus = 3
	UserUnloaded     WcmUserStatus = 4
)

type WcmNamespaceAccess int32

const (
	ReadOnlyAccess  WcmNamespaceAccess = 1
	ReadWriteAccess WcmNamespaceAccess = 2
)
