// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package xblidp implements the Windows.Win32.Xblidp namespace.
package xblidp

type XblIdpAuthManager struct {
}

type XblIdpAuthTokenResult struct {
}
