// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowsprogramming implements the Windows.Win32.WindowsProgramming namespace.
package windowsprogramming

type PROCESS_CREATION_FLAGS uint32

const (
	DEBUG_PROCESS = 1
	DEBUG_ONLY_THIS_PROCESS = 2
	CREATE_SUSPENDED = 4
	DETACHED_PROCESS = 8
	CREATE_NEW_CONSOLE = 16
	NORMAL_PRIORITY_CLASS = 32
	IDLE_PRIORITY_CLASS = 64
	HIGH_PRIORITY_CLASS = 128
	REALTIME_PRIORITY_CLASS = 256
	CREATE_NEW_PROCESS_GROUP = 512
	CREATE_UNICODE_ENVIRONMENT = 1024
	CREATE_SEPARATE_WOW_VDM = 2048
	CREATE_SHARED_WOW_VDM = 4096
	CREATE_FORCEDOS = 8192
	BELOW_NORMAL_PRIORITY_CLASS = 16384
	ABOVE_NORMAL_PRIORITY_CLASS = 32768
	INHERIT_PARENT_AFFINITY = 65536
	INHERIT_CALLER_PRIORITY = 131072
	CREATE_PROTECTED_PROCESS = 262144
	EXTENDED_STARTUPINFO_PRESENT = 524288
	PROCESS_MODE_BACKGROUND_BEGIN = 1048576
	PROCESS_MODE_BACKGROUND_END = 2097152
	CREATE_SECURE_PROCESS = 4194304
	CREATE_BREAKAWAY_FROM_JOB = 16777216
	CREATE_PRESERVE_CODE_AUTHZ_LEVEL = 33554432
	CREATE_DEFAULT_ERROR_MODE = 67108864
	CREATE_NO_WINDOW = 134217728
	PROFILE_USER = 268435456
	PROFILE_KERNEL = 536870912
	PROFILE_SERVER = 1073741824
	CREATE_IGNORE_SYSTEM_DEFAULT = 2147483648
)

type HANDLE_FLAG_OPTIONS int32

const (
	HANDLE_FLAG_INHERIT = 1
	HANDLE_FLAG_PROTECT_FROM_CLOSE = 2
)

type DUPLICATE_HANDLE_OPTIONS int32

const (
	DUPLICATE_CLOSE_SOURCE = 1
	DUPLICATE_SAME_ACCESS = 2
)

type STD_HANDLE_TYPE uint32

const (
	STD_INPUT_HANDLE = 4294967286
	STD_OUTPUT_HANDLE = 4294967285
	STD_ERROR_HANDLE = 4294967284
)

type VER_FLAGS uint32

const (
	VER_MINORVERSION = 1
	VER_MAJORVERSION = 2
	VER_BUILDNUMBER = 4
	VER_PLATFORMID = 8
	VER_SERVICEPACKMINOR = 16
	VER_SERVICEPACKMAJOR = 32
	VER_SUITENAME = 64
	VER_PRODUCT_TYPE = 128
)

type FORMAT_MESSAGE_OPTIONS int32

const (
	FORMAT_MESSAGE_ALLOCATE_BUFFER = 256
	FORMAT_MESSAGE_IGNORE_INSERTS = 512
	FORMAT_MESSAGE_FROM_STRING = 1024
	FORMAT_MESSAGE_FROM_HMODULE = 2048
	FORMAT_MESSAGE_FROM_SYSTEM = 4096
	FORMAT_MESSAGE_ARGUMENT_ARRAY = 8192
	FORMAT_MESSAGE_MAX_WIDTH_MASK = 255
)

type FIRMWARE_TYPE int32

const (
	FirmwareTypeUnknown = 0
	FirmwareTypeBios = 1
	FirmwareTypeUefi = 2
	FirmwareTypeMax = 3
)

type UpdateImpactLevel int32

const (
	UpdateImpactLevel_None = 0
	UpdateImpactLevel_Low = 1
	UpdateImpactLevel_Medium = 2
	UpdateImpactLevel_High = 3
)

type UpdateAssessmentStatus int32

const (
	UpdateAssessmentStatus_Latest = 0
	UpdateAssessmentStatus_NotLatestSoftRestriction = 1
	UpdateAssessmentStatus_NotLatestHardRestriction = 2
	UpdateAssessmentStatus_NotLatestEndOfSupport = 3
	UpdateAssessmentStatus_NotLatestServicingTrain = 4
	UpdateAssessmentStatus_NotLatestDeferredFeature = 5
	UpdateAssessmentStatus_NotLatestDeferredQuality = 6
	UpdateAssessmentStatus_NotLatestPausedFeature = 7
	UpdateAssessmentStatus_NotLatestPausedQuality = 8
	UpdateAssessmentStatus_NotLatestManaged = 9
	UpdateAssessmentStatus_NotLatestUnknown = 10
	UpdateAssessmentStatus_NotLatestTargetedVersion = 11
)

type THREAD_INFORMATION_CLASS int32

const (
	ThreadMemoryPriority = 0
	ThreadAbsoluteCpuPriority = 1
	ThreadDynamicCodePolicy = 2
	ThreadPowerThrottling = 3
	ThreadInformationClassMax = 4
)

type COMPUTER_NAME_FORMAT int32

const (
	ComputerNameNetBIOS = 0
	ComputerNameDnsHostname = 1
	ComputerNameDnsDomain = 2
	ComputerNameDnsFullyQualified = 3
	ComputerNamePhysicalNetBIOS = 4
	ComputerNamePhysicalDnsHostname = 5
	ComputerNamePhysicalDnsDomain = 6
	ComputerNamePhysicalDnsFullyQualified = 7
	ComputerNameMax = 8
)

type DEP_SYSTEM_POLICY_TYPE int32

const (
	DEPPolicyAlwaysOff = 0
	DEPPolicyAlwaysOn = 1
	DEPPolicyOptIn = 2
	DEPPolicyOptOut = 3
	DEPTotalPolicyCount = 4
)

type PROC_THREAD_ATTRIBUTE_NUM int32

const (
	ProcThreadAttributeParentProcess = 0
	ProcThreadAttributeHandleList = 2
	ProcThreadAttributeGroupAffinity = 3
	ProcThreadAttributePreferredNode = 4
	ProcThreadAttributeIdealProcessor = 5
	ProcThreadAttributeUmsThread = 6
	ProcThreadAttributeMitigationPolicy = 7
	ProcThreadAttributeSecurityCapabilities = 9
	ProcThreadAttributeProtectionLevel = 11
	ProcThreadAttributeJobList = 13
	ProcThreadAttributeChildProcessPolicy = 14
	ProcThreadAttributeAllApplicationPackagesPolicy = 15
	ProcThreadAttributeWin32kFilter = 16
	ProcThreadAttributeSafeOpenPromptOriginClaim = 17
	ProcThreadAttributeDesktopAppPolicy = 18
	ProcThreadAttributePseudoConsole = 22
)

type DOMNodeType int32

const (
	NODE_INVALID = 0
	NODE_ELEMENT = 1
	NODE_ATTRIBUTE = 2
	NODE_TEXT = 3
	NODE_CDATA_SECTION = 4
	NODE_ENTITY_REFERENCE = 5
	NODE_ENTITY = 6
	NODE_PROCESSING_INSTRUCTION = 7
	NODE_COMMENT = 8
	NODE_DOCUMENT = 9
	NODE_DOCUMENT_TYPE = 10
	NODE_DOCUMENT_FRAGMENT = 11
	NODE_NOTATION = 12
)

type XMLEMEM_TYPE int32

const (
	XMLELEMTYPE_ELEMENT = 0
	XMLELEMTYPE_TEXT = 1
	XMLELEMTYPE_COMMENT = 2
	XMLELEMTYPE_DOCUMENT = 3
	XMLELEMTYPE_DTD = 4
	XMLELEMTYPE_PI = 5
	XMLELEMTYPE_OTHER = 6
)

type FILE_INFORMATION_CLASS int32

const (
	FileDirectoryInformation = 1
)

type PROCESSINFOCLASS int32

const (
	ProcessBasicInformation = 0
	ProcessDebugPort = 7
	ProcessWow64Information = 26
	ProcessImageFileName = 27
	ProcessBreakOnTermination = 29
)

type THREADINFOCLASS int32

const (
	ThreadIsIoPending = 16
)

type SYSTEM_INFORMATION_CLASS int32

const (
	SystemBasicInformation = 0
	SystemPerformanceInformation = 2
	SystemTimeOfDayInformation = 3
	SystemProcessInformation = 5
	SystemProcessorPerformanceInformation = 8
	SystemInterruptInformation = 23
	SystemExceptionInformation = 33
	SystemRegistryQuotaInformation = 37
	SystemLookasideInformation = 45
	SystemCodeIntegrityInformation = 103
	SystemPolicyInformation = 134
)

type OBJECT_INFORMATION_CLASS int32

const (
	ObjectBasicInformation = 0
	ObjectTypeInformation = 2
)

type KEY_SET_INFORMATION_CLASS int32

const (
	KeyWriteTimeInformation = 0
	KeyWow64FlagsInformation = 1
	KeyControlFlagsInformation = 2
	KeySetVirtualizationInformation = 3
	KeySetDebugInformation = 4
	KeySetHandleTagsInformation = 5
	MaxKeySetInfoClass = 6
)

type WINSTATIONINFOCLASS int32

const (
	WinStationInformation = 8
)

type eUserAllocationState int32

const (
	AllocationStateUnknown = 0
	AllocationStateBusy = 1
	AllocationStateFree = 2
)

type eHeapAllocationState int32

const (
	HeapFullPageHeap = 1073741824
	HeapMetadata = -2147483648
	HeapStateMask = -65536
)

type eHeapEnumerationLevel int32

const (
	HeapEnumerationEverything = 0
	HeapEnumerationStop = -1
)

type eHANDLE_TRACE_OPERATIONS int32

const (
	OperationDbUnused = 0
	OperationDbOPEN = 1
	OperationDbCLOSE = 2
	OperationDbBADREF = 3
)

type eAvrfResourceTypes int32

const (
	AvrfResourceHeapAllocation = 0
	AvrfResourceHandleTrace = 1
	AvrfResourceMax = 2
)

type CameraUIControlMode int32

const (
	Browse = 0
	Linear = 1
)

type CameraUIControlLinearSelectionMode int32

const (
	Single = 0
	Multiple = 1
)

type CameraUIControlCaptureMode int32

const (
	PhotoOrVideo = 0
	Photo = 1
	Video = 2
)

type CameraUIControlPhotoFormat int32

const (
	Jpeg = 0
	Png = 1
	JpegXR = 2
)

type CameraUIControlVideoFormat int32

const (
	Mp4 = 0
	Wmv = 1
)

type CameraUIControlViewType int32

const (
	SingleItem = 0
	ItemList = 1
)

type FCIERROR int32

const (
	FCIERR_NONE = 0
	FCIERR_OPEN_SRC = 1
	FCIERR_READ_SRC = 2
	FCIERR_ALLOC_FAIL = 3
	FCIERR_TEMP_FILE = 4
	FCIERR_BAD_COMPR_TYPE = 5
	FCIERR_CAB_FILE = 6
	FCIERR_USER_ABORT = 7
	FCIERR_MCI_FAIL = 8
	FCIERR_CAB_FORMAT_LIMIT = 9
)

type FDIERROR int32

const (
	FDIERROR_NONE = 0
	FDIERROR_CABINET_NOT_FOUND = 1
	FDIERROR_NOT_A_CABINET = 2
	FDIERROR_UNKNOWN_CABINET_VERSION = 3
	FDIERROR_CORRUPT_CABINET = 4
	FDIERROR_ALLOC_FAIL = 5
	FDIERROR_BAD_COMPR_TYPE = 6
	FDIERROR_MDI_FAIL = 7
	FDIERROR_TARGET_FILE = 8
	FDIERROR_RESERVE_MISMATCH = 9
	FDIERROR_WRONG_CABINET = 10
	FDIERROR_USER_ABORT = 11
	FDIERROR_EOF = 12
)

type FDIDECRYPTTYPE int32

const (
	fdidtNEW_CABINET = 0
	fdidtNEW_FOLDER = 1
	fdidtDECRYPT = 2
)

type FDINOTIFICATIONTYPE int32

const (
	fdintCABINET_INFO = 0
	fdintPARTIAL_FILE = 1
	fdintCOPY_FILE = 2
	fdintCLOSE_FILE_INFO = 3
	fdintNEXT_CABINET = 4
	fdintENUMERATE = 5
)

type FEATURE_CHANGE_TIME int32

const (
	FEATURE_CHANGE_TIME_READ = 0
	FEATURE_CHANGE_TIME_MODULE_RELOAD = 1
	FEATURE_CHANGE_TIME_SESSION = 2
	FEATURE_CHANGE_TIME_REBOOT = 3
)

type FEATURE_ENABLED_STATE int32

const (
	FEATURE_ENABLED_STATE_DEFAULT = 0
	FEATURE_ENABLED_STATE_DISABLED = 1
	FEATURE_ENABLED_STATE_ENABLED = 2
)

type FH_TARGET_PROPERTY_TYPE int32

const (
	FH_TARGET_NAME = 0
	FH_TARGET_URL = 1
	FH_TARGET_DRIVE_TYPE = 2
	MAX_TARGET_PROPERTY = 3
)

type FH_TARGET_DRIVE_TYPES int32

const (
	FH_DRIVE_UNKNOWN = 0
	FH_DRIVE_REMOVABLE = 2
	FH_DRIVE_FIXED = 3
	FH_DRIVE_REMOTE = 4
)

type FH_PROTECTED_ITEM_CATEGORY int32

const (
	FH_FOLDER = 0
	FH_LIBRARY = 1
	MAX_PROTECTED_ITEM_CATEGORY = 2
)

type FH_LOCAL_POLICY_TYPE int32

const (
	FH_FREQUENCY = 0
	FH_RETENTION_TYPE = 1
	FH_RETENTION_AGE = 2
	MAX_LOCAL_POLICY = 3
)

type FH_RETENTION_TYPES int32

const (
	FH_RETENTION_DISABLED = 0
	FH_RETENTION_UNLIMITED = 1
	FH_RETENTION_AGE_BASED = 2
	MAX_RETENTION_TYPE = 3
)

type FH_BACKUP_STATUS int32

const (
	FH_STATUS_DISABLED = 0
	FH_STATUS_DISABLED_BY_GP = 1
	FH_STATUS_ENABLED = 2
	FH_STATUS_REHYDRATING = 3
	MAX_BACKUP_STATUS = 4
)

type FH_DEVICE_VALIDATION_RESULT int32

const (
	FH_ACCESS_DENIED = 0
	FH_INVALID_DRIVE_TYPE = 1
	FH_READ_ONLY_PERMISSION = 2
	FH_CURRENT_DEFAULT = 3
	FH_NAMESPACE_EXISTS = 4
	FH_TARGET_PART_OF_LIBRARY = 5
	FH_VALID_TARGET = 6
	MAX_VALIDATION_RESULT = 7
)

type FhBackupStopReason int32

const (
	BackupInvalidStopReason = 0
	BackupLimitUserBusyMachineOnAC = 1
	BackupLimitUserIdleMachineOnDC = 2
	BackupLimitUserBusyMachineOnDC = 3
	BackupCancelled = 4
)

type CommandStateChangeConstants int32

const (
	CSC_UPDATECOMMANDS = -1
	CSC_NAVIGATEFORWARD = 1
	CSC_NAVIGATEBACK = 2
)

type SecureLockIconConstants int32

const (
	secureLockIconUnsecure = 0
	secureLockIconMixed = 1
	secureLockIconSecureUnknownBits = 2
	secureLockIconSecure40Bit = 3
	secureLockIconSecure56Bit = 4
	secureLockIconSecureFortezza = 5
	secureLockIconSecure128Bit = 6
)

type NewProcessCauseConstants int32

const (
	ProtectedModeRedirect = 1
)

type BrowserNavConstants int32

const (
	navOpenInNewWindow = 1
	navNoHistory = 2
	navNoReadFromCache = 4
	navNoWriteToCache = 8
	navAllowAutosearch = 16
	navBrowserBar = 32
	navHyperlink = 64
	navEnforceRestricted = 128
	navNewWindowsManaged = 256
	navUntrustedForDownload = 512
	navTrustedForActiveX = 1024
	navOpenInNewTab = 2048
	navOpenInBackgroundTab = 4096
	navKeepWordWheelText = 8192
	navVirtualTab = 16384
	navBlockRedirectsXDomain = 32768
	navOpenNewForegroundTab = 65536
	navTravelLogScreenshot = 131072
	navDeferUnload = 262144
	navSpeculative = 524288
	navSuggestNewWindow = 1048576
	navSuggestNewTab = 2097152
	navReserved1 = 4194304
	navHomepageNavigate = 8388608
	navRefresh = 16777216
	navHostNavigation = 33554432
	navReserved2 = 67108864
	navReserved3 = 134217728
	navReserved4 = 268435456
	navReserved5 = 536870912
	navReserved6 = 1073741824
	navReserved7 = -2147483648
)

type RefreshConstants int32

const (
	REFRESH_NORMAL = 0
	REFRESH_IFEXPIRED = 1
	REFRESH_COMPLETELY = 3
)

type WSC_SECURITY_PRODUCT_SUBSTATUS int32

const (
	WSC_SECURITY_PRODUCT_SUBSTATUS_NOT_SET = 0
	WSC_SECURITY_PRODUCT_SUBSTATUS_NO_ACTION = 1
	WSC_SECURITY_PRODUCT_SUBSTATUS_ACTION_RECOMMENDED = 2
	WSC_SECURITY_PRODUCT_SUBSTATUS_ACTION_NEEDED = 3
)

type WSC_SECURITY_PRODUCT_STATE int32

const (
	WSC_SECURITY_PRODUCT_STATE_ON = 0
	WSC_SECURITY_PRODUCT_STATE_OFF = 1
	WSC_SECURITY_PRODUCT_STATE_SNOOZED = 2
	WSC_SECURITY_PRODUCT_STATE_EXPIRED = 3
)

type SECURITY_PRODUCT_TYPE int32

const (
	SECURITY_PRODUCT_TYPE_ANTIVIRUS = 0
	SECURITY_PRODUCT_TYPE_FIREWALL = 1
	SECURITY_PRODUCT_TYPE_ANTISPYWARE = 2
)

type WSC_SECURITY_SIGNATURE_STATUS int32

const (
	WSC_SECURITY_PRODUCT_OUT_OF_DATE = 0
	WSC_SECURITY_PRODUCT_UP_TO_DATE = 1
)

type WSC_SECURITY_PROVIDER int32

const (
	WSC_SECURITY_PROVIDER_FIREWALL = 1
	WSC_SECURITY_PROVIDER_AUTOUPDATE_SETTINGS = 2
	WSC_SECURITY_PROVIDER_ANTIVIRUS = 4
	WSC_SECURITY_PROVIDER_ANTISPYWARE = 8
	WSC_SECURITY_PROVIDER_INTERNET_SETTINGS = 16
	WSC_SECURITY_PROVIDER_USER_ACCOUNT_CONTROL = 32
	WSC_SECURITY_PROVIDER_SERVICE = 64
	WSC_SECURITY_PROVIDER_NONE = 0
	WSC_SECURITY_PROVIDER_ALL = 127
)

type WSC_SECURITY_PROVIDER_HEALTH int32

const (
	WSC_SECURITY_PROVIDER_HEALTH_GOOD = 0
	WSC_SECURITY_PROVIDER_HEALTH_NOTMONITORED = 1
	WSC_SECURITY_PROVIDER_HEALTH_POOR = 2
	WSC_SECURITY_PROVIDER_HEALTH_SNOOZE = 3
)

type TDI_TL_IO_CONTROL_TYPE int32

const (
	EndpointIoControlType = 0
	SetSockOptIoControlType = 1
	GetSockOptIoControlType = 2
	SocketIoControlType = 3
)

type WLDP_HOST int32

const (
	WLDP_HOST_RUNDLL32 = 0
	WLDP_HOST_SVCHOST = 1
	WLDP_HOST_MAX = 2
)

type WLDP_HOST_ID int32

const (
	WLDP_HOST_ID_UNKNOWN = 0
	WLDP_HOST_ID_GLOBAL = 1
	WLDP_HOST_ID_VBA = 2
	WLDP_HOST_ID_WSH = 3
	WLDP_HOST_ID_POWERSHELL = 4
	WLDP_HOST_ID_IE = 5
	WLDP_HOST_ID_MSI = 6
	WLDP_HOST_ID_ALL = 7
	WLDP_HOST_ID_MAX = 8
)

type DECISION_LOCATION int32

const (
	DECISION_LOCATION_REFRESH_GLOBAL_DATA = 0
	DECISION_LOCATION_PARAMETER_VALIDATION = 1
	DECISION_LOCATION_AUDIT = 2
	DECISION_LOCATION_FAILED_CONVERT_GUID = 3
	DECISION_LOCATION_ENTERPRISE_DEFINED_CLASS_ID = 4
	DECISION_LOCATION_GLOBAL_BUILT_IN_LIST = 5
	DECISION_LOCATION_PROVIDER_BUILT_IN_LIST = 6
	DECISION_LOCATION_ENFORCE_STATE_LIST = 7
	DECISION_LOCATION_NOT_FOUND = 8
	DECISION_LOCATION_UNKNOWN = 9
)

type WLDP_KEY int32

const (
	KEY_UNKNOWN = 0
	KEY_OVERRIDE = 1
	KEY_ALL_KEYS = 2
)

type VALUENAME int32

const (
	VALUENAME_UNKNOWN = 0
	VALUENAME_ENTERPRISE_DEFINED_CLASS_ID = 1
	VALUENAME_BUILT_IN_LIST = 2
)

type WLDP_WINDOWS_LOCKDOWN_MODE int32

const (
	WLDP_WINDOWS_LOCKDOWN_MODE_UNLOCKED = 0
	WLDP_WINDOWS_LOCKDOWN_MODE_TRIAL = 1
	WLDP_WINDOWS_LOCKDOWN_MODE_LOCKED = 2
	WLDP_WINDOWS_LOCKDOWN_MODE_MAX = 3
)

type WLDP_WINDOWS_LOCKDOWN_RESTRICTION int32

const (
	WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NONE = 0
	WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK = 1
	WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK_PERMANENT = 2
	WLDP_WINDOWS_LOCKDOWN_RESTRICTION_MAX = 3
)

type XmlNodeType int32

const (
	XmlNodeType_None = 0
	XmlNodeType_Element = 1
	XmlNodeType_Attribute = 2
	XmlNodeType_Text = 3
	XmlNodeType_CDATA = 4
	XmlNodeType_ProcessingInstruction = 7
	XmlNodeType_Comment = 8
	XmlNodeType_DocumentType = 10
	XmlNodeType_Whitespace = 13
	XmlNodeType_EndElement = 15
	XmlNodeType_XmlDeclaration = 17
	_XmlNodeType_Last = 17
)

type XmlConformanceLevel int32

const (
	XmlConformanceLevel_Auto = 0
	XmlConformanceLevel_Fragment = 1
	XmlConformanceLevel_Document = 2
	_XmlConformanceLevel_Last = 2
)

type DtdProcessing int32

const (
	DtdProcessing_Prohibit = 0
	DtdProcessing_Parse = 1
	_DtdProcessing_Last = 1
)

type XmlReadState int32

const (
	XmlReadState_Initial = 0
	XmlReadState_Interactive = 1
	XmlReadState_Error = 2
	XmlReadState_EndOfFile = 3
	XmlReadState_Closed = 4
)

type XmlReaderProperty int32

const (
	XmlReaderProperty_MultiLanguage = 0
	XmlReaderProperty_ConformanceLevel = 1
	XmlReaderProperty_RandomAccess = 2
	XmlReaderProperty_XmlResolver = 3
	XmlReaderProperty_DtdProcessing = 4
	XmlReaderProperty_ReadState = 5
	XmlReaderProperty_MaxElementDepth = 6
	XmlReaderProperty_MaxEntityExpansion = 7
	_XmlReaderProperty_Last = 7
)

type XmlError int32

const (
	MX_E_MX = -1072894464
	MX_E_INPUTEND = -1072894463
	MX_E_ENCODING = -1072894462
	MX_E_ENCODINGSWITCH = -1072894461
	MX_E_ENCODINGSIGNATURE = -1072894460
	WC_E_WC = -1072894432
	WC_E_WHITESPACE = -1072894431
	WC_E_SEMICOLON = -1072894430
	WC_E_GREATERTHAN = -1072894429
	WC_E_QUOTE = -1072894428
	WC_E_EQUAL = -1072894427
	WC_E_LESSTHAN = -1072894426
	WC_E_HEXDIGIT = -1072894425
	WC_E_DIGIT = -1072894424
	WC_E_LEFTBRACKET = -1072894423
	WC_E_LEFTPAREN = -1072894422
	WC_E_XMLCHARACTER = -1072894421
	WC_E_NAMECHARACTER = -1072894420
	WC_E_SYNTAX = -1072894419
	WC_E_CDSECT = -1072894418
	WC_E_COMMENT = -1072894417
	WC_E_CONDSECT = -1072894416
	WC_E_DECLATTLIST = -1072894415
	WC_E_DECLDOCTYPE = -1072894414
	WC_E_DECLELEMENT = -1072894413
	WC_E_DECLENTITY = -1072894412
	WC_E_DECLNOTATION = -1072894411
	WC_E_NDATA = -1072894410
	WC_E_PUBLIC = -1072894409
	WC_E_SYSTEM = -1072894408
	WC_E_NAME = -1072894407
	WC_E_ROOTELEMENT = -1072894406
	WC_E_ELEMENTMATCH = -1072894405
	WC_E_UNIQUEATTRIBUTE = -1072894404
	WC_E_TEXTXMLDECL = -1072894403
	WC_E_LEADINGXML = -1072894402
	WC_E_TEXTDECL = -1072894401
	WC_E_XMLDECL = -1072894400
	WC_E_ENCNAME = -1072894399
	WC_E_PUBLICID = -1072894398
	WC_E_PESINTERNALSUBSET = -1072894397
	WC_E_PESBETWEENDECLS = -1072894396
	WC_E_NORECURSION = -1072894395
	WC_E_ENTITYCONTENT = -1072894394
	WC_E_UNDECLAREDENTITY = -1072894393
	WC_E_PARSEDENTITY = -1072894392
	WC_E_NOEXTERNALENTITYREF = -1072894391
	WC_E_PI = -1072894390
	WC_E_SYSTEMID = -1072894389
	WC_E_QUESTIONMARK = -1072894388
	WC_E_CDSECTEND = -1072894387
	WC_E_MOREDATA = -1072894386
	WC_E_DTDPROHIBITED = -1072894385
	WC_E_INVALIDXMLSPACE = -1072894384
	NC_E_NC = -1072894368
	NC_E_QNAMECHARACTER = -1072894367
	NC_E_QNAMECOLON = -1072894366
	NC_E_NAMECOLON = -1072894365
	NC_E_DECLAREDPREFIX = -1072894364
	NC_E_UNDECLAREDPREFIX = -1072894363
	NC_E_EMPTYURI = -1072894362
	NC_E_XMLPREFIXRESERVED = -1072894361
	NC_E_XMLNSPREFIXRESERVED = -1072894360
	NC_E_XMLURIRESERVED = -1072894359
	NC_E_XMLNSURIRESERVED = -1072894358
	SC_E_SC = -1072894336
	SC_E_MAXELEMENTDEPTH = -1072894335
	SC_E_MAXENTITYEXPANSION = -1072894334
	WR_E_WR = -1072894208
	WR_E_NONWHITESPACE = -1072894207
	WR_E_NSPREFIXDECLARED = -1072894206
	WR_E_NSPREFIXWITHEMPTYNSURI = -1072894205
	WR_E_DUPLICATEATTRIBUTE = -1072894204
	WR_E_XMLNSPREFIXDECLARATION = -1072894203
	WR_E_XMLPREFIXDECLARATION = -1072894202
	WR_E_XMLURIDECLARATION = -1072894201
	WR_E_XMLNSURIDECLARATION = -1072894200
	WR_E_NAMESPACEUNDECLARED = -1072894199
	WR_E_INVALIDXMLSPACE = -1072894198
	WR_E_INVALIDACTION = -1072894197
	WR_E_INVALIDSURROGATEPAIR = -1072894196
	XML_E_INVALID_DECIMAL = -1072898019
	XML_E_INVALID_HEXIDECIMAL = -1072898018
	XML_E_INVALID_UNICODE = -1072898017
	XML_E_INVALIDENCODING = -1072897938
)

type XmlStandalone int32

const (
	XmlStandalone_Omit = 0
	XmlStandalone_Yes = 1
	XmlStandalone_No = 2
	_XmlStandalone_Last = 2
)

type XmlWriterProperty int32

const (
	XmlWriterProperty_MultiLanguage = 0
	XmlWriterProperty_Indent = 1
	XmlWriterProperty_ByteOrderMark = 2
	XmlWriterProperty_OmitXmlDeclaration = 3
	XmlWriterProperty_ConformanceLevel = 4
	XmlWriterProperty_CompactEmptyElement = 5
	_XmlWriterProperty_Last = 5
)

type DEVPROP_OPERATOR int32

const (
	DEVPROP_OPERATOR_MODIFIER_NOT = 65536
	DEVPROP_OPERATOR_MODIFIER_IGNORE_CASE = 131072
	DEVPROP_OPERATOR_NONE = 0
	DEVPROP_OPERATOR_EXISTS = 1
	DEVPROP_OPERATOR_NOT_EXISTS = 65537
	DEVPROP_OPERATOR_EQUALS = 2
	DEVPROP_OPERATOR_NOT_EQUALS = 65538
	DEVPROP_OPERATOR_GREATER_THAN = 3
	DEVPROP_OPERATOR_LESS_THAN = 4
	DEVPROP_OPERATOR_GREATER_THAN_EQUALS = 5
	DEVPROP_OPERATOR_LESS_THAN_EQUALS = 6
	DEVPROP_OPERATOR_EQUALS_IGNORE_CASE = 131074
	DEVPROP_OPERATOR_NOT_EQUALS_IGNORE_CASE = 196610
	DEVPROP_OPERATOR_BITWISE_AND = 7
	DEVPROP_OPERATOR_BITWISE_OR = 8
	DEVPROP_OPERATOR_BEGINS_WITH = 9
	DEVPROP_OPERATOR_ENDS_WITH = 10
	DEVPROP_OPERATOR_CONTAINS = 11
	DEVPROP_OPERATOR_BEGINS_WITH_IGNORE_CASE = 131081
	DEVPROP_OPERATOR_ENDS_WITH_IGNORE_CASE = 131082
	DEVPROP_OPERATOR_CONTAINS_IGNORE_CASE = 131083
	DEVPROP_OPERATOR_LIST_CONTAINS = 4096
	DEVPROP_OPERATOR_LIST_ELEMENT_BEGINS_WITH = 8192
	DEVPROP_OPERATOR_LIST_ELEMENT_ENDS_WITH = 12288
	DEVPROP_OPERATOR_LIST_ELEMENT_CONTAINS = 16384
	DEVPROP_OPERATOR_LIST_CONTAINS_IGNORE_CASE = 135168
	DEVPROP_OPERATOR_LIST_ELEMENT_BEGINS_WITH_IGNORE_CASE = 139264
	DEVPROP_OPERATOR_LIST_ELEMENT_ENDS_WITH_IGNORE_CASE = 143360
	DEVPROP_OPERATOR_LIST_ELEMENT_CONTAINS_IGNORE_CASE = 147456
	DEVPROP_OPERATOR_AND_OPEN = 1048576
	DEVPROP_OPERATOR_AND_CLOSE = 2097152
	DEVPROP_OPERATOR_OR_OPEN = 3145728
	DEVPROP_OPERATOR_OR_CLOSE = 4194304
	DEVPROP_OPERATOR_NOT_OPEN = 5242880
	DEVPROP_OPERATOR_NOT_CLOSE = 6291456
	DEVPROP_OPERATOR_ARRAY_CONTAINS = 268435456
	DEVPROP_OPERATOR_MASK_EVAL = 4095
	DEVPROP_OPERATOR_MASK_LIST = 61440
	DEVPROP_OPERATOR_MASK_MODIFIER = 983040
	DEVPROP_OPERATOR_MASK_NOT_LOGICAL = -267386881
	DEVPROP_OPERATOR_MASK_LOGICAL = 267386880
	DEVPROP_OPERATOR_MASK_ARRAY = -268435456
)

type DEV_OBJECT_TYPE int32

const (
	DevObjectTypeUnknown = 0
	DevObjectTypeDeviceInterface = 1
	DevObjectTypeDeviceContainer = 2
	DevObjectTypeDevice = 3
	DevObjectTypeDeviceInterfaceClass = 4
	DevObjectTypeAEP = 5
	DevObjectTypeAEPContainer = 6
	DevObjectTypeDeviceInstallerClass = 7
	DevObjectTypeDeviceInterfaceDisplay = 8
	DevObjectTypeDeviceContainerDisplay = 9
	DevObjectTypeAEPService = 10
	DevObjectTypeDevicePanel = 11
)

type DEV_QUERY_FLAGS int32

const (
	DevQueryFlagNone = 0
	DevQueryFlagUpdateResults = 1
	DevQueryFlagAllProperties = 2
	DevQueryFlagLocalize = 4
	DevQueryFlagAsyncClose = 8
)

type DEV_QUERY_STATE int32

const (
	DevQueryStateInitialized = 0
	DevQueryStateEnumCompleted = 1
	DevQueryStateAborted = 2
	DevQueryStateClosed = 3
)

type DEV_QUERY_RESULT_ACTION int32

const (
	DevQueryResultStateChange = 0
	DevQueryResultAdd = 1
	DevQueryResultUpdate = 2
	DevQueryResultRemove = 3
)

type _GlobalFilter int32

const (
	GF_FRAGMENTS = 2
	GF_STRONGHOST = 8
	GF_FRAGCACHE = 9
)

type _PfForwardAction int32

const (
	PF_ACTION_FORWARD = 0
	PF_ACTION_DROP = 1
)

type _PfAddresType int32

const (
	PF_IPV4 = 0
	PF_IPV6 = 1
)

type _PfFrameType int32

const (
	PFFT_FILTER = 1
	PFFT_FRAG = 2
	PFFT_SPOOF = 3
)

type EXTENDED_NAME_FORMAT int32

const (
	NameUnknown = 0
	NameFullyQualifiedDN = 1
	NameSamCompatible = 2
	NameDisplay = 3
	NameUniqueId = 6
	NameCanonical = 7
	NameUserPrincipal = 8
	NameCanonicalEx = 9
	NameServicePrincipal = 10
	NameDnsDomain = 12
	NameGivenName = 13
	NameSurname = 14
)

