// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package p2p implements the Windows.Win32.P2P namespace.
package p2p

type PNRP_CLOUD_ID struct {
	AddressFamily int
	Scope         int
	ScopeId       int
}

type PNRPINFO_V1 struct {
	DWSIZE            int
	LPWSZIDENTITY     int
	NMAXRESOLVE       int
	DWTIMEOUT         int
	DWLIFETIME        int
	ENRESOLVECRITERIA int
	DWFLAGS           int
	SAHINT            int
	ENNAMESTATE       int
}

type PNRPINFO_V2 struct {
	DWSIZE                int
	LPWSZIDENTITY         int
	NMAXRESOLVE           int
	DWTIMEOUT             int
	DWLIFETIME            int
	ENRESOLVECRITERIA     int
	DWFLAGS               int
	SAHINT                int
	ENNAMESTATE           int
	ENEXTENDEDPAYLOADTYPE int
	Anonymous             int
}

type PNRPCLOUDINFO struct {
	DWSIZE       int
	Cloud        int
	ENCLOUDSTATE int
	ENCLOUDFLAGS int
}

type PEER_VERSION_DATA struct {
	WVERSION        int
	WHIGHESTVERSION int
}

type PEER_DATA struct {
	CBDATA int
	PBDATA int
}

type PEER_RECORD struct {
	DWSIZE          int
	TYPE            int
	ID              int
	DWVERSION       int
	DWFLAGS         int
	PWZCREATORID    int
	PWZMODIFIEDBYID int
	PWZATTRIBUTES   int
	FTCREATION      int
	FTEXPIRATION    int
	FTLASTMODIFIED  int
	SECURITYDATA    int
	DATA            int
}

type PEER_ADDRESS struct {
	DWSIZE int
	SIN6   int
}

type PEER_CONNECTION_INFO struct {
	DWSIZE          int
	DWFLAGS         int
	ULLCONNECTIONID int
	ULLNODEID       int
	PWZPEERID       int
	ADDRESS         int
}

type PEER_EVENT_INCOMING_DATA struct {
	DWSIZE          int
	ULLCONNECTIONID int
	TYPE            int
	DATA            int
}

type PEER_EVENT_RECORD_CHANGE_DATA struct {
	DWSIZE     int
	CHANGETYPE int
	RECORDID   int
	RECORDTYPE int
}

type PEER_EVENT_CONNECTION_CHANGE_DATA struct {
	DWSIZE                   int
	STATUS                   int
	ULLCONNECTIONID          int
	ULLNODEID                int
	ULLNEXTCONNECTIONID      int
	HRCONNECTIONFAILEDREASON int
}

type PEER_EVENT_SYNCHRONIZED_DATA struct {
	DWSIZE     int
	RECORDTYPE int
}

type PEER_GRAPH_PROPERTIES struct {
	DWSIZE             int
	DWFLAGS            int
	DWSCOPE            int
	DWMAXRECORDSIZE    int
	PWZGRAPHID         int
	PWZCREATORID       int
	PWZFRIENDLYNAME    int
	PWZCOMMENT         int
	ULPRESENCELIFETIME int
	CPRESENCEMAX       int
}

type PEER_NODE_INFO struct {
	DWSIZE        int
	ULLNODEID     int
	PWZPEERID     int
	CADDRESSES    int
	PADDRESSES    int
	PWZATTRIBUTES int
}

type PEER_EVENT_NODE_CHANGE_DATA struct {
	DWSIZE     int
	CHANGETYPE int
	ULLNODEID  int
	PWZPEERID  int
}

type PEER_GRAPH_EVENT_REGISTRATION struct {
	EVENTTYPE int
	PTYPE     int
}

type PEER_GRAPH_EVENT_DATA struct {
	EVENTTYPE int
	Anonymous int
}

type PEER_SECURITY_INTERFACE struct {
	DWSIZE              int
	PWZSSPFILENAME      int
	PWZPACKAGENAME      int
	CBSECURITYINFO      int
	PBSECURITYINFO      int
	PVCONTEXT           int
	PFNVALIDATERECORD   int
	PFNSECURERECORD     int
	PFNFREESECURITYDATA int
	PFNAUTHFAILED       int
}

type PEER_CREDENTIAL_INFO struct {
	DWSIZE                int
	DWFLAGS               int
	PWZFRIENDLYNAME       int
	PPUBLICKEY            int
	PWZISSUERPEERNAME     int
	PWZISSUERFRIENDLYNAME int
	FTVALIDITYSTART       int
	FTVALIDITYEND         int
	CROLES                int
	PROLES                int
}

type PEER_MEMBER struct {
	DWSIZE          int
	DWFLAGS         int
	PWZIDENTITY     int
	PWZATTRIBUTES   int
	ULLNODEID       int
	CADDRESSES      int
	PADDRESSES      int
	PCREDENTIALINFO int
}

type PEER_INVITATION_INFO struct {
	DWSIZE                 int
	DWFLAGS                int
	PWZCLOUDNAME           int
	DWSCOPE                int
	DWCLOUDFLAGS           int
	PWZGROUPPEERNAME       int
	PWZISSUERPEERNAME      int
	PWZSUBJECTPEERNAME     int
	PWZGROUPFRIENDLYNAME   int
	PWZISSUERFRIENDLYNAME  int
	PWZSUBJECTFRIENDLYNAME int
	FTVALIDITYSTART        int
	FTVALIDITYEND          int
	CROLES                 int
	PROLES                 int
	CCLASSIFIERS           int
	PPWZCLASSIFIERS        int
	PSUBJECTPUBLICKEY      int
	AUTHSCHEME             int
}

type PEER_GROUP_PROPERTIES struct {
	DWSIZE                  int
	DWFLAGS                 int
	PWZCLOUD                int
	PWZCLASSIFIER           int
	PWZGROUPPEERNAME        int
	PWZCREATORPEERNAME      int
	PWZFRIENDLYNAME         int
	PWZCOMMENT              int
	ULMEMBERDATALIFETIME    int
	ULPRESENCELIFETIME      int
	DWAUTHENTICATIONSCHEMES int
	PWZGROUPPASSWORD        int
	GROUPPASSWORDROLE       int
}

type PEER_EVENT_MEMBER_CHANGE_DATA struct {
	DWSIZE      int
	CHANGETYPE  int
	PWZIDENTITY int
}

type PEER_GROUP_EVENT_REGISTRATION struct {
	EVENTTYPE int
	PTYPE     int
}

type PEER_GROUP_EVENT_DATA struct {
	EVENTTYPE int
	Anonymous int
}

type PEER_NAME_PAIR struct {
	DWSIZE          int
	PWZPEERNAME     int
	PWZFRIENDLYNAME int
}

type PEER_APPLICATION struct {
	ID             int
	DATA           int
	PWZDESCRIPTION int
}

type PEER_OBJECT struct {
	ID                 int
	DATA               int
	DWPUBLICATIONSCOPE int
}

type PEER_CONTACT struct {
	PWZPEERNAME        int
	PWZNICKNAME        int
	PWZDISPLAYNAME     int
	PWZEMAILADDRESS    int
	FWATCH             int
	WatcherPermissions int
	CREDENTIALS        int
}

type PEER_ENDPOINT struct {
	ADDRESS         int
	PWZENDPOINTNAME int
}

type PEER_PEOPLE_NEAR_ME struct {
	PWZNICKNAME int
	ENDPOINT    int
	ID          int
}

type PEER_INVITATION struct {
	APPLICATIONID   int
	APPLICATIONDATA int
	PWZMESSAGE      int
}

type PEER_INVITATION_RESPONSE struct {
	ACTION         int
	PWZMESSAGE     int
	HREXTENDEDINFO int
}

type PEER_APP_LAUNCH_INFO struct {
	PCONTACT    int
	PENDPOINT   int
	PINVITATION int
}

type PEER_APPLICATION_REGISTRATION_INFO struct {
	APPLICATION             int
	PWZAPPLICATIONTOLAUNCH  int
	PWZAPPLICATIONARGUMENTS int
	DWPUBLICATIONSCOPE      int
}

type PEER_PRESENCE_INFO struct {
	STATUS             int
	PWZDESCRIPTIVETEXT int
}

type PEER_COLLAB_EVENT_REGISTRATION struct {
	EVENTTYPE int
	PINSTANCE int
}

type PEER_EVENT_WATCHLIST_CHANGED_DATA struct {
	PCONTACT   int
	CHANGETYPE int
}

type PEER_EVENT_PRESENCE_CHANGED_DATA struct {
	PCONTACT      int
	PENDPOINT     int
	CHANGETYPE    int
	PPRESENCEINFO int
}

type PEER_EVENT_APPLICATION_CHANGED_DATA struct {
	PCONTACT     int
	PENDPOINT    int
	CHANGETYPE   int
	PAPPLICATION int
}

type PEER_EVENT_OBJECT_CHANGED_DATA struct {
	PCONTACT   int
	PENDPOINT  int
	CHANGETYPE int
	POBJECT    int
}

type PEER_EVENT_ENDPOINT_CHANGED_DATA struct {
	PCONTACT  int
	PENDPOINT int
}

type PEER_EVENT_PEOPLE_NEAR_ME_CHANGED_DATA struct {
	CHANGETYPE    int
	PPEOPLENEARME int
}

type PEER_EVENT_REQUEST_STATUS_CHANGED_DATA struct {
	PENDPOINT int
	HRCHANGE  int
}

type PEER_COLLAB_EVENT_DATA struct {
	EVENTTYPE int
	Anonymous int
}

type PEER_PNRP_ENDPOINT_INFO struct {
	PWZPEERNAME int
	CADDRESSES  int
	PPADDRESSES int
	PWZCOMMENT  int
	PAYLOAD     int
}

type PEER_PNRP_CLOUD_INFO struct {
	PWZCLOUDNAME int
	DWSCOPE      int
	DWSCOPEID    int
}

type PEER_PNRP_REGISTRATION_INFO struct {
	PWZCLOUDNAME          int
	PWZPUBLISHINGIDENTITY int
	CADDRESSES            int
	PPADDRESSES           int
	WPORT                 int
	PWZCOMMENT            int
	PAYLOAD               int
}

type DRT_DATA struct {
	CB int
	PB int
}

type DRT_REGISTRATION struct {
	KEY     int
	APPDATA int
}

type DRT_SECURITY_PROVIDER struct {
	PVCONTEXT                int
	Attach                   int
	Detach                   int
	RegisterKey              int
	UnregisterKey            int
	ValidateAndUnpackPayload int
	SecureAndPackPayload     int
	FreeData                 int
	EncryptData              int
	DecryptData              int
	GetSerializedCredential  int
	ValidateRemoteCredential int
	SignData                 int
	VerifyData               int
}

type DRT_BOOTSTRAP_PROVIDER struct {
	PVCONTEXT    int
	Attach       int
	Detach       int
	InitResolve  int
	IssueResolve int
	EndResolve   int
	Register     int
	Unregister   int
}

type DRT_SETTINGS struct {
	DWSIZE                int
	CBKEY                 int
	BPROTOCOLMAJORVERSION int
	BPROTOCOLMINORVERSION int
	ULMAXROUTINGADDRESSES int
	PWZDRTINSTANCEPREFIX  int
	HTRANSPORT            int
	PSECURITYPROVIDER     int
	PBOOTSTRAPPROVIDER    int
	ESECURITYMODE         int
}

type DRT_SEARCH_INFO struct {
	DWSIZE                     int
	FITERATIVE                 int
	FALLOWCURRENTINSTANCEMATCH int
	FANYMATCHINRANGE           int
	CMAXENDPOINTS              int
	PMAXIMUMKEY                int
	PMINIMUMKEY                int
}

type DRT_ADDRESS struct {
	SOCKETADDRESS int
	FLAGS         int
	NEARNESS      int
	LATENCY       int
}

type DRT_ADDRESS_LIST struct {
	AddressCount int
	AddressList  int
}

type DRT_SEARCH_RESULT struct {
	DWSIZE       int
	TYPE         int
	PVCONTEXT    int
	REGISTRATION int
}

type DRT_EVENT_DATA struct {
	TYPE      int
	HR        int
	PVCONTEXT int
	Anonymous int
}

type PEERDIST_PUBLICATION_OPTIONS struct {
	DWVERSION int
	DWFLAGS   int
}

type PEERDIST_CONTENT_TAG struct {
	Data int
}

type PEERDIST_RETRIEVAL_OPTIONS struct {
	CBSIZE                  int
	DWCONTENTINFOMINVERSION int
	DWCONTENTINFOMAXVERSION int
	DWRESERVED              int
}

type PEERDIST_STATUS_INFO struct {
	CBSIZE   int
	STATUS   int
	DWMINVER int
	DWMAXVER int
}

type PEERDIST_CLIENT_BASIC_INFO struct {
	FFLASHCROWD int
}
