// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowserrorreporting implements the Windows.Win32.WindowsErrorReporting namespace.
package windowserrorreporting

type WER_REPORT_UI int32

const (
	WerUIAdditionalDataDlgHeader  WER_REPORT_UI = 1
	WerUIIconFilePath             WER_REPORT_UI = 2
	WerUIConsentDlgHeader         WER_REPORT_UI = 3
	WerUIConsentDlgBody           WER_REPORT_UI = 4
	WerUIOnlineSolutionCheckText  WER_REPORT_UI = 5
	WerUIOfflineSolutionCheckText WER_REPORT_UI = 6
	WerUICloseText                WER_REPORT_UI = 7
	WerUICloseDlgHeader           WER_REPORT_UI = 8
	WerUICloseDlgBody             WER_REPORT_UI = 9
	WerUICloseDlgButtonText       WER_REPORT_UI = 10
	WerUIMax                      WER_REPORT_UI = 11
)

type WER_REGISTER_FILE_TYPE int32

const (
	WerRegFileTypeUserDocument WER_REGISTER_FILE_TYPE = 1
	WerRegFileTypeOther        WER_REGISTER_FILE_TYPE = 2
	WerRegFileTypeMax          WER_REGISTER_FILE_TYPE = 3
)

type WER_FILE_TYPE int32

const (
	WerFileTypeMicrodump     WER_FILE_TYPE = 1
	WerFileTypeMinidump      WER_FILE_TYPE = 2
	WerFileTypeHeapdump      WER_FILE_TYPE = 3
	WerFileTypeUserDocument  WER_FILE_TYPE = 4
	WerFileTypeOther         WER_FILE_TYPE = 5
	WerFileTypeTriagedump    WER_FILE_TYPE = 6
	WerFileTypeCustomDump    WER_FILE_TYPE = 7
	WerFileTypeAuxiliaryDump WER_FILE_TYPE = 8
	WerFileTypeEtlTrace      WER_FILE_TYPE = 9
	WerFileTypeMax           WER_FILE_TYPE = 10
)

type WER_SUBMIT_RESULT int32

const (
	WerReportQueued            WER_SUBMIT_RESULT = 1
	WerReportUploaded          WER_SUBMIT_RESULT = 2
	WerReportDebug             WER_SUBMIT_RESULT = 3
	WerReportFailed            WER_SUBMIT_RESULT = 4
	WerDisabled                WER_SUBMIT_RESULT = 5
	WerReportCancelled         WER_SUBMIT_RESULT = 6
	WerDisabledQueue           WER_SUBMIT_RESULT = 7
	WerReportAsync             WER_SUBMIT_RESULT = 8
	WerCustomAction            WER_SUBMIT_RESULT = 9
	WerThrottled               WER_SUBMIT_RESULT = 10
	WerReportUploadedCab       WER_SUBMIT_RESULT = 11
	WerStorageLocationNotFound WER_SUBMIT_RESULT = 12
	WerSubmitResultMax         WER_SUBMIT_RESULT = 13
)

type WER_REPORT_TYPE int32

const (
	WerReportNonCritical      WER_REPORT_TYPE = 0
	WerReportCritical         WER_REPORT_TYPE = 1
	WerReportApplicationCrash WER_REPORT_TYPE = 2
	WerReportApplicationHang  WER_REPORT_TYPE = 3
	WerReportKernel           WER_REPORT_TYPE = 4
	WerReportInvalid          WER_REPORT_TYPE = 5
)

type WER_CONSENT int32

const (
	WerConsentNotAsked     WER_CONSENT = 1
	WerConsentApproved     WER_CONSENT = 2
	WerConsentDenied       WER_CONSENT = 3
	WerConsentAlwaysPrompt WER_CONSENT = 4
	WerConsentMax          WER_CONSENT = 5
)

type WER_DUMP_TYPE int32

const (
	WerDumpTypeNone       WER_DUMP_TYPE = 0
	WerDumpTypeMicroDump  WER_DUMP_TYPE = 1
	WerDumpTypeMiniDump   WER_DUMP_TYPE = 2
	WerDumpTypeHeapDump   WER_DUMP_TYPE = 3
	WerDumpTypeTriageDump WER_DUMP_TYPE = 4
	WerDumpTypeMax        WER_DUMP_TYPE = 5
)

type REPORT_STORE_TYPES int32

const (
	E_STORE_USER_ARCHIVE    REPORT_STORE_TYPES = 0
	E_STORE_USER_QUEUE      REPORT_STORE_TYPES = 1
	E_STORE_MACHINE_ARCHIVE REPORT_STORE_TYPES = 2
	E_STORE_MACHINE_QUEUE   REPORT_STORE_TYPES = 3
	E_STORE_INVALID         REPORT_STORE_TYPES = 4
)

type EFaultRepRetVal int32

const (
	FRRVOK                 EFaultRepRetVal = 0
	FRRVOKMANIFEST         EFaultRepRetVal = 1
	FRRVOKQUEUED           EFaultRepRetVal = 2
	FRRVERR                EFaultRepRetVal = 3
	FRRVERRNODW            EFaultRepRetVal = 4
	FRRVERRTIMEOUT         EFaultRepRetVal = 5
	FRRVLAUNCHDEBUGGER     EFaultRepRetVal = 6
	FRRVOKHEADLESS         EFaultRepRetVal = 7
	FRRVERRANOTHERINSTANCE EFaultRepRetVal = 8
	FRRVERRNOMEMORY        EFaultRepRetVal = 9
	FRRVERRDOUBLEFAULT     EFaultRepRetVal = 10
)
