// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package networkpolicyserver implements the Windows.Win32.NetworkPolicyServer namespace.
package networkpolicyserver

type SdoMachine struct {
}

type RADIUS_ATTRIBUTE struct {
	DWATTRTYPE   int
	FDATATYPE    int
	CBDATALENGTH int
	Anonymous    int
}

type RADIUS_VSA_FORMAT struct {
	VendorId          int
	VendorType        int
	VendorLength      int
	AttributeSpecific int
}

type RADIUS_ATTRIBUTE_ARRAY struct {
	CBSIZE      int
	Add         int
	AttributeAt int
	GetSize     int
	InsertAt    int
	RemoveAt    int
	SetAt       int
}

type RADIUS_EXTENSION_CONTROL_BLOCK struct {
	CBSIZE          int
	DWVERSION       int
	REPPOINT        int
	RCREQUESTTYPE   int
	RCRESPONSETYPE  int
	GetRequest      int
	GetResponse     int
	SetResponseType int
}
