// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package http implements the Windows.Win32.Http namespace.
package http

type HTTP_PROPERTY_FLAGS struct {
	BITFIELD int
}

type HTTP_STATE_INFO struct {
	Flags int
	State int
}

type HTTP_QOS_SETTING_INFO struct {
	QosType    int
	QosSetting int
}

type HTTP_CONNECTION_LIMIT_INFO struct {
	Flags          int
	MaxConnections int
}

type HTTP_BANDWIDTH_LIMIT_INFO struct {
	Flags        int
	MaxBandwidth int
}

type HTTP_FLOWRATE_INFO struct {
	Flags            int
	MaxBandwidth     int
	MaxPeakBandwidth int
	BurstSize        int
}

type HTTP_SERVICE_CONFIG_TIMEOUT_SET struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_TIMEOUT_LIMIT_INFO struct {
	Flags           int
	EntityBody      int
	DrainEntityBody int
	RequestQueue    int
	IdleConnection  int
	HeaderWait      int
	MinSendRate     int
}

type HTTP_SERVICE_CONFIG_SETTING_SET struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_LISTEN_ENDPOINT_INFO struct {
	Flags         int
	EnableSharing int
}

type HTTP_SERVER_AUTHENTICATION_DIGEST_PARAMS struct {
	DomainNameLength int
	DomainName       int
	RealmLength      int
	Realm            int
}

type HTTP_SERVER_AUTHENTICATION_BASIC_PARAMS struct {
	RealmLength int
	Realm       int
}

type HTTP_SERVER_AUTHENTICATION_INFO struct {
	Flags                        int
	AuthSchemes                  int
	ReceiveMutualAuth            int
	ReceiveContextHandle         int
	DisableNTLMCredentialCaching int
	ExFlags                      int
	DigestParams                 int
	BasicParams                  int
}

type HTTP_SERVICE_BINDING_BASE struct {
	Type int
}

type HTTP_SERVICE_BINDING_A struct {
	Base       int
	Buffer     int
	BufferSize int
}

type HTTP_SERVICE_BINDING_W struct {
	Base       int
	Buffer     int
	BufferSize int
}

type HTTP_CHANNEL_BIND_INFO struct {
	Hardening            int
	Flags                int
	ServiceNames         int
	NumberOfServiceNames int
}

type HTTP_REQUEST_CHANNEL_BIND_STATUS struct {
	ServiceName      int
	ChannelToken     int
	ChannelTokenSize int
	Flags            int
}

type HTTP_REQUEST_TOKEN_BINDING_INFO struct {
	TokenBinding     int
	TokenBindingSize int
	EKM              int
	EKMSize          int
	KeyType          int
}

type HTTP_LOGGING_INFO struct {
	Flags               int
	LoggingFlags        int
	SoftwareName        int
	SoftwareNameLength  int
	DirectoryNameLength int
	DirectoryName       int
	Format              int
	Fields              int
	PEXTFIELDS          int
	NumOfExtFields      int
	MaxRecordSize       int
	RolloverType        int
	RolloverSize        int
	PSECURITYDESCRIPTOR int
}

type HTTP_BINDING_INFO struct {
	Flags              int
	RequestQueueHandle int
}

type HTTP_PROTECTION_LEVEL_INFO struct {
	Flags int
	Level int
}

type HTTP_BYTE_RANGE struct {
	StartingOffset int
	Length         int
}

type HTTP_VERSION struct {
	MajorVersion int
	MinorVersion int
}

type HTTP_KNOWN_HEADER struct {
	RawValueLength int
	PRAWVALUE      int
}

type HTTP_UNKNOWN_HEADER struct {
	NameLength     int
	RawValueLength int
	PNAME          int
	PRAWVALUE      int
}

type HTTP_LOG_DATA struct {
	Type int
}

type HTTP_LOG_FIELDS_DATA struct {
	Base              int
	UserNameLength    int
	UriStemLength     int
	ClientIpLength    int
	ServerNameLength  int
	ServiceNameLength int
	ServerIpLength    int
	MethodLength      int
	UriQueryLength    int
	HostLength        int
	UserAgentLength   int
	CookieLength      int
	ReferrerLength    int
	UserName          int
	UriStem           int
	ClientIp          int
	ServerName        int
	ServiceName       int
	ServerIp          int
	Method            int
	UriQuery          int
	Host              int
	UserAgent         int
	Cookie            int
	Referrer          int
	ServerPort        int
	ProtocolStatus    int
	Win32Status       int
	MethodNum         int
	SubStatus         int
}

type HTTP_DATA_CHUNK struct {
	DataChunkType int
	Anonymous     int
}

type HTTP_REQUEST_HEADERS struct {
	UnknownHeaderCount int
	PUNKNOWNHEADERS    int
	TrailerCount       int
	PTRAILERS          int
	KnownHeaders       int
}

type HTTP_RESPONSE_HEADERS struct {
	UnknownHeaderCount int
	PUNKNOWNHEADERS    int
	TrailerCount       int
	PTRAILERS          int
	KnownHeaders       int
}

type HTTP_DELEGATE_REQUEST_PROPERTY_INFO struct {
	ProperyId          int
	PropertyInfoLength int
	PropertyInfo       int
}

type HTTP_TRANSPORT_ADDRESS struct {
	PREMOTEADDRESS int
	PLOCALADDRESS  int
}

type HTTP_COOKED_URL struct {
	FullUrlLength     int
	HostLength        int
	AbsPathLength     int
	QueryStringLength int
	PFULLURL          int
	PHOST             int
	PABSPATH          int
	PQUERYSTRING      int
}

type HTTP_SSL_CLIENT_CERT_INFO struct {
	CertFlags          int
	CertEncodedSize    int
	PCERTENCODED       int
	Token              int
	CertDeniedByMapper int
}

type HTTP_SSL_INFO struct {
	ServerCertKeySize       int
	ConnectionKeySize       int
	ServerCertIssuerSize    int
	ServerCertSubjectSize   int
	PSERVERCERTISSUER       int
	PSERVERCERTSUBJECT      int
	PCLIENTCERTINFO         int
	SslClientCertNegotiated int
}

type HTTP_SSL_PROTOCOL_INFO struct {
	Protocol            int
	CipherType          int
	CipherStrength      int
	HashType            int
	HashStrength        int
	KeyExchangeType     int
	KeyExchangeStrength int
}

type HTTP_REQUEST_SIZING_INFO struct {
	Flags              int
	RequestIndex       int
	RequestSizingCount int
	RequestSizing      int
}

type HTTP_REQUEST_TIMING_INFO struct {
	RequestTimingCount int
	RequestTiming      int
}

type HTTP_REQUEST_INFO struct {
	InfoType   int
	InfoLength int
	PINFO      int
}

type HTTP_REQUEST_AUTH_INFO struct {
	AuthStatus           int
	SecStatus            int
	Flags                int
	AuthType             int
	AccessToken          int
	ContextAttributes    int
	PackedContextLength  int
	PackedContextType    int
	PackedContext        int
	MutualAuthDataLength int
	PMUTUALAUTHDATA      int
	PackageNameLength    int
	PPACKAGENAME         int
}

type HTTP_REQUEST_V1 struct {
	Flags             int
	ConnectionId      int
	RequestId         int
	UrlContext        int
	Version           int
	Verb              int
	UnknownVerbLength int
	RawUrlLength      int
	PUNKNOWNVERB      int
	PRAWURL           int
	CookedUrl         int
	Address           int
	Headers           int
	BytesReceived     int
	EntityChunkCount  int
	PENTITYCHUNKS     int
	RawConnectionId   int
	PSSLINFO          int
}

type HTTP_REQUEST_V2 struct {
	AnonymousBase_http_L1816_C35 int
	RequestInfoCount             int
	PREQUESTINFO                 int
}

type HTTP_RESPONSE_V1 struct {
	Flags            int
	Version          int
	StatusCode       int
	ReasonLength     int
	PREASON          int
	Headers          int
	EntityChunkCount int
	PENTITYCHUNKS    int
}

type HTTP_RESPONSE_INFO struct {
	Type   int
	Length int
	PINFO  int
}

type HTTP_MULTIPLE_KNOWN_HEADERS struct {
	HeaderId         int
	Flags            int
	KnownHeaderCount int
	KnownHeaders     int
}

type HTTP_RESPONSE_V2 struct {
	AnonymousBase_http_L2003_C36 int
	ResponseInfoCount            int
	PRESPONSEINFO                int
}

type HTTPAPI_VERSION struct {
	HttpApiMajorVersion int
	HttpApiMinorVersion int
}

type HTTP_CACHE_POLICY struct {
	Policy        int
	SecondsToLive int
}

type HTTP_SERVICE_CONFIG_SSL_KEY struct {
	PIPPORT int
}

type HTTP_SERVICE_CONFIG_SSL_KEY_EX struct {
	IpPort int
}

type HTTP_SERVICE_CONFIG_SSL_SNI_KEY struct {
	IpPort int
	Host   int
}

type HTTP_SERVICE_CONFIG_SSL_CCS_KEY struct {
	LocalAddress int
}

type HTTP_SERVICE_CONFIG_SSL_PARAM struct {
	SslHashLength                        int
	PSSLHASH                             int
	AppId                                int
	PSSLCERTSTORENAME                    int
	DefaultCertCheckMode                 int
	DefaultRevocationFreshnessTime       int
	DefaultRevocationUrlRetrievalTimeout int
	PDEFAULTSSLCTLIDENTIFIER             int
	PDEFAULTSSLCTLSTORENAME              int
	DefaultFlags                         int
}

type HTTP2_WINDOW_SIZE_PARAM struct {
	Http2ReceiveWindowSize int
}

type HTTP2_SETTINGS_LIMITS_PARAM struct {
	Http2MaxSettingsPerFrame  int
	Http2MaxSettingsPerMinute int
}

type HTTP_PERFORMANCE_PARAM struct {
	SendBufferingFlags         int
	EnableAggressiveICW        int
	MaxBufferedSendBytes       int
	MaxConcurrentClientStreams int
}

type HTTP_SERVICE_CONFIG_SSL_PARAM_EX struct {
	ParamType int
	Flags     int
	Anonymous int
}

type HTTP_SERVICE_CONFIG_SSL_SET struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_SERVICE_CONFIG_SSL_SNI_SET struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_SERVICE_CONFIG_SSL_CCS_SET struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_SERVICE_CONFIG_SSL_SET_EX struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_SERVICE_CONFIG_SSL_SNI_SET_EX struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_SERVICE_CONFIG_SSL_CCS_SET_EX struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_SERVICE_CONFIG_SSL_QUERY struct {
	QueryDesc int
	KeyDesc   int
	DWTOKEN   int
}

type HTTP_SERVICE_CONFIG_SSL_SNI_QUERY struct {
	QueryDesc int
	KeyDesc   int
	DWTOKEN   int
}

type HTTP_SERVICE_CONFIG_SSL_CCS_QUERY struct {
	QueryDesc int
	KeyDesc   int
	DWTOKEN   int
}

type HTTP_SERVICE_CONFIG_SSL_QUERY_EX struct {
	QueryDesc int
	KeyDesc   int
	DWTOKEN   int
	ParamType int
}

type HTTP_SERVICE_CONFIG_SSL_SNI_QUERY_EX struct {
	QueryDesc int
	KeyDesc   int
	DWTOKEN   int
	ParamType int
}

type HTTP_SERVICE_CONFIG_SSL_CCS_QUERY_EX struct {
	QueryDesc int
	KeyDesc   int
	DWTOKEN   int
	ParamType int
}

type HTTP_SERVICE_CONFIG_IP_LISTEN_PARAM struct {
	AddrLength int
	PADDRESS   int
}

type HTTP_SERVICE_CONFIG_IP_LISTEN_QUERY struct {
	AddrCount int
	AddrList  int
}

type HTTP_SERVICE_CONFIG_URLACL_KEY struct {
	PURLPREFIX int
}

type HTTP_SERVICE_CONFIG_URLACL_PARAM struct {
	PSTRINGSECURITYDESCRIPTOR int
}

type HTTP_SERVICE_CONFIG_URLACL_SET struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_SERVICE_CONFIG_URLACL_QUERY struct {
	QueryDesc int
	KeyDesc   int
	DWTOKEN   int
}

type HTTP_SERVICE_CONFIG_CACHE_SET struct {
	KeyDesc   int
	ParamDesc int
}

type HTTP_QUERY_REQUEST_QUALIFIER_TCP struct {
	Freshness int
}

type HTTP_QUERY_REQUEST_QUALIFIER_QUIC struct {
	Freshness int
}

type HTTP_REQUEST_PROPERTY_SNI struct {
	Hostname int
	Flags    int
}

type WINHTTP_ASYNC_RESULT struct {
	DWRESULT int
	DWERROR  int
}

type URL_COMPONENTS struct {
	DWSTRUCTSIZE      int
	LPSZSCHEME        int
	DWSCHEMELENGTH    int
	NSCHEME           int
	LPSZHOSTNAME      int
	DWHOSTNAMELENGTH  int
	NPORT             int
	LPSZUSERNAME      int
	DWUSERNAMELENGTH  int
	LPSZPASSWORD      int
	DWPASSWORDLENGTH  int
	LPSZURLPATH       int
	DWURLPATHLENGTH   int
	LPSZEXTRAINFO     int
	DWEXTRAINFOLENGTH int
}

type WINHTTP_PROXY_INFO struct {
	DWACCESSTYPE    int
	LPSZPROXY       int
	LPSZPROXYBYPASS int
}

type WINHTTP_AUTOPROXY_OPTIONS struct {
	DWFLAGS                int
	DWAUTODETECTFLAGS      int
	LPSZAUTOCONFIGURL      int
	LPVRESERVED            int
	DWRESERVED             int
	FAUTOLOGONIFCHALLENGED int
}

type WINHTTP_PROXY_RESULT_ENTRY struct {
	FPROXY      int
	FBYPASS     int
	ProxyScheme int
	PWSZPROXY   int
	ProxyPort   int
}

type WINHTTP_PROXY_RESULT struct {
	CENTRIES int
	PENTRIES int
}

type WINHTTP_PROXY_RESULT_EX struct {
	CENTRIES                 int
	PENTRIES                 int
	HPROXYDETECTIONHANDLE    int
	DWPROXYINTERFACEAFFINITY int
}

type WinHttpProxyNetworkKey struct {
	PBBUFFER int
}

type WINHTTP_PROXY_SETTINGS struct {
	DWSTRUCTSIZE                   int
	DWFLAGS                        int
	DWCURRENTSETTINGSVERSION       int
	PWSZCONNECTIONNAME             int
	PWSZPROXY                      int
	PWSZPROXYBYPASS                int
	PWSZAUTOCONFIGURL              int
	PWSZAUTOCONFIGSECONDARYURL     int
	DWAUTODISCOVERYFLAGS           int
	PWSZLASTKNOWNGOODAUTOCONFIGURL int
	DWAUTOCONFIGRELOADDELAYMINS    int
	FTLASTKNOWNDETECTTIME          int
	DWDETECTEDINTERFACEIPCOUNT     int
	PDWDETECTEDINTERFACEIP         int
	CNETWORKKEYS                   int
	PNETWORKKEYS                   int
}

type WINHTTP_CERTIFICATE_INFO struct {
	FTEXPIRY              int
	FTSTART               int
	LPSZSUBJECTINFO       int
	LPSZISSUERINFO        int
	LPSZPROTOCOLNAME      int
	LPSZSIGNATUREALGNAME  int
	LPSZENCRYPTIONALGNAME int
	DWKEYSIZE             int
}

type WINHTTP_CONNECTION_INFO struct {
	CBSIZE        int
	LocalAddress  int
	RemoteAddress int
}

type WINHTTP_REQUEST_TIMES struct {
	CTIMES     int
	RGULLTIMES int
}

type WINHTTP_REQUEST_STATS struct {
	ULLFLAGS   int
	ULINDEX    int
	CSTATS     int
	RGULLSTATS int
}

type WINHTTP_EXTENDED_HEADER struct {
	Anonymous1 int
	Anonymous2 int
}

type WINHTTP_CREDS struct {
	LPSZUSERNAME int
	LPSZPASSWORD int
	LPSZREALM    int
	DWAUTHSCHEME int
	LPSZHOSTNAME int
	DWPORT       int
}

type WINHTTP_CREDS_EX struct {
	LPSZUSERNAME int
	LPSZPASSWORD int
	LPSZREALM    int
	DWAUTHSCHEME int
	LPSZHOSTNAME int
	DWPORT       int
	LPSZURL      int
}

type WINHTTP_CURRENT_USER_IE_PROXY_CONFIG struct {
	FAUTODETECT       int
	LPSZAUTOCONFIGURL int
	LPSZPROXY         int
	LPSZPROXYBYPASS   int
}

type WINHTTP_WEB_SOCKET_ASYNC_RESULT struct {
	AsyncResult int
	Operation   int
}

type WINHTTP_WEB_SOCKET_STATUS struct {
	DWBYTESTRANSFERRED int
	EBUFFERTYPE        int
}
