// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package winrt implements the Windows.Win32.WinRT namespace.
package winrt

type EventRegistrationToken struct {
	VALUE int
}

type HSTRING struct {
	Value int
}

type HSTRING_HEADER struct {
	Reserved int
}

type PDF_RENDER_PARAMS struct {
	SourceRect         int
	DestinationWidth   int
	DestinationHeight  int
	BackgroundColor    int
	IgnoreHighContrast int
}

type AnonymousRecord_roapi_L45_C9 struct {
}

type APARTMENT_SHUTDOWN_REGISTRATION_COOKIE__ struct {
	UNUSED int
}

type ROPARAMIIDHANDLE__ struct {
	UNUSED int
}

type ServerInformation struct {
	DWSERVERPID       int
	DWSERVERTID       int
	UI64SERVERADDRESS int
}
