// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package dataexchange implements the Windows.Win32.DataExchange namespace.
package dataexchange

type METAFILEPICT struct {
	MM   int
	XEXT int
	YEXT int
	HMF  int
}

type DDEACK struct {
	BITFIELD int
}

type DDEADVISE struct {
	BITFIELD int
	CFFORMAT int
}

type DDEDATA struct {
	BITFIELD int
	CFFORMAT int
	Value    int
}

type DDEPOKE struct {
	BITFIELD int
	CFFORMAT int
	Value    int
}

type DDELN struct {
	BITFIELD int
	CFFORMAT int
}

type DDEUP struct {
	BITFIELD int
	CFFORMAT int
	RGB      int
}

type HCONVLIST__ struct {
	UNUSED int
}

type HCONV__ struct {
	UNUSED int
}

type HSZ__ struct {
	UNUSED int
}

type HDDEDATA__ struct {
	UNUSED int
}

type HSZPAIR struct {
	HSZSVC   int
	HSZTOPIC int
}

type CONVCONTEXT struct {
	CB         int
	WFLAGS     int
	WCOUNTRYID int
	ICODEPAGE  int
	DWLANGID   int
	DWSECURITY int
	QOS        int
}

type CONVINFO struct {
	CB            int
	HUSER         int
	HCONVPARTNER  int
	HSZSVCPARTNER int
	HSZSERVICEREQ int
	HSZTOPIC      int
	HSZITEM       int
	WFMT          int
	WTYPE         int
	WSTATUS       int
	WCONVST       int
	WLASTERROR    int
	HCONVLIST     int
	ConvCtxt      int
	HWND          int
	HWNDPARTNER   int
}

type DDEML_MSG_HOOK_DATA struct {
	UILO   int
	UIHI   int
	CBDATA int
	Data   int
}

type MONMSGSTRUCT struct {
	CB     int
	HWNDTO int
	DWTIME int
	HTASK  int
	WMSG   int
	WPARAM int
	LPARAM int
	DMHD   int
}

type MONCBSTRUCT struct {
	CB      int
	DWTIME  int
	HTASK   int
	DWRET   int
	WTYPE   int
	WFMT    int
	HCONV   int
	HSZ1    int
	HSZ2    int
	HDATA   int
	DWDATA1 int
	DWDATA2 int
	CC      int
	CBDATA  int
	Data    int
}

type MONHSZSTRUCTA struct {
	CB       int
	FSACTION int
	DWTIME   int
	HSZ      int
	HTASK    int
	STR      int
}

type MONHSZSTRUCTW struct {
	CB       int
	FSACTION int
	DWTIME   int
	HSZ      int
	HTASK    int
	STR      int
}

type MONERRSTRUCT struct {
	CB         int
	WLASTERROR int
	DWTIME     int
	HTASK      int
}

type MONLINKSTRUCT struct {
	CB           int
	DWTIME       int
	HTASK        int
	FESTABLISHED int
	FNODATA      int
	HSZSVC       int
	HSZTOPIC     int
	HSZITEM      int
	WFMT         int
	FSERVER      int
	HCONVSERVER  int
	HCONVCLIENT  int
}

type MONCONVSTRUCT struct {
	CB          int
	FCONNECT    int
	DWTIME      int
	HTASK       int
	HSZSVC      int
	HSZTOPIC    int
	HCONVCLIENT int
	HCONVSERVER int
}

type COPYDATASTRUCT struct {
	DWDATA int
	CBDATA int
	LPDATA int
}
