// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package printdocs implements the Windows.Win32.PrintDocs namespace.
package printdocs

type XPS_GLYPH_INDEX struct {
	INDEX            int
	ADVANCEWIDTH     int
	HORIZONTALOFFSET int
	VERTICALOFFSET   int
}
