// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowsnetworkvirtualization implements the Windows.Win32.WindowsNetworkVirtualization namespace.
package windowsnetworkvirtualization

type WNV_NOTIFICATION_TYPE int32

const (
	WnvPolicyMismatchType  WNV_NOTIFICATION_TYPE = 0
	WnvRedirectType        WNV_NOTIFICATION_TYPE = 1
	WnvObjectChangeType    WNV_NOTIFICATION_TYPE = 2
	WnvNotificationTypeMax WNV_NOTIFICATION_TYPE = 3
)

type WNV_OBJECT_TYPE int32

const (
	WnvProviderAddressType WNV_OBJECT_TYPE = 0
	WnvCustomerAddressType WNV_OBJECT_TYPE = 1
	WnvObjectTypeMax       WNV_OBJECT_TYPE = 2
)

type WNV_CA_NOTIFICATION_TYPE int32

const (
	WnvCustomerAddressAdded   WNV_CA_NOTIFICATION_TYPE = 0
	WnvCustomerAddressDeleted WNV_CA_NOTIFICATION_TYPE = 1
	WnvCustomerAddressMoved   WNV_CA_NOTIFICATION_TYPE = 2
	WnvCustomerAddressMax     WNV_CA_NOTIFICATION_TYPE = 3
)
