// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package windowsinformationprotection implements the Windows.Win32.WindowsInformationProtection namespace.
package windowsinformationprotection

type ENTERPRISE_DATA_POLICIES int32

const (
	ENTERPRISE_POLICY_NONE = 0
	ENTERPRISE_POLICY_ALLOWED = 1
	ENTERPRISE_POLICY_ENLIGHTENED = 2
	ENTERPRISE_POLICY_EXEMPT = 4
)

