// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package mobiledevicemanagementregistration implements the Windows.Win32.MobileDeviceManagementRegistration namespace.
package mobiledevicemanagementregistration

type REGISTRATION_INFORMATION_CLASS int32

const (
	DeviceRegistrationBasicInfo = 1
	MaxDeviceInfoClass = 2
)

