// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package mobiledevicemanagementregistration implements the Windows.Win32.MobileDeviceManagementRegistration namespace.
package mobiledevicemanagementregistration

type MANAGEMENT_SERVICE_INFO struct {
	PSZMDMSERVICEURI     int
	PSZAUTHENTICATIONURI int
}

type MANAGEMENT_REGISTRATION_INFO struct {
	FDEVICEREGISTEREDWITHMANAGEMENT int
	DWDEVICEREGISTIONKIND           int
	PSZUPN                          int
	PSZMDMSERVICEURI                int
}
