// AUTOGENERATED - DO NOT EDIT
// Generated by go-windows.

// Package extensibleauthenticationprotocol implements the Windows.Win32.ExtensibleAuthenticationProtocol namespace.
package extensibleauthenticationprotocol

type EAP_ATTRIBUTE_TYPE int32

const (
	eatMinimum                EAP_ATTRIBUTE_TYPE = 0
	eatUserName               EAP_ATTRIBUTE_TYPE = 1
	eatUserPassword           EAP_ATTRIBUTE_TYPE = 2
	eatMD5CHAPPassword        EAP_ATTRIBUTE_TYPE = 3
	eatNASIPAddress           EAP_ATTRIBUTE_TYPE = 4
	eatNASPort                EAP_ATTRIBUTE_TYPE = 5
	eatServiceType            EAP_ATTRIBUTE_TYPE = 6
	eatFramedProtocol         EAP_ATTRIBUTE_TYPE = 7
	eatFramedIPAddress        EAP_ATTRIBUTE_TYPE = 8
	eatFramedIPNetmask        EAP_ATTRIBUTE_TYPE = 9
	eatFramedRouting          EAP_ATTRIBUTE_TYPE = 10
	eatFilterId               EAP_ATTRIBUTE_TYPE = 11
	eatFramedMTU              EAP_ATTRIBUTE_TYPE = 12
	eatFramedCompression      EAP_ATTRIBUTE_TYPE = 13
	eatLoginIPHost            EAP_ATTRIBUTE_TYPE = 14
	eatLoginService           EAP_ATTRIBUTE_TYPE = 15
	eatLoginTCPPort           EAP_ATTRIBUTE_TYPE = 16
	eatUnassigned17           EAP_ATTRIBUTE_TYPE = 17
	eatReplyMessage           EAP_ATTRIBUTE_TYPE = 18
	eatCallbackNumber         EAP_ATTRIBUTE_TYPE = 19
	eatCallbackId             EAP_ATTRIBUTE_TYPE = 20
	eatUnassigned21           EAP_ATTRIBUTE_TYPE = 21
	eatFramedRoute            EAP_ATTRIBUTE_TYPE = 22
	eatFramedIPXNetwork       EAP_ATTRIBUTE_TYPE = 23
	eatState                  EAP_ATTRIBUTE_TYPE = 24
	eatClass                  EAP_ATTRIBUTE_TYPE = 25
	eatVendorSpecific         EAP_ATTRIBUTE_TYPE = 26
	eatSessionTimeout         EAP_ATTRIBUTE_TYPE = 27
	eatIdleTimeout            EAP_ATTRIBUTE_TYPE = 28
	eatTerminationAction      EAP_ATTRIBUTE_TYPE = 29
	eatCalledStationId        EAP_ATTRIBUTE_TYPE = 30
	eatCallingStationId       EAP_ATTRIBUTE_TYPE = 31
	eatNASIdentifier          EAP_ATTRIBUTE_TYPE = 32
	eatProxyState             EAP_ATTRIBUTE_TYPE = 33
	eatLoginLATService        EAP_ATTRIBUTE_TYPE = 34
	eatLoginLATNode           EAP_ATTRIBUTE_TYPE = 35
	eatLoginLATGroup          EAP_ATTRIBUTE_TYPE = 36
	eatFramedAppleTalkLink    EAP_ATTRIBUTE_TYPE = 37
	eatFramedAppleTalkNetwork EAP_ATTRIBUTE_TYPE = 38
	eatFramedAppleTalkZone    EAP_ATTRIBUTE_TYPE = 39
	eatAcctStatusType         EAP_ATTRIBUTE_TYPE = 40
	eatAcctDelayTime          EAP_ATTRIBUTE_TYPE = 41
	eatAcctInputOctets        EAP_ATTRIBUTE_TYPE = 42
	eatAcctOutputOctets       EAP_ATTRIBUTE_TYPE = 43
	eatAcctSessionId          EAP_ATTRIBUTE_TYPE = 44
	eatAcctAuthentic          EAP_ATTRIBUTE_TYPE = 45
	eatAcctSessionTime        EAP_ATTRIBUTE_TYPE = 46
	eatAcctInputPackets       EAP_ATTRIBUTE_TYPE = 47
	eatAcctOutputPackets      EAP_ATTRIBUTE_TYPE = 48
	eatAcctTerminateCause     EAP_ATTRIBUTE_TYPE = 49
	eatAcctMultiSessionId     EAP_ATTRIBUTE_TYPE = 50
	eatAcctLinkCount          EAP_ATTRIBUTE_TYPE = 51
	eatAcctEventTimeStamp     EAP_ATTRIBUTE_TYPE = 55
	eatMD5CHAPChallenge       EAP_ATTRIBUTE_TYPE = 60
	eatNASPortType            EAP_ATTRIBUTE_TYPE = 61
	eatPortLimit              EAP_ATTRIBUTE_TYPE = 62
	eatLoginLATPort           EAP_ATTRIBUTE_TYPE = 63
	eatTunnelType             EAP_ATTRIBUTE_TYPE = 64
	eatTunnelMediumType       EAP_ATTRIBUTE_TYPE = 65
	eatTunnelClientEndpoint   EAP_ATTRIBUTE_TYPE = 66
	eatTunnelServerEndpoint   EAP_ATTRIBUTE_TYPE = 67
	eatARAPPassword           EAP_ATTRIBUTE_TYPE = 70
	eatARAPFeatures           EAP_ATTRIBUTE_TYPE = 71
	eatARAPZoneAccess         EAP_ATTRIBUTE_TYPE = 72
	eatARAPSecurity           EAP_ATTRIBUTE_TYPE = 73
	eatARAPSecurityData       EAP_ATTRIBUTE_TYPE = 74
	eatPasswordRetry          EAP_ATTRIBUTE_TYPE = 75
	eatPrompt                 EAP_ATTRIBUTE_TYPE = 76
	eatConnectInfo            EAP_ATTRIBUTE_TYPE = 77
	eatConfigurationToken     EAP_ATTRIBUTE_TYPE = 78
	eatEAPMessage             EAP_ATTRIBUTE_TYPE = 79
	eatSignature              EAP_ATTRIBUTE_TYPE = 80
	eatARAPChallengeResponse  EAP_ATTRIBUTE_TYPE = 84
	eatAcctInterimInterval    EAP_ATTRIBUTE_TYPE = 85
	eatNASIPv6Address         EAP_ATTRIBUTE_TYPE = 95
	eatFramedInterfaceId      EAP_ATTRIBUTE_TYPE = 96
	eatFramedIPv6Prefix       EAP_ATTRIBUTE_TYPE = 97
	eatLoginIPv6Host          EAP_ATTRIBUTE_TYPE = 98
	eatFramedIPv6Route        EAP_ATTRIBUTE_TYPE = 99
	eatFramedIPv6Pool         EAP_ATTRIBUTE_TYPE = 100
	eatARAPGuestLogon         EAP_ATTRIBUTE_TYPE = 8096
	eatCertificateOID         EAP_ATTRIBUTE_TYPE = 8097
	eatEAPConfiguration       EAP_ATTRIBUTE_TYPE = 8098
	eatPEAPEmbeddedEAPTypeId  EAP_ATTRIBUTE_TYPE = 8099
	eatPEAPFastRoamedSession  EAP_ATTRIBUTE_TYPE = 8100
	eatFastRoamedSession      EAP_ATTRIBUTE_TYPE = 8100
	eatEAPTLV                 EAP_ATTRIBUTE_TYPE = 8102
	eatCredentialsChanged     EAP_ATTRIBUTE_TYPE = 8103
	eatInnerEapMethodType     EAP_ATTRIBUTE_TYPE = 8104
	eatClearTextPassword      EAP_ATTRIBUTE_TYPE = 8107
	eatQuarantineSoH          EAP_ATTRIBUTE_TYPE = 8150
	eatCertificateThumbprint  EAP_ATTRIBUTE_TYPE = 8250
	eatPeerId                 EAP_ATTRIBUTE_TYPE = 9000
	eatServerId               EAP_ATTRIBUTE_TYPE = 9001
	eatMethodId               EAP_ATTRIBUTE_TYPE = 9002
	eatEMSK                   EAP_ATTRIBUTE_TYPE = 9003
	eatSessionId              EAP_ATTRIBUTE_TYPE = 9004
	eatReserved               EAP_ATTRIBUTE_TYPE = -1
)

type EAP_CONFIG_INPUT_FIELD_TYPE int32

const (
	EapConfigInputUsername        EAP_CONFIG_INPUT_FIELD_TYPE = 0
	EapConfigInputPassword        EAP_CONFIG_INPUT_FIELD_TYPE = 1
	EapConfigInputNetworkUsername EAP_CONFIG_INPUT_FIELD_TYPE = 2
	EapConfigInputNetworkPassword EAP_CONFIG_INPUT_FIELD_TYPE = 3
	EapConfigInputPin             EAP_CONFIG_INPUT_FIELD_TYPE = 4
	EapConfigInputPSK             EAP_CONFIG_INPUT_FIELD_TYPE = 5
	EapConfigInputEdit            EAP_CONFIG_INPUT_FIELD_TYPE = 6
	EapConfigSmartCardUsername    EAP_CONFIG_INPUT_FIELD_TYPE = 7
	EapConfigSmartCardError       EAP_CONFIG_INPUT_FIELD_TYPE = 8
)

type EAP_INTERACTIVE_UI_DATA_TYPE int32

const (
	EapCredReq        EAP_INTERACTIVE_UI_DATA_TYPE = 0
	EapCredResp       EAP_INTERACTIVE_UI_DATA_TYPE = 1
	EapCredExpiryReq  EAP_INTERACTIVE_UI_DATA_TYPE = 2
	EapCredExpiryResp EAP_INTERACTIVE_UI_DATA_TYPE = 3
	EapCredLogonReq   EAP_INTERACTIVE_UI_DATA_TYPE = 4
	EapCredLogonResp  EAP_INTERACTIVE_UI_DATA_TYPE = 5
)

type EAP_METHOD_PROPERTY_TYPE int32

const (
	emptPropCipherSuiteNegotiation     EAP_METHOD_PROPERTY_TYPE = 0
	emptPropMutualAuth                 EAP_METHOD_PROPERTY_TYPE = 1
	emptPropIntegrity                  EAP_METHOD_PROPERTY_TYPE = 2
	emptPropReplayProtection           EAP_METHOD_PROPERTY_TYPE = 3
	emptPropConfidentiality            EAP_METHOD_PROPERTY_TYPE = 4
	emptPropKeyDerivation              EAP_METHOD_PROPERTY_TYPE = 5
	emptPropKeyStrength64              EAP_METHOD_PROPERTY_TYPE = 6
	emptPropKeyStrength128             EAP_METHOD_PROPERTY_TYPE = 7
	emptPropKeyStrength256             EAP_METHOD_PROPERTY_TYPE = 8
	emptPropKeyStrength512             EAP_METHOD_PROPERTY_TYPE = 9
	emptPropKeyStrength1024            EAP_METHOD_PROPERTY_TYPE = 10
	emptPropDictionaryAttackResistance EAP_METHOD_PROPERTY_TYPE = 11
	emptPropFastReconnect              EAP_METHOD_PROPERTY_TYPE = 12
	emptPropCryptoBinding              EAP_METHOD_PROPERTY_TYPE = 13
	emptPropSessionIndependence        EAP_METHOD_PROPERTY_TYPE = 14
	emptPropFragmentation              EAP_METHOD_PROPERTY_TYPE = 15
	emptPropChannelBinding             EAP_METHOD_PROPERTY_TYPE = 16
	emptPropNap                        EAP_METHOD_PROPERTY_TYPE = 17
	emptPropStandalone                 EAP_METHOD_PROPERTY_TYPE = 18
	emptPropMppeEncryption             EAP_METHOD_PROPERTY_TYPE = 19
	emptPropTunnelMethod               EAP_METHOD_PROPERTY_TYPE = 20
	emptPropSupportsConfig             EAP_METHOD_PROPERTY_TYPE = 21
	emptPropCertifiedMethod            EAP_METHOD_PROPERTY_TYPE = 22
	emptPropHiddenMethod               EAP_METHOD_PROPERTY_TYPE = 23
	emptPropMachineAuth                EAP_METHOD_PROPERTY_TYPE = 24
	emptPropUserAuth                   EAP_METHOD_PROPERTY_TYPE = 25
	emptPropIdentityPrivacy            EAP_METHOD_PROPERTY_TYPE = 26
	emptPropMethodChaining             EAP_METHOD_PROPERTY_TYPE = 27
	emptPropSharedStateEquivalence     EAP_METHOD_PROPERTY_TYPE = 28
	emptLegacyMethodPropertyFlag       EAP_METHOD_PROPERTY_TYPE = 31
	emptPropVendorSpecific             EAP_METHOD_PROPERTY_TYPE = 255
)

type EAP_METHOD_PROPERTY_VALUE_TYPE int32

const (
	empvtBool   EAP_METHOD_PROPERTY_VALUE_TYPE = 0
	empvtDword  EAP_METHOD_PROPERTY_VALUE_TYPE = 1
	empvtString EAP_METHOD_PROPERTY_VALUE_TYPE = 2
)

type EapCredentialType int32

const (
	EAP_EMPTY_CREDENTIAL             EapCredentialType = 0
	EAP_USERNAME_PASSWORD_CREDENTIAL EapCredentialType = 1
	EAP_WINLOGON_CREDENTIAL          EapCredentialType = 2
	EAP_CERTIFICATE_CREDENTIAL       EapCredentialType = 3
	EAP_SIM_CREDENTIAL               EapCredentialType = 4
)

type EapHostPeerMethodResultReason int32

const (
	EapHostPeerMethodResultAltSuccessReceived EapHostPeerMethodResultReason = 1
	EapHostPeerMethodResultTimeout            EapHostPeerMethodResultReason = 2
	EapHostPeerMethodResultFromMethod         EapHostPeerMethodResultReason = 3
)

type EapHostPeerResponseAction int32

const (
	EapHostPeerResponseDiscard             EapHostPeerResponseAction = 0
	EapHostPeerResponseSend                EapHostPeerResponseAction = 1
	EapHostPeerResponseResult              EapHostPeerResponseAction = 2
	EapHostPeerResponseInvokeUi            EapHostPeerResponseAction = 3
	EapHostPeerResponseRespond             EapHostPeerResponseAction = 4
	EapHostPeerResponseStartAuthentication EapHostPeerResponseAction = 5
	EapHostPeerResponseNone                EapHostPeerResponseAction = 6
)

type EapHostPeerAuthParams int32

const (
	EapHostPeerAuthStatus           EapHostPeerAuthParams = 1
	EapHostPeerIdentity             EapHostPeerAuthParams = 2
	EapHostPeerIdentityExtendedInfo EapHostPeerAuthParams = 3
	EapHostNapInfo                  EapHostPeerAuthParams = 4
)

type EAPHOST_AUTH_STATUS int32

const (
	EapHostInvalidSession       EAPHOST_AUTH_STATUS = 0
	EapHostAuthNotStarted       EAPHOST_AUTH_STATUS = 1
	EapHostAuthIdentityExchange EAPHOST_AUTH_STATUS = 2
	EapHostAuthNegotiatingType  EAPHOST_AUTH_STATUS = 3
	EapHostAuthInProgress       EAPHOST_AUTH_STATUS = 4
	EapHostAuthSucceeded        EAPHOST_AUTH_STATUS = 5
	EapHostAuthFailed           EAPHOST_AUTH_STATUS = 6
)

type ISOLATION_STATE int32

const (
	ISOLATION_STATE_UNKNOWN           ISOLATION_STATE = 0
	ISOLATION_STATE_NOT_RESTRICTED    ISOLATION_STATE = 1
	ISOLATION_STATE_IN_PROBATION      ISOLATION_STATE = 2
	ISOLATION_STATE_RESTRICTED_ACCESS ISOLATION_STATE = 3
)

type EapCode int32

const (
	EapCodeMinimum  EapCode = 1
	EapCodeRequest  EapCode = 1
	EapCodeResponse EapCode = 2
	EapCodeSuccess  EapCode = 3
	EapCodeFailure  EapCode = 4
	EapCodeMaximum  EapCode = 4
)

type EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION int32

const (
	EAP_METHOD_AUTHENTICATOR_RESPONSE_DISCARD         EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 0
	EAP_METHOD_AUTHENTICATOR_RESPONSE_SEND            EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 1
	EAP_METHOD_AUTHENTICATOR_RESPONSE_RESULT          EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 2
	EAP_METHOD_AUTHENTICATOR_RESPONSE_RESPOND         EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 3
	EAP_METHOD_AUTHENTICATOR_RESPONSE_AUTHENTICATE    EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 4
	EAP_METHOD_AUTHENTICATOR_RESPONSE_HANDLE_IDENTITY EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 5
)

type EapPeerMethodResponseAction int32

const (
	EapPeerMethodResponseActionDiscard  EapPeerMethodResponseAction = 0
	EapPeerMethodResponseActionSend     EapPeerMethodResponseAction = 1
	EapPeerMethodResponseActionResult   EapPeerMethodResponseAction = 2
	EapPeerMethodResponseActionInvokeUI EapPeerMethodResponseAction = 3
	EapPeerMethodResponseActionRespond  EapPeerMethodResponseAction = 4
	EapPeerMethodResponseActionNone     EapPeerMethodResponseAction = 5
)

type EapPeerMethodResultReason int32

const (
	EapPeerMethodResultUnknown EapPeerMethodResultReason = 1
	EapPeerMethodResultSuccess EapPeerMethodResultReason = 2
	EapPeerMethodResultFailure EapPeerMethodResultReason = 3
)

type EAP_AUTHENTICATOR_SEND_TIMEOUT int32

const (
	EAP_AUTHENTICATOR_SEND_TIMEOUT_NONE        EAP_AUTHENTICATOR_SEND_TIMEOUT = 0
	EAP_AUTHENTICATOR_SEND_TIMEOUT_BASIC       EAP_AUTHENTICATOR_SEND_TIMEOUT = 1
	EAP_AUTHENTICATOR_SEND_TIMEOUT_INTERACTIVE EAP_AUTHENTICATOR_SEND_TIMEOUT = 2
)

type RAS_AUTH_ATTRIBUTE_TYPE int32

const (
	raatMinimum                RAS_AUTH_ATTRIBUTE_TYPE = 0
	raatUserName               RAS_AUTH_ATTRIBUTE_TYPE = 1
	raatUserPassword           RAS_AUTH_ATTRIBUTE_TYPE = 2
	raatMD5CHAPPassword        RAS_AUTH_ATTRIBUTE_TYPE = 3
	raatNASIPAddress           RAS_AUTH_ATTRIBUTE_TYPE = 4
	raatNASPort                RAS_AUTH_ATTRIBUTE_TYPE = 5
	raatServiceType            RAS_AUTH_ATTRIBUTE_TYPE = 6
	raatFramedProtocol         RAS_AUTH_ATTRIBUTE_TYPE = 7
	raatFramedIPAddress        RAS_AUTH_ATTRIBUTE_TYPE = 8
	raatFramedIPNetmask        RAS_AUTH_ATTRIBUTE_TYPE = 9
	raatFramedRouting          RAS_AUTH_ATTRIBUTE_TYPE = 10
	raatFilterId               RAS_AUTH_ATTRIBUTE_TYPE = 11
	raatFramedMTU              RAS_AUTH_ATTRIBUTE_TYPE = 12
	raatFramedCompression      RAS_AUTH_ATTRIBUTE_TYPE = 13
	raatLoginIPHost            RAS_AUTH_ATTRIBUTE_TYPE = 14
	raatLoginService           RAS_AUTH_ATTRIBUTE_TYPE = 15
	raatLoginTCPPort           RAS_AUTH_ATTRIBUTE_TYPE = 16
	raatUnassigned17           RAS_AUTH_ATTRIBUTE_TYPE = 17
	raatReplyMessage           RAS_AUTH_ATTRIBUTE_TYPE = 18
	raatCallbackNumber         RAS_AUTH_ATTRIBUTE_TYPE = 19
	raatCallbackId             RAS_AUTH_ATTRIBUTE_TYPE = 20
	raatUnassigned21           RAS_AUTH_ATTRIBUTE_TYPE = 21
	raatFramedRoute            RAS_AUTH_ATTRIBUTE_TYPE = 22
	raatFramedIPXNetwork       RAS_AUTH_ATTRIBUTE_TYPE = 23
	raatState                  RAS_AUTH_ATTRIBUTE_TYPE = 24
	raatClass                  RAS_AUTH_ATTRIBUTE_TYPE = 25
	raatVendorSpecific         RAS_AUTH_ATTRIBUTE_TYPE = 26
	raatSessionTimeout         RAS_AUTH_ATTRIBUTE_TYPE = 27
	raatIdleTimeout            RAS_AUTH_ATTRIBUTE_TYPE = 28
	raatTerminationAction      RAS_AUTH_ATTRIBUTE_TYPE = 29
	raatCalledStationId        RAS_AUTH_ATTRIBUTE_TYPE = 30
	raatCallingStationId       RAS_AUTH_ATTRIBUTE_TYPE = 31
	raatNASIdentifier          RAS_AUTH_ATTRIBUTE_TYPE = 32
	raatProxyState             RAS_AUTH_ATTRIBUTE_TYPE = 33
	raatLoginLATService        RAS_AUTH_ATTRIBUTE_TYPE = 34
	raatLoginLATNode           RAS_AUTH_ATTRIBUTE_TYPE = 35
	raatLoginLATGroup          RAS_AUTH_ATTRIBUTE_TYPE = 36
	raatFramedAppleTalkLink    RAS_AUTH_ATTRIBUTE_TYPE = 37
	raatFramedAppleTalkNetwork RAS_AUTH_ATTRIBUTE_TYPE = 38
	raatFramedAppleTalkZone    RAS_AUTH_ATTRIBUTE_TYPE = 39
	raatAcctStatusType         RAS_AUTH_ATTRIBUTE_TYPE = 40
	raatAcctDelayTime          RAS_AUTH_ATTRIBUTE_TYPE = 41
	raatAcctInputOctets        RAS_AUTH_ATTRIBUTE_TYPE = 42
	raatAcctOutputOctets       RAS_AUTH_ATTRIBUTE_TYPE = 43
	raatAcctSessionId          RAS_AUTH_ATTRIBUTE_TYPE = 44
	raatAcctAuthentic          RAS_AUTH_ATTRIBUTE_TYPE = 45
	raatAcctSessionTime        RAS_AUTH_ATTRIBUTE_TYPE = 46
	raatAcctInputPackets       RAS_AUTH_ATTRIBUTE_TYPE = 47
	raatAcctOutputPackets      RAS_AUTH_ATTRIBUTE_TYPE = 48
	raatAcctTerminateCause     RAS_AUTH_ATTRIBUTE_TYPE = 49
	raatAcctMultiSessionId     RAS_AUTH_ATTRIBUTE_TYPE = 50
	raatAcctLinkCount          RAS_AUTH_ATTRIBUTE_TYPE = 51
	raatAcctEventTimeStamp     RAS_AUTH_ATTRIBUTE_TYPE = 55
	raatMD5CHAPChallenge       RAS_AUTH_ATTRIBUTE_TYPE = 60
	raatNASPortType            RAS_AUTH_ATTRIBUTE_TYPE = 61
	raatPortLimit              RAS_AUTH_ATTRIBUTE_TYPE = 62
	raatLoginLATPort           RAS_AUTH_ATTRIBUTE_TYPE = 63
	raatTunnelType             RAS_AUTH_ATTRIBUTE_TYPE = 64
	raatTunnelMediumType       RAS_AUTH_ATTRIBUTE_TYPE = 65
	raatTunnelClientEndpoint   RAS_AUTH_ATTRIBUTE_TYPE = 66
	raatTunnelServerEndpoint   RAS_AUTH_ATTRIBUTE_TYPE = 67
	raatARAPPassword           RAS_AUTH_ATTRIBUTE_TYPE = 70
	raatARAPFeatures           RAS_AUTH_ATTRIBUTE_TYPE = 71
	raatARAPZoneAccess         RAS_AUTH_ATTRIBUTE_TYPE = 72
	raatARAPSecurity           RAS_AUTH_ATTRIBUTE_TYPE = 73
	raatARAPSecurityData       RAS_AUTH_ATTRIBUTE_TYPE = 74
	raatPasswordRetry          RAS_AUTH_ATTRIBUTE_TYPE = 75
	raatPrompt                 RAS_AUTH_ATTRIBUTE_TYPE = 76
	raatConnectInfo            RAS_AUTH_ATTRIBUTE_TYPE = 77
	raatConfigurationToken     RAS_AUTH_ATTRIBUTE_TYPE = 78
	raatEAPMessage             RAS_AUTH_ATTRIBUTE_TYPE = 79
	raatSignature              RAS_AUTH_ATTRIBUTE_TYPE = 80
	raatARAPChallengeResponse  RAS_AUTH_ATTRIBUTE_TYPE = 84
	raatAcctInterimInterval    RAS_AUTH_ATTRIBUTE_TYPE = 85
	raatNASIPv6Address         RAS_AUTH_ATTRIBUTE_TYPE = 95
	raatFramedInterfaceId      RAS_AUTH_ATTRIBUTE_TYPE = 96
	raatFramedIPv6Prefix       RAS_AUTH_ATTRIBUTE_TYPE = 97
	raatLoginIPv6Host          RAS_AUTH_ATTRIBUTE_TYPE = 98
	raatFramedIPv6Route        RAS_AUTH_ATTRIBUTE_TYPE = 99
	raatFramedIPv6Pool         RAS_AUTH_ATTRIBUTE_TYPE = 100
	raatARAPGuestLogon         RAS_AUTH_ATTRIBUTE_TYPE = 8096
	raatCertificateOID         RAS_AUTH_ATTRIBUTE_TYPE = 8097
	raatEAPConfiguration       RAS_AUTH_ATTRIBUTE_TYPE = 8098
	raatPEAPEmbeddedEAPTypeId  RAS_AUTH_ATTRIBUTE_TYPE = 8099
	raatInnerEAPTypeId         RAS_AUTH_ATTRIBUTE_TYPE = 8099
	raatPEAPFastRoamedSession  RAS_AUTH_ATTRIBUTE_TYPE = 8100
	raatFastRoamedSession      RAS_AUTH_ATTRIBUTE_TYPE = 8100
	raatEAPTLV                 RAS_AUTH_ATTRIBUTE_TYPE = 8102
	raatCredentialsChanged     RAS_AUTH_ATTRIBUTE_TYPE = 8103
	raatCertificateThumbprint  RAS_AUTH_ATTRIBUTE_TYPE = 8250
	raatPeerId                 RAS_AUTH_ATTRIBUTE_TYPE = 9000
	raatServerId               RAS_AUTH_ATTRIBUTE_TYPE = 9001
	raatMethodId               RAS_AUTH_ATTRIBUTE_TYPE = 9002
	raatEMSK                   RAS_AUTH_ATTRIBUTE_TYPE = 9003
	raatSessionId              RAS_AUTH_ATTRIBUTE_TYPE = 9004
	raatReserved               RAS_AUTH_ATTRIBUTE_TYPE = -1
)

type PPP_EAP_ACTION int32

const (
	EAPACTION_NoAction                   PPP_EAP_ACTION = 0
	EAPACTION_Authenticate               PPP_EAP_ACTION = 1
	EAPACTION_Done                       PPP_EAP_ACTION = 2
	EAPACTION_SendAndDone                PPP_EAP_ACTION = 3
	EAPACTION_Send                       PPP_EAP_ACTION = 4
	EAPACTION_SendWithTimeout            PPP_EAP_ACTION = 5
	EAPACTION_SendWithTimeoutInteractive PPP_EAP_ACTION = 6
	EAPACTION_IndicateTLV                PPP_EAP_ACTION = 7
	EAPACTION_IndicateIdentity           PPP_EAP_ACTION = 8
)
